Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/Promoted_User_Story__c.object-meta.xml
<CustomObject>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promoted User Stories</relationshipLabel>
    <relationshipName>Promoted_User_Stories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status Outdated invalidates that this user story got promoted. The user story will be available again for automated promotions and back promotions if applicable.</description>
    <label>Active / Outdated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Outdated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Promotions</relationshipLabel>
    <relationshipName>Promoted_User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Back_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Back_Promotion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the promotion is from a higher environment to a lower environment in the deployment flow.</description>
    <inlineHelpText>Select this checkbox if you are promoting from a higher to a lower environment in the pipeline.</inlineHelpText>
    <label>Is Back-Promotion</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Destination_Environment__c.field-meta.xml
<CustomField>
    <fullName>Destination_Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Promotions (Destination Environment)</relationshipLabel>
    <relationshipName>Promotions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Destination_Org_Credential__c.field-meta.xml
<CustomField>
    <fullName>Destination_Org_Credential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The destination credential that will be used when creating the deployment. This credential is auto-populated based on the pipeline linked to the project.</inlineHelpText>
    <label>Destination Credential</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Org__c.Environment__c</field>
            <operation>equals</operation>
            <valueField>$Source.Destination_Environment__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Promotions (Destination Credential)</relationshipLabel>
    <relationshipName>Promotions2</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Source_Org_Credential__c.field-meta.xml
<CustomField>
    <fullName>Source_Org_Credential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The source credential that will be used when creating the deployment. This credential is auto-populated based on the pipeline linked to the project.</inlineHelpText>
    <label>Source Credential</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Org__c.Environment__c</field>
            <operation>equals</operation>
            <valueField>$Source.Source_Environment__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Promotions (Source Credential)</relationshipLabel>
    <relationshipName>Promotions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with errors</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Validation failed</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
            <value>
                <fullName>Conflicts Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Is_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Is_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Bundle</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the implementation of the User Story.</description>
    <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/recordTypes/Utility.recordType-meta.xml
<RecordType>
    <fullName>Utility</fullName>
    <active>true</active>
    <label>Utility</label>
</RecordType>

Dummy_Package_for_scratch_org/main/default/classes/PromotedUserStoriesSelector.cls
public with sharing class PromotedUserStoriesSelector extends fflib_SObjectSelector {
    public SObjectType getSObjectType() {
        return Promoted_User_Story__c.sObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{ Promoted_User_Story__c.User_Story__c, Promoted_User_Story__c.Promotion__c };
    }

    public List<Promoted_User_Story__c> byId(Set<Id> ids) {
        return (List<Promoted_User_Story__c>) selectSObjectsById(ids);
    }

    public List<Promoted_User_Story__c> byPromotionId(Set<Id> ids) {
        return (List<Promoted_User_Story__c>) Database.query(
            selectFields().setCondition(Promoted_User_Story__c.Promotion__c + ' IN :ids').toSOQL()
        );
    }

    public List<Promoted_User_Story__c> byPromotionIdWithFields(Set<Id> ids, Set<String> fields) {
        return new List<Promoted_User_Story__c>(
            (List<Promoted_User_Story__c>) Security.stripInaccessible(
                    AccessType.READABLE,
                    Database.query(newQueryFactory().setEnforceFLS(false).selectFields(fields).setCondition(Promoted_User_Story__c.Promotion__c + ' IN :ids').toSOQL())
                )
                .getRecords()
        );
    }

    public List<Promoted_User_Story__c> byBundleUSPromotions(Set<Id> promotionIds) {
        return (List<Promoted_User_Story__c>) Database.query(
            selectFields()
                .setCondition(
                    'Promotion__c IN :promotionIds AND Promotion__r.Back_Promotion__c = FALSE AND Promotion__r.Status__c = \'Completed\' AND User_Story__r.Is_Bundle__c = TRUE AND User_Story__r.RecordType.Name = \'Utility\''
                )
                .toSOQL()
        );
    }

    private fflib_QueryFactory selectFields() {
        return newQueryFactory()
                    .selectFields(new List<String> {
                        'User_Story__r.Name',
                        'Promotion__r.Destination_Environment__c',
                        'Promotion__r.Destination_Org_Credential__c',
                        'Promotion__r.Back_Promotion__c', 
                        'Promotion__r.Source_Org_Credential__c'
                    });
    }
}