Dummy_Package_for_scratch_org/main/default/objects/Automation_Template_For_CLI__c/fields/Automation_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Automation_Template_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>API name of Automation template</inlineHelpText>
    <label>Automation Template Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>This is a mandatory field if you intend to publish your automation template as copado extension package</inlineHelpText>
    <label>Api Name</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/recordTypes/Automation_Template.recordType-meta.xml
<RecordType>
    <fullName>Automation_Template</fullName>
    <active>true</active>
    <description>Group of steps to be executed in the future.</description>
    <label>Automation Template</label>
</RecordType>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production/Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Scratch Org</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <label>Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/dataJson__c.field-meta.xml
<CustomField>
    <fullName>dataJson__c</fullName>
    <description>If the step type is &quot;data&quot;  this should contains the json defining the query. 
In production this field should be HIDDEN</description>
    <label>dataJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MetaData</fullName>
                <default>true</default>
                <label>MetaData</label>
            </value>
            <value>
                <fullName>Full Profiles</fullName>
            </value>
            <value>
                <fullName>Full Permission Sets</fullName>
            </value>
            <value>
                <fullName>Users</fullName>
            </value>
            <value>
                <fullName>Translations</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Bulk Data</fullName>
            </value>
            <value>
                <fullName>Data Template</fullName>
            </value>
            <value>
                <fullName>Delete MetaData</fullName>
            </value>
            <value>
                <fullName>Custom Settings</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Git MetaData</fullName>
            </value>
            <value>
                <fullName>URL Callout</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/TestAutomationTemplateUpgrade.cls
@IsTest
private class TestAutomationTemplateUpgrade {
	@IsTest
    private static void run() {
        // Setup
        Deployment__c automationTemplate = getDeployment();
        insert new Automation_Template_For_CLI__c(Name = automationTemplate.Name, Automation_Template_Name__c = automationTemplate.ApiName__c);

        // Exercise
         String serializedResponse = new AutomationTemplateUpgrade().getInstance().run(new CliProxy.CLIWrapper());
        
        // Verify
    	AutomationTemplateUpgrade.Response response = (AutomationTemplateUpgrade.Response) JSON.deserialize(serializedResponse, 
                                                                                                            AutomationTemplateUpgrade.Response.class);
        
        System.assertEquals('OK', response.status);
    }
    
    // HELPER

    private static Deployment__c getDeployment(){
        return [SELECT Id, Name, ApiName__c FROM Deployment__c LIMIT 1];
    }
    
    @TestSetup
    private static void makeData() {
        Map<String, RecordTypeInfo> deploymentRecordTypes = SObjectType.Deployment__c.getRecordTypeInfosByDeveloperName();
        TestUtilities.enableLicenses(2, 2, 2, 2, 2, 30);
        ITestDefaults userCreation = new CopadoSetupTestDefaults.UserDefaults().createRunAsUsers().executeDML();
        User standardUser = userCreation.getRunAsUsers().get('Standard')[0];
        System.runAs(standardUser) {
            TestUtilities.assignLicense(String.valueOf(standardUser.Username), true, false, false, false, false);
            
            List<Environment__c> envList = TestDataFactory.createEnvironments(2);
            
            List<Org__c> orgList = TestDataFactory.createOrgCredentials(2, standardUser.Username, envList);
            
            ITestDefaults deploymentDefaults = new CopadoUserStoryTestDefaults.DeploymentDefaults()
                .setFieldDefaults()
                .setFieldValue(
                    Deployment__c.SObjectType,
                    Deployment__c.RecordTypeId,
                    deploymentRecordTypes.get('Automation_Template').getRecordTypeId()
                )
                .setFieldValue(Deployment__c.SObjectType, Deployment__c.ApiName__c, 'Deployment')
                .setDataSize(Deployment__c.SObjectType, 1)
                .generateDefaults()
                .includeDefaults(CopadoUserStoryTestDefaults.DeploymentStepDefaults.class)
                .setFieldValue(Step__c.SObjectType, Step__c.Type__c, 'Salesforce Flow')
                .setFieldValue(Step__c.SObjectType, Step__c.DataJson__c, '{"flowApiName": "TestFlow","type":"wait","flowParameters":[]}')
                .setDataSize(Step__c.SObjectType, 10)
                .setSObjectRelation(
                    Step__c.SObjectType,
                    Deployment__c.SObjectType,
                    new Map<Schema.SObjectField, Integer>{ Step__c.Deployment__c => 1 }
                )
                .generateDefaults()
                .executeDML();
        }
    }
}