Dummy_Package_for_scratch_org/main/default/objects/Automation_Template_For_CLI__c/fields/Automation_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Automation_Template_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>API name of Automation template</inlineHelpText>
    <label>Automation Template Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only Active Templates are available when searching for them, for example in deployment steps</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>This is a mandatory field if you intend to publish your automation template as copado extension package</inlineHelpText>
    <label>Api Name</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <label>Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/dataJson__c.field-meta.xml
<CustomField>
    <fullName>dataJson__c</fullName>
    <description>If the step type is &quot;data&quot;  this should contains the json defining the query. 
In production this field should be HIDDEN</description>
    <label>dataJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/AutomationTemplateUpgrade.cls
public with sharing class AutomationTemplateUpgrade implements CLIInterface {
    
    // PUBLIC

    public CLIInterface getInstance() {
        return new AutomationTemplateUpgrade();
    }

    public String run(CliProxy.CLIWrapper record) {
        List<AutomationTemplate> result = new List<AutomationTemplate>();

        for(Deployment__c automationTemplate : new DeploymentsSelector().byNameWithSteps(templateNames())) {
            result.add(asAutomationTemplate(automationTemplate));
        }

        return toResponse(result);
    }


    // PRIVATE
    
    private String toResponse(List<AutomationTemplate> automationTemplates) {
        Response result = new Response(CliSfDataWrapper.StatusResult.OK.name(), 'Templates loaded successfully', automationTemplates);
        
        return (JSON.serialize(result, true));
    }

    private AutomationTemplate asAutomationTemplate(Deployment__c deployment) {
        AutomationTemplate result = new AutomationTemplate();
        result.id = deployment.Id;
        result.label = deployment.Name;
        result.name = deployment.ApiName__c;
        result.isActive = deployment.Active__c;
        result.steps = asSteps(deployment.Steps__r);
        result.description = deployment.Description__c;

        return result;
    }

    private List<Step> asSteps(List<Step__c> deploymentSteps) {
        List<Step> result = new List<Step>();
        
        for(Step__c deploymentStep : deploymentSteps) {
            Step step = new Step();
            step.id = deploymentStep.Id;
            step.label = deploymentStep.Name;
            step.json = (StepJson) JSON.deserialize(deploymentStep.dataJson__c, StepJson.class);

            result.add(step);
        }
        
        return result;
    }

    private Set<String> templateNames() {
        Set<String> result = new Set<String>();

        for(Automation_Template_For_CLI__c cliTemplate : Automation_Template_For_CLI__c.getAll().values()) {
            result.add(cliTemplate.Automation_Template_Name__c);
        }

        return result;
    }

    public class AutomationTemplate { 
        public String id;
        public String name;
        public String label;
        public Boolean isActive;
        public List<Step> steps;
        public String description;
    }

    public class Step { 
        public String id;
        public String label;
        public StepJson json;
    }

    public class StepJson { 
        public String type;
        public String flowApiName;
        public String functionAPIName;
        public List<List<String>> flowParameters;
        public List<Parameter> functionParameters;
    }

    // INNER

    @TestVisible
    private class Response extends CliSfDataWrapper {
        List<AutomationTemplate> automationTemplates;

        public Response(String stat, String msg, List<AutomationTemplate> templates) {
            status = stat;
            message = msg;
            automationTemplates = templates;
        }
    }
}