Dummy_Package_for_scratch_org/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Application_Feature__c/Application_Feature__c.object-meta.xml
<CustomObject>
    <description>Copado&apos;s Feature object enables you to manage Features related to User Stories &amp; Applications. Features are made up of multiple User Stories.</description>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Application_Feature__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>ApplicationFeatures</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Application_Feature__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of Feature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Ready for Refinement</fullName>
            </value>
            <value>
                <fullName>Refinement in Progress</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Coming Soon</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Feature__c/Feature__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Track what Copado features the installation has access to.</description>
    <label>Feature</label>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User story that originated the result.</description>
    <inlineHelpText>User story that originated the result.</inlineHelpText>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Result</relationshipLabel>
    <relationshipName>Result</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Test Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feature</label>
    <referenceTo>Application_Feature__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ready for Test</fullName>
            </value>
            <value>
                <fullName>Testing in Progress</fullName>
            </value>
            <value>
                <fullName>Testing Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/TestType__mdt/fields/ExecuteVia__c.field-meta.xml
<CustomField>
    <fullName>ExecuteVia__c</fullName>
    <label>ExecuteVia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/TestType__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feature</label>
    <referenceTo>Copado_Feature__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <formula>IMAGE(&quot;/img/samples/color_green.gif&quot;, &quot;Completed&quot;, 15, (Progress__c*100) * 2) &amp;
IMAGE(&quot;/img/samples/color_yellow.gif&quot;, &quot;white&quot;, 15,
200 - ((Progress__c*100)* 2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Progress Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the implementation of the User Story.</description>
    <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/US_Feature__c.field-meta.xml
<CustomField>
    <fullName>US_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feature</label>
    <referenceTo>Application_Feature__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/TestsManagerCtrlTest.cls
@isTest
private with sharing class TestsManagerCtrlTest {
    private static String category = 'Mock Type';
    private static String tool = 'Mock Tool';

    @TestSetup
    private static void setupData() {
        insertData();
    }

    @isTest
    private static void executeForUserStory() {
        System.runAs(getTestUser()) {
            // Setup
            insertMockTestType();
            User_Story__c mockUserStory = getMockUserStory();

            // Exercise
            TestsManagerCtrl.runTestsOf(mockUserStory.Id);

            // Verify
            List<Result__c> results = [SELECT Job_Type__c, Progress_Status__c, Status__c FROM Result__c];
            System.assertEquals(5, results.size(), '5 results should have been created for the test execution');
            assertMockResult(results[0]);
        }
    }

    @isTest
    private static void executeForFeature() {
        System.runAs(getTestUser()) {
            // Setup
            insertMockTestType();
            Application_Feature__c mockFeature = getMockFeature();

            // Exercise
            TestsManagerCtrl.runTestsOf(mockFeature.Id);

            // Verify
            List<Result__c> results = [SELECT Job_Type__c, Progress_Status__c, Status__c FROM Result__c];
            System.assertEquals(10, results.size(), '10 results should have been created for the test execution');
            assertMockResult(results[0]);
        }
    }

    @isTest
    private static void executeForApplication() {
        System.runAs(getTestUser()) {
            // Setup
            insertMockTestType();
            Application__c mockApplication = getMockApplication();

            // Exercise
            TestsManagerCtrl.runTestsOf(mockApplication.Id);

            // Verify
            List<Result__c> results = [SELECT Job_Type__c, Progress_Status__c, Status__c FROM Result__c];
            System.assertEquals(15, results.size(), '15 results should have been created for the test execution');
            assertMockResult(results[0]);
        }
    }

    @isTest
    private static void executeWithoutExtensionSet() {
        System.runAs(getTestUser()) {
            // Setup
            User_Story__c mockUserStory = getMockUserStory();

            // Exercise
            Exception ex;
            try {
                TestsManagerCtrl.runTestsOf(mockUserStory.Id);
            } catch (Exception e) {
                ex = e;
            }

            // Verify
            System.assertEquals(ex.getMessage(), Label.NoTestExtensionConfigured, 'Exception should be: ' + Label.NoTestExtensionConfigured);
        }
    }

    @isTest
    private static void getTestsForUserStory() {
        System.runAs(getTestUser()) {
            // Setup
            insertMockTestType();
            User_Story__c mockUserStory = getMockUserStory();
            createRelatedResults(mockUserStory.Id);

            // Exercise
            List<TestsManagerCtrl.TestWrapper> tests = TestsManagerCtrl.getTests(mockUserStory.Id);

            // Verify
            System.assertEquals(5, tests.size(), 'there should be 5 tests for user story');
            assertGetTestMockResult(tests[0]);
        }
    }

    @isTest
    private static void getTestsForFeature() {
        System.runAs(getTestUser()) {
            // Setup
            insertMockTestType();
            Application_Feature__c mockFeature = getMockFeature();
            createRelatedResults(mockFeature.Id);

            // Exercise
            List<TestsManagerCtrl.TestWrapper> tests = TestsManagerCtrl.getTests(mockFeature.Id);

            // Verify
            System.assertEquals(10, tests.size(), 'there should be 10 tests for Feature');
            assertGetTestMockResult(tests[0]);
        }
    }

    @isTest
    private static void getTestsForApplication() {
        System.runAs(getTestUser()) {
            // Setup
            insertMockTestType();
            Application__c mockApplication = getMockApplication();
            createRelatedResults(mockApplication.Id);

            // Exercise
            List<TestsManagerCtrl.TestWrapper> tests = TestsManagerCtrl.getTests(mockApplication.Id);

            // Verify
            System.assertEquals(15, tests.size(), 'there should be 15 tests for application');
            assertGetTestMockResult(tests[0]);
        }
    }

    @SuppressWarnings('PMD.ApexUnitTestMethodShouldHaveIsTestAnnotation')
    private static void assertMockResult(Result__c mockResult) {
        System.assertEquals('Mock Type', mockResult.Job_Type__c, 'Result Job Type should be Mock Type');
        System.assertEquals('Success', mockResult.Progress_Status__c, 'Result Progress Status should be Completed');
        System.assertEquals('Success', mockResult.Status__c, 'Result Status should be Completed');
    }

    @SuppressWarnings('PMD.ApexUnitTestMethodShouldHaveIsTestAnnotation')
    private static void assertGetTestMockResult(TestsManagerCtrl.TestWrapper test) {
        Result__c result = [SELECT Id, Name FROM Result__c WHERE Test__c = :test.Id LIMIT 1];

        System.assertEquals('Mock Test 1', test.name, 'Test Name should be Mock Test 1');
        System.assertEquals('Mock Type', test.testType, 'Test Type should be Mock Type');
        System.assertEquals('Mock Tool', test.testTool, 'Test Tool should be Mock Tool');
        System.assertEquals('Success', test.status, 'Result Status should be Success');
        System.assertEquals(result.Name, test.result, 'Result Status should be ' + result.Name);
        System.assertEquals('/' + result.id, test.resultUrl, 'Result Status should be ' + test.resultUrl);
        System.assertEquals(
            System.now().format('dd/MM/yyyy hh:mm a'),
            test.runDate,
            'Result Run date should be ' + System.now().format('dd/MM/yyyy hh:mm a')
        );
    }

    private static void insertData() {
        ITestDefaults userCreation = new CopadoSetupTestDefaults.UserDefaults().createRunAsUsers().executeDML();
        User adminUser = userCreation.getRunAsUsers().get('Admin')[0];

        System.runAs(adminUser) {
            createMockData();
        }
    }

    private static User getTestUser() {
        User testUser = [SELECT Id, Name, LastName, Email, Username FROM User WHERE Email = 'test@test.org' LIMIT 1].get(0);
        TestUtilities.assignLicense(String.valueOf(testUser.Username), true, true, true, true, true);

        return testUser;
    }

    private static void createMockData() {
        Application__c app = new Application__c();
        insert app;

        Application_Feature__c feature = new Application_Feature__c();
        feature.Application__c = app.Id;
        insert feature;

        User_Story__c us = new User_Story__c();
        us.US_Feature__c = feature.Id;
        insert us;

        insertTestRecords(us.Id);
        insertTestRecords(feature.Id);
        insertTestRecords(app.Id);
    }

    private static void insertTestRecords(String parentId) {
        List<Test__c> tests = new List<Test__c>();

        for (Integer i = 1; i <= 5; i++) {
            Test__c test = new Test__c();
            test.Name = 'Mock Test ' + i;
            test.Category__c = category;
            test.Tool__c = tool;
            linkTestTo(parentId, test);
            tests.add(test);
        }
        insert tests;
    }

    private static void linkTestTo(Id parentId, Test__c test) {
        SObjectType sobjectType = parentId.getSObjectType();

        if (sobjectType == User_Story__c.sObjectType) {
            test.User_Story__c = parentId;
        } else if (sobjectType == Application_Feature__c.sObjectType) {
            test.Feature__c = parentId;
        } else if (sobjectType == Application__c.sObjectType) {
            test.Application__c = parentId;
        }
    }

    private static void createRelatedResults(Id parentId) {
        List<Result__c> results = new List<Result__c>();
        List<Test__c> tests = new TestsSelector().byParent(parentId);

        for (Test__c test : tests) {
            results.add(testMethodUtilities.createResult(test.Id));
        }

        insert results;
    }

    private static User_Story__c getMockUserStory() {
        return [SELECT Id FROM User_Story__c LIMIT 1];
    }

    private static Application_Feature__c getMockFeature() {
        return [SELECT Id FROM Application_Feature__c LIMIT 1];
    }

    private static Application__c getMockApplication() {
        return [SELECT Id FROM Application__c LIMIT 1];
    }

    private static List<Test__c> getMockTests() {
        return [SELECT Name, Tool__c FROM Test__c];
    }

    private static void insertMockTestType() {
        TestType__mdt mockTestType = new TestType__mdt();
        mockTestType.ExecuteVia__c = 'TestExtensionMock';
        mockTestType.Namespace__c = '';
        mockTestType.Category__c = category;
        mockTestType.Tool__c = tool;

        TestTypesSelector.mock(new List<TestType__mdt>{ mockTestType });
    }
}