Dummy_Package_for_scratch_org/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Feature__c/Feature__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Track what Copado features the installation has access to.</description>
    <label>Feature</label>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Date time when the job started.</description>
    <inlineHelpText>Date time when the job started.</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User story that originated the result.</description>
    <inlineHelpText>User story that originated the result.</inlineHelpText>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Result</relationshipLabel>
    <relationshipName>Result</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Test Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feature</label>
    <referenceTo>Application_Feature__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <displayFormat>TE-{0000000}</displayFormat>
    <label>Reference</label>
    <type>AutoNumber</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feature</label>
    <referenceTo>Copado_Feature__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/TestsSelector.cls
public with sharing class TestsSelector extends fflib_SObjectSelector {
    private static final String BY_PARENT_CONDITION = 'User_Story__c = :parentId OR Feature__c = :parentId OR Application__c = :parentId';

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{
            Test__c.Id,
            Test__c.Name,
            Test__c.Reference__c,
            Test__c.Category__c,
            Test__c.Tool__c,
            Test__c.User_Story__c,
            Test__c.Configuration__c
        };
    }

    public SObjectType getSObjectType() {
        return Test__c.sObjectType;
    }

    public List<Test__c> byIds(Set<Id> ids) {
        return (List<Test__c>) Database.query(newQueryFactory().setEnforceFLS(true).setCondition('Id IN :ids').toSOQL());
    }

    public List<Test__c> byParent(Id parentId) {
        return (List<Test__c>) Database.query(newQueryFactory().setEnforceFLS(true).setCondition(BY_PARENT_CONDITION).toSOQL());
    }

    public List<Test__c> byParentWithLatestResult(Id parentId) {
        fflib_QueryFactory query = newQueryFactory().setEnforceFLS(true).setCondition(BY_PARENT_CONDITION);
        String resultRelationship = Settings.ns + 'Results__r';

        query.subselectQuery(resultRelationship)
            .selectFields(new ResultsSelector().getSObjectFieldList())
            .addOrdering('Start_Time__c', fflib_QueryFactory.SortOrder.DESCENDING, true)
            .setLimit(1);
        
        return (List<Test__c>) Database.query(query.toSOQL());
    }
}