Dummy_Package_for_scratch_org/main/default/objects/SensitiveProperty__mdt/SensitiveProperty__mdt.object-meta.xml
<CustomObject>
    <description>Stores values of a System Property of sensitive type(Name of the record maps to system property)</description>
    <label>Sensitive Property</label>
    <pluralLabel>Sensitive Properties</pluralLabel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/SensitiveProperty__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Stores encrypted version of System setting of sensitive type</description>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/SensitivePropertySelector.cls
public with sharing class SensitivePropertySelector extends fflib_SObjectSelector {

    private static List<SensitiveProperty__mdt> mock = new List<SensitiveProperty__mdt>();
    
    public Schema.SObjectType getSObjectType() {
        return SensitiveProperty__mdt.SObjectType;
    }


    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            SensitiveProperty__mdt.Id,
            SensitiveProperty__mdt.Value__c,
            SensitiveProperty__mdt.DeveloperName
        };
    }


    public List<SensitiveProperty__mdt> byName(Set<Id> systemPropertyIds) {
        return (Test.isRunningTest()) ? mock : 
                (List<SensitiveProperty__mdt>) Database.query( newQueryFactory()
                                                                .setCondition(SensitiveProperty__mdt.DeveloperName + ' IN :systemPropertyIds')
                                                                .toSOQL() );
    }
    
    
    public static void mock(List<SensitiveProperty__mdt> properties) {
        mock = properties;
    }
}