Dummy_Package_for_scratch_org/main/default/objects/SensitiveProperty__mdt/SensitiveProperty__mdt.object-meta.xml
<CustomObject>
    <description>Stores values of a System Property of sensitive type(Name of the record maps to system property)</description>
    <label>Sensitive Property</label>
    <pluralLabel>Sensitive Properties</pluralLabel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/SensitiveProperty__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Stores encrypted version of System setting of sensitive type</description>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/System_Property__c.object-meta.xml
<CustomObject>
    <label>System Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Is_Sensitive__c.field-meta.xml
<CustomField>
    <fullName>Is_Sensitive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this field is selected, the value won&apos;t be accessible to any user, and it will be securely saved. The value will remain hidden unless the field is unchecked</inlineHelpText>
    <label>Hide Value</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/EncryptSensitiveProperties_Test.cls
@IsTest 
private class EncryptSensitiveProperties_Test {

    @IsTest
    private static void insertNonSenstitiveProperties() {

        // Exercise
        System_Property__c property = new System_Property__c();
        property.Is_Sensitive__c = false;
        property.Value__c = 'Sample Value';
        property.API_Name__c = 'InsensitivrProperty';

        property.User__c = UserInfo.getUserId();
        insert property;


        // Verify
        System.assertEquals('Sample Value', [SELECT Value__c FROM System_Property__c].Value__c);
    }
    

    @IsTest
    private static void insertSenstitiveProperties() {

        // Setup
        Test.setMock(WebServiceMock.class, new MdApiMock());
        
        // Exercise
        Test.startTest();
            System_Property__c property = new System_Property__c();
            property.Is_Sensitive__c = true;
            property.Value__c = 'Sample Value';
            property.API_Name__c = 'InsensitivrProperty';


        property.User__c = UserInfo.getUserId();
        insert property;
        Test.stopTest();



        // Verify
        System.assertEquals(null, [SELECT Value__c FROM System_Property__c].Value__c);
    }
   

    @IsTest
    private static void updateSenstitiveProperties() {

        // Setup
        Test.setMock(WebServiceMock.class, new MdApiMock());
        System_Property__c property = new System_Property__c();
        property.Is_Sensitive__c = true;
        property.Value__c = 'Sample Value';
        property.API_Name__c = 'InsensitivrProperty';


        property.User__c = UserInfo.getUserId();
        insert property;

        // Exercise
        Test.startTest();


        	property.Value__c = 'Updated Value';
        	update property;
		Test.stopTest();
        


        // Verify
        System.assertEquals(null, [SELECT Value__c FROM System_Property__c].Value__c);
    }
   

    @IsTest
    private static void updateNonSenstitivePropertiesToSensitive() {

        // Setup
        Test.setMock(WebServiceMock.class, new MdApiMock());
        System_Property__c property = new System_Property__c();
        property.Is_Sensitive__c = false;
        property.Value__c = 'Sample Value';
        property.API_Name__c = 'InsensitivrProperty';


        property.User__c = UserInfo.getUserId();
        insert property;

        // Exercise
        Test.startTest();


        	property.Is_Sensitive__c = true;
        	update property;
		Test.stopTest();
        


        // Verify
        System.assertEquals(null, [SELECT Value__c FROM System_Property__c].Value__c);
    }


    @IsTest
    private static void updateSenstitivePropertiesToNonSensitive() {

        // Setup
        Test.setMock(WebServiceMock.class, new MdApiMock());
        System_Property__c property = new System_Property__c();
        property.Is_Sensitive__c = true;
        property.Value__c = 'Sample Value';
        property.API_Name__c = 'InsensitivrProperty';


        property.User__c = UserInfo.getUserId();
        insert property;

        SensitivePropertySelector.mock(
            new List<SensitiveProperty__mdt>{
                new SensitiveProperty__mdt(DeveloperName = property.Id, Value__c = DeployAPI.encryptAPIKey('Sample Value'))
            }
        );



        // Exercise
        Test.startTest();
        	property.Is_Sensitive__c = false;
	        property.Value__c = null;
        	update property;
		Test.stopTest();
        


        // Verify
        System.assertEquals('Sample Value', [SELECT Value__c FROM System_Property__c].Value__c);
    }

    @IsTest
    private static void deleteSenstitiveProperties() {


        // Setup
        Test.setMock(WebServiceMock.class, new MdApiMock());
        System_Property__c property = new System_Property__c();
        property.Is_Sensitive__c = true;
        property.Value__c = 'Sample Value';
        property.API_Name__c = 'InsensitiveProperty';

        property.User__c = UserInfo.getUserId();

        insert property;
        
        SensitivePropertySelector.mock(new List<SensitiveProperty__mdt> {});
        


        // Exercise
        Test.startTest();
        	delete property;
		Test.stopTest();
        


        // Verify
        System.assertEquals(0, new SensitivePropertySelector().byName(new Set<Id> { property.Id}).size());
    }



    private class MdApiMock implements WebServiceMock {
        public void doInvoke(
            Object stub,
            Object request,
            Map<String, Object> response,
            String endpoint,
            String soapAction,
            String requestName,
            String responseNS,
            String responseName,
            String responseType
        ) {
            if (requestName == 'deleteMetadata') {
                response.put('response_x', deleteResponse());
            } else if (requestName == 'updateMetadata') {
                response.put('response_x', updateResponse());
            } else {


                response.put('response_x', createResponse());
            }
        }
        


        private MetadataService.createMetadataResponse_element createResponse() {
            MetadataService.createMetadataResponse_element responseElement = new MetadataService.createMetadataResponse_element();
            MetadataService.SaveResult sr = new MetadataService.SaveResult();
            sr.success = true;

            responseElement.result = new List<MetadataService.SaveResult>{ sr };
            
            return responseElement;
        }
        


        private MetadataService.updateMetadataResponse_element updateResponse() {
            MetadataService.updateMetadataResponse_element responseElement = new MetadataService.updateMetadataResponse_element();
            MetadataService.SaveResult sr = new MetadataService.SaveResult();
            sr.success = true;

            responseElement.result = new List<MetadataService.SaveResult>{ sr };
            
            return responseElement;
        }
        


        private MetadataService.deleteMetadataResponse_element deleteResponse() {
            MetadataService.deleteMetadataResponse_element responseElement = new MetadataService.deleteMetadataResponse_element();

            MetadataService.DeleteResult sr = new MetadataService.DeleteResult();
            sr.success = true;

            responseElement.result = new List<MetadataService.DeleteResult>{ sr };
            
            return responseElement;
        }
    }
}