Dummy_Package_for_scratch_org/main/default/objects/SensitiveProperty__mdt/SensitiveProperty__mdt.object-meta.xml
<CustomObject>
    <description>Stores values of a System Property of sensitive type(Name of the record maps to system property)</description>
    <label>Sensitive Property</label>
    <pluralLabel>Sensitive Properties</pluralLabel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/System_Property__c.object-meta.xml
<CustomObject>
    <label>System Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Is_Sensitive__c.field-meta.xml
<CustomField>
    <fullName>Is_Sensitive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this field is selected, the value won&apos;t be accessible to any user, and it will be securely saved. The value will remain hidden unless the field is unchecked</inlineHelpText>
    <label>Hide Value</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/DeleteSensitiveProperties.cls
public with sharing class DeleteSensitiveProperties implements Queueable, Database.AllowsCallouts {
    
    private List<System_Property__c> propertiesToBeDeleted = new List<System_Property__c>();
    
    // CONSTRUCTOR

    public DeleteSensitiveProperties(List<System_Property__c> records) {
        propertiesToBeDeleted = filterSensitiveRecords(records);
    }


    // PUBLIC

    public void execute() {
        if(!propertiesToBeDeleted.isEmpty()) {
            System.enqueueJob(this);
        }

    }


    public void execute(QueueableContext context) {
        CustomMetadata.deleteMetadata('CustomMetadata', sensitivePropertyNames());
    }


    // PRIVATE


    private List<System_Property__c> filterSensitiveRecords(List<System_Property__c> properties) {
        List<System_Property__c> result = new List<System_Property__c>();

        for(System_Property__c property : properties) {
            if(property.Is_Sensitive__c) {
                result.add(property);
            }
        }

        return result;
    }

    private List<String> sensitivePropertyNames() {
        List<String> result = new List<String>();

        for(System_Property__c property : propertiesToBeDeleted) {
            String metadataName = Settings.ns + 'SensitiveProperty__mdt.' + property.Id;

            result.add(metadataName);
        }

        return result;
    }
}