Dummy_Package_for_scratch_org/main/default/objects/CustomFunctionUsage__c/CustomFunctionUsage__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CustomFunctionUsage</label>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/CustomFunctionUsage__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/CustomFunctionUsage__c/fields/Year_Month__c.field-meta.xml
<CustomField>
    <fullName>Year_Month__c</fullName>
    <label>Year Month</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <inlineHelpText>This is used to validate if all required parameters are set before calling the execution.</inlineHelpText>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>The number of minutes after which the function will automatically end if there is no response from the function backend execution.</description>
    <inlineHelpText>The number of minutes after which the function will automatically end if there is no response from the function backend execution.</inlineHelpText>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Custom&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Worker_Size__c.field-meta.xml
<CustomField>
    <fullName>Worker_Size__c</fullName>
    <label>Worker Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <default>true</default>
                <label>S</label>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/ResultId__c.field-meta.xml
<CustomField>
    <fullName>ResultId__c</fullName>
    <label>Result Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Disable_Validation__c.field-meta.xml
<CustomField>
    <fullName>Disable_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this checkbox will not validate the credentials when the record is saved or viewed.</inlineHelpText>
    <label>Disable Validation</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Oauth_Signature__c.field-meta.xml
<CustomField>
    <fullName>Oauth_Signature__c</fullName>
    <description>This value is automatically set and updated by Copado.</description>
    <inlineHelpText>This value is automatically set and updated by Copado.</inlineHelpText>
    <label>Oauth Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/SFDC_Org_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Org_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Organization Id for the Environment.</description>
    <externalId>true</externalId>
    <inlineHelpText>Organization Id for the Environment.</inlineHelpText>
    <label>SFDC Org ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Validated_Date__c.field-meta.xml
<CustomField>
    <fullName>Validated_Date__c</fullName>
    <description>Latest OAuth authentication validation date.</description>
    <inlineHelpText>Latest OAuth authentication validation date.</inlineHelpText>
    <label>Validated Date</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/ApexCallback__c.field-meta.xml
<CustomField>
    <fullName>ApexCallback__c</fullName>
    <description>This field is updated automatically by Copado.</description>
    <inlineHelpText>This field is updated automatically by Copado.</inlineHelpText>
    <label>Apex Callback</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copado Function that triggered this result.</inlineHelpText>
    <label>Function</label>
    <referenceTo>Function__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function_Worker_Size__c.field-meta.xml
<CustomField>
    <fullName>Function_Worker_Size__c</fullName>
    <label>Function Worker Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Date time when the job started.</description>
    <inlineHelpText>Date time when the job started.</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/Function.cls
@SuppressWarnings('PMD.CyclomaticComplexity')
public with sharing class Function implements Queueable, Database.AllowsCallouts {
    private Boolean automatedProcess = UserInfo.getUserType() == 'AutomatedProcess';

    private Result__c result;
    private Function__c function;
    private FunctionPayload payload;
    private List<Parameter> parameters;
    private List<Parameter> options;
    private Id stepId;
    private String contextId;
    private String resultCallback;
    private final String apiName;
    private Boolean showValidationErrors = false;
    private Boolean isValidCredential = true;

    @TestVisible
    private static MC_Result__e mockResponse;

    // CONSTRUCTOR

    public Function(String apiName) {
        this.apiName = apiName;
    }

    // PUBLIC

    public Function contextId(String contextId) {
        this.contextId = contextId;
        return this;
    }

    public Function stepId(Id stepId) {
        this.stepId = stepId;
        return contextId(stepId);
    }

    public Function parameters(List<Parameter> parameters) {
        this.parameters = parameters;
        return this;
    }

    public Function options(List<Parameter> options) {
        this.options = options;
        return this;
    }

    public Function resultCallback(String resultCallback) {
        this.resultCallback = resultCallback;
        return this;
    }

    public Function showValidationErrors(Boolean showValidationErrors) {
        this.showValidationErrors = showValidationErrors;
        return this;
    }

    public Id execute() {
        try {
            function = new FunctionsSelector().byApiName(apiName);
            parameters = new TemplatingEngine(contextId, parameters).parse();
            isValidCredential = UserInfo.getUserType() == 'AutomatedProcess' || isValidCredential();
            result = createResult();
            validateFunction();
            if(Test.isRunningTest() && mockResponse != null) {
                mockResponse.ResultId__c = result.Id;
                Eventbus.publish(mockResponse);
            } else {
                verifyUser();
                checkCredits();
                payload = payload();
                System.enqueueJob(this);
            }
        } catch (Exception ex) {
            // needed for ease of internal troubleshooting when an error occurs in a subscriber org.
            System.debug(LoggingLevel.ERROR, 'error: ' + ex.getMessage() + ': ' + ex.getStackTraceString());
            CopadoFunctionException error = error(ex);
            if (showValidationErrors) {
                throw error;
            }
        }

        return result.Id;
    }

    public void execute(QueueableContext ctx) {
        try {
            new FunctionCallout(result.Id).payload(payload.toJson()).contextId(contextId).build().request().parseResponse();
        } catch (Exception ex) {
            error(ex);
        }
    }

    // PRIVATE

    private void verifyUser() {
        if (!automatedProcess) {
            checkLicense();
            checkAPIKey();
            checkCredential();
        }
    }

    private void checkLicense() {
        if (!FeatureHelper.isFunctionEnabled()) {
            throw new CopadoFunctionException(Label.FunctionNotEnabled);
        }
    }

    private void checkCredits() {
        if (isFunctionCustom(function)) {
            if (hardLimitReached()) {
                throw new CopadoFunctionException(Label.Function_Credit_Limit_Exceeded);
            }

            if(monthlyUsage().isEmpty()) {
                resetCredits();
            }
        }
    }

    private Boolean isFunctionCustom(Function__c function) {
        return function.Type__c != 'Standard';
    }

    private Boolean hardLimitReached() {
        return FeatureManagement.checkPackageIntegerValue('CustomFunctionHardCreditLimit') <=
            FeatureManagement.checkPackageIntegerValue('CustomFunctionCreditUsage');
    }

    private void resetCredits() {
        updateCustomFunctionCreditUsage(0);

        insert new CustomFunctionUsage__c(Name = String.valueOf(Date.today()), Year_Month__c = Date.today(), Credits__c = 0);
    }

    @Future
    private static void updateCustomFunctionCreditUsage(Integer usage) {
        FeatureManagement.setPackageIntegerValue('CustomFunctionCreditUsage', usage);
    }

    private List<CustomFunctionUsage__c> monthlyUsage() {
        // Protected system object, no security checks needed.
        return [
            SELECT Id
            FROM CustomFunctionUsage__c
            WHERE CALENDAR_YEAR(Year_Month__c) = :Date.today().year() AND CALENDAR_MONTH(Year_Month__c) = :Date.today().month()
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
    }

    private void checkAPIKey() {
        Personal_Settings__c settings = Personal_Settings__c.getInstance();
        if (settings == null || String.isBlank(settings.API_Key__c)) {
            throw new CopadoFunctionException(Label.Copado_API_Key_Required);
        }
    }

    private void checkCredential() {
        if (!isValidCredential) {
            throw new CopadoFunctionException(Label.Org_Credential_not_Validated);
        }
    }

    private Boolean isValidCredential() {
        Org__c credential = credential();

        return validatedRecently(credential) || validate(credential);
    }

    private Boolean validate(Org__c credential) {
        Boolean result;
        
        try {
            result = DeployAPI.validateOrg(credential.Id);
        } catch (Exception ex) {
            result = false;
        }
        
        return result;
    }

    private Org__c credential() {
        String sfdcOrgId = UserInfo.getOrganizationId() + '_' + UserInfo.getUserId();

        List<Org__c> credentials = [
            SELECT Disable_Validation__c, Oauth_Signature__c, Validated_Date__c
            FROM Org__c
            WHERE SFDC_Org_ID__c = :sfdcOrgId AND Username__c = :UserInfo.getUserName()
            WITH SECURITY_ENFORCED
        ];

        if (credentials.isEmpty()) {
            throw new CopadoFunctionException(Label.Credential_not_Found);
        }

        return credentials[0];
    }

    private Boolean validatedRecently(Org__c credential) {
        // TODO: Move validated date to custom setting
        return String.isNotBlank(credential.Oauth_Signature__c) && credential.Validated_Date__c >= Datetime.now().addDays(-1);
    }
  
    private void validateFunction() {
        if(function == null) {
            throw new CopadoFunctionException(Label.Function_not_Found + ': ' + apiName);
        }
    }

    private FunctionPayload payload() {
        return new FunctionPayload(function).parameters(parameters).options(options).validate(function.Parameters__c).resultId(result.Id);
    }

    private Result__c createResult() {
        Result__c result = new Result__c(
            JobStep__c = stepId,
            ParentId__c = contextId,
            Status__c = 'In Progress',
            Job_Type__c = apiName,
            Start_Time__c = Datetime.now(),
            ApexCallback__c = resultCallback,
            Function__c = function?.Id,
            Timeout__c = function?.Timeout__c,
            Function_Worker_Size__c = function?.Worker_Size__c
        );

        SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, new List<Result__c>{ result });
        result = (Result__c) decision.getRecords()[0];
        insert result;

        return result;
    }

    private CopadoFunctionException error(Exception ex) {
        CopadoFunctionException error = new CopadoFunctionException(ex.getMessage())
            .resultId(result?.Id)
            .contextId(contextId)
            .function(function)
            .stepId(stepId)
            .updateResult()
            .updateContext();

        return error;
    }
}