Dummy_Package_for_scratch_org/main/default/objects/CustomFunctionUsage__c/CustomFunctionUsage__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CustomFunctionUsage</label>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/CustomFunctionUsage__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/CustomFunctionUsage__c/fields/Year_Month__c.field-meta.xml
<CustomField>
    <fullName>Year_Month__c</fullName>
    <label>Year Month</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Handler format: ClassName
The class must implement the MCCallBack interface.</description>
    <inlineHelpText>Handler format: ClassName
The class must implement the MCCallBack interface.</inlineHelpText>
    <label>ApexClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Callback_Type__c.field-meta.xml
<CustomField>
    <fullName>Callback_Type__c</fullName>
    <description>Trigger a Flow or Apex class each time a function execution completes. This trigger happens when the function result status changes to Success or Failed.</description>
    <inlineHelpText>Trigger a Flow or Apex class each time a function execution completes. This trigger happens when the function result status changes to Success or Failed.</inlineHelpText>
    <label>Callback Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ApexClass</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/FlowHandler__c.field-meta.xml
<CustomField>
    <fullName>FlowHandler__c</fullName>
    <description>Handler format: FlowAPIName</description>
    <inlineHelpText>Handler format: FlowAPIName</inlineHelpText>
    <label>FlowHandler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Custom&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/IsFinished__c.field-meta.xml
<CustomField>
    <fullName>IsFinished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Finished</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Success</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/Result_Data__c.field-meta.xml
<CustomField>
    <fullName>Result_Data__c</fullName>
    <label>Result Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/ResultId__c.field-meta.xml
<CustomField>
    <fullName>ResultId__c</fullName>
    <label>Result Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/ApexCallback__c.field-meta.xml
<CustomField>
    <fullName>ApexCallback__c</fullName>
    <description>This field is updated automatically by Copado.</description>
    <inlineHelpText>This field is updated automatically by Copado.</inlineHelpText>
    <label>Apex Callback</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Custom_Function_Used_Credits__c.field-meta.xml
<CustomField>
    <fullName>Custom_Function_Used_Credits__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Custom Function Used Credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Custom_Function_Used_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Custom_Function_Used_Minutes__c</fullName>
    <label>Custom Function Used Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>Date time when the job ended.</description>
    <inlineHelpText>Date time when the job ended.</inlineHelpText>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copado Function that triggered this result.</inlineHelpText>
    <label>Function</label>
    <referenceTo>Function__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function_Worker_Size__c.field-meta.xml
<CustomField>
    <fullName>Function_Worker_Size__c</fullName>
    <label>Function Worker Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Result_Data__c.field-meta.xml
<CustomField>
    <fullName>Result_Data__c</fullName>
    <label>Result Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Date time when the job started.</description>
    <inlineHelpText>Date time when the job started.</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/HandleBackendResponse.cls
@SuppressWarnings('PMD.CyclomaticComplexity')
public with sharing class HandleBackendResponse {
    @TestVisible
    private static String mockCallback;

    private final Map<String, Decimal> workerSizeCredits = new Map<String, Integer>{ 'S' => 1, 'M' => 2, 'L' => 4, 'XL' => 8 };
    private List<MC_Result__e> records;

    private Integer totalUsedCredits = 0;

    // CONSTRUCTOR

    public HandleBackendResponse(List<MC_Result__e> records) {
        this.records = records;
    }

    @SuppressWarnings('PMD.EmptyStatementBlock')
    public HandleBackendResponse() {
    }

    // PUBLIC

    public void execute() {
        List<Result__c> resultsToUpdate = resultsToUpdate();

        update Security.stripInaccessible(AccessType.UPDATABLE, resultsToUpdate).getRecords();
        updateCreditUsage();
        executeCallbacks(resultsToUpdate);
    }

    public void resultCallback(Function__c function, Id resultId, String status) {
        Result__c result = new ResultsSelector().byIds(new Set<Id>{ resultId })[0];
        result.Status__c = status;

        resultCallback(function, result);
    }

    // PRIVATE

    private List<Result__c> resultsToUpdate() {
        List<Result__c> result = new List<Result__c>();

        Map<Id, MC_Result__e> events = eventsByResult(records);

        for (Result__c record : new ResultsSelector().inProgressByIds(events.keySet())) {
            MC_Result__e event = events.get(record.Id);
            Result__c updatedResult = updatedResult(record, event);

            if (event?.IsFinished__c == true) {
                totalUsedCredits += (Integer) updatedResult.Custom_Function_Used_Credits__c;
            }

            result.add(updatedResult);
        }

        return result;
    }

    private Result__c updatedResult(Result__c record, MC_Result__e event) {
        Integer usedMinutes = (isCustom(record) ? usedMinutes(record.Start_Time__c) : null);

        record.Status__c = statusFromEvent(event);
        record.Result_Data__c = setValue(record.Result_Data__c, event?.Result_Data__c);
        record.Error_Message__c = setValue(record.Error_Message__c, event?.Error_Message__c);
        record.Progress_Status__c = setValue(record.Progress_Status__c, event?.Progress_Status__c);
        record.End_Time__c = (event?.IsFinished__c == true ? Datetime.now() : null);
        record.Custom_Function_Used_Minutes__c = usedMinutes;
        record.Custom_Function_Used_Credits__c = usedCredits(usedMinutes, record.Function_Worker_Size__c);

        return record;
    }

    private String setValue(String oldValue, String newValue) {
        return String.isNotBlank(newValue) ? newValue : oldValue;
    }

    private Boolean isCustom(Result__c result) {
        return result.Function__r.Type__c != 'Standard';
    }

    private void updateCreditUsage() {
        List<CustomFunctionUsage__c> usage = monthlyUsage();

        if (usage.isEmpty()) {
            setCustomFunctionUsage(totalUsedCredits, null);
        } else {
            Integer credits = Integer.valueOf(usage[0].Credits__c + totalUsedCredits);
            setCustomFunctionUsage(credits, usage[0].Id);
        }

        updateMonthlyCreditUsage(totalUsedCredits, usage.isEmpty());
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    private void setCustomFunctionUsage(Integer totalUsedCredits, Id usageId) {
        // Note: protected custom setting
        if (String.isBlank(usageId)) {
            insert new CustomFunctionUsage__c(Name = String.valueOf(Date.today()), Year_Month__c = Date.today(), Credits__c = totalUsedCredits);
        } else {
            update new CustomFunctionUsage__c(Id = usageId, Credits__c = totalUsedCredits);
        }
    }

    @future
    private static void updateMonthlyCreditUsage(Integer totalUsedCredits, Boolean resetCredits) {
        Integer monthlyTotal = resetCredits ? 0 : FeatureManagement.checkPackageIntegerValue('CustomFunctionCreditUsage');
        FeatureManagement.setPackageIntegerValue('CustomFunctionCreditUsage', monthlyTotal + totalUsedCredits);
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    private List<CustomFunctionUsage__c> monthlyUsage() {
        // Note: Protected system object, no security checks needed.
        return [
            SELECT Credits__c
            FROM CustomFunctionUsage__c
            WHERE CALENDAR_YEAR(Year_Month__c) = :Date.today().year() AND CALENDAR_MONTH(Year_Month__c) = :Date.today().month()
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
    }

    private Integer usedMinutes(Datetime startDate) {
        Long startTime = startDate.getTime();
        Long endTime = DateTime.now().getTime();
        Long seconds = (endTime - startTime) / 1000;

        return Math.ceil(seconds / 60).intValue() == 0 ? 1 : Math.ceil(seconds / 60).intValue();
    }

    private Integer usedCredits(Long minutes, String workerSize) {
        return String.isBlank(workerSize) || minutes == null ? 0 : Integer.valueOf(minutes * workerSizeCredits.get(workerSize));
    }

    private Map<Id, MC_Result__e> eventsByResult(List<MC_Result__e> events) {
        Map<Id, MC_Result__e> result = new Map<Id, MC_Result__e>();

        for (MC_Result__e event : events) {
            result.put(event.ResultId__c, event);
        }

        return result;
    }

    private Map<Id, Function__c> functions(List<Result__c> results) {
        Set<Id> functionIds = new Set<Id>();

        for (Result__c result : results) {
            functionIds.add(result.Function__c);
        }

        return new Map<Id, Function__c>(new FunctionsSelector().byIds(functionIds));
    }

    private String statusFromEvent(MC_Result__e event) {
        String result;

        if (event?.IsFinished__c == true) {
            if (event.isSuccess__c) {
                result = 'Success';
            } else {
                result = 'Failed';
            }
        } else {
            result = 'In Progress';
        }

        return result;
    }

    private void executeCallbacks(List<Result__c> results) {
        Map<Id, Function__c> functions = functions(results);

        for (Result__c result : results) {
            try {
                functionCallback(functions.get(result.Function__c), result);
            } catch (Exception ex) {
                result = error(result, ex);
            }

            resultCallback(functions.get(result.Function__c), result);
        }
    }

    private void functionCallback(Function__c function, Result__c result) {
        switch on function.Callback_Type__c {
            when 'ApexClass' {
                executeApex(function, result);
            }
            when 'Flow' {
                executeFlow(function, result);
            }
        }
    }

    private void executeApex(Function__c function, Result__c result) {
        apexCallback(callbackName(function.ApexClass__c)).execute(function, result, result.Status__c);
    }

    private void executeFlow(Function__c function, Result__c result) {
        try {
            createFlowInterview(callbackName(function.FlowHandler__c), flowParameters(function, result));
        } catch (Exception ex) {
            throw new ApplicationException(String.format(Label.Flow_Callback_Failed, new List<String>{ ex.getMessage() }));
        }
    }

    private void resultCallback(Function__c function, Result__c result) {
        if (String.isNotBlank(result.ApexCallback__c)) {
            apexCallback(result.ApexCallback__c).execute(function, result, result.Status__c);
        }
    }

    private String callbackName(String callback) {
        String result;

        if (Test.isRunningTest() && String.isNotBlank(mockCallback)) {
            result = mockCallback;
        } else if (String.isNotBlank(callback)) {
            result = callback;
        }

        return result;
    }

    private Map<String, Object> flowParameters(Function__c function, Result__c result) {
        return new Map<String, Object>{ 'function' => function, 'result' => result, 'status' => result.Status__c };
    }

    private void createFlowInterview(String flowName, Map<String, Object> parameters) {
        Flow.Interview.createInterview(namespace(flowName), handler(flowName), parameters).start();
    }

    private MCCallBack apexCallback(String apexClass) {
        try {
            return ((MCCallBack) Type.forName(namespace(apexClass), handler(apexClass)).newInstance());
        } catch (Exception ex) {
            throw new ApplicationException(
                String.format(Label.Callback_not_Found, new List<String>{ 'ApexClass', apexClass }) +
                ' ' +
                Label.Callback_not_Found_Information
            );
        }
    }

    private String namespace(String name) {
        return name.contains('.') ? name.substringBefore('.') : '';
    }

    private String handler(String name) {
        return name.contains('.') ? name.substringAfter('.') : name;
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    private Result__c error(Result__c result, Exception ex) {
        // Note: needed for ease of internal troubleshooting when an error occurs in a subscriber org.
        System.debug(LoggingLevel.ERROR, 'Error in function/result callback: ' + ex.getMessage() + ': ' + ex.getStackTraceString());

        result.Status__c = 'Failed';
        result.End_Time__c = Datetime.now();
        result.Progress_Status__c = Label.Error;
        result.Error_Message__c = String.format(Label.Function_Callback_Failed, new List<String>{ ex.getMessage() });

        update Security.stripInaccessible(AccessType.UPDATABLE, new List<Result__c>{ result }).getRecords();

        return result;
    }
}