Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/User_Story_Title__c.field-meta.xml
<CustomField>
    <fullName>User_Story_Title__c</fullName>
    <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
    <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
    <label>User Story Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/FilterComponentControllerTest.cls
@isTest
public class FilterComponentControllerTest {
    @isTest
    public static void testgetFields(){
        List<FilterComponentController.FieldListWrapper> listOfField=FilterComponentController.getFields();
        system.assert(listOfField.size()>0);
    }
    @isTest
    public static void testfilterUserStoryRecord(){
        User_Story__c  userStoryobj = new User_Story__c ();
        userStoryobj.User_Story_Title__c ='test user story';
        insert userStoryobj;
        String jsonString = '{"filterString":"[]","ownerString":"All User Stories","recordId":"a1T09000000RGKmEAO","selectFieldSet":"Sprint_Wall_Columns","recordLimit":10000}';

        List<User_Story__c> listOfUserStory = FilterComponentController.filterUserStoryRecord(jsonString);
		FilterComponentController.FieldOperatorValueWrapper obj= new FilterComponentController.FieldOperatorValueWrapper();
        obj.valueForField='2';
        obj.fieldLableSelected='Priority';
        obj.fieldSelected='Priority';
        obj.operatorLableSelected='Equal';
        obj.operatorUsed='=';
        obj.valueForField='test';
         
        FilterComponentController.getWhereClause(obj);
        FilterComponentController.getNonStringClause(obj);

        system.assert(listOfUserStory.size()==0);
    }
}