Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The automation template that defined the steps of this deployment.</inlineHelpText>
    <label>Template</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Template Execution</relationshipLabel>
    <relationshipName>Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Git_Backup__c/Git_Backup__c.object-meta.xml
<CustomObject>
    <description>A Git Snapshot record in Copado defines a connection between a Salesforce Org with a Git Repository/branch.</description>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Callback__c.field-meta.xml
<CustomField>
    <fullName>Callback__c</fullName>
    <description>An apex class that must implement copado.JobExecutionCallback interface.</description>
    <inlineHelpText>An apex class that must implement copado.JobExecutionCallback interface.</inlineHelpText>
    <label>Callback</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/DataJson__c.field-meta.xml
<CustomField>
    <fullName>DataJson__c</fullName>
    <label>DataJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Job Executions (Destination)</relationshipLabel>
    <relationshipName>Job_Executions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/ParentRecord_Id__c.field-meta.xml
<CustomField>
    <fullName>ParentRecord_Id__c</fullName>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Snapshot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Snapshot</label>
    <referenceTo>Git_Backup__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/UserStoryCommit__c.field-meta.xml
<CustomField>
    <fullName>UserStoryCommit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field relates to the parent User Story Commit record of the job execution</description>
    <inlineHelpText>This field relates to the parent User Story Commit record of the job execution</inlineHelpText>
    <label>User Story Commit</label>
    <referenceTo>User_Story_Commit__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/VolumeOptions__c.field-meta.xml
<CustomField>
    <fullName>VolumeOptions__c</fullName>
    <label>VolumeOptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobTemplate__c.field-meta.xml
<CustomField>
    <fullName>JobTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/UserStory__c.field-meta.xml
<CustomField>
    <fullName>UserStory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Deployment Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/VolumeOptions__c.field-meta.xml
<CustomField>
    <fullName>VolumeOptions__c</fullName>
    <inlineHelpText>A JSON containing transaction and volume options</inlineHelpText>
    <label>VolumeOptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with errors</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Validation failed</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
            <value>
                <fullName>Conflicts Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Commit__c/User_Story_Commit__c.object-meta.xml
<CustomObject>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/classes/CreateExecution.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class CreateExecution {
    private Request request;
    private Integer order = 1;

    // GLOBAL

	@InvocableMethod(label='Execute Job Template')
	global static List<JobExecution__c> execute(List<Request> requests) {
		List<JobExecution__c> result = new List<JobExecution__c>();

		for (Request request : requests) {
            result.add(new CreateExecution(request).execute());
		}

		return result;
	}


    // CONSTRUCTOR

    public CreateExecution(Request request) {
        assertRequest(request);
        this.request = request;
    }


    // PUBLIC

    public JobExecution__c execute() {
        JobExecution__c result = jobExecution();

        if(request.runAfterInstantiation) {
            new RunJob(result).execute();
        }

        return result;
    }


    // PRIVATE


    @SuppressWarnings('PMD.ApexCRUDViolation')
    private JobExecution__c jobExecution() {
        JobExecution__c result = new JobExecution__c();
        JobTemplate__c template = getTemplate();

        if(String.isNotBlank(request.parentId)) {
            setParentId(result, Id.valueOf(request.parentId));
        }

        result.Status__c = 'Not Started';
        result.Template__c = template.Id;
        result.Callback__c = request.callback;
        result.DataJson__c = request.dataJson;
        result.Pipeline__c = request.pipelineId;
        result.Source__c = String.isNotBlank(request.sourceId) ? Id.valueOf(request.sourceId) : null;
        result.Destination__c = String.isNotBlank(request.destinationId) ? Id.valueOf(request.destinationId) : null;
        result = (JobExecution__c) Security.stripInaccessible(AccessType.CREATABLE, new List<SObject> { result }).getRecords().get(0);
        insert result;

        result.VolumeOptions__c = JSON.serializePretty(volumeOptions(template, result.Id), true);
        update result;

        cloneSteps(result, template.JobSteps__r);

        return result;
    }


    private JobTemplate__c getTemplate() {
        List<JobTemplate__c> result = new JobTemplatesSelector().byName(request.templateName);

        if(result.isEmpty()) {
            throw new ApplicationException(Label.InvalidTemplateId);
        }

        return result[0];
    }


    private List<Parameter> volumeOptions(JobTemplate__c template, Id executionId) {
        List<Parameter> result = new List<Parameter>();

        if(String.isNotBlank(template.VolumeOptions__c)) {
            result = (List<Parameter>) JSON.deserialize(template.VolumeOptions__c, List<Parameter>.class);
        }

        result.add(transactionParameter(executionId));

        return result;
    }


    private Parameter transactionParameter(Id executionId) {
        String transactionId = (String.isNotBlank(request.transactionId)) ? request.transactionId : executionId;

        return new Parameter('transactionId', transactionId);
    }


    private void setParentId(JobExecution__c job, Id parentId) {
        String objectType = objectType(parentId);
        String parentField = parentFieldByType().containsKey(objectType) ? parentFieldByType().get(objectType) : 'ParentRecord_Id__c';

        job.put(parentField, parentId);
    }


    private void cloneSteps(JobExecution__c job, List<JobStep__c> steps) {
        List<JobStep__c> result = new List<JobStep__c>();

        if(request.preSteps != null) {
            result.addAll(asClonedStep(job, request.preSteps));
        }

        result.addAll(asClonedStep(job, steps));

        if(request.postSteps != null) {
            result.addAll(asClonedStep(job, request.postSteps));
        }

        insert Security.stripInaccessible(AccessType.CREATABLE, result).getRecords();
    }


    private List<JobStep__c> asClonedStep(JobExecution__c job, List<JobStep__c> steps) {
        List<JobStep__c> result = new List<JobStep__c>();

        for(JobStep__c step : steps) {
            result.add(asClonedStep(job, step));
        }

        return result;
    }

    private JobStep__c asClonedStep(JobExecution__c job, JobStep__c step) {
        JobStep__c result = step.clone();
        result.Order__c = order++;
        result.JobTemplate__c = null;
        result.UserStory__c = null;
        result.JobExecution__c = job.Id;

        return result;
    }


    private void assertRequest(Request request) {
        if(String.isBlank(request.templateName)) {
            throw new ApplicationException(Label.InvalidTemplateId);
        }
    }


    private String objectType(Id recordId) {
        return (String.isNotBlank(recordId) ? recordId.getSObjectType().getDescribe().getLocalName() : '');
    }


    private Map<String, String> parentFieldByType() {
        return new Map<String, String> {
            'Deployment__c' => 'Deployment__c',
            'Promotion__c' => 'Promotion__c',
            'User_Story_Commit__c' => 'UserStoryCommit__c',
            'Git_Backup__c' => 'Snapshot__c'
        };
    }


	// INNER

	global class Request {
		@InvocableVariable
		global String templateName;

		@InvocableVariable
		global String transactionId;

		@InvocableVariable
		global String parentId;
        
		@InvocableVariable
		global String pipelineId;

		@InvocableVariable
		global String sourceId;

		@InvocableVariable
		global String destinationId;

		@InvocableVariable
		global String callback;

		@InvocableVariable
		global String dataJson;

		@InvocableVariable
		global List<JobStep__c> preSteps;

		@InvocableVariable
		global List<JobStep__c> postSteps;

		@InvocableVariable
		global Boolean runAfterInstantiation = false;
	}
}