Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/recordTypes/Advanced_multi_step.recordType-meta.xml
<RecordType>
    <fullName>Advanced_multi_step</fullName>
    <active>true</active>
    <description>Create multiple types of deployment steps. (Technical knowledge needed)</description>
    <label>Advanced (multi-step)</label>
</RecordType>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/Destination_Org__c.object-meta.xml
<CustomObject>
    <label>Destination Credential</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Credential Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipName>Destination_Orgs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/DataJson__c.field-meta.xml
<CustomField>
    <fullName>DataJson__c</fullName>
    <label>DataJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <formula>IF(NOT(ISBLANK( Deployment__c )), Deployment__c, 
    IF(NOT(ISBLANK( Promotion__c )), Promotion__c, 
        IF(NOT(ISBLANK( UserStoryCommit__c )), UserStoryCommit__c, 
            IF(NOT(ISBLANK( Snapshot__c )), Snapshot__c,  ParentRecord_Id__c)
        )
    )
)</formula>
    <label>Parent Id(Formula)</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/Promoted_User_Story__c.object-meta.xml
<CustomObject>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status Outdated invalidates that this user story got promoted. The user story will be available again for automated promotions and back promotions if applicable.</description>
    <label>Active / Outdated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Outdated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Promotions</relationshipLabel>
    <relationshipName>Promoted_User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with errors</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Validation failed</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
            <value>
                <fullName>Conflicts Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the implementation of the User Story.</description>
    <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/PromotionDeployAction.cls
@SuppressWarnings('PMD')
global with sharing class PromotionDeployAction extends PromoteActionService implements JobExecutionCallback {
    // TODO: Remove this comment
    private static CreateExecutionRequestData requestData;

    global class Request {
        @InvocableVariable(required=true label='Promotion Id' description='Id of the Promotion record. Copado will create a new deployment with the parameter values provided.')
        global Id promotionId;
        @InvocableVariable(label='Execute Deployment' description='Include this parameter if you want to run the deploy job template.')
        global boolean executeDeployment;
        @InvocableVariable(label='Deployment Dry Run' description='Include this parameter if you want to perform a validation-only deployment.')
        global boolean deploymentDryRun; // NOTE: this is "validate only", but more generic for other technologies
        @InvocableVariable(label='Other Information' description='Additional information that can be passed for the job execution in JSON format')
        global String otherInformation; // "other information" in json, additional values associated with this commit
    }

    global with sharing class Response {
        @InvocableVariable
        global JobExecution__c jobExecution;
    }


    // GLOBAL

    @InvocableMethod(label='Run a Copado promotion deployment' description='' category='Copado Multi-Cloud')
    global static List<Response> deploy(List<Request> requests) {
        requestData = new CreateExecutionRequestData();

        // Note: No need of bulkification, so keep it simple
        Request request = requests[0];
        requestData.promotionId = request.promotionId != null ? request.promotionId : null;
        requestData.executeDeployment = request.executeDeployment != null ? request.executeDeployment : false;
        requestData.deploymentDryRun = request.deploymentDryRun != null ? request.deploymentDryRun : false;
        requestData.otherInformation = request.otherInformation != null ? request.otherInformation : null;

        getPromotionDetails(requestData);

        Boolean updatePromotionStatus = requestData.executeDeployment || requestData.deploymentDryRun;
        if(requestData.promotion.Status__c != PromoteActionService.IN_PROGRESS && updatePromotionStatus) {
            PromotionTriggerHelper.bypassPromotionTrigger = true;
            updatePromotion(requestData.promotionId, PromoteActionService.IN_PROGRESS);
        }

        if(isDeploymentJobExecutionCreated(requestData)) {
            if(requestData.deployment != null) {
                Id jobExecutionId = new JobExecutionsSelector().byDeploymentId(requestData.deployment.Id).Id;
                updateJobExecutionDataJson(jobExecutionId, requestData);
                runOutstandingJobs(jobExecutionId);
            }
        } else {
            insertDeploymentWithDestinations();

            // TODO: the order of the user stories in the promotion needs to be configurable
            List<Promoted_User_Story__c> promotedUserStories = new PromotedUserStoriesSelector().byPromotionId(new Set<Id>{ requestData.promotion.Id });
            List<JobStep__c> allSteps = new JobStepsSelector().byUserStoryId( userStoryIds(promotedUserStories) );
            List<JobStep__c> preSteps = filterBySequence(allSteps, 'before');
            List<JobStep__c> postSteps = filterBySequence(allSteps, 'after');

            populateUserStoryParameters(requestData, promotedUserStories);
            populateChangeParameters(requestData);
            populateFileParameters(requestData, requestData.deployment.Id, 'Copado Deploy changes.json');

            String templateName = deploymentTemplateAPIName();
            String parentId = requestData.deployment.Id;
            String callbackClass = Settings.ns.replace('__', '.') + 'PromotionDeployAction';
            requestData.promotionBranchName = 'promotion/' + requestData.promotion.Name;
            requestData.destinationBranchName = destinationBranchName(requestData.promotion);

            CreateExecution.execute( asRequests(requestData, templateName, parentId, callbackClass, preSteps, postSteps) );
        }

        Response responseRecord = new Response();
        responseRecord.jobExecution = new JobExecutionsSelector().byDeploymentId(requestData.deploymentId);
        return new List<Response>{ responseRecord };
    }

    // Callback after the job finishes
    global void execute(JobExecution__c job, String status) {
        requestData = (CreateExecutionRequestData)JSON.deserialize(job.DataJson__c, CreateExecutionRequestData.class);
        // TODO: ... notify the User? TBD how, or which service
        String promotionStatus = status == PromoteActionService.SUCCESSFUL ? PromoteActionService.COMPLETED : PromoteActionService.COMPLETED_WITH_ERRORS;
        String deploymentStatus = status == PromoteActionService.SUCCESSFUL ? 'Completed Successfully' : 'Completed with Errors';
        Destination_Org__c destinationOrg = getDestinationOrgDetails(job.ParentId__c);
        List<SObject> records = new List<SObject> {
            getPromotion(destinationOrg.Deployment__r.Promotion__c, promotionStatus, requestData.deploymentDryRun),
            getDestinationOrg(destinationOrg.Id, deploymentStatus),
            getDeployment(job.ParentId__c, deploymentStatus)
        };

        fflib_SObjectDomain.getTriggerEvent(DeploymentTriggerHandler.class).disableAll();
        fflib_SObjectDomain.getTriggerEvent(DestinationOrgTriggerHandler.class).disableAll();

        if(requestData.deploymentDryRun) {
           PromotionTriggerHelper.resetUserStories = false; 
        }

        update Security.stripInaccessible(AccessType.UPDATABLE, records).getRecords();

        fflib_SObjectDomain.getTriggerEvent(DestinationOrgTriggerHandler.class).enableAll();
        fflib_SObjectDomain.getTriggerEvent(DeploymentTriggerHandler.class).enableAll();
    }


    // PRIVATE

    private static void insertDeploymentWithDestinations() {
        fflib_SObjectDomain.getTriggerEvent(DestinationOrgTriggerHandler.class).disableAll();
        SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, new List<Destination_Org__c>{ destination() });
        insert decision.getRecords();
        fflib_SObjectDomain.getTriggerEvent(DestinationOrgTriggerHandler.class).enableAll();
    }

    private static Destination_Org__c destination() {
        insertDeployment();
        return new Destination_Org__c(
            Deployment__c = requestData.deployment.Id,
            To_Org__c = requestData.promotion.Destination_Org_Credential__c,
            Status__c = PromoteActionService.IN_PROGRESS
        );
    }

    private static void insertDeployment() {
        fflib_SObjectDomain.getTriggerEvent(DeploymentTriggerHandler.class).disableAll();
        SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, new List<Deployment__c>{ deployment() });
        insert decision.getRecords();
        fflib_SObjectDomain.getTriggerEvent(DeploymentTriggerHandler.class).enableAll();

        requestData.deployment = (Deployment__c) (decision.getRecords().get(0));
        requestData.deploymentId = requestData.deployment.Id;
        shareDeploymentWithPromotionOwner();
    }

    private static Deployment__c deployment() {
        String advancedDeploymentRecordId = Schema.Sobjecttype.Deployment__c.getRecordTypeInfosByDeveloperName().get('Advanced_multi_step').getRecordTypeId();

        return new Deployment__c(
            RecordTypeId = advancedDeploymentRecordId,
            Name = requestData.promotion.Name,
            Status__c = 'In progress',
            Promotion__c = requestData.promotion.Id,
            From_Org__c = requestData.promotion.Source_Org_Credential__c
        );
    }

    private static void shareDeploymentWithPromotionOwner() {
        Deployment__Share deploymentShare = new Deployment__Share();
        deploymentShare.ParentId = requestData.deployment.Id;
        deploymentShare.UserOrGroupId = requestData.promotion.OwnerId;
        deploymentShare.AccessLevel = 'Read';
        deploymentShare.RowCause = Schema.Deployment__Share.RowCause.Manual;
        Database.insert(deploymentShare, false);
    }

    private static String deploymentTemplateAPIName() {
        String overridenTemplate = requestData.promotion.Destination_Environment__r.Deployment_Job_Template_Override__r?.ApiName__c;
		
        String templateApiName = '';
        if(requestData.promotion.Project__c != null) {
            templateApiName = requestData.promotion.Project__r.Deployment_Flow__r.Deployment_Job_Template__r.ApiName__c;
        } else if(requestData.promotion.Release__c != null) {
            templateApiName = requestData.promotion.Release__r.Project__r.Deployment_Flow__r.Deployment_Job_Template__r.ApiName__c;
        }
        
        return (overridenTemplate != null) ? overridenTemplate : templateApiName;
    }

    private static List<JobStep__c> filterBySequence(List<JobStep__c> steps, String executionSequence) {
        List<JobStep__c> result = new List<JobStep__c>();

        for (JobStep__c step : steps) {
            if(step.ExecutionSequence__c == executionSequence) {
                result.add(step);
            }
        }

        return result;
    }

    private static Set<Id> userStoryIds(List<Promoted_User_Story__c> promotedUserStories) {
        Set<Id> result = new Set<Id>();

        for(Promoted_User_Story__c promotedUserStory : promotedUserStories) {
            result.add(promotedUserStory.User_Story__c);
        }

        return result;
    }


    // EXECUTED IN CALLBACK

    private Promotion__c getPromotion(Id promotionId, String status, Boolean deploymentDryRun) {
        Boolean promotionMergedAndDeployed = status == COMPLETED && !deploymentDryRun;
        return new Promotion__c(Id = promotionId, Status__c = status, Completed__c = promotionMergedAndDeployed);
    }

    private Deployment__c getDeployment(Id deploymentId, String status) {
        return new Deployment__c(Id = deploymentId, Status__c = status);
    }

    private Destination_Org__c getDestinationOrgDetails(Id deploymentId) {
        return [SELECT Id, Status__c, Deployment__c, Deployment__r.Promotion__c FROM Destination_Org__c WHERE Deployment__c = :deploymentId WITH SECURITY_ENFORCED LIMIT 1];
    }

    private Destination_Org__c getDestinationOrg(Id destinationId, String status) {
        return new Destination_Org__c(Id = destinationId, Status__c = status);
    }
}