Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/From_Org__c.field-meta.xml
<CustomField>
    <fullName>From_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Credential</label>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Deployments (From Credential)</relationshipLabel>
    <relationshipName>Deployments_From_Org</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Parent_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Parent_Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Deployments (Parent Deployment)</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The automation template that defined the steps of this deployment.</inlineHelpText>
    <label>Template</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Template Execution</relationshipLabel>
    <relationshipName>Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/recordTypes/Advanced_multi_step.recordType-meta.xml
<RecordType>
    <fullName>Advanced_multi_step</fullName>
    <active>true</active>
    <description>Create multiple types of deployment steps. (Technical knowledge needed)</description>
    <label>Advanced (multi-step)</label>
</RecordType>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/Deployment_Job__c.object-meta.xml
<CustomObject>
    <label>Deployment Job</label>
    <nameField>
        <displayFormat>DJ-{00000}</displayFormat>
        <label>Deployment Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/Destination_Org__c.object-meta.xml
<CustomObject>
    <label>Destination Credential</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Credential Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipName>Destination_Orgs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Deployment_Automation_Override__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Automation_Override__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select an Automation Template to override the default Deployment Behaviour defined in the Pipeline</inlineHelpText>
    <label>Deployment Automation Override</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active automation templates are allowed</errorMessage>
        <filterItems>
            <field>Deployment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Automation Template</value>
        </filterItems>
        <filterItems>
            <field>Deployment__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Environments (Deployment Automation Override)</relationshipLabel>
    <relationshipName>DeploymentAutomationEnvironments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&quot;Salesforce&quot;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Promotion_Override__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Override__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select an Automation Template to override the default Promotion Behaviour defined in the Pipeline</inlineHelpText>
    <label>Promotion Automation Override</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active automation templates are allowed</errorMessage>
        <filterItems>
            <field>Deployment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Automation Template</value>
        </filterItems>
        <filterItems>
            <field>Deployment__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Environments (Promotion Automation Override)</relationshipLabel>
    <relationshipName>PromotionAutomationsEnvironments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Destination_Environment__c.field-meta.xml
<CustomField>
    <fullName>Destination_Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Promotions (Destination Environment)</relationshipLabel>
    <relationshipName>Promotions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Destination_Org_Credential__c.field-meta.xml
<CustomField>
    <fullName>Destination_Org_Credential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The destination credential that will be used when creating the deployment. This credential is auto-populated based on the pipeline linked to the project.</inlineHelpText>
    <label>Destination Credential</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Org__c.Environment__c</field>
            <operation>equals</operation>
            <valueField>$Source.Destination_Environment__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Promotions (Destination Credential)</relationshipLabel>
    <relationshipName>Promotions2</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <formula>IF( NOT(ISBLANK( Project__c )) ,  TEXT(Project__r.Deployment_Flow__r.Platform__c) ,  IF( NOT(ISBLANK( Release__c )),  TEXT(Release__r.Project__r.Deployment_Flow__r.Platform__c) , &apos;Salesforce&apos;) )</formula>
    <inlineHelpText>This field auto-populates and displays the pipeline platform.</inlineHelpText>
    <label>Platform</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Source_Org_Credential__c.field-meta.xml
<CustomField>
    <fullName>Source_Org_Credential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The source credential that will be used when creating the deployment. This credential is auto-populated based on the pipeline linked to the project.</inlineHelpText>
    <label>Source Credential</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Org__c.Environment__c</field>
            <operation>equals</operation>
            <valueField>$Source.Source_Environment__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Promotions (Source Credential)</relationshipLabel>
    <relationshipName>Promotions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with errors</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Validation failed</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
            <value>
                <fullName>Conflicts Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/NonSalesforcePipelineOperationService.cls
public with sharing class NonSalesforcePipelineOperationService extends PipelineOperationsHelper implements PipelineOperationsInterface {
    private Map<Id, Id> newStepRecordIdsByOldStepRecordIds;

    public PipelineManagerExtension.PipelineOperationsServiceJobsResult validation(
        PipelineManagerExtension.PipelineOperationsServiceJobsParameters jobParameters
    ) {
        result = new PipelineManagerExtension.PipelineOperationsServiceJobsResult();
        return result;
    }

    public PipelineManagerExtension.PipelineOperationsServiceJobsResult createPromotionAndPromotedUserStories(
        PipelineManagerExtension.PipelineOperationsServiceJobsParameters jobParameters
    ) {
        overlayWrapperRecord = jobParameters.overlayWrapperRecord;
        testLevelValue = jobParameters.testLevelValue;
        result = new PipelineManagerExtension.PipelineOperationsServiceJobsResult();
        preparePromotionAndRelations();
        return result;
    }

    public PipelineManagerExtension.PipelineOperationsServiceJobsResult promoteAndDeploy(
        PipelineManagerExtension.PipelineOperationsServiceJobsParameters jobParameters
    ) {
        createPromotionAndPromotedUserStories(jobParameters);
        jobParameters.promotionWrappers = result.promotionWrappers;
        try {
            return commonOperations(jobParameters, true);
        } catch (Exception ex) {
            throw new PipelineOperationsHelperException(ex.getMessage());
        }
    }

    public PipelineManagerExtension.PipelineOperationsServiceJobsResult deploy(
        PipelineManagerExtension.PipelineOperationsServiceJobsParameters jobParameters
    ) {
        result = new PipelineManagerExtension.PipelineOperationsServiceJobsResult();
        try {
            return commonOperations(jobParameters, false);
        } catch (Exception ex) {
            throw new PipelineOperationsHelperException(ex.getMessage());
        }
    }

    private PipelineManagerExtension.PipelineOperationsServiceJobsResult commonOperations(
        PipelineManagerExtension.PipelineOperationsServiceJobsParameters jobParameters,
        Boolean isPromoteAndDeploy
    ) {
        List<Promotion__c> promotions = new List<Promotion__c>();
        List<Deployment__c> deployments = new List<Deployment__c>();
        testLevelValuesByPromotionIds = new Map<String, String>();
        String destinationEnvironmentId = '';
        for (PipelineManagerExtension.PromotionWrapper promotionItem : jobParameters.promotionWrappers) {
            if (promotionItem.isSelected && promotionItem.promotion.Status__c != COMPLETED) {
                promotionItem.promotion.Status__c = SCHEDULED;
                promotions.add(promotionItem.promotion);
                testLevelValuesByPromotionIds.put(promotionItem.promotion.Id, '');
                if (String.isBlank(destinationEnvironmentId)) {
                    destinationEnvironmentId = promotionItem.promotion.Destination_Environment__c;
                }
            }
        }
        SObjectAccessDecision promotionDecision = Security.stripInaccessible(AccessType.UPDATABLE, promotions);
        update promotionDecision.getRecords();
        promotions.clear();
        promotions = [
            SELECT 
                Id, 
                Name, 
                Source_Org_Credential__c,
                Destination_Org_Credential__c,
                Destination_Environment__c,
                Destination_Environment__r.Name,
                Destination_Environment__r.Platform__c,
                Destination_Environment__r.Deployment_Automation_Override__c,
                Destination_Environment__r.Deployment_Automation_Override__r.Name,
                Destination_Environment__r.Promotion_Override__c,
                Destination_Environment__r.Promotion_Override__r.Name
            FROM Promotion__c
            WHERE Id IN :testLevelValuesByPromotionIds.keySet()
            WITH SECURITY_ENFORCED
        ];

        String targetCredentialId = promotions[0].Destination_Org_Credential__c;
        String deploymentTemplateId = promotions[0].Destination_Environment__r.Deployment_Automation_Override__c != null
            ? promotions[0].Destination_Environment__r.Deployment_Automation_Override__c
            : jobParameters.pipelineDeploymentAutomationTemplateId;
        String deploymentTemplateName = promotions[0].Destination_Environment__r.Deployment_Automation_Override__r.Name != null
            ? promotions[0].Destination_Environment__r.Deployment_Automation_Override__r.Name
            : jobParameters.pipelineDeploymentAutomationTemplateName;
        String promotionTemplateId = promotions[0].Destination_Environment__r.Promotion_Override__c != null
            ? promotions[0].Destination_Environment__r.Promotion_Override__c
            : jobParameters.pipelinePromotionAutomationTemplateId;
        String promotionTemplateName = promotions[0].Destination_Environment__r.Promotion_Override__r.Name != null
            ? promotions[0].Destination_Environment__r.Promotion_Override__r.Name
            : jobParameters.pipelinePromotionAutomationTemplateName;

        for (Promotion__c promotionRecord : promotions) {
            if (isPromoteAndDeploy) {
                deployments.add(prepareDeployment(promotionRecord, promotionTemplateId, promotionTemplateName, true));
                deployments.add(prepareDeployment(promotionRecord, deploymentTemplateId, deploymentTemplateName, false));
            } else {
                deployments.add(prepareDeployment(promotionRecord, promotionTemplateId, promotionTemplateName, false));
            }
        }

        SObjectAccessDecision deploymentDecision = Security.stripInaccessible(AccessType.CREATABLE, deployments);
        insert deploymentDecision.getRecords();
        deployments = (List<Deployment__c>) deploymentDecision.getRecords();

        if (isPromoteAndDeploy) {
            Map<Id, Id> deploymentIdsByTemplateIds = new Map<Id, Id>();
            for (Deployment__c deploymentRecord : deployments) {
                deploymentIdsByTemplateIds.put(deploymentRecord.Template__c, deploymentRecord.Id);
            }

            for (Deployment__c deploymentRecord : deployments) {
                if (deploymentRecord.Template__c == promotionTemplateId) {
                    deploymentRecord.Parent_Deployment__c = deploymentIdsByTemplateIds.get(deploymentTemplateId);
                }
            }
            deploymentDecision = Security.stripInaccessible(AccessType.UPDATABLE, deployments);
            update deploymentDecision.getRecords();
            deployments = (List<Deployment__c>) deploymentDecision.getRecords();
        }

        List<String> stepParentIds = new List<String>();
        stepParentIds.add(promotionTemplateId);
        if (isPromoteAndDeploy) {
            stepParentIds.add(deploymentTemplateId);
        }

        cloneSteps(stepParentIds, deployments);
        createDestinationOrgs(targetCredentialId, deployments);
        updateFirstDeploymentJobsStatusToInvokeDeployments(isPromoteAndDeploy);
        checkPromotionsStatuses();
        result.enabledPromotionBackPromotionPoller = true;
        return result;
    }

    private Deployment__c prepareDeployment(Promotion__c promotionRecord, String templateId, String templateName, Boolean doNotUpdatePromotion) {
        String advancedDeploymentRecordId = Schema.Sobjecttype.Deployment__c.getRecordTypeInfosByDeveloperName()
            .get('Advanced_multi_step')
            .getRecordTypeId();

        Deployment__c deploymentRecord = new Deployment__c();
        deploymentRecord.Name = Label.Execution_of + ' ' + templateName;
        deploymentRecord.RecordTypeId = advancedDeploymentRecordId;
        deploymentRecord.Template__c = templateId;
        deploymentRecord.From_Org__c = promotionRecord.Source_Org_Credential__c;
        deploymentRecord.Status__c = SCHEDULED;
        deploymentRecord.Promotion__c = promotionRecord.Id;
        deploymentRecord.Deployment_Completed_email_sent__c = false;
        deploymentRecord.Deployment_command_sent__c = null;
        deploymentRecord.Do_Not_Update_Promotion__c = doNotUpdatePromotion;
        deploymentRecord.Parent_Deployment__c = null;
        if (deploymentRecord.Schedule__c == DEPLOY_NOW) {
            deploymentRecord.Date__c = System.now();
        }
        return deploymentRecord;
    }

    private void cloneSteps(List<String> templateIds, List<Deployment__c> deployments) {
        List<Step__c> steps = Utilities.getStepsByDeploymentIds(templateIds);
        List<String> deploymentIds = new List<String>();
        List<Step__c> newSteps = new List<Step__c>();
        for (Deployment__c deploymentRecord : deployments) {
            for (Step__c stepRecord : steps) {
                if (deploymentRecord.Template__c == stepRecord.Deployment__c) {
                    Step__c newStep = stepRecord.clone();
                    newStep.Deployment__c = deploymentRecord.Id;
                    newStep.Status__c = NOT_STARTED;
                    newSteps.add(newStep);
                }
            }
            deploymentIds.add(deploymentRecord.Id);
        }

        fflib_SObjectDomain.getTriggerEvent(StepTriggerHandler.class).disableBeforeInsert();
        SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, newSteps);
        insert decision.getRecords();
        fflib_SObjectDomain.getTriggerEvent(StepTriggerHandler.class).enableBeforeInsert();
       
        newSteps = Utilities.getStepsByDeploymentIds(deploymentIds);

        newStepRecordIdsByOldStepRecordIds = new Map<Id, Id>();
        for (Step__c oldStepRecord : steps) {
            for (Step__c newStepRecord : newSteps) {
                if (oldStepRecord.Order__c == newStepRecord.Order__c && oldStepRecord.Deployment__c == newStepRecord.Deployment__r.Template__c) {
                    newStepRecordIdsByOldStepRecordIds.put(oldStepRecord.Id, newStepRecord.Id);
                }
            }
        }
        cloneAttachments();
    }

    private void cloneAttachments() {
        List<Attachment> newAttachments = new List<Attachment>();
        for (Attachment attachmentRecord : [
            SELECT Id, Body, Name, ContentType, IsPrivate, ParentId
            FROM Attachment
            WHERE ParentId = :newStepRecordIdsByOldStepRecordIds.keySet()
            WITH SECURITY_ENFORCED
        ]) {
            Attachment newAtachmentRecord = attachmentRecord.clone(false, false, false, false);
            newAtachmentRecord.ParentId = newStepRecordIdsByOldStepRecordIds.get(attachmentRecord.ParentId);
            newAttachments.add(newAtachmentRecord);
        }

        fflib_SObjectDomain.getTriggerEvent(AttachmentTriggerHandler.class).disableBeforeInsert();
        SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, newAttachments);
        insert decision.getRecords();
        fflib_SObjectDomain.getTriggerEvent(AttachmentTriggerHandler.class).enableBeforeInsert();
    }

    private void createDestinationOrgs(Id targetCredentialId, List<Deployment__c> deployments) {
        List<Destination_Org__c> destinationOrgs = new List<Destination_Org__c>();
        for (Deployment__c deploymentRecord : deployments) {
            Destination_Org__c destinationOrg = new Destination_Org__c();
            destinationOrg.Deployment__c = deploymentRecord.Id;
            destinationOrg.To_Org__c = targetCredentialId;
            destinationOrg.Status__c = NOT_STARTED;
            destinationOrgs.add(destinationOrg);
        }
        SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, destinationOrgs);
        insert decision.getRecords();
    }

    private void updateFirstDeploymentJobsStatusToInvokeDeployments(Boolean isPromoteAndDeploy) {
        List<Deployment_Job__c> deploymentJobsToBeUpdated;
        if (isPromoteAndDeploy) {
            deploymentJobsToBeUpdated = [
                SELECT Id, Status__c
                FROM Deployment_Job__c
                WHERE
                    Step__c IN :newStepRecordIdsByOldStepRecordIds.values()
                    AND Step__r.Order__c = 1
                    AND Step__r.Deployment__r.Parent_Deployment__c != null
                WITH SECURITY_ENFORCED
            ];
        } else {
            deploymentJobsToBeUpdated = [
                SELECT Id, Status__c
                FROM Deployment_Job__c
                WHERE
                    Step__c IN :newStepRecordIdsByOldStepRecordIds.values()
                    AND Step__r.Order__c = 1
                    AND Step__r.Deployment__r.Parent_Deployment__c = null
                WITH SECURITY_ENFORCED
            ];
        }
        for (Deployment_Job__c deploymentJobRecord : deploymentJobsToBeUpdated) {
            deploymentJobRecord.Status__c = IN_PROGRESS;
        }

        SObjectAccessDecision decision = Security.stripInaccessible(AccessType.UPDATABLE, deploymentJobsToBeUpdated);
        update decision.getRecords();
    }

    public class FunctionStepAttachmentDetails {
        public String functionId { get; set; }
        public String functionApiName { get; set; }
        public List<Parameter> functionParameters { get; set; }
    }
}