Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Deployment_Last_Step__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Last_Step__c</fullName>
    <label>Deployment Last Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/From_Org__c.field-meta.xml
<CustomField>
    <fullName>From_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Credential</label>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Deployments (From Credential)</relationshipLabel>
    <relationshipName>Deployments_From_Org</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Rolled_back_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Rolled_back_Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the original deployment that was rolled back for reporting purposes</description>
    <inlineHelpText>Identifies the original deployment that was rolled back for reporting purposes</inlineHelpText>
    <label>Rolled back Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Deployments (Rolled back Deployment)</relationshipLabel>
    <relationshipName>RolledBackDeployments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/Destination_Org__c.object-meta.xml
<CustomObject>
    <label>Destination Credential</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Credential Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipName>Destination_Orgs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/To_Org__c.field-meta.xml
<CustomField>
    <fullName>To_Org__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>To Credential</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Org__c.CreatedById</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Destination Credentials</relationshipLabel>
    <relationshipName>Deployments_to</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with errors</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Validation failed</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
            <value>
                <fullName>Conflicts Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/RollbackWizardExt.cls
public with sharing class RollbackWizardExt extends DeploymentHelper {
    private Promotion__c promotion;
    private Deployment__c lastDeployment;

    // CTOR

    public RollbackWizardExt(ApexPages.StandardController stdCtrl) {
        if (!Test.isRunningTest()) {
            stdCtrl.addFields(new List<String>(Schema.SObjectType.Promotion__c.fields.getMap().keySet()));
        }

        promotion = (Promotion__c) stdCtrl.getRecord();
        List<Deployment__c> deployments = [
            SELECT Name, From_Org__c, Status__c, (SELECT To_Org__c, To_Org__r.Environment__r.Enable_Rollback__c FROM Destination_Orgs__r LIMIT 1)
            FROM Deployment__c
            WHERE Promotion__c = :promotion.Id
            WITH SECURITY_ENFORCED
            ORDER BY lastModifiedDate DESC
            LIMIT 1
        ];
        if (!deployments.isEmpty()) {
            lastDeployment = deployments[0];
        } else {
            addErrorMessage(Label.RollbackNoEligibleSteps);
        }
    }

    // PUBLIC
    public PageReference redirectToCorrectPage() {
        if (!pageMessagesMap.isEmpty()) {
            return null;
        }

        String rollbackDeploymentName = 'Rollback ' + lastDeployment.Name;
        List<Deployment__c> lastRollbackDeployment = [
            SELECT Name, Deployment_Last_Step__c
            FROM Deployment__c
            WHERE Name = :rollbackDeploymentName
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        if (!lastRollbackDeployment.isEmpty()) {
            deployment = deploymentWillBeRedirected = lastRollbackDeployment[0];
        } else {
            Deployment__c rollbackDeployment = new Deployment__c(Name = rollbackDeploymentName, Rolled_Back_Deployment__c = lastDeployment.Id);

            try {
                Utilities.Secure_DML(rollbackDeployment, Utilities.DML_Action.INS, schema.SObjectType.Deployment__c);
            } catch(Exception e) {
                addErrorMessage(Label.Insufficient_Access_Rights + ': ' + Label.Related_Object + ' ' + Schema.SObjectType.Deployment__c.getLabel());
                return null;
            }

            Destination_org__c rollbackDestination = new Destination_org__c(
                To_Org__c = lastDeployment.Destination_Orgs__r[0].To_Org__c,
                Deployment__c = rollbackDeployment.Id
            );

            try {
                Utilities.Secure_DML(rollbackDestination, Utilities.DML_Action.INS, schema.SObjectType.Destination_org__c);
            } catch(Exception e) {
                addErrorMessage(
                    Label.Insufficient_Access_Rights +
                    ': ' +
                    Label.Related_Object +
                    ' ' +
                    Schema.SObjectType.Destination_org__c.getLabel()
                );
                return null;
            }

            deployment = deploymentWillBeRedirected = rollbackDeployment;
        }

        initializeServiceClasses();
        return goToNextStep();
    }
}