Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/From_Org__c.field-meta.xml
<CustomField>
    <fullName>From_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Credential</label>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Deployments (From Credential)</relationshipLabel>
    <relationshipName>Deployments_From_Org</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/Deployment_Flow_Step__c.object-meta.xml
<CustomObject>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Pipeline Connections</relationshipLabel>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_History__c/Deployment_History__c.object-meta.xml
<CustomObject>
    <label>Copado Deployment History</label>
    <nameField>
        <displayFormat>CDH-{0000000}</displayFormat>
        <label>Copado Deployment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copado Deployment History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_History__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Copado Deployment History</relationshipLabel>
    <relationshipName>Copado_Deployment_History</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/Destination_Org__c.object-meta.xml
<CustomObject>
    <label>Destination Credential</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Credential Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipName>Destination_Orgs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/To_Org__c.field-meta.xml
<CustomField>
    <fullName>To_Org__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>To Credential</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Org__c.CreatedById</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Destination Credentials</relationshipLabel>
    <relationshipName>Deployments_to</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&quot;Salesforce&quot;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Disable_Validation__c.field-meta.xml
<CustomField>
    <fullName>Disable_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this checkbox will not validate the credentials when the record is saved or viewed.</inlineHelpText>
    <label>Disable Validation</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Metadata_Types__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Types__c</fullName>
    <inlineHelpText>Empty means all types. Select one or more types to limit the backup only to selected items.</inlineHelpText>
    <label>Metadata Types</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Oauth_Signature__c.field-meta.xml
<CustomField>
    <fullName>Oauth_Signature__c</fullName>
    <description>This value is automatically set and updated by Copado.</description>
    <inlineHelpText>This value is automatically set and updated by Copado.</inlineHelpText>
    <label>Oauth Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <formula>TEXT(Environment__r.Platform__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Platform</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Validated_Status__c.field-meta.xml
<CustomField>
    <fullName>Validated_Status__c</fullName>
    <formula>IF(ISBLANK(Validated_Date__c),
&quot;Error&quot; ,
 IF( DATEVALUE(Validated_Date__c) == TODAY(), 
    &quot;OK&quot;,&quot;None&quot;) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Validated Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Pipeline.</inlineHelpText>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <formula>IF( NOT(ISBLANK( Project__c )) ,  TEXT(Project__r.Deployment_Flow__r.Platform__c) ,  IF( NOT(ISBLANK( Release__c )),  TEXT(Release__r.Project__r.Deployment_Flow__r.Platform__c) , &apos;Salesforce&apos;) )</formula>
    <inlineHelpText>This field auto-populates and displays the pipeline platform.</inlineHelpText>
    <label>Platform</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a project linked to an active pipeline.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will provide the ability to deploy User Stories within a Release.</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/DeploymentExt.cls
global with sharing class DeploymentExt {
    private final String OK_STRING = 'OK';
    public Deployment__c deployment { get; set; }
    public Boolean sourceCredentialValidated { get; set; }
    public Boolean showError { get; set; }
    public Boolean showOptions { get; set; }
    public List<Map<String, String>> messagesQueue = new List<Map<String, String>>();
    public Boolean showOtherInformation { get; set; }
    public Boolean ccdEnabled { get; set; }
    public String selectedToOrg { get; set; }
    public Boolean isDeploymentModeNew { get; set; }
    public Boolean showStepsOnly { get; set; } // MY: Added for DX post SO job preview. Since we will use deployments as data load and post success jobs we need to display steps on DX operation panel.
    public Boolean historyVisible = false;
    public Destination_Org__c[] destinations { get; set; }
    public Step__c[] steps { get; set; }
    public Org__c fromOrg { get; set; }
    public Boolean orgFiltered { get; set; }
    public String metadata_url { get; set; }
    public String describe_url { get; set; }
    public String sobjects_url { get; set; }
    public String testquery_url { get; set; }
    public String users_url { get; set; }
    public String cancel_url { get; set; }
    public String custom_settings_url { get; set; }
    public String git_metadata_url { get; set; }
    public String quick_actions_url { get; set; }
    public String urlParameters { get; set; }
    public String herokuServer { get; set; }
    public Boolean isShareable { get; set; }
    private Set<String> destinationCredentialIds;

    public DeploymentExt(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) {
            stdController.addFields(Utilities.getAllFields('Deployment__c').get(Label.FIELDS).split(','));
            stdController.addFields(
                new List<String>{
                    'From_Org__r.Disable_Validation__c',
                    'From_Org__r.Oauth_Signature__c',
                    'Promotion__r.Project__r.Deployment_Flow__c',
                    'Promotion__r.Release__r.Project__r.Deployment_Flow__c'
                }
            );
        }
        this.deployment = (Deployment__c) stdController.getRecord();

        initializeVariables();
        isLicenseEnabled();
        deploymentSourceCredentialValidation();
        setUrls();
        initializeDestinationCredentials();
        initializeDeploymentSteps();
    }

    private void initializeVariables() {
        showOptions = true;
        showError = false;
        sourceCredentialValidated = false;
        isDeploymentModeNew = String.isBlank(this.deployment.Id);
        destinations = new List<Destination_Org__c>{};
        steps = new List<Step__c>{};
        showOtherInformation = SObjectType.Deployment__c.fieldSets.CustomFields.getFields().size() > 0;
        Map<String, Schema.SObjectType> globalDescribeValuesOfDeploymentObject = Schema.getGlobalDescribe();
        isShareable = globalDescribeValuesOfDeploymentObject.containsKey('Deployment__Share');
        // MY: Added for DX post SO job preview. Since we will use deployments as data load and post success jobs we need to display steps on DX operation panel.
        String stepsOnlyParam = ApexPages.currentPage().getParameters().get('stepsOnly');
        showStepsOnly = String.isNotBlank(stepsOnlyParam);
    }

    private void isLicenseEnabled() {
        if (!LicenseHelper.actionIsLicenseEnabled('viewEditDeployment')) {
            ApexPages.addMessage(
                new ApexPages.Message(ApexPages.Severity.WARNING, Label.CE_License_Restriction.replace('__License__', Label.CCH_or_CCM_License))
            );
            showError = true;
            showOptions = false;
        }
    }

    private void deploymentSourceCredentialValidation() {
        if (!isDeploymentModeNew) {
            if (deployment.From_Org__c != null) {
                populateSourceCredentialRecord();
            }
        }
    }

    private void populateSourceCredentialRecord() {
        fromOrg = Utilities.getOrgById(deployment.From_Org__c);
        orgFiltered = String.isNotBlank(fromOrg.Metadata_Types__c);
        checkAndValidateSourceCredential();
    }

    private void checkAndValidateSourceCredential() {
        if ((fromOrg.Platform__c == null || fromOrg.Platform__c == 'Salesforce') && fromOrg.Validated_Status__c != OK_STRING) {
            sourceCredentialValidated = DeployAPI.validateOrg(fromOrg.Id);
            if (!sourceCredentialValidated) {
                addErrorMessagesToMessageQueueMap(Label.ORG_NOT_VALIDATED);
            }
        } else {
            sourceCredentialValidated = true;
        }
    }

    private void setUrls() {
        cancel_url = getCancelURL();
        urlParameters = '?nosid=1';
        herokuServer = Settings.server_url;
        String baseURL = herokuServer + '/json/v1/';
        git_metadata_url = baseURL + 'gitmetadata/{repositoryId}/{commitId}' + urlParameters + '&branch={branch}';
        if (deployment.From_Org__c == null) {
            return;
        }
        if (fromOrg != null && String.isNotBlank(fromOrg.Metadata_Types__c)) {
            urlParameters += '&filter=' + EncodingUtil.urlEncode(fromOrg.Metadata_Types__c, 'UTF-8');
        }
        String sourceCredentialEncoded = EncodingUtil.urlEncode(deployment.From_Org__c, 'UTF-8');
        metadata_url = baseURL + 'metadata/' + sourceCredentialEncoded + urlParameters + '&dates=format';
        describe_url = baseURL + 'describe/' + sourceCredentialEncoded + '/{sobject}' + urlParameters;
        sobjects_url = baseURL + 'listSObjects/' + sourceCredentialEncoded + urlParameters;
        testquery_url = baseURL + 'test-query/' + sourceCredentialEncoded + urlParameters;
        users_url = baseURL + 'users/' + sourceCredentialEncoded + urlParameters;
        custom_settings_url = baseURL + 'customSetting/' + sourceCredentialEncoded + '/{sobject}' + urlParameters;
        quick_actions_url = baseURL + 'quickActions/' + sourceCredentialEncoded + '/{sobject}' + urlParameters;
    }

    private String getCancelURL() {
        Schema.DescribeSObjectResult result = Deployment__c.SObjectType.getDescribe();
        return '/' + result.getKeyPrefix();
    }

    private void initializeDestinationCredentials() {
        destinationCredentialIds = new Set<String>();
        Set<String> destinationEnvironmentIds = new Set<String>();

        if (!isDeploymentModeNew) {
            destinations = CopadoAPI.getDestinationsOrg(this.deployment.Id);
            //pre-fill set helper in order to validate faster duplicates
            for (Destination_Org__c destinationCredentialRecord : destinations) {
                destinationCredentialIds.add(destinationCredentialRecord.To_Org__c);
                destinationEnvironmentIds.add(destinationCredentialRecord.To_Org__r.Environment__c);
            }
            if (destinations.size() == 1) {
                checkDestinationCredentialsForConnectionBehavior(destinationCredentialIds);
                checkPipelineConnectionForConnectionBehavior(destinationEnvironmentIds);
            }
        }
        if (destinations.isEmpty()) {
            addDestination();
        }
    }

    private void checkDestinationCredentialsForConnectionBehavior(Set<String> credentialIds) {
        for (Org__c credentialRecord : [
            SELECT Id, Environment__c, Environment__r.Connection_Behavior__c, Environment__r.Connection_Behavior__r.Promotion_Behavior__c
            FROM Org__c
            WHERE Id IN :credentialIds
            WITH SECURITY_ENFORCED
        ]) {
            Boolean credentialEnvironmentHasConnectionBehavior = null != credentialRecord.Environment__r.Connection_Behavior__c;
            Boolean connectionBehaviorHasPromotionBehavior = credentialRecord.Environment__r.Connection_Behavior__r.Promotion_Behavior__c != '';
            Boolean hasConnectionBehavior = credentialEnvironmentHasConnectionBehavior && connectionBehaviorHasPromotionBehavior;
            ccdEnabled = hasConnectionBehavior;
        }
    }

    private void checkPipelineConnectionForConnectionBehavior(Set<String> destinationEnvironmentIds) {
        if (null != deployment.Promotion__c & destinations.size() == 1) {
            Id pipelineId = null != deployment.Promotion__r.Project__c
                ? deployment.Promotion__r.Project__r.Deployment_Flow__c
                : deployment.Promotion__r.Release__r.Project__r.Deployment_Flow__c;
            for (Deployment_Flow_Step__c pipelineConnectionRecord : [
                SELECT Id, Connection_Behavior__c
                FROM Deployment_Flow_Step__c
                WHERE
                    Source_Environment__c = :deployment.Source_Environment__c
                    AND Destination_Environment__c IN :destinationEnvironmentIds
                    AND Deployment_Flow__c = :pipelineId
                WITH SECURITY_ENFORCED
            ]) {
                if (String.isNotBlank(pipelineConnectionRecord.Connection_Behavior__c)) {
                    ccdEnabled = true;
                }
            }
        }
    }

    public void addDestination() {
        destinations.add(new Destination_Org__c(Deployment__c = this.deployment.Id));
    }

    private void initializeDeploymentSteps() {
        if (!isDeploymentModeNew) {
            steps = CopadoAPI.listSteps(this.deployment.Id);
        }
    }

    public PageReference saveDeployment() {
        runNecessaryValidationBeforeSavingDeployment();
        if (!messagesQueue.isEmpty()) {
            return null;
        }

        try {
            SObjectAccessDecision deploymentDecision = Security.stripInaccessible(AccessType.UPSERTABLE, new List<Deployment__c>{ deployment });
            upsert deploymentDecision.getRecords();
            deployment = (Deployment__c) deploymentDecision.getRecords()[0];
            addSuccessMessageToMessageQueueMap(Label.Deployment_Saved);
            if (isDeploymentModeNew) {
                return new Apexpages.StandardController(deployment).view();
            }
        } catch (Exception ex) {
            addErrorMessagesToMessageQueueMap(ex.getMessage());
        }
        return null;
    }

    private void runNecessaryValidationBeforeSavingDeployment() {
        if (String.isNotBlank(deployment.From_Org__c) && !sourceCredentialValidated) {
            addErrorMessagesToMessageQueueMap(Label.WRONG_CREDENTIALS);
        }
        if (LicenseHelper.isLicensesExceeded()) {
            addErrorMessagesToMessageQueueMap(Label.LICENSES_EXCEEDED);
        }
        if (!LicenseHelper.isCopadoEnabled() && !isAttachDeploymentFileChanged()) {
            addErrorMessagesToMessageQueueMap(Label.COPADO_DEPLOYER_LICENSE_NOT_ENABLED);
        }
    }

    private Boolean isAttachDeploymentFileChanged() {
        Deployment__c oldDeploymentRecord = [
            SELECT Id, Name, Attach_Deployment_File__c, Send_Deployment_Complete_email__c, From_Org__c
            FROM Deployment__c
            WHERE Id = :deployment.Id
            WITH SECURITY_ENFORCED
        ];
        return (deployment.Name == oldDeploymentRecord.Name &&
        deployment.Send_Deployment_Complete_email__c == oldDeploymentRecord.Send_Deployment_Complete_email__c &&
        deployment.From_Org__c == oldDeploymentRecord.From_Org__c &&
        deployment.Attach_Deployment_File__c != oldDeploymentRecord.Attach_Deployment_File__c);
    }

    private void addErrorMessagesToMessageQueueMap(String message) {
        addMessageToQueueMap('ERROR', message);
    }

    private void addSuccessMessageToMessageQueueMap(String message) {
        addMessageToQueueMap('CONFIRM', message);
    }

    private void addMessageToQueueMap(String type, String message) {
        //we are using this map in order to save messages from apex
        //and then render them as a json object in order to be used by the JSApp
        Map<String, String> messagesByMessageType = new Map<String, String>();
        messagesByMessageType.put('s', type);
        messagesByMessageType.put('m', message);

        messagesQueue.add(messagesByMessageType);
    }

    public PageReference validateFromOrg() {
        PageReference pReference = null;
        if (deployment.From_Org__c == null) {
            fromOrg = null;
            return pReference;
        }

        populateSourceCredentialRecord();

        if (sourceCredentialValidated) {
            pReference = saveDeployment();
            setUrls();
        }
        return pReference;
    }

    public void saveDestination() {
        Destination_Org__c newDestinationCredential = new Destination_Org__c();
        for (Destination_Org__c destinationCredentialRecord : destinations) {
            if (String.isBlank(destinationCredentialRecord.Id)) {
                newDestinationCredential = destinationCredentialRecord;
                break;
            }
        }

        destinationCredentialNecessaryValidations(newDestinationCredential);
        if (!messagesQueue.isEmpty()) {
            return;
        }

        Org__c org = Utilities.getOrgById(newDestinationCredential.To_Org__c);
        if ((org.Platform__c == null || org.Platform__c == 'Salesforce') && org.Validated_Status__c != OK_STRING) {
            if (!DeployAPI.validateOrg(org.Id)) {
                addErrorMessagesToMessageQueueMap(Label.DESTINATION_ORG_NOT_VALIDATED);
                return;
            }
        }
        CopadoAPI.addDestinationOrg(this.deployment.Id, newDestinationCredential.To_Org__c);
        initializeDestinationCredentials();
        addSuccessMessageToMessageQueueMap(Label.DESTINATION_ORG_SAVED);
    }

    private void destinationCredentialNecessaryValidations(Destination_Org__c destinationCredentialRecord) {
        if (String.isBlank(destinationCredentialRecord.To_Org__c)) {
            addErrorMessagesToMessageQueueMap(Label.ORG_NOT_VALIDATED);
        }
        if (destinationCredentialIds.contains(destinationCredentialRecord.To_Org__c)) {
            addErrorMessagesToMessageQueueMap(Label.DESTINATION_ORG_ALREADY_SELECTED);
        }
    }

    public PageReference deleteDestOrg() {
        ccdEnabled = false;
        CopadoAPI.removeDestinationOrg(this.deployment.Id, selectedToOrg);
        initializeDestinationCredentials();
        return null;
    }

    public String getDestinationsJson() {
        return JSON.serialize(this.destinations);
    }

    public String getStepsJson() {
        return JSON.serialize(this.steps);
    }

    public String getDepJson() {
        return JSON.serialize(this.deployment);
    }

    public String getjsonMessagesQueue() {
        return JSON.serialize(this.messagesQueue);
    }

    @RemoteAction
    global static void sortSteps(String[] ids) {
        List<Step__c> steps = new List<Step__c>();
        Integer index = 1;
        for (String stepId : ids) {
            steps.add(new Step__c(Id = stepId, Order__c = index));
            index++;
        }

        SObjectAccessDecision stepDecision = Security.stripInaccessible(AccessType.UPSERTABLE, steps);
        upsert stepDecision.getRecords();
        steps = (List<Step__c>) stepDecision.getRecords();
    }

    @RemoteAction
    global static void deleteStep(String stepId) {
        if (String.isNotBlank(stepId)) {
            CopadoAPI.removeStep(stepId);
        }
    }

    public Boolean getHistoryVisible() {
        return Schema.SObjectType.Deployment_History__c.fields.Deployment__c.isAccessible();
    }

    public String getJobsManagerMatchingKey() {
        String matchingKey = '', flow_id = '', target_branch = '';
        Step__c gitPromotionStep = null;
        for (Step__c stepRecord : steps) {
            if (stepRecord.Type__c == 'Git Promotion') {
                gitPromotionStep = stepRecord;
                break;
            }
        }
        if (gitPromotionStep == null) {
            return '';
        }
        try {
            for (Attachment att : [
                SELECT Id, Body
                FROM Attachment
                WHERE ParentId = :gitPromotionStep.Id AND Name = 'Git-Promotion.json'
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC
                LIMIT 1
            ]) {
                Map<String, Object> contents = (Map<String, Object>) JSON.deserializeUntyped(att.Body.toString());
                flow_id = (String) contents.get('flow_id');
                target_branch = (String) contents.get('target_branch');
                break;
            }

            if (String.isNotBlank(flow_id) && String.isNotBlank(target_branch)) {
                for (Deployment_Flow__c df : [SELECT Git_Repository__c FROM Deployment_Flow__c WHERE Id = :flow_id WITH SECURITY_ENFORCED LIMIT 1]) {
                    matchingKey = 'GIT-' + df.Git_Repository__c + '-' + target_branch;
                    break;
                }
            }
        } catch (Exception ex) {
            addErrorMessagesToMessageQueueMap(ex.getMessage());
        }
        return matchingKey;
    }

    public static Boolean getisChatterEnabled() {
        return Schema.SObjectType.User.isFeedEnabled() && Schema.SObjectType.Deployment__c.isFeedEnabled();
    }
}