Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/RunPromoteAndDeployJobTemplateHandler.cls
public with sharing class RunPromoteAndDeployJobTemplateHandler extends DeployJobTemplateHelper {

    // PUBLIC

    @AuraEnabled
    public static Boolean validate(Id recordId){
        return isPromotedUserStoriesCreated(recordId); 
    }

    @AuraEnabled
    public static Boolean deploymentJobAlreadyExecuted(Id recordId){
        return isDeploymentJobExecutionCreated(recordId); 
    }
    
    @AuraEnabled
    public static void execute(Id recordId){
        if(isPromoteJobExecutionCreated(recordId)) {
            RunDeployJobTemplateHandler.execute(recordId);
        } else {
            getPromotionDetails(recordId);
            prepareJobParameters();
            run();
        }
    }

    @AuraEnabled
    public static void executeOutstanding(Id recordId, Boolean runAllSteps) {
        
        JobExecution__c promoteJobExecution = new JobExecutionsSelector().byPromotionId(recordId);
        updatePromotion(recordId, 'In Progress');

        if(runAllSteps || promoteJobExecution.Status__c != 'Successful') {
            runOutstandingJobs(promoteJobExecution.Id, runAllSteps);       
        } else {
            Deployment__c deployment = new DeploymentsSelector().byPromotionId(recordId);
            if(deployment != null) {
                runOutstandingJobs(new JobExecutionsSelector().byDeploymentId(deployment.Id).Id, runAllSteps);
            } 
        }      
    }
}