Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Rolled_back_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Rolled_back_Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the original deployment that was rolled back for reporting purposes</description>
    <inlineHelpText>Identifies the original deployment that was rolled back for reporting purposes</inlineHelpText>
    <label>Rolled back Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Deployments (Rolled back Deployment)</relationshipLabel>
    <relationshipName>RolledBackDeployments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/Destination_Org__c.object-meta.xml
<CustomObject>
    <label>Destination Credential</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Credential Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipName>Destination_Orgs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Destination_Org__c/fields/To_Org__c.field-meta.xml
<CustomField>
    <fullName>To_Org__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>To Credential</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Org__c.CreatedById</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Destination Credentials</relationshipLabel>
    <relationshipName>Deployments_to</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Enable_Rollback__c.field-meta.xml
<CustomField>
    <fullName>Enable_Rollback__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable Rollbacks for any Deployments/Promotions have this Environment as destination. Rollbacks will be available for Deployments/Promotions created after this feature is enabled</description>
    <inlineHelpText>Enable Rollbacks for any Deployments/Promotions have this Environment as destination. Rollbacks will be available for Deployments/Promotions created after this feature is enabled</inlineHelpText>
    <label>Enable Rollback</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production/Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Scratch Org</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Disable_Validation__c.field-meta.xml
<CustomField>
    <fullName>Disable_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this checkbox will not validate the credentials when the record is saved or viewed.</inlineHelpText>
    <label>Disable Validation</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Validated_Status__c.field-meta.xml
<CustomField>
    <fullName>Validated_Status__c</fullName>
    <formula>IF(ISBLANK(Validated_Date__c),
&quot;Error&quot; ,
 IF( DATEVALUE(Validated_Date__c) == TODAY(), 
    &quot;OK&quot;,&quot;None&quot;) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Validated Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/CheckOnly__c.field-meta.xml
<CustomField>
    <fullName>CheckOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This only Apply for Metadata Steps. None of the other Steps types are affected by this checkbox. 
WARNING: Credits consumption will apply as a regular deployment since resource-wise is exactly the same as a real deployment.</inlineHelpText>
    <label>CheckOnly</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MetaData</fullName>
                <default>true</default>
                <label>MetaData</label>
            </value>
            <value>
                <fullName>Full Profiles</fullName>
            </value>
            <value>
                <fullName>Full Permission Sets</fullName>
            </value>
            <value>
                <fullName>Users</fullName>
            </value>
            <value>
                <fullName>Translations</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Bulk Data</fullName>
            </value>
            <value>
                <fullName>Data Template</fullName>
            </value>
            <value>
                <fullName>Delete MetaData</fullName>
            </value>
            <value>
                <fullName>Custom Settings</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Git MetaData</fullName>
            </value>
            <value>
                <fullName>URL Callout</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/RollbackWizardStartExt.cls
public with sharing class RollbackWizardStartExt extends DeploymentHelper {
    private List<String> stepTypesAvailableForRollback = new List<String>{ 'Git Promotion', 'Delete MetaData' };

    private List<String> deploymentStatusesForRollback = new List<String>{ 'Completed Successfully', 'Completed With Errors' };

    public RollbackWizardStartExt(ApexPages.StandardController stdCtrl) {
        if (!Test.isRunningTest()) {
            stdCtrl.addFields(new List<String>(Schema.SObjectType.Deployment__c.fields.getMap().keySet()));
        }
        Deployment__c rollbackDeployment = (Deployment__c) stdCtrl.getRecord();
        deployment = rollbackDeployment;
        initializeServiceClasses();
        populateNecessaryData();
        populateStepsList();
        populatePagesList();
    }

    // PUBLIC

    public PageReference saveAndGoToNextStep() {
        upsertDeployment(true);
        PageReference pageRef = pageMessagesMap.isEmpty() ? goToNextStep() : null;
        return pageRef;
    }

    // PRIVATE

    private void populateNecessaryData() {
        pageMessagesMap.clear();
        sourceList = new List<SourceWrapper>();

        if (!isRollbackAvailable()) {
            return;
        }

        try {
            for (Step__c step : [
                SELECT
                    Id,
                    Name,
                    Type__c,
                    Status__c,
                    CheckOnly__c,
                    Order__c,
                    (
                        SELECT Id
                        FROM ContentDocumentLinks
                        WHERE ContentDocument.Title = 'Rollback Index' OR ContentDocument.Title = 'Rollback Index.json'
                    )
                FROM Step__c
                WHERE Deployment__c = :deployment.Rolled_Back_Deployment__c
                WITH SECURITY_ENFORCED
                ORDER BY Order__c ASC
            ]) {
                String reason = getRollbackAvailability(step);
                sourceList.add(new SourceWrapper(step.Name, step.Type__c, step.Status__c, reason == '', reason));
            }
        } catch (Exception e) {
            addErrorMessage(
                Label.Insufficient_Access_Rights +
                ' ' +
                Label.Related_Object +
                ' ' +
                Schema.SObjectType.Step__c.getLabel() +
                '/' +
                Schema.SObjectType.ContentDocumentLink.getLabel()
            );
            return;
        }
    }

    private Boolean isRollbackAvailable() {
        try {
            Deployment__c rolledBackDeployment = [
                SELECT Status__c, (SELECT To_Org__c, To_Org__r.Environment__r.Enable_Rollback__c FROM Destination_Orgs__r LIMIT 1)
                FROM Deployment__c
                WHERE Id = :deployment.Rolled_Back_Deployment__c
                WITH SECURITY_ENFORCED
            ];

            if (!rolledBackDeployment.Destination_Orgs__r[0].To_Org__r.Environment__r.Enable_Rollback__c) {
                addErrorMessage(Label.RollbackNotEnabled);
                return false;
            }
        } catch (Exception e) {
            addErrorMessage(
                Label.Insufficient_Access_Rights +
                ': ' +
                Label.Related_Object +
                ' ' +
                Schema.SObjectType.Deployment__c.getLabel() +
                '/' +
                Schema.SObjectType.Destination_Org__c.getLabel()
            );
            return false;
        }

        if (!areAvailableSteps()) {
            return false;
        }

        if (!isDestinationOrgValidated()) {
            addErrorMessage(Label.DESTINATION_ORG_NOT_VALIDATED);
            return false;
        }

        return true;
    }

    private Boolean areAvailableSteps() {
        try {
            List<Step__c> steps = [
                SELECT
                    Id,
                    Name,
                    Type__c,
                    Status__c,
                    (
                        SELECT Id
                        FROM ContentDocumentLinks
                        WHERE ContentDocument.Title = 'Rollback Index.json' OR ContentDocument.Title = 'Rollback metadata.zip'
                    )
                FROM Step__c
                WHERE
                    Deployment__c = :deployment.Rolled_Back_Deployment__c
                    AND Type__c IN :stepTypesAvailableForRollback
                    AND Status__c IN :deploymentStatusesForRollback
                    AND CheckOnly__c = FALSE
                WITH SECURITY_ENFORCED
            ];

            if (steps.isEmpty()) {
                addErrorMessage(Label.RollbackNoEligibleSteps);
                return false;
            }

            for (Step__c step : steps) {
                if ((step.ContentDocumentLinks.isEmpty() || step.ContentDocumentLinks.size() < 2) && !Test.isRunningTest()) {
                    addErrorMessage(Label.RollbackMissingFiles);
                    return false;
                }
            }

            return true;
        } catch (Exception e) {
            addErrorMessage(Label.Insufficient_Access_Rights + ': ' + Label.Related_Object + ' ' + Schema.SObjectType.Step__c.getLabel());
            return false;
        }
    }

    private Boolean isDestinationOrgValidated() {
        Destination_Org__c destOrg = getDestinationOrg();
        if (destOrg.To_Org__c != null) {
            try {
                List<Org__c> orgs = new OrgsSelector().byId(new Set<Id>{ destOrg.To_Org__c });
                if (!orgs[0].Disable_Validation__c && orgs[0].Validated_Status__c != C_OK) {
                    return DeployAPI.validateOrg(destOrg.To_Org__c);
                }
                return true;
            } catch (Exception e) {
                addErrorMessage(Label.Insufficient_Access_Rights + ' ' + Label.Related_Object + ' ' + Schema.SObjectType.Org__c.getLabel());
            }
        } else {
            addErrorMessage(Label.RollbackMissingDestOrg);
        }
        return false;
    }

    private String getRollbackAvailability(Step__c step) {
        String result = '';

        if (!stepTypesAvailableForRollback.contains(step.Type__c)) {
            result = Label.RollbackStepTypeNotEligible;
        } else if (step.CheckOnly__c) {
            result = Label.RollbackValidationStepMessage;
        } else if (step.ContentDocumentLinks.isEmpty()) {
            result = Label.RollbackMissingFilesMessage;
        }

        return result;
    }
}