Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/Promoted_User_Story__c.object-meta.xml
<CustomObject>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promoted User Stories</relationshipLabel>
    <relationshipName>Promoted_User_Stories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status Outdated invalidates that this user story got promoted. The user story will be available again for automated promotions and back promotions if applicable.</description>
    <label>Active / Outdated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Outdated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Promotions</relationshipLabel>
    <relationshipName>Promoted_User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with errors</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Validation failed</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
            <value>
                <fullName>Conflicts Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/User_Story_Metadata__c.object-meta.xml
<CustomObject>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Action to be performed with the current metadata when committing</description>
    <inlineHelpText>Action to be performed with the current metadata when committing</inlineHelpText>
    <label>Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Represents a grouping of metadata, i.e. vlocity, cpq</description>
    <inlineHelpText>Represents a grouping of metadata, i.e. vlocity, cpq</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/JsonInformation__c.field-meta.xml
<CustomField>
    <fullName>JsonInformation__c</fullName>
    <description>Additional values associated with this commit</description>
    <inlineHelpText>Additional values associated with this commit</inlineHelpText>
    <label>Json Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/Metadata_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Metadata_API_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/ModuleDirectory__c.field-meta.xml
<CustomField>
    <fullName>ModuleDirectory__c</fullName>
    <description>Folder where the metadata is allocated</description>
    <inlineHelpText>Folder where the metadata is allocated</inlineHelpText>
    <label>Directory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the metadata</description>
    <inlineHelpText>Type of the metadata</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Metadata</relationshipLabel>
    <relationshipName>User_Story_Metadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/PromoteActionService.cls
@SuppressWarnings('PMD')
public with sharing virtual class PromoteActionService {
    // TODO: Remove this comment

    public static final String IN_PROGRESS = 'In Progress';
    public static final String SUCCESSFUL = 'Successful';
    public static final String COMPLETED = 'Completed';
    public static final String COMPLETED_WITH_ERRORS = 'Completed with errors';

    // PUBLIC

    public static void populateUserStoryParameters(CreateExecutionRequestData requestData, List<Promoted_User_Story__c> promotedUserStories) {
        requestData.userStoryIds = new List<Id>();
        requestData.userStoryBranches = new List<String>();
        for(Promoted_User_Story__c promotedUserStory : promotedUserStories) {
            requestData.userStoryIds.add(promotedUserStory.User_Story__c);
            requestData.userStoryBranches.add('feature/' + promotedUserStory.User_Story__r.Name);
        }
    }

    public static void populateChangeParameters(CreateExecutionRequestData requestData) {
        // read all the User_Story_Metadata objects of all the user stories, make it a unique list
        // and save it into requestData.changes
        requestData.changes = new List<Change>();
        List<User_Story_Metadata__c> userStoryMetadatas = [SELECT Metadata_API_Name__c, Type__c, Action__c, 
                                                           ModuleDirectory__c, Category__c, JsonInformation__c
                                                           FROM User_Story_Metadata__c 
                                             WHERE User_Story__c IN :requestData.userStoryIds
                                             WITH SECURITY_ENFORCED
                                             ORDER BY CreatedDate DESC LIMIT 8000];
        for(User_Story_Metadata__c userStoryMetadata : userStoryMetadatas) {
            Change changeItem = new Change(userStoryMetadata.Metadata_API_Name__c, 
                                           userStoryMetadata.Type__c, 
                                           userStoryMetadata.ModuleDirectory__c, 
                                           userStoryMetadata.Action__c, 
                                           userStoryMetadata.Category__c, 
                                           userStoryMetadata.JsonInformation__c);
            requestData.changes.add(changeItem);
        }
    }

    public static void populateFileParameters(CreateExecutionRequestData requestData, Id parentId, String fileName) {
        // THIS is the File that the  Job will read if/when executed, avoiding the need of any Flow to gather the information
        String changesJson = Json.serialize(requestData.changes, true);
        requestData.changes = null; // remove the changes from the request
        ContentVersion contentVersionRecord = upsertFileWithParent(parentId, fileName, changesJson);
        requestData.fileWithSelectedChanges = contentVersionRecord.Id;
    }

    public static Boolean isDeploymentJobExecutionCreated(CreateExecutionRequestData requestData) {
        requestData.deployment = new DeploymentsSelector().byPromotionId(requestData.promotionId);
        return requestData.deployment != null && (new JobExecutionsSelector().byDeploymentId(requestData.deployment.Id)) != null;
    }

    public static void updatePromotion(Id promotionId, String status) {
        List<SObject> records = new List<SObject> {
            new Promotion__c(Id = promotionId, Status__c = status)
        };

        update Security.stripInaccessible(AccessType.UPDATABLE, records).getRecords();
    }

    public static void updateJobExecutionDataJson(Id jobExecutionId, CreateExecutionRequestData requestData) {
        requestData.promotion = null;
        requestData.deployment = null;

        List<SObject> records = new List<SObject> {
            new JobExecution__c(Id = jobExecutionId, DataJson__c = Json.serializePretty(requestData, true))
        };

        update Security.stripInaccessible(AccessType.UPDATABLE, records).getRecords();
    }

    public static void runOutstandingJobs(Id jobId) {
        RunJob.Request request = new RunJob.Request();
        request.jobId = jobId;
        request.allSteps = true;

        RunJob.execute(new List<RunJob.Request>{ request });
    }

    public static void getPromotionDetails(CreateExecutionRequestData requestData) {
        List<Promotion__c> promotions = new PromotionsSelector().onlyPromotionsDetailByIds(new Set<Id>{ requestData.promotionId });
        requestData.promotion = promotions.isEmpty() ? new Promotion__c() : promotions[0];
    }

    public static List<CreateExecution.Request> asRequests(CreateExecutionRequestData requestData, String templateName, Id parentId, String callbackClass, List<JobStep__c> preStep, List<JobStep__c> postStep) {
        CreateExecution.Request requestRecord = new CreateExecution.Request();
        requestRecord.templateName = templateName;
        requestRecord.parentId = parentId;
        requestRecord.sourceId = requestData.promotion.Source_Environment__c;
        requestRecord.destinationId = requestData.promotion.Destination_Environment__c;
        requestRecord.callback = callbackClass;
        requestRecord.runAfterInstantiation = requestData.executePromotion != null ? requestData.executePromotion : requestData.executeDeployment;
        requestRecord.preSteps = preStep;
        requestRecord.postSteps = postStep;

        requestData.promotion = null;
        requestData.deployment = null;

        requestRecord.dataJson = Json.serializePretty(requestData, true);

        return new List<CreateExecution.Request>{ requestRecord };
    }

    public static List<CreateExecution.Request> asRequests(CreateExecutionRequestData requestData, String templateName, Id parentId, String callbackClass) {
        return asRequests(requestData, templateName, parentId, callbackClass, null, null);
    }

    public static String destinationBranchName(Promotion__c promotion) {
        String pipelineId = pipeline(promotion);
        String branch = [SELECT Id, Branch__c FROM Deployment_Flow_Step__c WHERE Deployment_Flow__c = :pipelineId AND Source_Environment__c = :promotion.Destination_Environment__c WITH SECURITY_ENFORCED]?.Branch__c;
        if(String.isBlank(branch)) {
            branch = [SELECT Id, Main_Branch__c FROM Deployment_Flow__c WHERE Id = :pipelineId WITH SECURITY_ENFORCED]?.Main_Branch__c;
        }
        return branch;
    }


    // PRIVATE 

    private static ContentVersion upsertFileWithParent(Id parentId, String name, String content) {
        deletePreviousFileWithParent(parentId);
                
        // create new file
        ContentVersion contentVersionRecord = new ContentVersion();
        contentVersionRecord.ContentLocation = 'S'; // 'S' = a Salesforce File
        contentVersionRecord.VersionData = Blob.valueOf(content);
        contentVersionRecord.Title = name;
        contentVersionRecord.PathOnClient = contentVersionRecord.Title;
        insert contentVersionRecord;
        
        Id contentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersionRecord.Id].ContentDocumentId;
        ContentDocumentLink contentDocumentLinkRecord = new ContentDocumentLink();
        contentDocumentLinkRecord.LinkedEntityId = parentId;
        contentDocumentLinkRecord.ContentDocumentId = contentDocumentId;
        contentDocumentLinkRecord.shareType = 'V';
        insert contentDocumentLinkRecord;
        
        return contentVersionRecord;
    }

    private static void deletePreviousFileWithParent(Id parentId) {
        // TODO first check iof we cvan delete the file for different owner. Also check if we need to SOQL with security enforced.
        // TODO not sure if we need to check OLS for content version

        // delete previous file(s) with the same name and parentId, if any
        List<ContentDocumentLink> contentDocumentLinks = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :parentId LIMIT 100];
        if(!contentDocumentLinks.isEmpty()) {
            Set<Id> contentDocumentLinkIds = new Set<Id>();
            for(ContentDocumentLink contentDocumentLinkRecord : contentDocumentLinks) {
                contentDocumentLinkIds.add(contentDocumentLinkRecord.ContentDocumentId);
            }
            List<ContentDocument> existingFiles = [SELECT Id FROM ContentDocument WHERE Id IN :contentDocumentLinkIds];
            delete existingFiles;
        }
    }

    private static String pipeline(Promotion__c promotion) {
        String pipelineId = '';
        if(promotion.Project__c != null) {
            pipelineId = promotion.Project__r.Deployment_Flow__c;
        } else if(promotion.Release__c != null) {
            pipelineId = promotion.Release__r.Project__r.Deployment_Flow__c;
        }
        return pipelineId;
    }


    // WRAPPER 

    public class CreateExecutionRequestData {
        // Common variables for both Promote and Deploy action
        public Id promotionId;
        public Boolean deploymentDryRun; 
        public Boolean executeDeployment;
        public String otherInformation;

        // Variables for Promote action
        public Id sourceEnvironmentId;
        public Boolean isBackPromotion;
        public Id projectId;
        public Boolean executePromotion;

        // Only used by the Job execution for both action
        public List<Change> changes; // list of all changes of each user story
        public Promotion__c promotion;
        public String destinationBranchName;
        public String promotionBranchName;
        public Id fileWithSelectedChanges;
        public List<Id> userStoryIds;

        // Only used by the Job execution for Deploy Action
        public Id deploymentId;
        public Deployment__c deployment;

        // Only used by the Job execution for Promote Action
        public Id sourceCredentialId;
        public Id destinationCredentialId;
        public List<String> userStoryBranches = new List<String>();
        public List<Promotion__c> promotions;
    }

    // NOTE: names are short to reduce memory/heap/transmission sizes
    public class Change {
        @InvocableVariable(required=true)
        public String n; // "name"

        @InvocableVariable
        public String t; // "type"

        @InvocableVariable
        public String m; // "module directory"

        @InvocableVariable(required=true)
        public String a; // "action" add, delete, retrieve-only, full pps, "deleteCascade"

        @InvocableVariable
        public String c; // optional, not used right now, "category" of this item: copadodx, vlocity, cpq, ...

        @InvocableVariable
        public String j; // "json additional information"... other values associated with this File

        public Change(String n, String t, String m,  String a, String c, String j) {
            this.n = n;
            this.t = t;
            this.m = m;
            this.a = a;
            this.c = c;
            this.j = j;
        }
    }
}