Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/Deployment_Job__c.object-meta.xml
<CustomObject>
    <label>Deployment Job</label>
    <nameField>
        <displayFormat>DJ-{00000}</displayFormat>
        <label>Deployment Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <referenceTo>Step__c</referenceTo>
    <relationshipLabel>Deployment Jobs</relationshipLabel>
    <relationshipName>Deployment_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Parent_Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Owner_Id__c</fullName>
    <formula>IF(NOT(ISBLANK( JobExecution__r.Deployment__c )), JobExecution__r.Deployment__r.Promotion__r.OwnerId,
    IF(NOT(ISBLANK( JobExecution__r.Promotion__c )), JobExecution__r.Promotion__r.OwnerId, OwnerId))</formula>
    <label>Parent Owner Id</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to track multi-step deployment overall results.</description>
    <inlineHelpText>Used to track multi-step deployment overall results.</inlineHelpText>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>Date time when the job ended.</description>
    <inlineHelpText>Date time when the job ended.</inlineHelpText>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copado Function that triggered this result.</inlineHelpText>
    <label>Function</label>
    <referenceTo>Function__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/FunctionCallout.cls
public with sharing class FunctionCallout extends HttpCallout {
    private static final Boolean AUTOMATED_PROCESS = UserInfo.getUserType() == 'AutomatedProcess';
    private String resultId;
    private String payload;
    private String contextId;

    public FunctionCallout(String resultId) {
        if (namedCredentialExists()) {
        super('callout:' + Settings.functionsNamedCredential, HttpMethod.POST);
        this.resultId = resultId;
        } else {
            throw new FunctionCalloutException(
                String.format(Label.Endpoint_not_Found, new List<String>{ String.valueOf(Settings.functionsNamedCredential) })
            );
        }
    }

    public FunctionCallout payload(String payload) {
        this.payload = payload;
        return this;
    }

    public FunctionCallout contextId(String contextId) {
        this.contextId = contextId;
        return this;
    }

    /**
     * @exception throws Exception. Make sure to handle it from the calling context.
     */
    public FunctionCallout build() {
        setHeaders();
        body(payload);
        path('/function/' + resultId);
        timeout(120000);

        return this;
    }

    public override Object processResponse() {
        HttpResponse response = response();
        Integer statusCode = response.getStatusCode();
        if (statusCode != 200 && statusCode != 201) {
            update Security.stripInaccessible(
                    AccessType.UPDATABLE,
                    new List<Result__c>{
                        new Result__c(
                            Id = resultId,
                            End_Time__c = Datetime.now(),
                            Status__c = 'Failed',
                            Progress_Status__c = Label.Error,
                    Error_Message__c = response.getBody(),
                    Error_Code__c = String.valueOf(statusCode)
                )
                    }
                )
                .getRecords();

                Result__c result = new ResultsSelector().byid(resultId);
                new HandleBackendResponse().resultCallback(new FunctionsSelector().byId(result.Function__c), resultId, 'Error');
        } else {
            if (resultMonitor().isEmpty()) {
                FunctionResultMonitor.start();
            }
        }
        return response;
    }

    private void setHeaders() {
        User user = user();
        header('userId', user.Id);
        header('user-email', user.Email);
        header('user-name', user.Name);
        header('copado-url', Settings.server_url);
        header('copado-namespace', Settings.ns);
        header('Content-Type', 'application/json');
        header('token2', DeployAPI.getAuthToken2(user.Id));
        header('orgId', UserInfo.getOrganizationId());
        header('copado-api-key', apiKey(user.Id));
    }

    // To avoid creating remote site settings for the named credential endpoint, we only query it to check if it exists
    // and then reference it using the 'callout:namedCredential' notation. This will allow us to throw our own expection,
    // as opposed to having Salesforce throw an UnexpectedException, which cannot be caught.
    private Boolean namedCredentialExists() {
        String name = Settings.functionsNamedCredential.replace(Settings.ns, '');
        List<NamedCredential> result = [SELECT Id FROM NamedCredential WHERE DeveloperName = :name];

        return !result.isEmpty();
    }

    private User user() {
        User user;

        if (AUTOMATED_PROCESS) {
            user = [SELECT Email, Name FROM User WHERE Id = :ownerId()];
        } else {
            user = [SELECT Email, Name FROM User WHERE Id = :UserInfo.getUserId()];
        }

        return user;
    }

    private String apiKey(Id userId) {
        String result;

        if (AUTOMATED_PROCESS) {
            result = ownerKey(userId);
        } else {
            result = new Settings().mySettings.API_Key__c;
        }

        return result;
    }

    private List<Crontrigger> resultMonitor() {
        return [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name LIKE 'FunctionResultMonitor%' LIMIT 1];
    }

    private String ownerKey(Id userId) {
        return DeployAPI.decryptAPIKey([SELECT API_Key__c FROM Personal_Settings__c WHERE SetupOwnerId = :userId LIMIT 1]?.API_Key__c);
    }

    private Id ownerId() {
        Id result;
        String objectType = objectType();

        if (objectType == 'Deployment_Job__c') {
            result = [SELECT Step__r.Deployment__r.OwnerId FROM Deployment_Job__c WHERE Id = :contextId WITH SECURITY_ENFORCED]
            ?.Step__r.Deployment__r.OwnerId;
        } else if(objectType == 'JobStep__c') {
            result = [SELECT Parent_Owner_Id__c FROM JobStep__c WHERE Id = :contextId WITH SECURITY_ENFORCED]?.Parent_Owner_Id__c;
		} else {
            String query = 'SELECT OwnerId FROM ' + objectType + ' WHERE Id = :contextId WITH SECURITY_ENFORCED';

            List<SObject> records = Database.query(query);
            result = (records.isEmpty()) ? null : (Id) records[0].get('OwnerId');
        }

        if (String.isBlank(result)) {
            throw new FunctionCalloutException(Label.Context_Owner_Not_Found);
        }

        return result;
    }

    private String objectType() {
        return String.isNotBlank(contextId) ? Id.valueOf(contextId).getSObjectType().getDescribe().getLocalName() : '';
    }

    private class FunctionCalloutException extends CopadoFunctionException {
    }
}