Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/Deployment_Job__c.object-meta.xml
<CustomObject>
    <label>Deployment Job</label>
    <nameField>
        <displayFormat>DJ-{00000}</displayFormat>
        <label>Deployment Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/fields/Last_Result__c.field-meta.xml
<CustomField>
    <fullName>Last_Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Latest result with more details of the job execution.</inlineHelpText>
    <label>Last Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Deployment Jobs</relationshipLabel>
    <relationshipName>Deployment_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <referenceTo>Step__c</referenceTo>
    <relationshipLabel>Deployment Jobs</relationshipLabel>
    <relationshipName>Deployment_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to track multi-step deployment overall results.</description>
    <inlineHelpText>Used to track multi-step deployment overall results.</inlineHelpText>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/DeploymentStatusService.cls
public with sharing class DeploymentStatusService implements CLIInterface {
       
    // PUBLIC

    public CLIInterface getInstance() {
        return this;
    }

    public String run(CliProxy.CLIWrapper record) {
        DeploymentStatus result = new DeploymentStatus();
        Request request = (Request) JSON.deserialize(record.body, Request.class);

        String messageLabel = 'Automation is {0}, {1} of {2} steps completed';
        Integer stepsCompleted = 0;

        List<Deployment__c> deployments = new DeploymentsSelector().byIdWithSteps(new Set<Id> {request.deploymentId});

        if(deployments.isEmpty()) {
            throw new CliException('Invalid deployment id: ' + record.body);
        }

        result.status = deployments[0].Status__c;
        Map<Id, Result> resultsByStepId = resultsByStepId(deployments[0].Steps__r);

        for(Step__c step : deployments[0].Steps__r) {
            Result stepResult = resultsByStepId.containsKey(step.Id) ? resultsByStepId.get(step.Id) : null;
            Boolean isCompleted = step.Status__c == 'Completed Successfully' || step.Status__c == 'Completed with Errors';
            result.addStepStatus(new StepStatus(step.Name, step.Status__c, isCompleted, stepResult));
        }
        String message = String.format(messageLabel, new List<String> {result.status, String.valueOf(result.stepsCompleted), String.valueOf(deployments[0].Steps__r.size())});
        
        return toResponse(message, result);
    }


    // PRIVATE
    
    private Map<Id, Result> resultsByStepId(List<Step__c> steps) {
        Map<Id, Result> result = new Map<Id, Result>();

        Set<Id> stepIds = new Map<Id, Step__c>(steps).keySet();
        
        for(Deployment_Job__c job : [SELECT Id, Step__c, Last_Result__c, Last_Result__r.Error_Message__c FROM Deployment_Job__c WHERE Step__c IN :stepIds]) {
            result.put(job.Step__c, new Result(job.Last_Result__c, job.Last_Result__r.Error_Message__c));
        }

        return result;
    }

    private String toResponse(String message, DeploymentStatus deploymentStatus) {
        Response result = new Response(CliSfDataWrapper.StatusResult.OK.name(), message, deploymentStatus);
        
        return (JSON.serialize(result));
    }

    // INNER

    public class Result { 
        public Id id;
        public String message;

        public Result(Id id, String message) {
            this.id = id;
            this.message = message;
        }
    }

    @TestVisible
    public class Response extends CliSfDataWrapper {
        DeploymentStatus deploymentStatus;

        public Response(String stat, String msg, DeploymentStatus deploymentStatus) {
            status = stat;
            message = msg;
            this.deploymentStatus = deploymentStatus;
        }
    }

    public class DeploymentStatus { 
        public String status;
        public Integer stepsCompleted = 0;
        public List<StepStatus> stepStatuses = new List<StepStatus>();

        public void addStepStatus(StepStatus stepStatus) {
            stepStatuses.add(stepStatus);
            stepsCompleted += (stepStatus.isCompleted ? 1 : 0);
        }
    }

    public class StepStatus { 
        public String name;
        public String status;
        public Result stepResult;
        public Boolean isCompleted;

        public StepStatus(String name, String status, Boolean isCompleted, Result stepResult) {
            this.name = name;
            this.status = status;
            this.stepResult = stepResult;
            this.isCompleted = isCompleted;
        }
    }

    public class Request { 
        public String deploymentId;
    }
}