Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Feature__c/Feature__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Track what Copado features the installation has access to.</description>
    <label>Feature</label>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/dataJson__c.field-meta.xml
<CustomField>
    <fullName>dataJson__c</fullName>
    <description>If the step type is &quot;data&quot;  this should contains the json defining the query. 
In production this field should be HIDDEN</description>
    <label>dataJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Manual_Task_Notified__c.field-meta.xml
<CustomField>
    <fullName>Manual_Task_Notified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To prevent sending multiple notifications to the same Manual Task owner per Task</description>
    <label>Manual Task Notified</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MetaData</fullName>
                <default>true</default>
                <label>MetaData</label>
            </value>
            <value>
                <fullName>Full Profiles</fullName>
            </value>
            <value>
                <fullName>Full Permission Sets</fullName>
            </value>
            <value>
                <fullName>Users</fullName>
            </value>
            <value>
                <fullName>Translations</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Bulk Data</fullName>
            </value>
            <value>
                <fullName>Data Template</fullName>
            </value>
            <value>
                <fullName>Delete MetaData</fullName>
            </value>
            <value>
                <fullName>Custom Settings</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Git MetaData</fullName>
            </value>
            <value>
                <fullName>URL Callout</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/StepTriggerHelper.cls
public without sharing class StepTriggerHelper {
    private static final String NAMESPACE = Settings.ns;

    private List<Step__c> steps;

    // CONSTRUCTOR

    public StepTriggerHelper(List<Step__c> steps) {
        this.steps = steps;
    }

    // PUBLIC

    public void notifyManualStepOwner() {
        for(Step__c step : steps) {
            if (isManualTaskInProgress(step)) {
                notifyTaskOwner(step);
            }
        }
    }

    public void validate() {
        checkFeature();

        // Note: Skip license check for Automated process
        if (UserInfo.getUserType() != 'AutomatedProcess') {
            checkLicense();
        }
    }

    public void afterInsert() {
        DeployJobHelper.upsertDeployJobs( getDeployments() );
    }

    // PRIVATE

    private Boolean isManualTaskInProgress(Step__c step) {
        return (
            step.Status__c == 'In Progress' &&
            step.Type__c == 'Manual Task' &&
            !step.Manual_Task_Notified__c
        );
    }

    private List<Deployment__c> getDeployments() {
        List<Deployment__c> result = new List<Deployment__c>();

        for (Step__c step : steps) {
            result.add(new Deployment__c(Id = step.Deployment__c));
        }

        return result;
    }


    private void checkFeature() {
        for (Step__c step : steps) {
            String feature = step.Type__c + ' step';
            Feature__c featureRecord = Feature__c.getValues(feature);

            if (featureRecord != null && !featureRecord.Enabled__c) {
                step.addError(Label.STEP_NOT_SUPPORTED);
            }
        }
    }

    private void checkLicense() {
        Boolean isLicensesExceeded = LicenseHelper.isLicensesExceeded();
        Boolean isCopadoEnabled = LicenseHelper.isCopadoEnabled();
        Boolean isCCMEnabled = LicenseHelper.isCCMEnabled();

        for (Step__c step : steps) {
            if (isLicensesExceeded) {
                step.addError(Label.LICENSES_EXCEEDED);
            }
            else if (!isCopadoEnabled && !isCCMEnabled) {
                step.addError(Label.COPADO_DEPLOYER_LICENSE_NOT_ENABLED);
            }
        }
    }

    private static void notifyTaskOwner(Step__c step) {
        step.Manual_Task_Notified__c = true;

        ManualTaskJSONdata taskData = (ManualTaskJSONdata) JSON.deserialize(step.dataJson__c, ManualTaskJSONdata.class);
        String chatterMessage = ' ' + System.Label.MANUAL_TASK_WAITING + ' ' + step.Name;

        // TODO: Bulkify send email part
        if (String.isEmpty(taskData.Task_Owner)) {
            return;
        }

        if ((taskData.Notify_Task_Owner == 'Chatter' || taskData.Notify_Task_Owner == 'Chatter and Email') &&
            Utilities.isChatterEnabled(NAMESPACE + 'Deployment__c')) {
            Utilities.notifyUsingChatterWithAtMention(taskData.Task_Owner, chatterMessage, step.Deployment__c);
        }

        if (taskData.Notify_Task_Owner == 'Email' || taskData.Notify_Task_Owner == 'Chatter and Email') {
            notifyUsingEmail(taskData.Task_Owner, step.Name, step.Deployment__c);
        }
    }

    // Note: User is a special object and non-admin users will not have access to it
    @SuppressWarnings('PMD.ApexCRUDViolation')
    private static void notifyUsingEmail(String userId, String stepName, Id deploymentId) {
        User ownerOfTask = [SELECT Email FROM User WHERE Id = :userId LIMIT 1];

        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = new List<String>{ ownerOfTask.Email };
        String htmlBody = System.Label.MANUAL_TASK_WAITING + ' ' + stepName + '<br/>';
        htmlBody += 'Deployment link: ' + Url.getSalesforceBaseUrl().toExternalForm() + '/' + deploymentId;
        message.setHtmlBody(htmlBody);
        message.setSubject(System.Label.MANUAL_TASK_WAITING + ' ' + stepName);
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ message });
    }

    // INNER

    // Note: needs to look exactly like the API JSON
    @SuppressWarnings('PMD.PropertyNamingConventions')
    private class ManualTaskJSONdata {
        public Boolean Perform_in_Destination_Org { get; set; }
        public Boolean Perform_in_Source_Org { get; set; }
        public String Task_Description { get; set; }
        public String Task_Owner { get; set; }
        public String Notify_Task_Owner { get; set; }
    }
}