Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>This is a mandatory field if you intend to publish your automation template as copado extension package</inlineHelpText>
    <label>Api Name</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/recordTypes/Automation_Template.recordType-meta.xml
<RecordType>
    <fullName>Automation_Template</fullName>
    <active>true</active>
    <description>Group of steps to be executed in the future.</description>
    <label>Automation Template</label>
</RecordType>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <label>Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MetaData</fullName>
                <default>true</default>
                <label>MetaData</label>
            </value>
            <value>
                <fullName>Full Profiles</fullName>
            </value>
            <value>
                <fullName>Full Permission Sets</fullName>
            </value>
            <value>
                <fullName>Users</fullName>
            </value>
            <value>
                <fullName>Translations</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Bulk Data</fullName>
            </value>
            <value>
                <fullName>Data Template</fullName>
            </value>
            <value>
                <fullName>Delete MetaData</fullName>
            </value>
            <value>
                <fullName>Custom Settings</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Git MetaData</fullName>
            </value>
            <value>
                <fullName>URL Callout</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/SetDefaultStepOrder.cls
public with sharing class SetDefaultStepOrder {

    private List<Step__c> steps;

    // CONSTRUCTOR

    public SetDefaultStepOrder(List<Step__c> steps) {
        this.steps = steps;
    }

    // PUBLIC

    public void execute() {

        Id automationTemplateRecordTypeId = Schema.SObjectType.Deployment__c.getRecordTypeInfosByDeveloperName().get('Automation_Template').getRecordTypeId();

        List<Deployment__c> deployments = new DeploymentsSelector().byIdWithSteps(deploymentIds());

        Map<Id, Deployment__c> deploymentsById = new Map<Id, Deployment__c>(deployments);
        Map<Id, Integer> deploymentStepsSizeByDeploymentIds = new Map<Id, Integer>();
        for (Deployment__c deployment : deployments) {
            deploymentStepsSizeByDeploymentIds.put(deployment.Id, deployment.Steps__r.size());
        }
        
        // To be able set correct order to deployment steps which comes from user story deployment tasks(created by backend)
        // or created in an automation template
        Map<Id, Integer> stepOrderCounterByDeploymentId = new Map<Id, Integer>();
        for (Step__c step : steps) {
            step.ApiName__c = deploymentsById.get(step.Deployment__c).ApiName__c + '_' + step.Name;

            Boolean isEditableDeploymentTaskStep =
                deploymentStepsSizeByDeploymentIds.containsKey(step.Deployment__c) &&
                isValidType(step.Type__c) &&
                !step.Read_Only__c;

            Boolean isAutomationTemplateStep =
                deploymentsById.get(step.Deployment__c).RecordTypeId == automationTemplateRecordTypeId;

            if (isEditableDeploymentTaskStep || isAutomationTemplateStep) {
                if (stepOrderCounterByDeploymentId.containsKey(step.Deployment__c)) {
                    stepOrderCounterByDeploymentId.put(step.Deployment__c, stepOrderCounterByDeploymentId.get(step.Deployment__c) + 1);
                } else {
                    stepOrderCounterByDeploymentId.put(step.Deployment__c, 1);
                }

                Integer numberOfSiblingSteps = deploymentStepsSizeByDeploymentIds.containsKey(step.Deployment__c)
                    ? deploymentStepsSizeByDeploymentIds.get(step.Deployment__c)
                    : 0;
                step.Order__c = numberOfSiblingSteps + stepOrderCounterByDeploymentId.get(step.Deployment__c);
            }
        }
    }

    private Set<Id> deploymentIds() {
        Set<Id> result = new Set<Id>();
        for (Step__c step : steps) {
            result.add(step.Deployment__c);
        }

        return result;
    }
    
    private Boolean isValidType(String type) {
        Set<String> deploymentTaskTypes = new Set<String> {
            'Manual Task',
            'Data',
            'Bulk Data',
            'Data Template',
            'Delete Metadata',
            'Custom Settings',
            'Apex',
            'URL Callout',
            'Salesforce Flow'
        };

        return deploymentTaskTypes.contains(type);
    }
}