Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed Successfully</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Callback__c.field-meta.xml
<CustomField>
    <fullName>Callback__c</fullName>
    <description>An apex class that must implement copado.JobExecutionCallback interface.</description>
    <inlineHelpText>An apex class that must implement copado.JobExecutionCallback interface.</inlineHelpText>
    <label>Callback</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/DataJson__c.field-meta.xml
<CustomField>
    <fullName>DataJson__c</fullName>
    <label>DataJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <formula>IF(NOT(ISBLANK( Deployment__c )), Deployment__c, 
    IF(NOT(ISBLANK( Promotion__c )), Promotion__c, 
        IF(NOT(ISBLANK( UserStoryCommit__c )), UserStoryCommit__c, 
            IF(NOT(ISBLANK( Snapshot__c )), Snapshot__c,  ParentRecord_Id__c)
        )
    )
)</formula>
    <label>Parent Id(Formula)</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/ParentRecord_Id__c.field-meta.xml
<CustomField>
    <fullName>ParentRecord_Id__c</fullName>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/VolumeOptions__c.field-meta.xml
<CustomField>
    <fullName>VolumeOptions__c</fullName>
    <label>VolumeOptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with errors</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Validation failed</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
            <value>
                <fullName>Conflicts Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/JobExecutionsSelector.cls
public with sharing class JobExecutionsSelector extends fflib_SObjectSelector {
    private String namespace = JobExecutionsSelector.class.getName().substringBefore('JobExecutionsSelector').removeEnd('.').toLowerCase();

    public SObjectType getSObjectType() {
        return JobExecution__c.sObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{
            JobExecution__c.Id,
            JobExecution__c.Name,
            JobExecution__c.OwnerId,
            JobExecution__c.Status__c,
            JobExecution__c.ParentId__c,
            JobExecution__c.Promotion__c,
            JobExecution__c.Deployment__c,
            JobExecution__c.Callback__c,
            JobExecution__c.DataJson__c,
            JobExecution__c.VolumeOptions__c,
            JobExecution__c.ParentRecord_Id__c
        };
    }


    public JobExecution__c byId(Id recordId) {
        List<JobExecution__c> result = byId(new Set<Id>{ recordId });

        return (result.isEmpty() ? null : result[0]);
    }


    public List<JobExecution__c> byId(Set<Id> recordIds) {
        return (List<JobExecution__c>) selectSObjectsById(new Set<Id>(recordIds));
    }

    
    public JobExecution__c byPromotionId(Id promotionId) {
        fflib_QueryFactory query = newQueryFactory().setCondition(JobExecution__c.Promotion__c + ' = :promotionId');
        namespace = String.isNotBlank(namespace) ? namespace + '__' : namespace;
        new JobStepsSelector().addQueryFactorySubselect(query, namespace + 'JobSteps__r');

        List<JobExecution__c> result = (List<JobExecution__c>) Database.query(query.toSOQL());

        return (result.isEmpty() ? null : result[0]);
    }

    public JobExecution__c byDeploymentId(Id deploymentId) {
        fflib_QueryFactory query = newQueryFactory().setCondition(JobExecution__c.Deployment__c + ' = :deploymentId');
        namespace = String.isNotBlank(namespace) ? namespace + '__' : namespace;
        new JobStepsSelector().addQueryFactorySubselect(query, namespace + 'JobSteps__r');

        List<JobExecution__c> result = (List<JobExecution__c>) Database.query(query.toSOQL());

        return (result.isEmpty() ? null : result[0]);
    }
}