Dummy_Package_for_scratch_org/main/default/objects/Event__e/fields/Topic_Uri__c.field-meta.xml
<CustomField>
    <fullName>Topic_Uri__c</fullName>
    <label>Topic Uri</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/ApexCallback__c.field-meta.xml
<CustomField>
    <fullName>ApexCallback__c</fullName>
    <description>This field is updated automatically by Copado.</description>
    <inlineHelpText>This field is updated automatically by Copado.</inlineHelpText>
    <label>Apex Callback</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Date time when the job started.</description>
    <inlineHelpText>Date time when the job started.</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/Flow.cls
public inherited sharing class Flow {
    private Id stepId;
    private String flowName;
    private String callback;
    private List<Parameter> parameters;

    @TestVisible
    private static Event__e mockResponse;


    // CONSTRUCTOR

    public Flow(Id stepId, String flowName) {
        this.stepId = stepId;
        this.flowName = flowName;
    }


    // PUBLIC

    public Id execute() {
        Result__c result = result();
        insert result;

        try {
            parameters = new TemplatingEngine(stepId, parameters).parse();

            if(Test.isRunningTest()) {
                mockResponse.Topic_Uri__c += result.Id;
                Eventbus.publish(mockResponse);
            }
            else {
                Map<String, String> flowParameter = asMap(parameters);
                flowParameter.put('resultId', result.Id);

                Flow.Interview.createInterview(namespace(flowName), localName(flowName), flowParameter).start();
            }
        }
        catch(Exception ex) {
            result.Status__c = 'Error';
            result.Error_Message__c = ex.getMessage();
            update result;

            Event__e stepCompleted = new Event__e();
            stepCompleted.Payload__c = asPayload(false, ex.getMessage());
            stepCompleted.Topic_Uri__c = OnJobStepComplete.STEP_ENDPOINT + result.Id;
            EventBus.publish(stepCompleted);
        }

        return result.Id;
    }


    public Flow resultCallback(String callback) {
        this.callback = callback;

        return this;
    }


    public Flow parameters(List<Parameter> parameters) {
        this.parameters = parameters;

        return this;
    }


    // PRIVATE

    private Map<String, String> asMap(List<Parameter> parameters) {
        Map<String, String> result = new Map<String, String>();

        for(Parameter parameter : parameters) {
            result.put(parameter.name, parameter.value);
        }

        return result;
    }


    private Result__c result() {
        Result__c result = new Result__c();
        result.JobStep__c = stepId;
        result.Job_Type__c = flowName;
        result.ParentId__c = stepId;
        result.Status__c = 'In Progress';
        result.ApexCallback__c = callback;
        result.Start_Time__c = Datetime.now();

        return (Result__c) Security.stripInaccessible(AccessType.CREATABLE, new List<SObject> { result }).getRecords().get(0);
    }


    private String asPayload(Boolean isSuccess, String message) {
        OnJobStepComplete.EventPayload result = new OnJobStepComplete.EventPayload(isSuccess, message);

        return JSON.serialize(result);
    }


    private String namespace(String name) {
        return name.contains('.') ? name.substringBefore('.') : '';
    }


    private String localName(String name) {
        return name.contains('.') ? name.substringAfter('.') : name;
    }
}