Dummy_Package_for_scratch_org/main/default/objects/Event__e/fields/Topic_Uri__c.field-meta.xml
<CustomField>
    <fullName>Topic_Uri__c</fullName>
    <label>Topic Uri</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/ResultDataJson__c.field-meta.xml
<CustomField>
    <fullName>ResultDataJson__c</fullName>
    <label>Result Data Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Result_Data__c.field-meta.xml
<CustomField>
    <fullName>Result_Data__c</fullName>
    <label>Result Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/OnJobStepComplete.cls
public with sharing class OnJobStepComplete {

    public static final String STEP_ENDPOINT = '/events/copado/v1/step-result/';
    private List<Event__e> records;

    // CONSTRUCTOR

    public OnJobStepComplete(List<Event__e> records) {
        this.records = records;
    }


    // PUBLIC

    public void execute() {

        for(Event__e event : filterRelevant( records )) {
            Id resultId = Id.valueOf(event.Topic_Uri__c.substringAfter(STEP_ENDPOINT));
            EventPayload payload = asEventPayload(event.Payload__c);

            Result__c result = updateStatus(resultId, payload);

            new StepCallback().execute(result.JobStep__r.JobExecution__c, payload.status());
        }
    }


    // PRIVATE

    private Result__c updateStatus(Id resultId, EventPayload payload) {
        Result__c result = [SELECT Id, JobStep__c, JobStep__r.JobExecution__c, Result_Data__c, Error_Message__c FROM Result__c WHERE Id = :resultId WITH SECURITY_ENFORCED];
        result.Status__c = payload.status();
        result.Result_Data__c = payload.data;
        result.Error_Message__c = payload.errorMessage;
        update Security.stripInaccessible(AccessType.UPDATABLE, new List<SObject> { result }).getRecords();

        JobStep__c step = new JobStep__c();
        step.Id = result.JobStep__c;
        step.ResultDataJson__c = payload.data;
        update Security.stripInaccessible(AccessType.UPDATABLE, new List<SObject> { step }).getRecords();

        return result;
    }


    private EventPayload asEventPayload(String payload) {
        EventPayload result;

        try {
            result = (EventPayload) JSON.deserialize(payload, EventPayload.class);
        }
        catch (Exception ex) {
            result = new EventPayload(false, Label.invalidStepPayload);
        }

        return result;
    }


    private List<Event__e> filterRelevant(List<Event__e> arbitraryEvents) {
        List<Event__e> result = new List<Event__e>();

        for(Event__e event : arbitraryEvents) {
            if(isRelevant(event)) {
                result.add(event);
            }
        }

        return result;
    }


    private Boolean isRelevant(Event__e event) {
        return (event.Topic_Uri__c != null &&
                 event.Topic_Uri__c.startsWith(STEP_ENDPOINT) &&
                 isResult(event));
    }


    private Boolean isResult(Event__e event) {
        String recordId = event.Topic_Uri__c.substringAfter(STEP_ENDPOINT);

        return (objectType(recordId) == 'Result__c');
    }


    private String objectType(Id recordId) {
        return (String.isNotBlank(recordId) ? recordId.getSObjectType().getDescribe().getLocalName() : '');
    }


    // INNER

    public class EventPayload {

        public String data;
        public String errorMessage;
        public Boolean isSuccess = false;


        public EventPayload(Boolean isSuccess, String errorMessage) {
            this.isSuccess = isSuccess;
            this.errorMessage = errorMessage;
        }


        public EventPayload(Boolean isSuccess, String errorMessage, String data) {
            this.data = data;
            this.isSuccess = isSuccess;
            this.errorMessage = errorMessage;
        }

        public String status() {
            return (isSuccess) ? 'Success' : 'Failed';
        }
    }
}