Dummy_Package_for_scratch_org/main/default/objects/Event__e/fields/Topic_Uri__c.field-meta.xml
<CustomField>
    <fullName>Topic_Uri__c</fullName>
    <label>Topic Uri</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Custom&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/ConfigJson__c.field-meta.xml
<CustomField>
    <fullName>ConfigJson__c</fullName>
    <label>ConfigJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobTemplate__c.field-meta.xml
<CustomField>
    <fullName>JobTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Custom&apos;</defaultValue>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/IsFinished__c.field-meta.xml
<CustomField>
    <fullName>IsFinished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Finished</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Success</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/Result_Data__c.field-meta.xml
<CustomField>
    <fullName>Result_Data__c</fullName>
    <label>Result Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Oauth_Signature__c.field-meta.xml
<CustomField>
    <fullName>Oauth_Signature__c</fullName>
    <description>This value is automatically set and updated by Copado.</description>
    <inlineHelpText>This value is automatically set and updated by Copado.</inlineHelpText>
    <label>Oauth Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/SFDC_Org_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Org_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Organization Id for the Environment.</description>
    <externalId>true</externalId>
    <inlineHelpText>Organization Id for the Environment.</inlineHelpText>
    <label>SFDC Org ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Validated_Date__c.field-meta.xml
<CustomField>
    <fullName>Validated_Date__c</fullName>
    <description>Latest OAuth authentication validation date.</description>
    <inlineHelpText>Latest OAuth authentication validation date.</inlineHelpText>
    <label>Validated Date</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copado Function that triggered this result.</inlineHelpText>
    <label>Function</label>
    <referenceTo>Function__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Result_Data__c.field-meta.xml
<CustomField>
    <fullName>Result_Data__c</fullName>
    <label>Result Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/RunJobTest.cls
@IsTest
private class RunJobTest {
    @TestSetup
    private static void setupData() {
        List<User> users = TestDataFactory.createUsers();
        List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();

        for (PermissionSet ps : [SELECT Id FROM PermissionSet WHERE Name = 'Copado_User' OR Name = 'Copado_Job_Engine']) {
            assignments.add(new PermissionSetAssignment(AssigneeId = users[0].Id, PermissionSetId = ps.Id));
        }
        insert assignments;
    }

    @IsTest
    private static void executeWithInvalidExecutionId() {
        // Setup
        Exception expectedException = null;
        RunJob.Request request = new RunJob.Request();

        // Exercise
        try {
            System.runAs(user()) {
                RunJob.execute(new List<RunJob.Request>{ request });
            }
        } catch (Exception ex) {
            expectedException = ex;
        }

        // Verify
        System.assertNotEquals(null, expectedException);
        System.assertEquals(Label.InvalidExecutionId, expectedException.getMessage());
    }

    @IsTest
    private static void shouldNotStartNextStepIfJobIsAlreadyInProgress() {
        // Setup
        Helper helper = new Helper().createExecution('In Progress').addStep('step1', 'Manual', 1, '');

        RunJob.Request request = new RunJob.Request();
        request.jobId = helper.execution.Id;

        // Exercise
        System.runAs(user()) {
            RunJob.execute(new List<RunJob.Request>{ request });
        }

        // Verify
        System.assertEquals(0, [SELECT COUNT() FROM Result__c]);
    }

    @IsTest
    private static void shouldResetResultOnExistingStepsOnRerun() {
        // Setup
        Helper helper = new Helper()
            .createExecution('Failed')
            .addStep('step1', 'Manual', 1, '')
            .addStep('step2', 'Manual', 2, '')
            .addResultFor('step1', 'Manual', 'Success')
            .addResultFor('step2', 'Manual', 'Failed');

        RunJob.Request request = new RunJob.Request();
        request.jobId = helper.execution.Id;

        // Exercise
        Test.startTest();
        System.runAs(user()) {
            RunJob.execute(new List<RunJob.Request>{ request });
        }
        Test.stopTest();
        Test.getEventBus().deliver();

        // Verify
        System.assertEquals(3, [SELECT COUNT() FROM Result__c]);
        System.assertEquals('In Progress', [SELECT Status__c FROM JobExecution__c].Status__c);
        System.assertEquals(null, [SELECT Result__c FROM JobStep__c WHERE Name = 'step2'].Result__c);
        System.assertNotEquals(null, [SELECT Result__c FROM JobStep__c WHERE Name = 'step1'].Result__c);
    }

    @IsTest
    private static void shouldFailExecutionForInvalidFlow() {
        // Setup
        Helper helper = new Helper().createExecution('Not Started').addStep('step1', 'Flow', 2, '{"flowName" : "Invalid Flow"}');

        RunJob.Request request = new RunJob.Request();
        request.jobId = helper.execution.Id;

        // Exercise
        Test.startTest();
        System.runAs(user()) {
            RunJob.execute(new List<RunJob.Request>{ request });
        }
        Test.stopTest();

        // Verify
        JobStep__c step1 = [SELECT Status__c, JobExecution__r.Status__c FROM JobStep__c WHERE Name = :'step1'];

        System.assertEquals(1, [SELECT COUNT() FROM Result__c]);

        System.assertEquals('Failed', step1.Status__c);
        System.assertEquals('Error', step1.JobExecution__r.Status__c);
    }

    @IsTest
    private static void shouldFailExecutionForInvalidFunctionName() {
        // Setup
        Helper helper = new Helper().createExecution('Not Started').addStep('step1', 'Function', 2, '{"functionName" : "Invalid Function"}');

        RunJob.Request request = new RunJob.Request();
        request.jobId = helper.execution.Id;

        Org__c org = new Org__c();
        org.Validated_Date__c = System.today();
        org.SFDC_Org_ID__c = UserInfo.getOrganizationId() + '_' + UserInfo.getUserId();
        org.Username__c = UserInfo.getUserName();
        org.Oauth_Signature__c = 'Valid';
        insert org;

        // Exercise
        Test.startTest();
        System.runAs(user()) {
            RunJob.execute(new List<RunJob.Request>{ request });
            Test.getEventBus().deliver();
        }
        Test.stopTest();
        Test.getEventBus().deliver();

        // Verify
        String errorMessage = Label.Function_not_Found + ': Invalid Function';
        List<Result__c> results = [SELECT Error_Message__c FROM Result__c];

        System.assertEquals(1, results.size());
        System.assertEquals('Error', [SELECT Status__c FROM JobExecution__c].Status__c);
        System.assert(results[0].Error_Message__c.contains(errorMessage));
    }

    @IsTest
    private static void shouldCompleteIfAllStepsSucceed() {
        // Setup
        Helper helper = new Helper()
            .createExecution('Not Started')
            .addStep('step1', 'Flow', 1, '{"flowName" : "MockedFlow"}')
            .addStep('step2', 'Function', 2, '{"functionName" : "MockedFunction"}');

        RunJob.Request request = new RunJob.Request();
        request.jobId = helper.execution.Id;
        request.allSteps = true;

        Flow.mockResponse = flowCompletionEvent(true, '', 'Success data 1');
        Function.mockResponse = functionCompletionEvent(true, '', 'Success data 2');

        // Exercise
        Test.startTest();
        System.runAs(user()) {
            RunJob.execute(new List<RunJob.Request>{ request });
            Test.getEventBus().deliver();
        }
        Test.stopTest();
        Test.getEventBus().deliver();

        // Verify
        JobStep__c step1 = [SELECT Status__c, Result__r.Result_Data__c FROM JobStep__c WHERE Name = 'step1'];
        JobStep__c step2 = [SELECT Status__c, Result__r.Result_Data__c FROM JobStep__c WHERE Name = 'step2'];

        System.assertEquals(2, [SELECT COUNT() FROM Result__c]);
        System.assertEquals('Successful', [SELECT Status__c FROM JobExecution__c].Status__c);

        System.assertEquals('Success', step1.Status__c);
        System.assertEquals('Success', step2.Status__c);

        System.assertEquals('Success data 1', step1.Result__r.Result_Data__c);
        System.assertEquals('Success data 2', step2.Result__r.Result_Data__c);
    }

    @IsTest
    private static void shouldFailIfAnyStepFails() {
        // Setup
        Helper helper = new Helper()
            .createExecution('Not Started')
            .addStep('step1', 'Flow', 1, '{"flowName" : "MockedFlow"}')
            .addStep('step2', 'Function', 2, '{"functionName" : "MockedFunction"}');

        RunJob.Request request = new RunJob.Request();
        request.jobId = helper.execution.Id;
        request.allSteps = true;

        Flow.mockResponse = flowCompletionEvent(true, '', 'Success data');
        Function.mockResponse = functionCompletionEvent(false, 'Custom error', '');

        // Exercise
        Test.startTest();
        System.runAs(user()) {
            RunJob.execute(new List<RunJob.Request>{ request });
            Test.getEventBus().deliver();
        }
        Test.stopTest();
        Test.getEventBus().deliver();

        // Verify
        JobStep__c step1 = [SELECT Status__c, Result__r.Result_Data__c FROM JobStep__c WHERE Name = 'step1'];
        JobStep__c step2 = [SELECT Status__c, Result__r.Error_Message__c FROM JobStep__c WHERE Name = 'step2'];

        System.assertEquals(2, [SELECT COUNT() FROM Result__c]);
        System.assertEquals('Error', [SELECT Status__c FROM JobExecution__c].Status__c);

        System.assertEquals('Success', step1.Status__c);
        System.assertEquals('Failed', step2.Status__c);

        System.assertEquals('Success data', step1.Result__r.Result_Data__c);
        System.assertEquals('Custom error', step2.Result__r.Error_Message__c);
    }

    @IsTest
    private static void shouldReRunFailedStepsIfAnyStepFails() {
        // Setup
        Helper helper = new Helper()
            .createExecution('Failed')
            .addStep('step1', 'Flow', 1, '{"flowName" : "MockedFlow"}')
            .addStep('step2', 'Function', 2, '{"functionName" : "MockedFunction"}')
            .addResultFor('step1', 'MockedFlow', 'Success')
            .addResultFor('step2', 'MockedFunction', 'Failed');

        RunJob.Request request = new RunJob.Request();
        request.jobId = helper.execution.Id;
        request.allSteps = false;

        Org__c org = new Org__c();
        org.Oauth_Signature__c = 'Valid';
        org.Validated_Date__c = System.today();
        org.Username__c = UserInfo.getUserName();
        org.SFDC_Org_ID__c = UserInfo.getOrganizationId() + '_' + UserInfo.getUserId();
        insert org;

        Flow.mockResponse = flowCompletionEvent(true, '', 'Success data');
        Function.mockResponse = functionCompletionEvent(true, '', 'Sample Data');

        // Exercise
        Test.startTest();
        System.runAs(user()) {
            RunJob.execute(new List<RunJob.Request>{ request });
            Test.getEventBus().deliver();
        }
        Test.stopTest();
        Test.getEventBus().deliver();

        // Verify
        JobStep__c step2 = [SELECT Result__r.Result_Data__c, Status__c, JobExecution__r.Status__c FROM JobStep__c WHERE Name = 'step2'];

        System.assertEquals(3, [SELECT COUNT() FROM Result__c]);

        System.assertEquals('Success', step2.Status__c);
        System.assertEquals('Sample Data', step2.Result__r.Result_Data__c);
        System.assertEquals('Successful', step2.JobExecution__r.Status__c);
    }

    @IsTest
    private static void shouldReRunAllStepsIfAnyStepFails() {
        // Setup
        Helper helper = new Helper()
            .createExecution('Failed')
            .addStep('step1', 'Flow', 1, '{"flowName" : "MockedFlow"}')
            .addStep('step2', 'Function', 2, '{"functionName" : "MockedFunction"}')
            .addResultFor('step1', 'MockedFlow', 'Success')
            .addResultFor('step2', 'MockedFunction', 'Failed');

        Flow.mockResponse = flowCompletionEvent(true, '', 'Success data');
        Function.mockResponse = functionCompletionEvent(true, '', 'Sample Data');

        RunJob.Request request = new RunJob.Request();
        request.jobId = helper.execution.Id;
        request.allSteps = true;

        // Exercise
        Test.startTest();
        System.runAs(user()) {
            RunJob.execute(new List<RunJob.Request>{ request });
            Test.getEventBus().deliver();
        }
        Test.stopTest();
        Test.getEventBus().deliver();

        // Verify
        JobStep__c step2 = [SELECT Result__r.Result_Data__c, Status__c, JobExecution__r.Status__c FROM JobStep__c WHERE Name = 'step2'];

        System.assertEquals(4, [SELECT COUNT() FROM Result__c]);

        System.assertEquals('Success', step2.Status__c);
        System.assertEquals('Sample Data', step2.Result__r.Result_Data__c);
        System.assertEquals('Successful', step2.JobExecution__r.Status__c);
    }

    @IsTest
    private static void executeOutstanding() {
        // Setup
        Helper helper = new Helper()
            .createExecution('Failed')
            .addStep('step1', 'Flow', 1, '{"flowName" : "MockedFlow"}')
            .addStep('step2', 'Function', 2, '{"functionName" : "MockedFunction"}')
            .addResultFor('step1', 'MockedFlow', 'Success')
            .addResultFor('step2', 'MockedFunction', 'Failed');

        insert credential();

        Flow.mockResponse = flowCompletionEvent(true, '', 'Success data');
        Function.mockResponse = functionCompletionEvent(true, '', 'Sample Data');

        // Exercise
        Test.startTest();
        System.runAs(user()) {
            RunJobController.execute(helper.execution.Id, false);
            Test.getEventBus().deliver();
        }
        Test.stopTest();
        Test.getEventBus().deliver();

        // Verify
        JobStep__c step2 = [SELECT Result__r.Result_Data__c, Status__c, JobExecution__r.Status__c FROM JobStep__c WHERE Name = 'step2'];

        System.assertEquals(3, [SELECT COUNT() FROM Result__c]);

        System.assertEquals('Success', step2.Status__c);
        System.assertEquals('Sample Data', step2.Result__r.Result_Data__c);
        System.assertEquals('Successful', step2.JobExecution__r.Status__c);
    }

    @IsTest
    private static void restartExecution() {
        // Setup
        Helper helper = new Helper()
            .createExecution('Failed')
            .addStep('step1', 'Flow', 1, '{"flowName" : "MockedFlow"}')
            .addStep('step2', 'Function', 2, '{"functionName" : "MockedFunction"}')
            .addResultFor('step1', 'MockedFlow', 'Success')
            .addResultFor('step2', 'MockedFunction', 'Failed');

        Flow.mockResponse = flowCompletionEvent(true, '', 'Success data');
        Function.mockResponse = functionCompletionEvent(true, '', 'Sample Data');

        // Exercise
        Test.startTest();
        System.runAs(user()) {
            RunJobController.execute(helper.execution.Id, true);
            Test.getEventBus().deliver();
        }
        Test.stopTest();
        Test.getEventBus().deliver();

        // Verify
        JobStep__c step2 = [SELECT Result__r.Result_Data__c, Status__c, JobExecution__r.Status__c FROM JobStep__c WHERE Name = 'step2'];

        System.assertEquals(4, [SELECT COUNT() FROM Result__c]);

        System.assertEquals('Success', step2.Status__c);
        System.assertEquals('Sample Data', step2.Result__r.Result_Data__c);
        System.assertEquals('Successful', step2.JobExecution__r.Status__c);
    }

    @IsTest
    private static void getNextStepOutstanding() {
        // Setup
        Helper helper = new Helper()
            .createExecution('Failed')
            .addStep('step1', 'Flow', 1, '{"flowName" : "MockedFlow"}')
            .addStep('step2', 'Function', 2, '{"functionName" : "MockedFunction"}')
            .addResultFor('step1', 'MockedFlow', 'Success')
            .addResultFor('step2', 'MockedFunction', 'Failed');

        // Exercise
        JobStep__c nextStep;
        Test.startTest();
        System.runAs(user()) {
            nextStep = RunJobController.getNextStep(helper.execution.Id, false);
        }
        Test.stopTest();

        //Verify
        System.assertEquals('step2', nextStep.Name);
    }

    @IsTest
    private static void getNextStepRestartExecution() {
        // Setup
        Helper helper = new Helper()
            .createExecution('Failed')
            .addStep('step1', 'Flow', 1, '{"flowName" : "MockedFlow"}')
            .addStep('step2', 'Function', 2, '{"functionName" : "MockedFunction"}')
            .addResultFor('step1', 'MockedFlow', 'Success')
            .addResultFor('step2', 'MockedFunction', 'Failed');

        // Exercise
        JobStep__c nextStep;
        Test.startTest();
        System.runAs(user()) {
            nextStep = RunJobController.getNextStep(helper.execution.Id, true);
        }
        Test.stopTest();

        //Verify
        System.assertEquals('step1', nextStep.Name);
    }

    // HELPER

    private static Org__c credential() {
        return new Org__c(
            Oauth_Signature__c = 'Valid',
            Validated_Date__c = System.today(),
            Username__c = UserInfo.getUserName(),
            SFDC_Org_ID__c = UserInfo.getOrganizationId() + '_' + UserInfo.getUserId()
        );
    }

    private static User user() {
        return [SELECT Id, Name, LastName, Email, Username FROM User WHERE Email = 'test1@test1.com' LIMIT 1];
    }

    private class Helper {
        private JobTemplate__c template;
        private Function__c function;
        private JobExecution__c execution;
        private List<JobStep__c> steps = new List<JobStep__c>();

        private Helper createExecution(String status) {
            function = new Function__c();
            function.API_Name__c = 'MockedFunction';
            insert function;

            template = new JobTemplate__c(Name = 'Sample', Version__c = 1);
            insert template;
            execution = new JobExecution__c(Template__c = template.Id, Status__c = status);
            insert execution;

            return this;
        }

        @SuppressWarnings('PMD.ExcessiveParameterList')
        private Helper addStep(String name, String type, Integer order, String configJson) {
            JobStep__c step = new JobStep__c();
            step.Name = name;
            step.Type__c = type;
            step.Order__c = order;
            step.ConfigJson__c = configJson;
            step.JobExecution__c = execution.Id;
            insert step;

            steps.add(step);

            return this;
        }

        private Helper addResultFor(String stepName, String type, String status) {
            JobStep__c step = findByName(stepName);
            Result__c result = new Result__c(JobStep__c = step.Id, Job_Type__c = type, Status__c = status, Function__c = function.Id);
            insert result;

            step.Result__c = result.Id;
            update step;

            return this;
        }

        private JobStep__c findByName(String stepName) {
            JobStep__c result;

            for (JobStep__c step : steps) {
                if (step.Name == stepName) {
                    result = step;
                    break;
                }
            }

            return result;
        }
    }

    private static Event__e flowCompletionEvent(Boolean isSuccess, String errorMessage, String data) {
        Event__e result = new Event__e();
        result.Topic_Uri__c = OnJobStepComplete.STEP_ENDPOINT;
        result.Payload__c = Json.serialize(new OnJobStepComplete.EventPayload(isSuccess, errorMessage, data));

        return result;
    }

    private static MC_Result__e functionCompletionEvent(Boolean isSuccess, String errorMessage, String data) {
        MC_Result__e result = new MC_Result__e();
        result.IsFinished__c = true;
        result.Result_Data__c = data;
        result.IsSuccess__c = isSuccess;
        result.Error_Message__c = errorMessage;

        return result;
    }
}