Dummy_Package_for_scratch_org/main/default/objects/ExtensionPackageConfiguration__mdt/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Multi cloud platform type. Ex: Salesforce, Heroku, SAP</inlineHelpText>
    <label>Platform</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/UISection__mdt/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/UISection__mdt/fields/Extension_Package_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Extension_Package_Configuration__c</fullName>
    <label>Extension Package Configuration</label>
    <referenceTo>ExtensionPackageConfiguration__mdt</referenceTo>
    <relationshipLabel>UISections</relationshipLabel>
    <relationshipName>UISections</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/UISection__mdt/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/UISectionHelper.cls
public with sharing class UISectionHelper {
    @AuraEnabled
    public static UISection__mdt fetchUISection(String platform, String uiSectionId) {
        try {
            UISection__mdt uiSection = [
                SELECT Component__c, Location__c, NamespacePrefix
                FROM UISection__mdt
                WHERE Extension_Package_Configuration__r.Platform__c = :platform AND Location__c = :uiSectionId
            ];//NOPMD
            return uiSection;
        } catch (Exception e) {
            throw new AuraHandledException(String.format(Label.UISectionNotFound, new List<Object>{ platform, uiSectionId, e.getMessage() }));
        }
    }
}