Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Api Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/ConfigJson__c.field-meta.xml
<CustomField>
    <fullName>ConfigJson__c</fullName>
    <label>ConfigJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobTemplate__c.field-meta.xml
<CustomField>
    <fullName>JobTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Custom&apos;</defaultValue>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/CustomJobStepControllerTest.cls
@isTest
private with sharing class CustomJobStepControllerTest {
    static {
        User user = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(user) {
            assignPermissions(user.Id);
        }
    }

    @testSetup
    private static void setup() {
        insertData();
    }

    @isTest
    private static void createStep() {
        // Setup

        JobTemplate__c template = jobTemplate();

        // Exercise

        JobStep__c manualStep;
        JobStep__c functionStep;
        System.runAs(user()) {
            Test.startTest();
            manualStep = CustomJobStepController.getStep(CustomJobStepController.saveStep(manualStep(template.Id)));
            functionStep = CustomJobStepController.getStep(CustomJobStepController.saveStep(functionStep(template.Id)));
            Test.stopTest();
        }

        // Verify

        System.assertEquals(1, manualStep.Order__c, 'Incorrect order assigned to manual step.');
        System.assertEquals(2, functionStep.Order__c, 'Incorrect order assigned to function step.');
    }

    @isTest
    private static void getStepOptions() {
        //Exercise

        List<CustomJobStepController.StepOption> options;
        System.runAs(user()) {
            Test.startTest();
            options = CustomJobStepController.getStepOptions();
            Test.stopTest();
        }

        // Verify

        System.assert(!options.isEmpty(), 'No step options were returned by the controller.');
    }

    @isTest
    private static void getNamespace() {
        //Exercise

        String namespace;
        System.runAs(user()) {
            Test.startTest();
            namespace = CustomJobStepController.getNamespace();
            Test.stopTest();
        }

        // Verify

        System.assertEquals(Settings.ns, namespace, 'Incorrect namespace was returned by the controller.');
    }

    // HELPER

    private static JobTemplate__c jobTemplate() {
        return [SELECT Id FROM JobTemplate__c WHERE ApiName__c = 'Copado Promote_1' LIMIT 1];
    }

    private static JobStep__c manualStep(Id parentId) {
        return new JobStep__c(
            Name = 'Manual Approval',
            Type__c = 'Manual',
            JobTemplate__c = parentId,
            ConfigJSON__c = '{"instructions":"approval","parameters":[{"name":"ownerId","value":"0052o000008q0USAAY"},{"name":"notificationType","value":"Email_Chatter"}]}'
        );
    }

    private static JobStep__c functionStep(Id parentId) {
        return new JobStep__c(
            Name = 'Echo Promote',
            Type__c = 'Function',
            JobTemplate__c = parentId,
            ConfigJSON__c = '{"functionName":"echoClone","parameters":[{"name":"my_name","value":"rafael"},{"name":"email","value":"{$User.Email}"},{"name":"sessionId","value":"{$RecordId.Credential.SessionId}"}]}'
        );
    }

    private static User user() {
        return [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
    }

    private static void assignPermissions(Id userId) {
        List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();

        for (PermissionSet permissionSet : [
            SELECT Id
            FROM PermissionSet
            WHERE
                Name IN ('Copado_User', 'Copado_Functions', 'Copado_Job_Engine')
                AND Id NOT IN (SELECT PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId = :userId)
        ]) {
            assignments.add(new PermissionSetAssignment(AssigneeId = userId, PermissionSetId = permissionSet.Id));
        }

        insert assignments;
    }

    private static void insertData() {
        JobTemplate__c template = new JobTemplate__c(Name = 'Copado Promote', Version__c = 1, Type__c = 'Custom');
        insert template;
    }
}