Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobTemplate__c.field-meta.xml
<CustomField>
    <fullName>JobTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Custom&apos;</defaultValue>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Settings__c/fields/Enable_Standard_Job_Template_Edit__c.field-meta.xml
<CustomField>
    <fullName>Enable_Standard_Job_Template_Edit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Standard Job Template  Edit</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/RestrictStandardStepModification.cls
public with sharing class RestrictStandardStepModification {

    private List<JobStep__c> steps;

    // CONSTRUCTOR

    public RestrictStandardStepModification(List<JobStep__c> steps) {
        this.steps = steps;
    }


    // PUBLIC

    public void execute() {
        if(!isStandardEditAllowed()) {
            Map<Id, JobTemplate__c> templatesById = templatesById();

            for(JobStep__c step : steps) {
                if(isStandard(templatesById,step)) {
                    step.addError(Label.StandardTemplateModificationNotAllowed);
                }
            }
        }
    }


    // PRIVATE

    private Boolean isStandard(Map<Id, JobTemplate__c> templatesById, JobStep__c step) {
        return (
            templatesById.containsKey(step.JobTemplate__c) &&
            templatesById.get(step.JobTemplate__c).Type__c == 'Standard'
        );
    }


    private Map<Id, JobTemplate__c> templatesById() {
        Set<Id> templateIds = templateIds();

        return new Map<Id, JobTemplate__c>([SELECT Id, Name, Type__c FROM JobTemplate__c WHERE Id IN :templateIds]);
    }


    private Set<Id> templateIds() {
        Set<Id> result = new Set<Id>();

        for(JobStep__c step : steps) {
            if(step.JobTemplate__c != null) {
                result.add(step.JobTemplate__c);
            }
        }

        return result;
    }


    private Boolean isStandardEditAllowed() {
        Settings__c setting = Settings__c.getOrgDefaults();

        return Boolean.valueOf(setting.Enable_Standard_Job_Template_Edit__c);
    }
}