Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Api Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobTemplate__c.field-meta.xml
<CustomField>
    <fullName>JobTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Custom&apos;</defaultValue>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/VolumeOptions__c.field-meta.xml
<CustomField>
    <fullName>VolumeOptions__c</fullName>
    <inlineHelpText>A JSON containing transaction and volume options</inlineHelpText>
    <label>VolumeOptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/JobTemplatesSelector.cls
public with sharing class JobTemplatesSelector extends fflib_SObjectSelector {

    public SObjectType getSObjectType() {
        return JobTemplate__c.sObjectType;
    }


    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{
            JobTemplate__c.Id,
            JobTemplate__c.Name,
            JobTemplate__c.Type__c,
            JobTemplate__c.ApiName__c,
            JobTemplate__c.VolumeOptions__c
        };
    }


    public List<JobTemplate__c> byId(Set<Id> recordIds) {
        return (List<JobTemplate__c>) selectSObjectsById(recordIds);
    }


    public List<JobTemplate__c> byName(String name) {
        return byName(new Set<String> { name });
    }


    public List<JobTemplate__c> byName(Set<String> names) {
        fflib_QueryFactory query = newQueryFactory().setCondition(JobTemplate__c.ApiName__c + ' IN :names');

        String stepRelationship = Settings.ns + 'JobSteps__r';
        query.subselectQuery(stepRelationship)
                .selectFields(new JobStepsSelector().getSObjectFieldList()).setOrdering('Order__c', fflib_QueryFactory.SortOrder.ASCENDING);

        return (List<JobTemplate__c>) Database.query(query.toSOQL());
    }
}