Dummy_Package_for_scratch_org/main/default/objects/Copado_Setting__mdt/fields/Text_Field__c.field-meta.xml
<CustomField>
    <fullName>Text_Field__c</fullName>
    <label>Text Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/IsFinished__c.field-meta.xml
<CustomField>
    <fullName>IsFinished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Finished</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Success</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/ResultId__c.field-meta.xml
<CustomField>
    <fullName>ResultId__c</fullName>
    <label>Result Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copado Function that triggered this result.</inlineHelpText>
    <label>Function</label>
    <referenceTo>Function__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/FunctionResultMonitor.cls
public with sharing class FunctionResultMonitor implements Database.Batchable<sObject>, Schedulable {
    private final Datetime now;
    private final Decimal timeout;

    // CTOR

    public FunctionResultMonitor() {
        now = Datetime.now();
        timeout = Test.isRunningTest() ? -1 : timeout();
    }

    // PUBLIC

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query());
    }

    public void execute(Database.BatchableContext BC, List<Result__c> results) {
        List<MC_Result__e> events = new List<MC_Result__e>();
        for (Result__c result : results) {
            if (timedOut(result)) {
                events.add(event(result));
            }
        }
        if (!events.isEmpty()) {
            EventBus.publish(events);
        }
    }

    public void finish(Database.BatchableContext BC) {
    }

    public void execute(SchedulableContext SC) {
        Database.executeBatch(new FunctionResultMonitor(), 1000);
    }

    public static void start() {
        // Schedule to run every 5 minutes
        for (Integer i = 0; i < 60; i += 5) {
            String minute = (i < 10 ? '0' : '') + i;
            String cronExpression = '0 ' + minute + ' * * * ?';
            System.schedule('FunctionResultMonitor ' + minute, cronExpression, new FunctionResultMonitor());
        }
    }

    // PRIVATE

    private String query() {
        return 'SELECT LastModifiedDate, Status__c, Progress_Status__c FROM Result__c WHERE Function__c != null AND Status__c = \'In Progress\' WITH SECURITY_ENFORCED';
    }

    @TestVisible
    private Decimal timeout() {
        Decimal result = 330; // default timeout in seconds

        try {
            String defaultTimeout = defaultTimeout();
            if (String.isNotBlank(defaultTimeout)) {
                result = Decimal.valueOf(defaultTimeout);
            }
        } catch (Exception ex) {
            // no action required. If query fails, return default timeout.
        }

        return result;
    }

    private String defaultTimeout() {
        return [SELECT Text_Field__c FROM Copado_Setting__mdt WHERE DeveloperName = 'Functions_backend_communication_timeout' WITH SECURITY_ENFORCED]
        ?.Text_Field__c;
    }

    private Boolean timedOut(Result__c result) {
        return secondsElapsed(result.LastModifiedDate) > timeout;
    }

    private Long secondsElapsed(Datetime lastModifiedDate) {
        Long milliseconds = now.getTime() - lastModifiedDate.getTime();
        Long seconds = milliseconds / 1000;
        return seconds;
    }

    private MC_Result__e event(Result__c result) {
        return new MC_Result__e(
            ResultId__c = result.Id,
            isFinished__c = true,
            isSuccess__c = false,
            Error_Message__c = String.format(Label.Function_Execution_Timed_Out, new List<String>{ String.valueOf(timeout) })
        );
    }
}