Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production/Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Scratch Org</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Image_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Name__c</fullName>
    <description>The docker image name provided by Copado. You will find available image paths in the Copado documentation. An image name is made up of slash-separated name components, prefixed by a registry hostname.</description>
    <inlineHelpText>The docker image name provided by Copado. You will find available image paths in the Copado documentation. An image name is made up of slash-separated name components, prefixed by a registry hostname.</inlineHelpText>
    <label>Image Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <inlineHelpText>This is used to validate if all required parameters are set before calling the execution.</inlineHelpText>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Script</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>The number of minutes after which the function will automatically end if there is no response from the function backend execution.</description>
    <inlineHelpText>The number of minutes after which the function will automatically end if there is no response from the function backend execution.</inlineHelpText>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Custom&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Worker_Size__c.field-meta.xml
<CustomField>
    <fullName>Worker_Size__c</fullName>
    <label>Worker Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <default>true</default>
                <label>S</label>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copado Function that triggered this result.</inlineHelpText>
    <label>Function</label>
    <referenceTo>Function__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MetaData</fullName>
                <default>true</default>
                <label>MetaData</label>
            </value>
            <value>
                <fullName>Full Profiles</fullName>
            </value>
            <value>
                <fullName>Full Permission Sets</fullName>
            </value>
            <value>
                <fullName>Users</fullName>
            </value>
            <value>
                <fullName>Translations</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Bulk Data</fullName>
            </value>
            <value>
                <fullName>Data Template</fullName>
            </value>
            <value>
                <fullName>Delete MetaData</fullName>
            </value>
            <value>
                <fullName>Custom Settings</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Git MetaData</fullName>
            </value>
            <value>
                <fullName>URL Callout</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/System_Property__c.object-meta.xml
<CustomObject>
    <label>System Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>System Properties</relationshipLabel>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/RunCopadoFunctionTest.cls
@IsTest
private class RunCopadoFunctionTest {
    static {
        User user = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(user) {
            assignPermissions(user.Id);
        }
    }

    @TestSetup
    private static void makeData() {
        TestUtilities.assignLicense(UserInfo.getUserName(), true, true, true, true, true);
        insertTestData();
    }

    @IsTest
    private static void execute() {
        // Setup

        setMockHttpResponse();

        User user = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(user) {
            FeatureManagement.setPackageIntegerValue('Functions', 1);
        }
        
        // Exercise

        Test.startTest();
        RunCopadoFunction.InvocableVariables variables = new RunCopadoFunction.InvocableVariables();
        variables.functionApiName = 'muleDeploy';
        variables.contextId = [SELECT Id FROM Deployment_Job__c LIMIT 1]?.Id;
        variables.parameters = (List<Parameter>) JSON.deserialize(
            [SELECT Parameters__c FROM Function__c LIMIT 1]
            ?.Parameters__c,
            List<Parameter>.class
        );
        variables.optionsJSON = '[{ "name": "volumeSize", "value": "5" }, { "name": "volumeTTL", "value": "3600" }, { "name": "transactionId", "value": "a1f2o00000GOw2OAAT" }]';

        RunCopadoFunction.execute(new List<RunCopadoFunction.InvocableVariables>{ variables });
        Test.stopTest();

        // Verify

        List<Result__c> results = [SELECT Id FROM Result__c WHERE Job_Type__c = 'muleDeploy' LIMIT 1];
        System.assert(!results.isEmpty(), 'Result was not created before executing the function.');
    }

    @IsTest
    private static void executeWithError() {
        // Setup

        setMockHttpResponse();

        User user = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(user) {
            FeatureManagement.setPackageIntegerValue('Functions', 1);
        }
        
        // Exercise

        Test.startTest();
        RunCopadoFunction.InvocableVariables variables = new RunCopadoFunction.InvocableVariables();
        variables.functionApiName = 'unknown';
        variables.contextId = [SELECT Id FROM Deployment_Job__c LIMIT 1]?.Id;
        variables.showValidationErrors = true;

        Exception result;

        try {
            System.runAs(user) {
            RunCopadoFunction.execute(new List<RunCopadoFunction.InvocableVariables>{ variables });
            }
        } catch (Exception ex) {
            result = ex;
        }

        Test.stopTest();

        // Verify
        System.assert(result.getMessage().contains(Label.Function_not_Found), 'The error should come from a non-existing function in the system.');
    }

    @IsTest
    private static void executeWithoutFeatureLicense() {
        // Setup
        Exception expectedException = null;
        setMockHttpResponse();

        User user = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(user) {
            FeatureManagement.setPackageIntegerValue('Functions', 0);
        }

        // Exercise
        Test.startTest();
        RunCopadoFunction.InvocableVariables variables = new RunCopadoFunction.InvocableVariables();
        variables.functionApiName = 'muleDeploy';
        variables.contextId = [SELECT Id FROM Deployment_Job__c LIMIT 1]?.Id;
        variables.showValidationErrors = true;

        try {
            
            System.runAs(user) {
            RunCopadoFunction.execute(new List<RunCopadoFunction.InvocableVariables>{ variables });
            }
        } catch (CopadoFunctionException ex) {
            expectedException = ex;
        }


        Test.stopTest();


        // Verify
        System.assertNotEquals(null, expectedException);
        System.assert(expectedException.getMessage().contains(expectedException.getMessage()));
    }

    @IsTest
    private static void payloadWithOptions() {
        // Setup

        Function__c function = function();
        String volumeOptions = '[{ "name": "volumeSize", "value": "5" }, { "name": "volumeTTL", "value": "3600" }, { "name": "transactionId", "value": "a1f2o00000GOw2OAAT" }]';

        // Exercise

        Test.startTest();
        FunctionPayload payload = new FunctionPayload(function)
            .parameters((List<Parameter>) JSON.deserialize(function.Parameters__c, List<Parameter>.class))
            .options((List<Parameter>) JSON.deserialize(volumeOptions, List<Parameter>.class));
        Test.stopTest();

        // Verify

        String result = payload.toJson();
        System.assert(result.contains('branchName'), 'branchName parameter was not added to the payload options.');
        System.assert(result.contains('transactionId'), 'transactionId parameter was not added to the payload options.');
        System.assert(result.contains('volumeSize'), 'volumeSize parameter was not added to the payload options.');
        System.assert(result.contains('volumeTTL'), 'volumeTTL parameter was not added to the payload options.');
    }

    // Helpers

    private static void assignPermissions(Id userId) {
        List<PermissionSet> permissionSets = [
            SELECT Id
            FROM PermissionSet
            WHERE
                Name IN ('Copado_User', 'Copado_Functions', 'Copado_Job_Engine')
                AND Id NOT IN (SELECT PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId = :userId)
        ];
        List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();
        for (PermissionSet permissionSet : permissionSets) {
            assignments.add(new PermissionSetAssignment(AssigneeId = userId, PermissionSetId = permissionSet.Id));
        }
        insert assignments;
    }

    private static Function__c function() {
        return [
            SELECT API_Name__c, Script__c, Image_Name__c, Parameters__c, Options__c, Worker_Size__c
            FROM Function__c
            WHERE API_Name__c = 'muleDeploy'
            LIMIT 1
        ];
    }

    private static void insertTestData() {
        insert new Personal_Settings__c(SetupOwnerId = UserInfo.getUserId(), API_Key__c = DeployAPI.encryptAPIKey('000111222333'));

        Function__c function = new Function__c(
            Name = 'muleDeploy',
            API_Name__c = 'muleDeploy',
            Script__c = 'echo hello world $par1',
            Type__c = 'Custom',
            Parameters__c = '[{"name": "SourceDBName", "defaultValue": "{$Source.Property.DBName}", "required": true},' +
                '{"name": "DestinationDBProvider", "defaultValue": "{$Destination.Property.DB-Provider}", "required": true},' +
                '{"name": "PipelineUsername", "defaultValue": "{$Pipeline.Property.Username}", "required": true},' +
                '{"name": "UserEmail", "defaultValue": "{$User.Property.Email}", "required": true},' +
                '{"name": "LogLevel", "defaultValue": "ERROR", "required": false}]',
            Options__c = '[{"name": "gitUrl", "value": "xxxxxx", "sensitive": true},' +
                '{"name": "gitUsername", "value": "", "sensitive": true},' +
                '{"name": "gitPassword", "value": "", "sensitive": true},' +
                '{"name": "branchName", "value": "", "sensitive": false}]',
            Image_Name__c = 'copadoCore',
            Timeout__c = 5
        );
        insert function;

        List<Environment__c> environments = new List<Environment__c>();
        Environment__c dev1Environment = CMTestMethodUtilities.createEnvironment('DEV-1', '000000000000000001');
        environments.add(dev1Environment);
        Environment__c intEnvironment = CMTestMethodUtilities.createEnvironment('INT', '000000000000000002');
        environments.add(intEnvironment);
        insert environments;

        List<Org__c> orgs = new List<Org__c>();
        Org__c userCredential = CMTestMethodUtilities.createOrg(
            'USER-ORG',
            'Production',
            UserInfo.getOrganizationId() +
            '_' +
            UserInfo.getUserId(),
            null,
            UserInfo.getUserName(),
            System.now(),
            null
        );
        userCredential.Oauth_Signature__c = '111222333444';
        orgs.add(userCredential);
        Org__c dev1Credential = CMTestMethodUtilities.createOrg(
            'DEV-1',
            'Production',
            '000000000000000001',
            null,
            null,
            System.now(),
            dev1Environment.Id
        );
        orgs.add(dev1Credential);
        Org__c intCredential = CMTestMethodUtilities.createOrg(
            'INT',
            'Production',
            '000000000000000002',
            null,
            null,
            System.now(),
            intEnvironment.Id
        );
        orgs.add(intCredential);
        insert orgs;

        Deployment_Flow__c pipeline = CMTestMethodUtilities.createFlow('PIPELINE');
        pipeline.Active__c = true;
        insert pipeline;

        Deployment_Flow_Step__c pipelineConnection = CMTestMethodUtilities.createFlowStep(dev1Environment.Id, intEnvironment.Id, pipeline.Id);
        insert pipelineConnection;

        Project__c project = CMTestMethodUtilities.createProject('PROJECT');
        project.Deployment_Flow__c = pipeline.Id;
        insert project;

        Promotion__c promotion = CMTestMethodUtilities.createPromotion(project.Id, dev1Environment.Id);
        promotion.Source_Org_Credential__c = dev1Credential.Id;
        insert promotion;

        Deployment__c deployment = testMethodUtilities.create('DEPLOYMENT', Datetime.now(), Datetime.now(), dev1Credential.Id, null, 'In progress');
        deployment.Promotion__c = promotion.Id;
        insert deployment;

        Step__c step = testMethodUtilities.create(
            'STEP',
            null,
            '{"functionId":"' +
            function.Id +
            '","functionAPIName":"' +
            function.API_Name__c +
            '","functionParameters":' +
            '[{"name": "SourceDBName", "value": "dbname"},' +
            '{"name": "DestinationDBProvider", "value": "provider"},' +
            '{"name": "PipelineUsername", "value": "username"},' +
            '{"name": "UserEmail", "value": "email"},' +
            '{"name": "LogLevel", "value": "ERROR"}]}',
            deployment.Id,
            0,
            'In progress',
            'Function'
        );
        insert step;

        Destination_Org__c destination = testMethodUtilities.create(deployment.Id, 'In progress', intCredential.Id);
        insert destination;

        Deployment_Job__c job = testMethodUtilities.create(1, destination.Id, null, 'In progress', step.Id);
        insert job;

        List<System_Property__c> properties = new List<System_Property__c>();
        System_Property__c sourceProperty = new System_Property__c(
            API_Name__c = 'DBName',
            Value__c = 'OracleDB',
            Environment__c = dev1Environment.Id
        );
        properties.add(sourceProperty);
        System_Property__c destinationProperty = new System_Property__c(
            API_Name__c = 'DB-Provider',
            Value__c = 'Oracle',
            Environment__c = intEnvironment.Id
        );
        properties.add(destinationProperty);
        System_Property__c pipelineProperty = new System_Property__c(
            API_Name__c = 'Username',
            Value__c = 'user@oracledb.com',
            Pipeline__c = pipeline.Id
        );
        properties.add(pipelineProperty);
        System_Property__c userProperty = new System_Property__c(
            API_Name__c = 'Email',
            Value__c = 'user@example.com',
            User__c = UserInfo.getUserId()
        );
        properties.add(userProperty);
        insert properties;
    }

    private static void setMockHttpResponse() {
        MockHttpResponseGenerator mockResponse = new MockHttpResponseGenerator(
            200,
            'Complete',
            '{"id": "123123123", "status": "pending", "messages": ["function received and Queued", "executin will start shortly"]}',
            null
        );
        Test.setMock(HttpCalloutMock.class, mockResponse);
    }
}