Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/System_Property__c.object-meta.xml
<CustomObject>
    <label>System Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>System Properties</relationshipLabel>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>This value is automatically populated when selecting a Pipeline, Environment or User. If none is selected, the record Id this property is linked to must be entered manually.</description>
    <inlineHelpText>This value is automatically populated when selecting a Pipeline, Environment or User. If none is selected, the record Id this property is linked to must be entered manually.</inlineHelpText>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>System Properties</relationshipLabel>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/SetPropertyParents.cls
public with sharing class SetPropertyParents {
    private List<System_Property__c> records;
    private Map<Id, System_Property__c> old;

    // CONSTRUCTOR

    public SetPropertyParents(List<System_Property__c> records) {
        this.records = records;
    }

    public SetPropertyParents(List<System_Property__c> records, Map<Id, System_Property__c> old) {
        this(records);
        this.old = old;
    }

    // PUBLIC

    public void execute() {
        for (System_Property__c property : records) {
            updateParentLookups(property);
            if (String.isBlank(property.ParentId__c)) {
                property.addError(Label.ParentIdRequired);
            }
        }
    }

    // PRIVATE

    private void updateParentLookups(System_Property__c property) {
        property.ParentId__c = parentId(property);
        if (property.ParentId__c != property.User__c) {
            property.User__c = null;
        }
        if (property.ParentId__c != property.Environment__c) {
            property.Environment__c = null;
        }
        if (property.ParentId__c != property.Pipeline__c) {
            property.Pipeline__c = null;
        }
    }

    private Id parentId(System_Property__c property) {
        Id parentId;
        Boolean setFromLookup = false;
        System_Property__c oldRecord;
        if (Trigger.isInsert) {
            setFromLookup = property.User__c != null || property.Environment__c != null || property.Pipeline__c != null;
        } else if (Trigger.isUpdate) {
            oldRecord = old.get(property.Id);
            setFromLookup =
                property.User__c != oldRecord.User__c ||
                property.Environment__c != oldRecord.Environment__c ||
                property.Pipeline__c != oldRecord.Pipeline__c ||
                property.ParentId__c != oldRecord.ParentId__c;
        }
        if (setFromLookup) {
            parentId = fromLookup(property, oldRecord);
        } else {
            parentId = property.ParentId__c;
        }
        return parentId;
    }

    private Id fromLookup(System_Property__c property, System_Property__c oldRecord) {
        return new Map<Boolean, Id>{
                property.User__c != oldRecord?.User__c && String.isNotBlank(property.User__c) => property.User__c,
                property.Environment__c != oldRecord?.Environment__c && String.isNotBlank(property.Environment__c) => property.Environment__c,
                property.Pipeline__c != oldRecord?.Pipeline__c && String.isNotBlank(property.Pipeline__c) => property.Pipeline__c,
                property.ParentId__c != oldRecord?.ParentId__c && String.isNotBlank(property.ParentId__c) => property.ParentId__c
            }
            .get(true);
    }
}