Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Org ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&quot;Salesforce&quot;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production/Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Scratch Org</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Metadata_Types__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Types__c</fullName>
    <inlineHelpText>Empty means all types. Select one or more types to limit the backup only to selected items.</inlineHelpText>
    <label>Metadata Types</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Org_Type__c.field-meta.xml
<CustomField>
    <fullName>Org_Type__c</fullName>
    <label>Org Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production/Developer</fullName>
                <default>true</default>
                <label>Production/Developer</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Scratch Org - Test only</fullName>
            </value>
            <value>
                <fullName>Scratch Org</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <formula>TEXT(Environment__r.Platform__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Platform</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/SFDC_Org_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Org_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Organization Id for the Environment.</description>
    <externalId>true</externalId>
    <inlineHelpText>Organization Id for the Environment.</inlineHelpText>
    <label>SFDC Org ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Test_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Test_Frequency__c</fullName>
    <description>Continuous Integration feature. Run all Apex Test methods and save the results in the Apex Test Result object to create email alerts or reports. This feature is very powerful along with Git Backups to detect recent failing changes automatically.</description>
    <inlineHelpText>Continuous Integration feature. Run all Apex Test methods and save the results in the Apex Test Result object to create email alerts or reports. This feature is very powerful along with Git Backups to detect recent failing changes automatically.</inlineHelpText>
    <label>Test Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Validated_Date__c.field-meta.xml
<CustomField>
    <fullName>Validated_Date__c</fullName>
    <description>Latest OAuth authentication validation date.</description>
    <inlineHelpText>Latest OAuth authentication validation date.</inlineHelpText>
    <label>Validated Date</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/OrgTriggerHelper.cls
public without sharing class OrgTriggerHelper {
    private static Boolean sched = false;
    private static String[] idsToRemoveAttach = new List<String>{};
    private static Map<String, Environment__c> environmentsBySFDCOrgIds;
    public static List<Environment__c> environments;

    public static void prepareData(List<SObject> records) {
        environments = new List<Environment__c>();
        environmentsBySFDCOrgIds = new Map<String, Environment__c>();
        Set<String> orgIds = new Set<String>();

        for (SObject so : records) {
            Org__c credentialRecord = (Org__c) so;
            String sfdcOrgId = extractOrgId((String) credentialRecord.SFDC_Org_ID__c);
            Boolean isSalesforceCredential = credentialRecord.Platform__c == null || credentialRecord.Platform__c == 'Salesforce';
            if (isSalesforceCredential && sfdcOrgId != null) {
                orgIds.add(sfdcOrgId);
            }
        }
        if (!orgIds.isEmpty()) {
            populateEnvionmentMap(orgIds);

            for (SObject so : records) {
                Org__c neworg = (Org__c) so;
                String sfdcorgId = extractOrgId((String) neworg.SFDC_Org_ID__c);
                Environment__c newEnvironment = environmentsBySFDCOrgIds.get(sfdcorgId);
                if (!environmentsBySFDCOrgIds.containsKey(sfdcorgId)) {
                    newEnvironment = new Environment__c();
                    newEnvironment.Name = neworg.Name;
                    newEnvironment.Type__c = neworg.Org_Type__c;
                    newEnvironment.Org_ID__c = sfdcorgId;
                    newEnvironment.Platform__c = 'Salesforce';
                    environments.add(newEnvironment);
                }
            }
            upsert environments;

            populateEnvionmentMap(orgIds);
        }
    }
    private static void populateEnvionmentMap(Set<String> orgIds) {
        for (Environment__c environmentRecord : [SELECT Id, Name, Org_ID__c FROM Environment__c WHERE Org_ID__c IN :orgIds]) {
            environmentsBySFDCOrgIds.put(environmentRecord.Org_ID__c, environmentRecord);
        }
    }
    public static Boolean isScheduled(Org__c credentialRecord) {
        if (
            credentialRecord.Test_Frequency__c != null &&
            credentialRecord.Test_Frequency__c != 'None' &&
            credentialRecord.Validated_Date__c != null
        ) {
            sched = true;
            return true;
        }
        return false;
    }
    public static void checkApexTest(Org__c credentialRecord) {
        if (isScheduled(credentialRecord) && !FeatureHelper.isFeatureEnabled('Apex Test')) {
            credentialRecord.Test_Frequency__c = 'None';
        }
    }
    public static void enforceScheduler() {
        if (sched)
            BatchHelper.enforceScheduler();
    }
    public static void isMetadataChanged(Org__c credentialRecord, Org__c oldcredentialRecord) {
        if (oldcredentialRecord.Metadata_Types__c != credentialRecord.Metadata_Types__c) {
            idsToRemoveAttach.add(credentialRecord.Id);
        }
    }
    public static void deleteMetadataAttachments() {
        Utilities.Secure_DML(
            [SELECT Id FROM Attachment WHERE ParentId = :idsToRemoveAttach AND Name = 'MetaData'],
            Utilities.DML_Action.DEL,
            schema.SObjectType.Attachment
        );
    }
    public static void setOrgEnvironment(Org__c newCredentialRecord) {
        String newId = extractOrgId(newCredentialRecord.SFDC_Org_ID__c);
        Boolean isSalesforceCredential = newCredentialRecord.Platform__c == null || newCredentialRecord.Platform__c == 'Salesforce';
        if (isSalesforceCredential && newId != null && environmentsBySFDCOrgIds.containsKey(newId)) {
            newCredentialRecord.Environment__c = environmentsBySFDCOrgIds.get(newId).Id;
        }
    }
    private static String extractOrgId(String sfdxOrgId) {
        if (sfdxOrgId == null) {
            return null;
        }
        if (sfdxOrgId.length() >= 37 && sfdxOrgId.contains('_')) {
            return sfdxOrgId.split('_')[0];
        }
        if (sfdxOrgId.length() == 18 && sfdxOrgId.startsWith('00D')) {
            return sfdxOrgId;
        }
        return null;
    }
    private static Boolean isValidCopadoSFDC_Org_Id(String credentialId) {
        return String.isNotBlank(credentialId) && credentialId.length() >= 37;
    }
    private static String getBaseSFDC_Org_Id(String credentialId) {
        if (!isValidCopadoSFDC_Org_Id(credentialId)) {
            return credentialId;
        }
        return credentialId.substring(0, 37);
    }
}