Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/Promoted_User_Story__c.object-meta.xml
<CustomObject>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promoted User Stories</relationshipLabel>
    <relationshipName>Promoted_User_Stories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status Outdated invalidates that this user story got promoted. The user story will be available again for automated promotions and back promotions if applicable.</description>
    <label>Active / Outdated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Outdated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Promotions</relationshipLabel>
    <relationshipName>Promoted_User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a project linked to an active pipeline.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will provide the ability to deploy User Stories within a Release.</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed with errors</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Validation failed</fullName>
            </value>
            <value>
                <fullName>Merge Conflict</fullName>
            </value>
            <value>
                <fullName>Conflicts Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
    <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project where the User Story belongs.</description>
    <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product version or release where this User Story will be released.</description>
    <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the implementation of the User Story.</description>
    <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/JobTemplateService.cls
@SuppressWarnings('PMD')
public with sharing class JobTemplateService extends PipelineOperationsHelper implements PipelineOperationsInterface {
    private PipelineManagerExtension.PipelineOperationsServiceJobsParameters innerJobParameters;
    private List<Promotion__c> promotions;
    private Set<Id> promotionIds;

    // PUBLIC

    public PipelineManagerExtension.PipelineOperationsServiceJobsResult validation(
        PipelineManagerExtension.PipelineOperationsServiceJobsParameters jobParameters
    ) {
        result = new PipelineManagerExtension.PipelineOperationsServiceJobsResult();
        return result;
    }

    public PipelineManagerExtension.PipelineOperationsServiceJobsResult createPromotionAndPromotedUserStories(
        PipelineManagerExtension.PipelineOperationsServiceJobsParameters jobParameters
    ) {
        overlayWrapperRecord = jobParameters.overlayWrapperRecord;
        testLevelValue = jobParameters.testLevelValue;
        result = new PipelineManagerExtension.PipelineOperationsServiceJobsResult();
        insertPromotionAndRelations();
        return result;
    }

    public PipelineManagerExtension.PipelineOperationsServiceJobsResult promoteAndDeploy(
        PipelineManagerExtension.PipelineOperationsServiceJobsParameters jobParameters
    ) {
        createPromotionAndPromotedUserStories(jobParameters);
        jobParameters.promotionWrappers = result.promotionWrappers;
        try {
            return commonOperations(jobParameters, true, true);
        } catch (Exception ex) {
            throw new PipelineOperationsHelperException(ex.getMessage() + ex.getStackTraceString());
        }
    }

    public PipelineManagerExtension.PipelineOperationsServiceJobsResult deploy(
        PipelineManagerExtension.PipelineOperationsServiceJobsParameters jobParameters
    ) {
        result = new PipelineManagerExtension.PipelineOperationsServiceJobsResult();
        try {
            return commonOperations(jobParameters, false, true);
        } catch (Exception ex) {
            throw new PipelineOperationsHelperException(ex.getMessage() + ex.getStackTraceString());
        }
    }

    public PipelineManagerExtension.PipelineOperationsServiceJobsResult commonOperations(
        PipelineManagerExtension.PipelineOperationsServiceJobsParameters jobParameters,
        Boolean isPromoteAndDeploy,
        Boolean checkPromotionStatus
    ) {
        innerJobParameters = jobParameters;
        updatePromotions();
        promotions = new PromotionsSelector().onlyPromotionsDetailByIds(promotionIds);
        // Agreed with Nahuel that it will be inside for loop, since each call will be async there will be no problem
        for (Promotion__c promotionRecord : promotions) {
            request(promotionRecord.Id, true, isPromoteAndDeploy, false);
        }

        populateVariables();
        if(checkPromotionStatus) {
            checkPromotionsStatuses();
            result.enabledPromotionBackPromotionPoller = true;
        }
        return result;
    }


    // PRIVATE

    private void insertPromotionAndRelations() {
        promotionByUserStoryReleases = new Map<String, Promotion__c>();
        List<Promotion__c> promotions = new List<Promotion__c>();
        selectedUserStories = new List<User_Story__c>();

        Boolean isBackPromotion = overlayWrapperRecord.pathType.toLowerCase() == C_PULL;

        Set<Id> usIds = new Set<Id>();
        for (BranchManagementExtension.UserStoryWrapper userStoryWrapperItem : overlayWrapperRecord.userStories) {
            usIds.add(userStoryWrapperItem.userStory.Id);
        } 
        Map<Id, User_Story__c> userStoriesByIds = new UserStoriesSelector().byUserStoryIds(usIds);

        for (BranchManagementExtension.UserStoryWrapper userStoryWrapperItem : overlayWrapperRecord.userStories) {
            if (userStoryWrapperItem.isSelected) {
                selectedUserStories.add(userStoryWrapperItem.userStory);
                if (!promotionByUserStoryReleases.containsKey(userStoryWrapperItem.userStory.Release__c)) {
                    User_Story__c userStory = userStoriesByIds.get(userStoryWrapperItem.userStory.Id);
                    String projectId = String.isNotBlank(userStory.Project__c) ? userStory.Project__c : userStory.Release__r.Project__c;
                    PromoteAction.Request request = new PromoteAction.Request();
                    request.sourceEnvironmentId = isBackPromotion ? overlayWrapperRecord.toEnvId : userStory.Environment__c;
                    request.projectId = projectId;
                    request.isBackPromotion = isBackPromotion;
                    // TODO for now check promotions per project but later it will change with release
                    promotionByUserStoryReleases.put(projectId, PromoteAction.createPromotionRecord(request));
                }
            }
        }

        if (selectedUserStories.isEmpty()) {
            throw new PipelineOperationsHelperException(Label.CBM2_at_least1_us);
        }

        try {
            promotions = promotionByUserStoryReleases.values();
            if(!promotions.isEmpty()) {
                promotions =  PromoteAction.insertPromotions(promotions);
            }

            Set<Id> promotionIds = new Set<Id>();
            for (Promotion__c promotionRecord : promotions) {
                promotionByUserStoryReleases.put(promotionRecord.Project__c, promotionRecord);
                promotionIds.add(promotionRecord.Id);
            }
            
            List<Promoted_User_Story__c> promotedUserStories = new List<Promoted_User_Story__c>();
            for (User_Story__c userStoryRecord : selectedUserStories) {
                User_Story__c tempUserStoryRecord = userStoriesByIds.get(userStoryRecord.Id);
                String projectId = String.isNotBlank(tempUserStoryRecord.Project__c) ? tempUserStoryRecord.Project__c : tempUserStoryRecord.Release__r.Project__c;
                Promotion__c promotion = promotionByUserStoryReleases.get(projectId);
                promotedUserStories.add(PromoteAction.createPromotedUserStoryRecord(promotion, tempUserStoryRecord));
            }
            PromoteAction.insertPromotedUserStories(promotedUserStories);

            // Agreed with Nahuel that it will be inside for loop, since each call will be async there will be no problem
            for (Promotion__c promotionRecord : promotions) {
                request(promotionRecord.Id, false, false, false);
            }

            getPendingPromotions(promotionIds);
        } catch (Exception ex) {
            throw new PipelineOperationsHelperException(ex.getMessage() + ex.getStackTraceString());
        }
    }

    private void updatePromotions() {
        promotions = new List<Promotion__c>();
        promotionIds = new Set<Id>();
        for (PipelineManagerExtension.PromotionWrapper promotionItem : innerJobParameters.promotionWrappers) {
            if (promotionItem.isSelected && promotionItem.promotion.Status__c != COMPLETED) {
                promotionItem.promotion.Status__c = IN_PROGRESS;
                promotions.add(promotionItem.promotion);
                promotionIds.add(promotionItem.promotion.Id);
            }
        }

        PromotionTriggerHelper.bypassPromotionTrigger = true;
        SObjectAccessDecision promotionDecision = Security.stripInaccessible(AccessType.UPDATABLE, promotions);
        update promotionDecision.getRecords();
        promotions.clear();
    }

    private void populateVariables() {
        testLevelValuesByPromotionIds = new Map<String, String>();
        for (Promotion__c promotionRecord : promotions) {
            testLevelValuesByPromotionIds.put(promotionRecord.Id, '');
        }
    }

    private void request(String promotionId, Boolean executePromotion, Boolean executeDeployment, Boolean deploymentDryRun) {
        List<PromoteAction.Request> requests = new List<PromoteAction.Request>();
        PromoteAction.Request request = new PromoteAction.Request();
        request.promotionId = promotionId;
        request.executePromotion = executePromotion;
        request.executeDeployment = executeDeployment;
        request.deploymentDryRun = deploymentDryRun;
        requests.add(request);
        PromoteAction.promote(requests);
    }
}