Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/SensitiveProperty__mdt/SensitiveProperty__mdt.object-meta.xml
<CustomObject>
    <description>Stores values of a System Property of sensitive type(Name of the record maps to system property)</description>
    <label>Sensitive Property</label>
    <pluralLabel>Sensitive Properties</pluralLabel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/SensitiveProperty__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Stores encrypted version of System setting of sensitive type</description>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/System_Property__c.object-meta.xml
<CustomObject>
    <label>System Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>System Properties</relationshipLabel>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Is_Sensitive__c.field-meta.xml
<CustomField>
    <fullName>Is_Sensitive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this field is selected, the value won&apos;t be accessible to any user, and it will be securely saved. The value will remain hidden unless the field is unchecked</inlineHelpText>
    <label>Hide Value</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>This value is automatically populated when selecting a Pipeline, Environment or User. If none is selected, the record Id this property is linked to must be entered manually.</description>
    <inlineHelpText>This value is automatically populated when selecting a Pipeline, Environment or User. If none is selected, the record Id this property is linked to must be entered manually.</inlineHelpText>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>System Properties</relationshipLabel>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <description>Read-only field used internally for system property replacement.</description>
    <formula>ParentId__c + &quot;-&quot; + API_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Read-only field used internally for system property replacement.</inlineHelpText>
    <label>UID</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/SystemPropertiesSelector.cls
public with sharing class SystemPropertiesSelector extends fflib_SObjectSelector {

    private static List<System_Property__c> mock = new List<System_Property__c>();
    
    public Schema.SObjectType getSObjectType() {
        return System_Property__c.SObjectType;
    }


    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            System_Property__c.Id,
            System_Property__c.UID__c,
            System_Property__c.User__c,
            System_Property__c.Value__c,
            System_Property__c.API_Name__c,
            System_Property__c.Pipeline__c,
            System_Property__c.ParentId__c,
            System_Property__c.Is_Sensitive__c,
            System_Property__c.Environment__c
        };
    }


    public System_Property__c byUID(String uId) {
        return byUID(new Set<String> { uId }).get(uId);
    }


    public Map<String, System_Property__c> byUID(Set<String> uIds) {
        List<System_Property__c> properties = (List<System_Property__c>) Database.query( newQueryFactory()
                                                                                .setCondition(System_Property__c.UID__c + ' IN :uIds')
                                                                                .toSOQL() );

        return whithDecryptedValues(properties);
    }
    

    // PRIVATE

    private Map<String, System_Property__c> whithDecryptedValues(List<System_Property__c> properties) {
        Map<String, System_Property__c> result = new Map<String, System_Property__c>();

        Set<Id> systemPropertyIds = new Map<Id, System_Property__c>(properties).keySet();
        Map<String, SensitiveProperty__mdt> sensitivePropertyByName = groupById( new SensitivePropertySelector().byName(systemPropertyIds) );

        for(System_Property__c property : properties) {
            if(sensitivePropertyByName.containsKey(property.Id)) {
                String value = sensitivePropertyByName.get(property.Id).Value__c;
                property.Value__c = DeployAPI.decryptAPIKey(value);
            }

            result.put(property.UID__c, property);
        }

        return result;
    }


    private Map<String, SensitiveProperty__mdt> groupById(List<SensitiveProperty__mdt> sensitiveProperties) {
        Map<String, SensitiveProperty__mdt> result = new Map<String, SensitiveProperty__mdt>();

        for(SensitiveProperty__mdt sensitiveProperty : sensitiveProperties) {
            result.put(sensitiveProperty.DeveloperName, sensitiveProperty);
        }

        return result;
    }
}