Dummy_Package_for_scratch_org/main/default/objects/Data_Set__c/Data_Set__c.object-meta.xml
<CustomObject>
    <description>Stores a set of file attachments with record data from a Data Template.</description>
    <label>Data Set</label>
    <nameField>
        <label>Data Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/Deployment_Task__c.object-meta.xml
<CustomObject>
    <label>Deployment Task</label>
    <nameField>
        <label>Deployment Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/fields/dataJSON__c.field-meta.xml
<CustomField>
    <fullName>dataJSON__c</fullName>
    <description>Standard views (New, Edit, View, Clone) for Deployment Task object are overwritten. This field is being used by to controller extension class of the page that overwrites the standards.</description>
    <label>dataJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Deployment Tasks</relationshipLabel>
    <relationshipName>Deployment_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Data_Commit__c/User_Story_Data_Commit__c.object-meta.xml
<CustomObject>
    <label>User Story Data Commit</label>
    <nameField>
        <displayFormat>USDC-{0000000}</displayFormat>
        <label>User Story Data Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Data Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Data_Commit__c/fields/Data_Set__c.field-meta.xml
<CustomField>
    <fullName>Data_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Set</label>
    <referenceTo>Data_Set__c</referenceTo>
    <relationshipLabel>User Story Data Commits</relationshipLabel>
    <relationshipName>User_Story_Data_Commits</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Data_Commit__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Data Commits</relationshipLabel>
    <relationshipName>User_Story_Data_Commits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/DataCommitDeploymentTaskHandler.cls
public virtual with sharing class DataCommitDeploymentTaskHandler {
    private Map<Id, List<Deployment_Task__c>> existingDeploymentTasksByUserStory {
        get {
            if (existingDeploymentTasksByUserStory == null) {
                existingDeploymentTasksByUserStory = new DeploymentTasksSelector().byUserStory(this.dataCommitsByUserStory.keySet());
            }
            return existingDeploymentTasksByUserStory;
        }
        set;
    }

    private Map<Id, List<User_Story_Data_Commit__c>> existingDataCommitsByUserStory {
        get {
            if (existingDataCommitsByUserStory == null) {
                existingDataCommitsByUserStory = new UserStoryDataCommitsSelector().byUserStory(this.dataCommitsByUserStory.keySet());
            }
            return existingDataCommitsByUserStory;
        }
        set;
    }

    private Map<Id, Data_Set__c> dataSetsById {
        get {
            if (dataSetsById == null) {
                Set<Id> dataSetIds = new Set<Id>();
                for(Id userStoryId : this.dataCommitsByUserStory.keySet()){
                    for (User_Story_Data_Commit__c dataCommit : this.dataCommitsByUserStory.get(userStoryId)) {
                        dataSetIds.add(dataCommit.Data_Set__c);
                    }
                }
                dataSetsById = new Map<Id, Data_Set__c>(new DataSetsSelector().byId(dataSetIds));
            }
            return dataSetsById;
        }
        set;
    }

    private Map<Id, List<User_Story_Data_Commit__c>> dataCommitsByUserStory;

    public DataCommitDeploymentTaskHandler(List<User_Story_Data_Commit__c> records) {
        this.dataCommitsByUserStory = getDataCommitsByUserStory(records);
    }

    protected Map<Id, List<User_Story_Data_Commit__c>> getRecords() {
        return this.dataCommitsByUserStory;
    }

    protected List<Deployment_Task__c> getDeploymentTasks(Id userStoryId) {
        return this.existingDeploymentTasksByUserStory.containsKey(userStoryId) ? this.existingDeploymentTasksByUserStory.get(userStoryId) : new List<Deployment_Task__c>();
    }

    protected Data_Set__c getDataSet(Id dataSetId) {
        return this.dataSetsById.get(dataSetId);
    }

    protected Deployment_Task__c getDeploymentTaskForDataSet(List<Deployment_Task__c> deploymentTasks, Id dataSetId) {
        Deployment_Task__c result = null;
        for (Deployment_Task__c deploymentTask : deploymentTasks) {
            DataStepData stepData = (DataStepData) JSON.deserialize(deploymentTask.dataJSON__c, DataStepData.class);
            Id sourceDataSet = stepData.source?.id != null && stepData.source?.id instanceof Id ? stepData.source.Id : null;
            if (sourceDataSet == dataSetId) {
                result = deploymentTask;
                break;
            }
        }
        return result;
    }

    protected List<User_Story_Data_Commit__c> getRemainingDataCommits(Id userStoryId) {
        List<User_Story_Data_Commit__c> result = new List<User_Story_Data_Commit__c>(this.existingDataCommitsByUserStory.get(userStoryId));
        List<User_Story_Data_Commit__c> currentDataCommits = this.dataCommitsByUserStory.get(userStoryId);
        for (Integer i = (result.size() - 1); i >= 0; i--) {
            User_Story_Data_Commit__c dataCommit = result.get(i);
            for (User_Story_Data_Commit__c currentDataCommit : currentDataCommits) {
                if (dataCommit.Id == currentDataCommit.Id) {
                    result.remove(i);
                }
            }
        }
        return result;
    }

    protected Boolean isDataSetInAnotherDataCommit(List<User_Story_Data_Commit__c> dataCommits, Id dataSetId) {
        Boolean result = false;
        for (User_Story_Data_Commit__c dataCommit : dataCommits) {
            if (dataCommit.Data_Set__c == dataSetId) {
                result = true;
                break;
            }
        }
        return result;
    }

    private Map<Id, List<User_Story_Data_Commit__c>> getDataCommitsByUserStory(List<User_Story_Data_Commit__c> records) {
        Map<Id, List<User_Story_Data_Commit__c>> dataCommitsByUserStory = new Map<Id, List<User_Story_Data_Commit__c>>();
        for (User_Story_Data_Commit__c userStoryDataCommit : records) {
            Id userStoryId = userStoryDataCommit.User_Story__c;
            if (!dataCommitsByUserStory.containsKey(userStoryId)) {
                dataCommitsByUserStory.put(userStoryId, new List<User_Story_Data_Commit__c>());
            }
            dataCommitsByUserStory.get(userStoryId).add(userStoryDataCommit);
        }
        return dataCommitsByUserStory;
    }
}