Dummy_Package_for_scratch_org/main/default/objects/Data_Set__c/Data_Set__c.object-meta.xml
<CustomObject>
    <description>Stores a set of file attachments with record data from a Data Template.</description>
    <label>Data Set</label>
    <nameField>
        <label>Data Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Data_Set__c/fields/Data_Template__c.field-meta.xml
<CustomField>
    <fullName>Data_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Data Template record that defines related objects and their relationships for the attachments of this Data Set.</description>
    <inlineHelpText>The selected Data Template will be used as a base for object relationships, related fields and filtering.</inlineHelpText>
    <label>Data Template</label>
    <referenceTo>Data_Template__c</referenceTo>
    <relationshipLabel>Data Sets</relationshipLabel>
    <relationshipName>Data_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Data_Template__c/Data_Template__c.object-meta.xml
<CustomObject>
    <label>Data Template</label>
    <nameField>
        <label>Data Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/Deployment_Task__c.object-meta.xml
<CustomObject>
    <label>Deployment Task</label>
    <nameField>
        <label>Deployment Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/fields/dataJSON__c.field-meta.xml
<CustomField>
    <fullName>dataJSON__c</fullName>
    <description>Standard views (New, Edit, View, Clone) for Deployment Task object are overwritten. This field is being used by to controller extension class of the page that overwrites the standards.</description>
    <label>dataJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/fields/Perform_Manual_Task__c.field-meta.xml
<CustomField>
    <fullName>Perform_Manual_Task__c</fullName>
    <label>Perform Deployment Task</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Before Deployment</fullName>
                <default>true</default>
                <label>Before Deployment</label>
            </value>
            <value>
                <fullName>After Deployment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual Task</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Bulk Data</fullName>
            </value>
            <value>
                <fullName>Data Template</fullName>
            </value>
            <value>
                <fullName>Delete MetaData</fullName>
            </value>
            <value>
                <fullName>Custom Settings</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>URL Callout</fullName>
            </value>
            <value>
                <fullName>Salesforce Flow</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
                <isActive>false</isActive>
                <label>Custom Setting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Deployment Tasks</relationshipLabel>
    <relationshipName>Deployment_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production/Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Scratch Org</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/SFDC_Org_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Org_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Organization Id for the Environment.</description>
    <externalId>true</externalId>
    <inlineHelpText>Organization Id for the Environment.</inlineHelpText>
    <label>SFDC Org ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
    <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Data_Commit__c/User_Story_Data_Commit__c.object-meta.xml
<CustomObject>
    <label>User Story Data Commit</label>
    <nameField>
        <displayFormat>USDC-{0000000}</displayFormat>
        <label>User Story Data Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Data Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Data_Commit__c/fields/Data_Set__c.field-meta.xml
<CustomField>
    <fullName>Data_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Set</label>
    <referenceTo>Data_Set__c</referenceTo>
    <relationshipLabel>User Story Data Commits</relationshipLabel>
    <relationshipName>User_Story_Data_Commits</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Data_Commit__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Data Commits</relationshipLabel>
    <relationshipName>User_Story_Data_Commits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/GenerateDataCommitDeploymentTaskTest.cls
@IsTest
private with sharing class GenerateDataCommitDeploymentTaskTest {
    @TestSetup
    private static void setup() {
        User standardUser = setupUser();
        System.runAs(standardUser) {
            setupLicense();
            createTestData();
        }
    }

    @IsTest
    private static void commitDataSet() {
        User standardUser = getStandardUser();
        System.runAs(standardUser) {
            // Setup
            User_Story__c userStory = getUserStory();
            List<Data_Set__c> dataSets = getDataSets();
            Data_Set__c dataSet = dataSets[0];

            // Exercise
            Test.startTest();
            User_Story_Data_Commit__c dataCommit = createDataCommit(userStory.Id, dataSet.Id);
            insert dataCommit;
            Test.stopTest();

            // Verify
            List<Deployment_Task__c> deploymentTasks = getDeploymentTasks(userStory.Id);

            System.assertEquals(1, deploymentTasks.size(), 'Deployment Task record should be created');
            System.assertEquals('Data Template', deploymentTasks[0].Type__c, 'Task type should be Data Template');
            System.assertEquals('After Deployment', deploymentTasks[0].Perform_Manual_Task__c, 'Task should be performed after deployment');
            DataStepData stepData = (DataStepData) JSON.deserialize(deploymentTasks[0].dataJSON__c, DataStepData.class);
            Id sourceDataSet = stepData.source?.id != null && stepData.source?.id instanceof Id ? stepData.source.Id : null;
            System.assertEquals(dataSet.Id, sourceDataSet, 'Task should be linked to the Data Set in the dataJSON field');
        }
    }

    @IsTest
    private static void commitMultipleDataSets() {
        User standardUser = getStandardUser();
        System.runAs(standardUser) {
            // Setup
            User_Story__c userStory = getUserStory();
            List<Data_Set__c> dataSets = getDataSets();

            // Exercise
            Test.startTest();
            List<User_Story_Data_Commit__c> dataCommits = new List<User_Story_Data_Commit__c>();
            for (Integer i = 0; i < dataSets.size(); i++) {
                Data_Set__c dataSet = dataSets[i];
                dataCommits.add(createDataCommit(userStory.Id, dataSet.Id));
            }
            insert dataCommits;
            Test.stopTest();

            // Verify
            List<Deployment_Task__c> deploymentTasks = getDeploymentTasks(userStory.Id);

            System.assertEquals(2, deploymentTasks.size(), 'Deployment Tasks record should be created');
            for (Integer i = 0; i < deploymentTasks.size(); i++) {
                Deployment_Task__c deploymentTask = deploymentTasks[i];
                Data_Set__c dataSet = dataSets[i];
                System.assertEquals('Data Template', deploymentTask.Type__c, 'Task type should be Data Template');
                System.assertEquals('After Deployment', deploymentTask.Perform_Manual_Task__c, 'Task should be performed after deployment');
                DataStepData stepData = (DataStepData) JSON.deserialize(deploymentTask.dataJSON__c, DataStepData.class);
                Id sourceDataSet = stepData.source?.id != null && stepData.source?.id instanceof Id ? stepData.source.Id : null;
                System.assertEquals(dataSet.Id, sourceDataSet, 'Task should be linked to the Data Set in the dataJSON field');
            }
        }
    }

    @IsTest
    private static void commitSameDataSets() {
        User standardUser = getStandardUser();
        System.runAs(standardUser) {
            // Setup
            User_Story__c userStory = getUserStory();
            List<Data_Set__c> dataSets = getDataSets();
            Data_Set__c dataSet = dataSets[0];

            // Exercise
            Test.startTest();
            List<User_Story_Data_Commit__c> dataCommits = new List<User_Story_Data_Commit__c>();
            for (Integer i = 0; i < 2; i++) {
                dataCommits.add(createDataCommit(userStory.Id, dataSet.Id));
            }
            insert dataCommits;
            Test.stopTest();

            // Verify
            List<Deployment_Task__c> deploymentTasks = getDeploymentTasks(userStory.Id);

            System.assertEquals(1, deploymentTasks.size(), 'Deployment Task record should be created');
            System.assertEquals('Data Template', deploymentTasks[0].Type__c, 'Task type should be Data Template');
            System.assertEquals('After Deployment', deploymentTasks[0].Perform_Manual_Task__c, 'Task should be performed after deployment');
            DataStepData stepData = (DataStepData) JSON.deserialize(deploymentTasks[0].dataJSON__c, DataStepData.class);
            Id sourceDataSet = stepData.source?.id != null && stepData.source?.id instanceof Id ? stepData.source.Id : null;
            System.assertEquals(dataSet.Id, sourceDataSet, 'Task should be linked to the Data Set in the dataJSON field');
        }
    }

    private static User setupUser() {
        ITestDefaults userCreation = new CopadoSetupTestDefaults.UserDefaults().createRunAsUsers().executeDML();
        User standardUser = userCreation.getRunAsUsers().get('Standard')[0];
        return standardUser;
    }

    private static void setupLicense() {
        TestUtilities.enableLicenses(2, 2, 2, 2, 2, 2, 2);
        TestUtilities.assignLicense(String.valueOf(UserInfo.getUserName()), true, true, true, true, true, true);
    }

    private static User getStandardUser() {
        User standardUser = [
            SELECT Id
            FROM User
            WHERE ProfileId IN (SELECT Id FROM Profile WHERE Name = 'Standard User')
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
        return standardUser;
    }

    private static void createTestData() {
        List<Environment__c> environments = TestDataFactory.createEnvironments(1);
        List<Org__c> orgs = TestDataFactory.createOrgCredentials(1, UserInfo.getUserName(), environments);
        for (Org__c org : orgs) {
            org.SFDC_Org_ID__c = UserInfo.getOrganizationId() + '_' + UserInfo.getUserId();
        }
        update orgs;
        User_Story__c userStory = TestDataFactory.createUserStory('test', null, null, null, null, orgs[0].Id);
        insert userStory;
        Data_Template__c dataTemplate = TestDataFactory.createDataTemplate('test', orgs.get(0).Id, 'Account', null, null, null, null, null);
        List<Data_Set__c> dataSets = new List<Data_Set__c>();
        for (Integer i = 0; i < 2; i++) {
            dataSets.add(new Data_Set__c(Name = 'Data Set ' + i, Data_Template__c = dataTemplate.Id));
        }
        insert dataSets;
    }

    private static User_Story_Data_Commit__c createDataCommit(Id userStoryId, Id dataSetId) {
        User_Story_Data_Commit__c dataCommit = new User_Story_Data_Commit__c(User_Story__c = userStoryId, Data_Set__c = dataSetId);
        return dataCommit;
    }

    private static User_Story__c getUserStory() {
        return [SELECT Id, Name FROM User_Story__c LIMIT 1];
    }

    private static List<Data_Set__c> getDataSets() {
        return [SELECT Id, Data_Template__c FROM Data_Set__c];
    }

    private static List<Deployment_Task__c> getDeploymentTasks(Id userStoryId) {
        return [SELECT Id, User_Story__c, dataJSON__c, Perform_Manual_Task__c, Type__c FROM Deployment_Task__c WHERE User_Story__c = :userStoryId];
    }
}