Dummy_Package_for_scratch_org/main/default/objects/Data_Set__c/Data_Set__c.object-meta.xml
<CustomObject>
    <description>Stores a set of file attachments with record data from a Data Template.</description>
    <label>Data Set</label>
    <nameField>
        <label>Data Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/Deployment_Task__c.object-meta.xml
<CustomObject>
    <label>Deployment Task</label>
    <nameField>
        <label>Deployment Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Data_Commit__c/User_Story_Data_Commit__c.object-meta.xml
<CustomObject>
    <label>User Story Data Commit</label>
    <nameField>
        <displayFormat>USDC-{0000000}</displayFormat>
        <label>User Story Data Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Data Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Data_Commit__c/fields/Data_Set__c.field-meta.xml
<CustomField>
    <fullName>Data_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Set</label>
    <referenceTo>Data_Set__c</referenceTo>
    <relationshipLabel>User Story Data Commits</relationshipLabel>
    <relationshipName>User_Story_Data_Commits</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/DeleteDataCommitDeploymentTask.cls
public with sharing class DeleteDataCommitDeploymentTask extends DataCommitDeploymentTaskHandler {
    public DeleteDataCommitDeploymentTask(List<User_Story_Data_Commit__c> records) {
        super(records);
    }

    public void execute() {
        Set<Id> deploymentTaskIdsToDelete = new Set<Id>();
        Set<Id> dataSetIdsToDelete = new Set<Id>();

        Map<Id, List<User_Story_Data_Commit__c>> dataCommitsByUserStory = getRecords();
        for (Id userStoryId : dataCommitsByUserStory.keySet()) {
            List<User_Story_Data_Commit__c> dataCommitsToDelete = dataCommitsByUserStory.get(userStoryId);

            if (!dataCommitsToDelete.isEmpty()) {
                List<User_Story_Data_Commit__c> remainingDataCommits = getRemainingDataCommits(userStoryId);
                List<Deployment_Task__c> existingDeploymentTasks = getDeploymentTasks(userStoryId);

                for (User_Story_Data_Commit__c dataCommitToDelete : dataCommitsToDelete) {
                    Id dataSetId = dataCommitToDelete.Data_Set__c;

                    Deployment_Task__c deploymentTaskForDataSet = getDeploymentTaskForDataSet(existingDeploymentTasks, dataSetId);
                    if (deploymentTaskForDataSet != null) {
                        Boolean deleteTask = !isDataSetInAnotherDataCommit(remainingDataCommits, dataSetId);

                        if (deleteTask) {
                            deploymentTaskIdsToDelete.add(deploymentTaskForDataSet.Id);
                            dataSetIdsToDelete.add(dataSetId);
                        }
                    }
                }
            }
        }

        List<sObject> deploymentTasksToDelete = createDeletionRecords(deploymentTaskIdsToDelete);
        List<sObject> dataSetsToDelete = createDeletionRecords(dataSetIdsToDelete);

        Utilities.Secure_DML(deploymentTasksToDelete, Utilities.DML_Action.DEL, Schema.SObjectType.Deployment_Task__c);
        Utilities.Secure_DML(dataSetsToDelete, Utilities.DML_Action.DEL, Schema.SObjectType.Data_Set__c);
    }

    private List<sObject> createDeletionRecords(Set<Id> recordIds) {
        List<sObject> result = new List<sObject>();

        for (Id recordId : recordIds) {
            sObject deletionRecord = recordId.getSobjectType().newSobject(recordId);
            result.add(deletionRecord);
        }
        
        return result;
    }
}