Dummy_Package_for_scratch_org/main/default/objects/Sensitive_Information__c/Sensitive_Information__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Sensitive Information</label>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Sensitive_Information__c/fields/API_Token__c.field-meta.xml
<CustomField>
    <fullName>API_Token__c</fullName>
    <label>API Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Static_Code_Analysis_Settings__c/Static_Code_Analysis_Settings__c.object-meta.xml
<CustomObject>
    <label>Static Code Analysis Settings</label>
    <nameField>
        <label>Static Code Analysis Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Static Code Analysis Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Static_Code_Analysis_Settings__c/fields/Cloud_Organization__c.field-meta.xml
<CustomField>
    <fullName>Cloud_Organization__c</fullName>
    <description>You can get this Organization Id in CodeScan Cloud, under your profile, in the &quot;My Organizations&quot; setup menu.</description>
    <inlineHelpText>You can get this Organization Id in CodeScan Cloud, under your profile, in the &quot;My Organizations&quot; setup menu.</inlineHelpText>
    <label>Cloud Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Static_Code_Analysis_Settings__c/fields/CodeScan_Token__c.field-meta.xml
<CustomField>
    <fullName>CodeScan_Token__c</fullName>
    <label>CodeScan Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Static_Code_Analysis_Settings__c/fields/CodeScan_URL__c.field-meta.xml
<CustomField>
    <fullName>CodeScan_URL__c</fullName>
    <label>CodeScan URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Static_Code_Analysis_Settings__c/fields/CodeScan_Version__c.field-meta.xml
<CustomField>
    <fullName>CodeScan_Version__c</fullName>
    <inlineHelpText>Cloud version requires a CodeScan Cloud license.
On-premise SonarQube requires your SonarQube instance to be accesible through internet.</inlineHelpText>
    <label>CodeScan Version</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>On-premise SonarQube</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/GetStaticCodeAnalysis.cls
public with sharing class GetStaticCodeAnalysis {
    public GetStaticCodeAnalysis() {

    }
    @AuraEnabled(cacheable=true)
    public static Static_Code_Analysis_Settings__c getStaticCodeAnalysisSettingById(Id recordId){
        Static_Code_Analysis_Settings__c staticCodeAnalysisSettings;
        try {
            List<Static_Code_Analysis_Settings__c> scaSettingsList = [
                SELECT RecordTypeId, Id, Name, Cloud_Organization__c, CodeScan_Token__c, CodeScan_URL__c, CodeScan_Version__c
                FROM Static_Code_Analysis_Settings__c
                WHERE Id = :recordId
                LIMIT 1
        ];
        if(!scaSettingsList.isEmpty()) {
            staticCodeAnalysisSettings = scaSettingsList[0];
            List<Sensitive_Information__c> sensitiveInformations = [SELECT API_Token__c FROM Sensitive_Information__c WHERE Name = :recordId];
            if(!sensitiveInformations.isEmpty()) {
                staticCodeAnalysisSettings.CodeScan_Token__c = sensitiveInformations[0].API_Token__c;
            }
        }
        return staticCodeAnalysisSettings;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static void updateStaticCodeAnalysisSetting(Static_Code_Analysis_Settings__c scaSettings){
        String TOKENMASK = '**************************';
        String sensitiveToken = scaSettings.CodeScan_Token__c;
        scaSettings.CodeScan_Token__c = TOKENMASK;
        Utilities.Secure_DML(scaSettings, Utilities.DML_Action.UPS, schema.SObjectType.Static_Code_Analysis_Settings__c);
        List<Sensitive_Information__c> sensitiveInformations = [SELECT API_Token__c FROM Sensitive_Information__c WHERE Name = :scaSettings.Id];
            if(sensitiveInformations.isEmpty()) {
                Sensitive_Information__c si = new Sensitive_Information__c(
                        Name = String.valueOf(scaSettings.Id),
                        API_Token__c = sensitiveToken);
                Utilities.Secure_DML(si, Utilities.DML_Action.INS, schema.SObjectType.Sensitive_Information__c);
            } else {
                sensitiveInformations[0].API_Token__c = sensitiveToken;
                Utilities.Secure_DML(sensitiveInformations, Utilities.DML_Action.UPD, schema.SObjectType.Sensitive_Information__c);
            }
    }

}