Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User story that originated the result.</description>
    <inlineHelpText>User story that originated the result.</inlineHelpText>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Result</relationshipLabel>
    <relationshipName>Result</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Test Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <formula>IMAGE(&quot;/img/samples/color_green.gif&quot;, &quot;Completed&quot;, 15, (Progress__c*100) * 2) &amp;
IMAGE(&quot;/img/samples/color_yellow.gif&quot;, &quot;white&quot;, 15,
200 - ((Progress__c*100)* 2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Progress Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/DefinitionOfDoneCtrl1.cls
public with sharing class DefinitionOfDoneCtrl1 {
    //PUBLIC
    @AuraEnabled(cacheable=true)
    public static List<Test> getTests(Id recordId) {
        List<Test> result = new List<Test>();
        List<Test__c> tests = new TestsSelector().byUserStoryId(new Set<Id>{ recordId });
        Map<Id, String> testStatusById = getTestStatusById(new Map<Id, Test__c>(tests).keyset());
        for (Test__c test : tests) {
            result.add(new Test(test, testStatusById.get(test.Id)));
        }
        
        return result;
    }

    //PRIVATE
    private static Map<Id, String> getTestStatusById(Set<Id> testIds) {
        Map<Id, String> result = new Map<Id, String>();
        List<AggregateResult> testResult = [
            SELECT Test__c, Max(LastModifiedDate), Progress_Status__c
            FROM Result__c 
            WHERE Test__c IN :testIds WITH SECURITY_ENFORCED
            GROUP BY Test__c, Progress_Status__c 
        ];
        for (AggregateResult agr : testResult) {
            Id testId = (Id) agr.get('Test__c');
            String status = (String) agr.get('Progress_Status__c');
            if (!result.containsKey(testId)) {
                result.put(testId, status);
            }
        }

        return result;
    }
    public with sharing class Test {
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String type;
        @AuraEnabled
        public String level;
        @AuraEnabled
        public String url;
        @AuraEnabled
        public Boolean isSuccess;
        public Test(Test__c test, String status) {
            this.id = test.id;
            this.name = test.Name;
            this.type = test.Category__c;
            this.level =  String.isNotBlank(test.User_Story__c) ? 'User Story' : '';
            this.isSuccess = String.isNotBlank(status) && status.equalsIgnoreCase('success') ? true : false;
            this.url = '/' + id;
        }
    }
}