Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/ResultMonitorTest.cls
@IsTest
private class ResultMonitorTest {
    @TestSetup
    private static void setup() {
        insertData();
    }

    @IsTest
    private static void getRecord() {
        // Setup

        Result__c record = result();

        // Exercise

        Test.startTest();
        Result__c result = ResultMonitor.result(record.Id);
        Test.stopTest();

        // Verify

        System.assertEquals(record.Id, result.Id, 'Incorrect result retrieved.');
        System.assertEquals(record.Status__c, result.Status__c, 'Incorrect result status retrieved.');
        System.assertEquals(record.Progress_Status__c, result.Progress_Status__c, 'Incorrect result progress status retrieved.');
    }

    @IsTest
    private static void error() {
        // Exercise

        Exception ex;
        Test.startTest();
        try {
            Result__c result = ResultMonitor.result(null);
        } catch (Exception error) {
            ex = error;
        }
        Test.stopTest();

        // Verify

        System.assert(ex != null, 'No error was thrown for a null result id.');
    }

    // Helpers

    private static Result__c result() {
        return [SELECT Status__c, Progress_Status__c FROM Result__c LIMIT 1];
    }

    private static void insertData() {
        insert new Result__c(Status__c = 'In Progress', Progress_Status__c = 'Executing', Job_Type__c = 'echo');
    }
}