Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User story that originated the result.</description>
    <inlineHelpText>User story that originated the result.</inlineHelpText>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Result</relationshipLabel>
    <relationshipName>Result</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Test Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ready for Test</fullName>
            </value>
            <value>
                <fullName>Testing in Progress</fullName>
            </value>
            <value>
                <fullName>Testing Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the implementation of the User Story.</description>
    <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/DefinitionOfDoneCtrl.cls
public with sharing class DefinitionOfDoneCtrl {
    //PUBLIC
    @AuraEnabled(cacheable=true)
    public static List<TestWrapper> getTests(Id recordId) {
        try{
            List<TestWrapper> result = new List<TestWrapper>();

            for (Test__c test : new TestsSelector().byParentWithLatestResult(recordId)) {
                parseToTestWrapper(test,result);
            }

            return result;
        }catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }
    
    @AuraEnabled
    public static void deleteTest(Id recordId) {
        try {
            List<Test__c> tests = new TestsSelector().byIds(new Set<Id>{ recordId });
            Utilities.Secure_DML(tests, Utilities.DML_Action.DEL, Schema.SObjectType.Test__c);
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }

    //PRIVATE
    private static void parseToTestWrapper(Test__c test, List<TestWrapper> testWrapper) {
        if (test.Results__r.isEmpty()) {
            testWrapper.add(new TestWrapper(test, ''));
        } else {
            testWrapper.add(new TestWrapper(test, test.Results__r[0].Status__c));
        }
    }

    public with sharing class TestWrapper {
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String type;
        @AuraEnabled
        public String level;
        @AuraEnabled
        public String url;
        @AuraEnabled
        public Boolean isSuccess;
        public TestWrapper(Test__c test, String status) {
            this.id = test.id;
            this.name = test.Name;
            this.type = test.Category__c;
            this.level =  String.isNotBlank(test.User_Story__c) ? 'User Story' : '';
            this.isSuccess = String.isNotBlank(status) && status.equalsIgnoreCase('success') ? true : false;
            this.url = '/' + id;
        }
    }
}