Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/classes/RunTestAction.cls
public with sharing class RunTestAction {
    public with sharing class Request {
        @InvocableVariable(label='Test ID')
        public Id testId;
    }
    public with sharing class Result {
        @InvocableVariable(label='Result ID')
        public Id resultId;

        Result(Id resultId) {
            this.resultId = resultId;
        }
    }

    // PUBLIC

    @InvocableMethod(
        label='Run Individual Test'
        description='Run an individual test with the logic provided by the related extension package'
        category='Test'
    )
    public static List<Result> execute(List<Request> requests) {
        List<Test__c> tests = new TestsSelector().byIds(new Set<Id>{ requests[0].testId });
        List<Result__c> extensionResults = new RunTestsInExtension(tests).execute();

        return new List<Result>{ new Result(extensionResults[0].Id) };
    }
}