Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User story that originated the result.</description>
    <inlineHelpText>User story that originated the result.</inlineHelpText>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Result</relationshipLabel>
    <relationshipName>Result</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/classes/DefinitionOfDoneCtrlTest1.cls
@isTest
private with sharing class DefinitionOfDoneCtrlTest1 {
   
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void validateGetTests(){
        System.runAs(getStandardUser()) {
            // Setup
            User_Story__c userStory = [Select Id from User_Story__c limit 1];
            // Exercise
            List<DefinitionOfDoneCtrl.Test> tests = DefinitionOfDoneCtrl.getTests(userStory.Id);
            // Verify
            assertTest(tests[0]);
        }
    }
    @SuppressWarnings('PMD.ApexUnitTestMethodShouldHaveIsTestAnnotation')
    private static void assertTest(DefinitionOfDoneCtrl.Test test){
        System.assertEquals('test',test.name, 'expected test but found '+test.name);
        System.assertEquals('test category',test.type, 'expected test category but found '+test.type);
        System.assertEquals('User Story',test.level, 'expected test tool but found '+test.level);
        System.assertEquals(false,test.isSuccess, 'expected true but found '+test.isSuccess);
    }

    @TestSetup
    private static void makeData() {
        User standardUser = setupUser();
        System.runAs(standardUser) {
            User_Story__c userStory = CMTestMethodUtilities.createUserStory('Test');
            insert userStory;
            Test__c test = TestMethodUtilities.createTest(userStory.Id);
            insert test;
            Result__c result = TestMethodUtilities.createResult(test.Id);
            insert result;
            
        }
    }

    private static User setupUser() {
        ITestDefaults userCreation = new CopadoSetupTestDefaults.UserDefaults().createRunAsUsers().executeDML();
        User standardUser = userCreation.getRunAsUsers().get('Standard')[0];
        setOrgTimeZone(standardUser);
        return standardUser;
    }

    private static void setOrgTimeZone(User user) {
        List<Organization> organizations = [SELECT TimeZoneSidKey FROM Organization LIMIT 1];
        if(!organizations.isEmpty()){
            user.TimeZoneSidKey = organizations.get(0).TimeZoneSidKey;
            update user;
        }
    }
    
    private static User getStandardUser() {
        User standardUser = [
            SELECT Id
            FROM User
            WHERE ProfileId IN (SELECT Id FROM Profile WHERE Name = 'Standard User')
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
        return standardUser;
    }
}