Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Test Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ready for Test</fullName>
            </value>
            <value>
                <fullName>Testing in Progress</fullName>
            </value>
            <value>
                <fullName>Testing Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Test__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/TestType__mdt/fields/ExecuteVia__c.field-meta.xml
<CustomField>
    <fullName>ExecuteVia__c</fullName>
    <label>ExecuteVia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/TestType__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/RunTestActionTest.cls
@isTest
private with sharing class RunTestActionTest {
    private static String category = 'Mock Type';
    private static String tool = 'Mock Tool';

    @TestSetup
    private static void setupData() {
        insertData();
    }

    @isTest
    private static void execute() {
        System.runAs(getTestUser()) {
            // Setup
            insertMockTestType();

            Test__c mockTest = getMockTest();

            RunTestAction.Request request = new RunTestAction.Request();
            request.testId = mockTest.Id;
            List<RunTestAction.Request> requests = new List<RunTestAction.Request>{ request };

            // Exercise
            RunTestAction.execute(requests);

            // Verify
            List<Result__c> results = [SELECT Job_Type__c, Progress_Status__c, Status__c FROM Result__c];
            System.assertEquals(1, results.size(), '1 results should have been created for the test execution');
            assertMockResult(results[0]);
        }
    }

    @isTest
    private static void executeWithoutExtensionSet() {
        System.runAs(getTestUser()) {
            // Setup
            Test__c mockTest = getMockTest();

            RunTestAction.Request request = new RunTestAction.Request();
            request.testId = mockTest.Id;

            List<RunTestAction.Request> requests = new List<RunTestAction.Request>{ request };

            // Exercise
            Exception ex;
            try {
                RunTestAction.execute(requests);
            } catch (Exception e) {
                ex = e;
            }

            // Verify
            System.assertEquals(ex.getMessage(), Label.NoTestExtensionConfigured, 'Exception should be: ' + Label.NoTestExtensionConfigured);
        }
    }

    @SuppressWarnings('PMD.ApexUnitTestMethodShouldHaveIsTestAnnotation')
    private static void assertMockResult(Result__c mockResult) {
        System.assertEquals('Mock Type', mockResult.Job_Type__c, 'Result Job Type should be Mock Type');
        System.assertEquals('Success', mockResult.Progress_Status__c, 'Result Progress Status should be Success');
        System.assertEquals('Success', mockResult.Status__c, 'Result Status should be Success');
    }

    private static void insertData() {
        ITestDefaults userCreation = new CopadoSetupTestDefaults.UserDefaults().createRunAsUsers().executeDML();
        User adminUser = userCreation.getRunAsUsers().get('Admin')[0];

        System.runAs(adminUser) {
            createMockTest();
        }
    }

    private static User getTestUser() {
        User testUser = [SELECT Id, Name, LastName, Email, Username FROM User WHERE Email = 'test@test.org' LIMIT 1].get(0);
        TestUtilities.assignLicense(String.valueOf(testUser.Username), true, true, true, true, true);

        return testUser;
    }

    private static void createMockTest() {
        Test__c test = new Test__c(Name = 'Mock Test', Category__c = category, Tool__c = tool);

        insert test;
    }

    private static Test__c getMockTest() {
        return [SELECT Name FROM Test__c LIMIT 1];
    }

    private static void insertMockTestType() {
        TestType__mdt mockTestType = new TestType__mdt();
        mockTestType.ExecuteVia__c = 'TestExtensionMock';
        mockTestType.Namespace__c = '';
        mockTestType.Category__c = category;
        mockTestType.Tool__c = tool;

        TestTypesSelector.mock(new List<TestType__mdt>{ mockTestType });
    }
}