Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/SetJobTemplateApiNameTest.cls
@IsTest
private class SetJobTemplateApiNameTest {

    @IsTest
    private static void execute() {
        // Setup
        JobTemplate__c template = new JobTemplate__c();
        template.Name = 'Sample';
        template.Version__c = 1;


        // Exercise
        insert template;


        // Verify
        System.assertEquals('Sample_1', [SELECT ApiName__c FROM JobTemplate__c WHERE Id = :template.Id].ApiName__c);
    }
}