Dummy_Package_for_scratch_org/main/default/objects/SupportedObject__mdt/SupportedObject__mdt.object-meta.xml
<CustomObject>
    <label>Supported Object</label>
    <pluralLabel>Supported Objects</pluralLabel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/SupportedObject__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>SupportedObjects</relationshipLabel>
    <relationshipName>SupportedObjects</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/CreateStandardRecordCtrl.cls
public with sharing class CreateStandardRecordCtrl {

    @AuraEnabled
    public static List<SupportedObject> getSupportedObjects() {
        List<SupportedObject> result = new List<SupportedObject>();

        try {
            for(SupportedObject__mdt supportedObject : new SupportedObjectsSelector().allObjects()) {
                result.add(new SupportedObject(supportedObject.SObject__r?.Label, supportedObject.SObject__r?.QualifiedApiName));
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return result;
    }

    @AuraEnabled
    public static String getRecordBundle(List<Id> recordIds) {
        String result;

        try {
            result = CreateStandardRecords.serialize(new Set<Id>(recordIds));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return result;
    }

    // INNER

    public class SupportedObject {
        @AuraEnabled
        public String label;
        
        @AuraEnabled
        public String value;

        public SupportedObject(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
}