Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Disable_Validation__c.field-meta.xml
<CustomField>
    <fullName>Disable_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this checkbox will not validate the credentials when the record is saved or viewed.</inlineHelpText>
    <label>Disable Validation</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Metadata_Types__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Types__c</fullName>
    <inlineHelpText>Empty means all types. Select one or more types to limit the backup only to selected items.</inlineHelpText>
    <label>Metadata Types</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Oauth_Signature__c.field-meta.xml
<CustomField>
    <fullName>Oauth_Signature__c</fullName>
    <description>This value is automatically set and updated by Copado.</description>
    <inlineHelpText>This value is automatically set and updated by Copado.</inlineHelpText>
    <label>Oauth Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Org_Type__c.field-meta.xml
<CustomField>
    <fullName>Org_Type__c</fullName>
    <label>Org Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production/Developer</fullName>
                <default>true</default>
                <label>Production/Developer</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Scratch Org - Test only</fullName>
            </value>
            <value>
                <fullName>Scratch Org</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <formula>TEXT(Environment__r.Platform__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Platform</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Test_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Test_Frequency__c</fullName>
    <description>Continuous Integration feature. Run all Apex Test methods and save the results in the Apex Test Result object to create email alerts or reports. This feature is very powerful along with Git Backups to detect recent failing changes automatically.</description>
    <inlineHelpText>Continuous Integration feature. Run all Apex Test methods and save the results in the Apex Test Result object to create email alerts or reports. This feature is very powerful along with Git Backups to detect recent failing changes automatically.</inlineHelpText>
    <label>Test Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/CredentialRecordPageHandler.cls
public with sharing class CredentialRecordPageHandler {
    private static List<ValidationResult> validationResults { get; set; }

    private static final String ACTION_INFO = 'action:info';
    private static final String ACTION_CLOSE = 'action:close';
    private static final String ACTION_APPROVAL = 'action:approval';

    @AuraEnabled
    public static String getMetadataTypesFieldHelpText() {
        return Org__c.Metadata_Types__c.getDescribe().getInlineHelpText();
    }

    @AuraEnabled
    public static List<ValidationResult> validateOrgAndReturnResultWrapper(String credentialId) {
        validationResults = new List<ValidationResult>();
        if (String.isNotBlank(credentialId)) {
            Org__c credential = [
                SELECT Id, Org_Type__c, Test_Frequency__c, Disable_Validation__c, Oauth_Signature__c, Platform__c
                FROM Org__c
                WHERE Id = :credentialId
            ];
            if (credential.Platform__c != null && credential.Platform__c != 'Salesforce') {
                createValidationResultRecordAndAddToList(ACTION_INFO, Label.Non_Salesforce_Credential);
                populateKeyNumberOfValidationResult();
                return validationResults;
            }

            Boolean isScratchOrg = String.isNotBlank(credential.Org_Type__c) && credential.Org_Type__c.startsWithIgnoreCase('Scratch Org');
            if (credential.Id != null && !credential.Disable_Validation__c && !isScratchOrg) {
                if (credential.Oauth_Signature__c == null) {
                    createValidationResultRecordAndAddToList(ACTION_INFO, Label.ADD_AUTHENTICATION);
                    populateKeyNumberOfValidationResult();
                    return validationResults;
                } else {
                    if (!DeployAPI.validateOrg(credential.Id)) {
                        createValidationResultRecordAndAddToList(ACTION_CLOSE, Label.WRONG_CREDENTIALS);
                        populateKeyNumberOfValidationResult();
                        return validationResults;
                    } else {
                        createValidationResultRecordAndAddToList(ACTION_APPROVAL, Label.OK_CREDENTIALS);
                    }
                }
                if (credential.Test_Frequency__c != null && credential.Test_Frequency__c != 'None') {
                    Org__c copadoOrg = DeployAPI.getCustomerOrg();
                    if (copadoOrg == null) {
                        createValidationResultRecordAndAddToList(ACTION_CLOSE, Label.CUSTOMER_ORG_NOT_EXISTS);
                        populateKeyNumberOfValidationResult();
                        return validationResults;
                    }
                    if (!DeployAPI.validateOrg(copadoOrg.Id)) {
                        createValidationResultRecordAndAddToList(ACTION_CLOSE, Label.CUSTOMER_ORG_NOT_VALIDATED);
                    }
                }
            }
        }
        populateKeyNumberOfValidationResult();
        return validationResults;
    }

    private static void createValidationResultRecordAndAddToList(String iconName, String message) {
        ValidationResult validationResultItem = new ValidationResult();
        validationResultItem.iconName = iconName;
        validationResultItem.message = message;
        validationResults.add(validationResultItem);
    }

    private static void populateKeyNumberOfValidationResult() {
        for (integer i = 0; i < validationResults.size(); i++) {
            validationResults[i].keyNumber = i;
        }
    }

    @AuraEnabled
    public static List<String> getMetadataTypesForGivenCredentialId(String credentialId) {
        return MetadataTypesHelper.getMetadataTypesByOrgId(credentialId);
    }

    public with sharing class ValidationResult {
        @AuraEnabled
        public Integer keyNumber;
        @AuraEnabled
        public String iconName;
        @AuraEnabled
        public String message;
    }
}