Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Api Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobTemplate__c.field-meta.xml
<CustomField>
    <fullName>JobTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/SetJobStepApiName.cls
public inherited sharing class SetJobStepApiName {
    private List<JobStep__c> steps;

    // CONSTRUCTOR

    public SetJobStepApiName(List<JobStep__c> steps) {
        this.steps = steps;
    }


    // PUBLIC

    public void execute() {
        Set<Id> parentIds = parentIds(steps);
        Map<Id, JobExecution__c> executionsById = new Map<Id, JobExecution__c>( new JobExecutionsSelector().byId(parentIds) );
        Map<Id, JobTemplate__c> templatesById = new Map<Id, JobTemplate__c>( new JobTemplatesSelector().byId(parentIds) );

        for(JobStep__c step : steps) {
            String parentName = templatesById.containsKey(step.JobTemplate__c) ?
                                    (String) templatesById.get(step.JobTemplate__c).get('Name') :
                                (executionsById.containsKey(step.JobExecution__c) ?
                                    (String) executionsById.get(step.JobExecution__c).get('Name') : null);

            step.ApiName__c = parentName + '_' + step.Name;
        }
    }

    // PRIVATE

    private Set<Id> parentIds(List<JobStep__c> steps) {
        Set<Id> result = new Set<Id>();

        for (JobStep__c step : steps) {
            if(step.JobExecution__c != null) {
                result.add(step.JobExecution__c);
            }
            else if(step.JobTemplate__c != null) {
                result.add(step.JobTemplate__c);
            }
        }

        return result;
    }
}