Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Callback__c.field-meta.xml
<CustomField>
    <fullName>Callback__c</fullName>
    <description>An apex class that must implement copado.JobExecutionCallback interface.</description>
    <inlineHelpText>An apex class that must implement copado.JobExecutionCallback interface.</inlineHelpText>
    <label>Callback</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <formula>IF(NOT(ISBLANK( Deployment__c )), Deployment__c, 
    IF(NOT(ISBLANK( Promotion__c )), Promotion__c, 
        IF(NOT(ISBLANK( UserStoryCommit__c )), UserStoryCommit__c, 
            IF(NOT(ISBLANK( Snapshot__c )), Snapshot__c,  ParentRecord_Id__c)
        )
    )
)</formula>
    <label>Parent Id(Formula)</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/VolumeOptions__c.field-meta.xml
<CustomField>
    <fullName>VolumeOptions__c</fullName>
    <label>VolumeOptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/ConfigJson__c.field-meta.xml
<CustomField>
    <fullName>ConfigJson__c</fullName>
    <label>ConfigJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/ResultDataJson__c.field-meta.xml
<CustomField>
    <fullName>ResultDataJson__c</fullName>
    <label>Result Data Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/ApexCallback__c.field-meta.xml
<CustomField>
    <fullName>ApexCallback__c</fullName>
    <description>This field is updated automatically by Copado.</description>
    <inlineHelpText>This field is updated automatically by Copado.</inlineHelpText>
    <label>Apex Callback</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Date time when the job started.</description>
    <inlineHelpText>Date time when the job started.</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/RunJob.cls
@SuppressWarnings('PMD.AvoidGlobalModifier, PMD.CyclomaticComplexity')
global with sharing class RunJob implements Queueable, Database.AllowsCallouts {

	private static final String STEP_CALLBACK = 'StepCallback';

	private JobExecution__c job;
	private String transactionId;
	private List<JobStep__c> steps;

	// CONSTRUCTOR

	public RunJob(Id jobId) {
		this( new JobExecutionsSelector().byId(jobId));
	}


	public RunJob(JobExecution__c job) {
		this.job = job;
	}


	// GLOBAL

	@InvocableMethod(label='Execute Job')
	global static void execute(List<Request> requests) {
		for (Request request : requests) {
			new RunJob(request.jobId).execute(request.allSteps, request.transactionId);
		}
	}


	// PUBLIC

	public void execute() {
		Boolean allSteps = true;
		String transactionId = null;

		execute(allSteps, transactionId);
	}


	public void execute(Boolean allSteps, String transactionId) {
		if(job == null) {
			throw new ApplicationException(Label.InvalidExecutionId);
		}

		// Note: if the job is already in progress, no need to start next step execution
		if(job.Status__c != 'In Progress') {
			clearSteps(allSteps);
            job.ErrorMessage__c = null;
            job.Status__c = 'In Progress';

            update Security.stripInaccessible(AccessType.UPDATABLE, new List<SObject> { job }).getRecords();

            System.enqueueJob(this);
		}
	}


    public void execute(QueueableContext ctx) {
        executeNextStep();
    }


	public void executeNextStep() {
		JobStep__c next = nextStep();

		if (next == null) {
			finish('Successful');
		}
		else {
			try {
				next.Result__c = invoke(next);
				update Security.stripInaccessible(AccessType.UPDATABLE, new List<SObject> { next }).getRecords();
			}
			catch(CopadoFunctionException ex) {
				next.Result__c = ex.resultId;
				update Security.stripInaccessible(AccessType.UPDATABLE, new List<SObject> { next }).getRecords();

				job.ErrorMessage__c = ex.getMessage();
				finish('Error');
			}
			catch(Exception ex) {
				job.ErrorMessage__c = ex.getMessage();
				finish('Error');
			}
		}
	}


	public void finish(String status) {
		job.Status__c = status;

		try {
			runCallback(job, status);
		}
		catch (Exception ex) {
			job.Status__c = 'Error';
			job.ErrorMessage__c = ex.getMessage();
		}

		update Security.stripInaccessible(AccessType.UPDATABLE, new List<SObject> { job }).getRecords();
	}


	// PRIVATE

	private String volumeOptionWithTransactionId(JobExecution__c job) {
		String result = job.VolumeOptions__c;

		if(String.isNotBlank(transactionId) && String.isNotBlank(job.VolumeOptions__c)) {
			List<Parameter> parameters = (List<Parameter>) JSON.deserialize(job.VolumeOptions__c, List<Parameter>.class);

			for(Parameter parameter : parameters) {
				if(parameter.name == 'transactionId') {
					parameter.name = transactionId;
				}
			}

			result = JSON.serialize(parameters);
		}

		return result;
	}


	private void clearSteps(Boolean allSteps) {
		steps = new JobStepsSelector().byJob(job.Id);

		for (JobStep__c step : steps) {
			if (allSteps || step.Status__c == 'Failed') {
				step.Result__c = null;
				step.ResultDataJson__c = null;
			}
		}

		update Security.stripInaccessible(AccessType.UPDATABLE, steps).getRecords();
	}


	private List<Parameter> volumeOptions(JobStep__c step) {
		List<Parameter> result = new List<Parameter>();

        if(String.isNotBlank(job.VolumeOptions__c)) {
            result = (List<Parameter>) JSON.deserialize(job.VolumeOptions__c, List<Parameter>.class);
        }

		if(isLastFunction(step) && getValue(result, 'preserveVolumeAfterExecution') == 'false') {
			result.add(new Parameter('killVolume', 'true'));
		}

		return result;
	}


	private String getValue(List<Parameter> parameters, String key) {
		String result = null;

		for(Parameter parameter : parameters) {
			if(parameter.name == key) {
				result = parameter.value;
				break;
			}
		}

		return result;
	}


	private Boolean isLastFunction(JobStep__c step) {
		Boolean result = false;

		for(Integer i = steps.size() - 1; i >= 0; i--) {
			if(steps[i].Type__c == 'Function') {
				result = (steps[i].Id == step.Id);
				break;
			}
		}

		return result;
	}


	private JobStep__c nextStep() {
		steps = new JobStepsSelector().byJob(job.Id);

		for(JobStep__c step : steps) {
			if(step.Status__c == 'Pending') {
				return step;
			}
		}

		return null;
	}


	private void runCallback(JobExecution__c job, String status) {
		if( String.isNotBlank(job.Callback__c) ) {
			Type callback = Type.forName(ns(job), localClass(job));
			if(callback == null) {
				throw new ApplicationException('Invalid class: ' + job.Callback__c);
			}

			((JobExecutionCallback) callback.newInstance()).execute(job, status);
		}
	}


	private Id invoke(JobStep__c step) {
		Id result;

		if (step.Type__c == 'Function') {
			result = invokeFunction(step);
		}
		else if (step.Type__c == 'Flow') {
			result = invokeFlow(step);
		}
		else if (step.Type__c == 'Manual') {
			result = invokeManual(step);
		}

		return result;
	}


	private Id invokeFunction(JobStep__c step) {
		StepConfig config = config(step);

		return new Function(config.functionName)
					.stepId(step.Id)
					.showValidationErrors(true)
					.parameters(config.parameters)
					.resultCallback(STEP_CALLBACK)
					.options(volumeOptions(step))
					.execute();
	}


	private Id invokeFlow(JobStep__c step) {
		StepConfig config = config(step);

		return new Flow(step.Id, config.flowName)
					.parameters(config.parameters)
					.resultCallback(STEP_CALLBACK)
					.execute();
	}


	private Id invokeManual(JobStep__c step) {
		return createResult(step, 'In Progress');
	}


	private Id createResult(JobStep__c step, String status) {
		return createResult(step, status, null);
	}


	private Id createResult(JobStep__c step, String status, String errorMessage) {
        Result__c result = new Result__c();
        result.Status__c = status;
        result.JobStep__c = step.Id;
        result.Job_Type__c = step.Type__c;
        result.ParentId__c = job.ParentId__c;
        result.Start_Time__c = Datetime.now();
        result.Error_Message__c = errorMessage;
        result.ApexCallback__c = STEP_CALLBACK;

		result = (Result__c) Security.stripInaccessible(AccessType.CREATABLE, new List<SObject> { result }).getRecords().get(0);
		insert result;

		return result.Id;
	}


    private String ns(JobExecution__c job) {
        return job.Callback__c.contains('.') ? job.Callback__c.substringBefore('.') : '';
    }


    private String localClass(JobExecution__c job) {
        return job.Callback__c.contains('.') ? job.Callback__c.substringAfter('.') : job.Callback__c;
    }


	private StepConfig config(JobStep__c step) {
		return (StepConfig) JSON.deserialize(step.ConfigJson__c, StepConfig.class);
	}


	// INNER

	global class Request {
		@InvocableVariable
		global Id jobId;

		@InvocableVariable
		global Id transactionId;

		@InvocableVariable
		global Boolean allSteps = true;
	}


	@TestVisible
	private class StepConfig {
		@TestVisible
        private String flowName;

		@TestVisible
        private String functionName;

		@TestVisible
        private List<Parameter> parameters;
	}
}