Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/ResultMonitorLWCHandler.cls
public with sharing class ResultMonitorLWCHandler {
    private static Id recordId;
    private static String objectName;
    private static String fieldName;
    private static String templateName;
    private static String jobExecutionId;


    // PUBLIC

    @AuraEnabled(cacheable=false)
    public static ResultStatusDetail result(Id recId, String objectApiName, String fieldApiName) {
        recordId = recId != null ? recId : null;
        objectName = getObjectApiName(objectApiName);
        fieldName = String.isNotBlank(fieldApiName) ? fieldApiName : '';

        recordDetail();
        return getResultStatusDetail();
    }


    // PRIVATE

    private static String getObjectApiName(String objectApiName) {
        return recordId != null ? recordId.getSObjectType().getDescribe().getName() : ((SObject) Type.forName(objectApiName).newInstance()).getSObjectType().getDescribe().getName();
    }

    private static void recordDetail() {
        String secureId = String.escapeSingleQuotes(recordId);
        String whereClause = 'Id = :secureId';

        String query = String.format(
            'SELECT {0} FROM {1} WHERE {2} LIMIT 1',
            new List<String>{ fieldName, objectName, whereClause }
        );

        jobExecutionId = (String) Database.query(query)[0]?.get(fieldName);
    } 

    public static ResultStatusDetail getResultStatusDetail() {
        ResultStatusDetail result = new ResultStatusDetail();
        result.jobExecutionId = jobExecutionId;
        result.jobExecutionObjectApiName = SObjectType.JobExecution__c.getLocalName();
        result.resultDetails = populateResultDetails();
        result.mainTitle = templateName;

        return result;
    }

    private static List<ResultStatusDetail.ResultDetail> populateResultDetails() {
        List<ResultStatusDetail.ResultDetail> resultDetails = new List<ResultStatusDetail.ResultDetail>();
        for(JobStep__c jobStep : jobSteps()) {
            ResultStatusDetail.ResultDetail detail = new ResultStatusDetail.ResultDetail();
            detail.jobStepId = jobStep.Id;
            detail.jobStepObjectApiName = SObjectType.JobStep__c.getLocalName();
            detail.jobStepLabel = jobStep.Name;
            detail.resultId = jobStep.Result__c != null ? jobStep.Result__r.Id : null;
            detail.resultStatus = jobStep.Result__c != null ? jobStep.Result__r.Status__c : 'Not Started';
            detail.resultValue = jobStep.Result__c != null ? jobStep.Result__r.Name : '';
            detail.resultLabel = Label.View_result;
            detail.resultObjectApiName = SObjectType.Result__c.getLocalName();
            resultDetails.add(detail);

            if(String.isBlank(templateName)) {
                templateName = jobStep.JobExecution__r.Template__r.Name;
            }
        }
        return resultDetails;
    }

    private static List<JobStep__c> jobSteps() {
        return [SELECT Id,
                        Name,
                        Result__c,
                        Result__r.Name, 
                        Result__r.Status__c,
                        Result__r.Progress_Status__c,
                        JobExecution__r.Template__r.Name
                FROM JobStep__c 
                WHERE JobExecution__c != NULL AND JobExecution__c = :jobExecutionId
                WITH SECURITY_ENFORCED 
                ORDER BY JobExecution__r.CreatedDate, Order__c];
    }
}