Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/ConfigJson__c.field-meta.xml
<CustomField>
    <fullName>ConfigJson__c</fullName>
    <label>ConfigJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/CustomType__c.field-meta.xml
<CustomField>
    <fullName>CustomType__c</fullName>
    <label>Custom Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobTemplate__c.field-meta.xml
<CustomField>
    <fullName>JobTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Custom&apos;</defaultValue>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Custom_Job_Step__mdt/MC_Custom_Job_Step__mdt.object-meta.xml
<CustomObject>
    <label>MC Custom Job Step</label>
    <pluralLabel>MC Custom Job Steps</pluralLabel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/MC_Custom_Job_Step__mdt/fields/CustomType__c.field-meta.xml
<CustomField>
    <fullName>CustomType__c</fullName>
    <label>Custom Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Custom_Job_Step__mdt/fields/LWC_Name__c.field-meta.xml
<CustomField>
    <fullName>LWC_Name__c</fullName>
    <label>LWC Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Custom_Job_Step__mdt/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/CustomJobStepController.cls
public with sharing class CustomJobStepController {
    @AuraEnabled(cacheable=true)
    public static String getNamespace() {
        try {
            return Settings.ns;
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }

    @AuraEnabled(cacheable=false)
    public static JobStep__c getStep(String stepId) {
        try {
            return [SELECT Name, Type__c, CustomType__c, Order__c, ConfigJson__c FROM JobStep__c WHERE Id = :stepId WITH SECURITY_ENFORCED];
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }

    @AuraEnabled(cacheable=false)
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public static Id saveStep(JobStep__c record) {
        try {
            if (String.isBlank(record.Id)) {
                record.Order__c = getOrder(parentId(record));
            }

            JobStep__c step = (JobStep__c) Security.stripInaccessible(AccessType.UPSERTABLE, new List<JobStep__c>{ record }).getRecords()[0];
            upsert step;

            return step.Id;
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }

    @AuraEnabled(cacheable=true)
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public static List<StepOption> getStepOptions() {
        List<StepOption> result = new List<StepOption>();

        try {
            for (MC_Custom_Job_Step__mdt record : [
                SELECT LWC_Name__c, Platform__c, CustomType__c, NamespacePrefix
                FROM MC_Custom_Job_Step__mdt
                ORDER BY CustomType__c NULLS FIRST
            ]) {
                result.add(new StepOption(record.CustomType__c, record.Platform__c, lwcName(record)));
            }
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }

        return result;
    }

    // PRIVATE

    private static String lwcName(MC_Custom_Job_Step__mdt config) {
        return (String.isBlank(config.NamespacePrefix) ? 'c' : config.NamespacePrefix) + ':' + config.LWC_Name__c;
    }

    private static Id parentId(JobStep__c record) {
        return String.isNotBlank(record.JobTemplate__c) ? record.JobTemplate__c : record.JobExecution__c;
    }

    private static Integer getOrder(String parentId) {
        Integer result = 1;

        try {
            List<JobStep__c> steps = [
                SELECT Order__c
                FROM JobStep__c
                WHERE (JobTemplate__c = :parentId OR JobExecution__c = :parentId) AND Order__c != NULL
                WITH SECURITY_ENFORCED
                ORDER BY Order__c DESC
                LIMIT 1
            ];
            if (!steps.isEmpty()) {
                result = (Integer) steps[0].Order__c + 1;
            }
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }

        return result;
    }

    public class StepOption {
        @AuraEnabled
        public String type;
        @AuraEnabled
        public String label;
        @AuraEnabled
        public String component;

        public StepOption(String type, String platform, String component) {
            this.type = type;
            this.label = label(platform);
            this.component = component;
        }

        private String label(String platform) {
            return type + (String.isNotBlank(platform) ? ' - ' + platform : '');
        }
    }
}