Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Personal_Settings__c/fields/Disable_Re_Create_Feature_Branch_in_US__c.field-meta.xml
<CustomField>
    <fullName>Disable_Re_Create_Feature_Branch_in_US__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Re-Create Feature Branch in US</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/User_Story_Metadata__c.object-meta.xml
<CustomObject>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/classes/UserStoryCommitCtrl.cls
public with sharing class UserStoryCommitCtrl {

    // PUBLIC

    @AuraEnabled(cacheable=true)
    public static Boolean isReCreateFeatureBranchAvailable() {
        try {
            return !Personal_Settings__c.getInstance().Disable_Re_Create_Feature_Branch_in_US__c;
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }

    @AuraEnabled
    public static JobExecution__c commitChanges(UserStoryCommitRequest request) {
        try {
            return CommitAction.commitChanges(new List<CommitAction.Request>{ request.parse() })[0].jobExecution;
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<User_Story_Metadata__c> getUserStoryMetadata(String recordId) {
        try {
            return new UserStoriesMetadataSelector().byUserStoryId(new Set<Id>{ recordId });
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }
}