Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/Deployment_Flow_Step__c.object-meta.xml
<CustomObject>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Pipeline Connections</relationshipLabel>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Destination_Environment__c.field-meta.xml
<CustomField>
    <fullName>Destination_Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Source_Environment__c.field-meta.xml
<CustomField>
    <fullName>Source_Environment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&quot;Salesforce&quot;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/ValidatePlatformTypeTest.cls
@IsTest
private class ValidatePlatformTypeTest {
    
    @IsTest
    private static void updateEnvironmentPlatformToSameType() {

        // Setup
        Exception expectedException = null;
        Deployment_Flow__c pipeline = createPipeline();
        Environment__c environment = createEnvironment();
        Deployment_Flow_Step__c connection = createConnection(pipeline.Id, environment.Id);

        
        // Exercise
        try {
            environment.Platform__c = 'Salesforce';
            update environment;
        }
        catch(Exception ex) {
            expectedException = ex;
        }


        // Verify
        System.assertEquals(null, expectedException);
    }
    
    
    @IsTest
    private static void updateEnvironmentPlatformToDifferentType() {

        // Setup
        Exception expectedException = null;
        Deployment_Flow__c pipeline = createPipeline();
        Environment__c environment = createEnvironment();
        Deployment_Flow_Step__c connection = createConnection(pipeline.Id, environment.Id);
        
        
        // Exercise
        try {
            environment.Platform__c = 'Other';
            update environment;
        }
        catch(Exception ex) {
            expectedException = ex;
        }


        // Verify
        System.assertNotEquals(null, expectedException);
    }
    
    
    @IsTest
    private static void updatePipelinePlatformToDifferentType() {

        // Setup
        Exception expectedException = null;
        Deployment_Flow__c pipeline = createPipeline();
        Environment__c environment = createEnvironment();
        Deployment_Flow_Step__c connection = createConnection(pipeline.Id, environment.Id);
        
        
        // Exercise
        try {
            pipeline.Platform__c = 'Other';
            update pipeline;
        }
        catch(Exception ex) {
            expectedException = ex;
        }


        // Verify
        System.assertNotEquals(null, expectedException);
    }
    
    
    // Helper
    
    private static Deployment_Flow__c createPipeline() {
        Deployment_Flow__c result = new Deployment_Flow__c();
        result.Platform__c = 'Salesforce';
        insert result;
        
        return result;
    }
    
        
    private static Environment__c createEnvironment() {
        Environment__c result = new Environment__c();
        result.Platform__c = 'Salesforce';
        insert result;
        
        return result;
    }
    
    
    private static Deployment_Flow_Step__c createConnection(Id pipelineId, Id environmentId) {
        Deployment_Flow_Step__c result = new Deployment_Flow_Step__c();
        result.Deployment_Flow__c = pipelineId;
        result.Source_Environment__c = environmentId;
        result.Destination_Environment__c = environmentId;
        insert result;
        
        return result;
    }
}