Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/Deployment_Flow_Step__c.object-meta.xml
<CustomObject>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Pipeline Connections</relationshipLabel>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Destination_Environment__c.field-meta.xml
<CustomField>
    <fullName>Destination_Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Source_Environment__c.field-meta.xml
<CustomField>
    <fullName>Source_Environment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&quot;Salesforce&quot;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/ValidatePlatformType.cls
public inherited sharing class ValidatePlatformType {
    // TODO: remove this comment
    List<SObject> records;
    Map<Id, List<Deployment_Flow_Step__c>> connectionsByParentId;

    
    // CONSTRUCTOR

    public ValidatePlatformType(List<Environment__c> environments, Map<Id, Environment__c> oldRecords) {
        records = filter(environments, oldRecords);
        connectionsByParentId = new DeploymentFlowStepsSelector().byEnvironment(records);
    }


    public ValidatePlatformType(List<Deployment_Flow__c> piplines, Map<Id, Deployment_Flow__c> oldRecords) {
        records = filter(piplines, oldRecords);
        connectionsByParentId = new DeploymentFlowStepsSelector().byPipeline(records);
    }


    // PUBLIC

    public void execute() {
        for(SObject record : records) {
            if(connectionsByParentId.containsKey(record.Id)) {
                for(Deployment_Flow_Step__c connection : connectionsByParentId.get(record.Id)) {
                    if(platformTypeDifferent(connection)) {
                        record.addError(Label.InValidPlatformType);
                    }
                }
            }
        }
    }


    // PRIVATE

    private Boolean platformTypeDifferent(Deployment_Flow_Step__c connection) {
        return ((connection.Source_Environment__c != null && platformType(connection.Deployment_Flow__r.Platform__c) != platformType(connection.Source_Environment__r.Platform__c)) || 
                (connection.Destination_Environment__c != null && platformType(connection.Deployment_Flow__r.Platform__c) != platformType(connection.Destination_Environment__r.Platform__c)));
    }


    private List<SObject> filter(List<SObject> records, Map<Id, SObject> oldRecords) {
        List<SObject> result = new List<SObject>();

        if(records != null) {
            for(SObject record : records) {
                SObject oldRecord = oldRecords?.get(record.Id);
                
                if(isPlatformTypeChanged(record, oldRecord)) {
                    result.add(record);
                }
            }   
        }

        return result;
    }


    private Boolean isPlatformTypeChanged(SObject record, SObject oldRecord) {
        return (String.valueOf(record.get('Platform__c')) != String.valueOf(oldRecord?.get('Platform__c')));
    }


    private String platformType(String platformType) {
        return String.isBlank(platformType) ? 'Salesforce' : platformType;
    }
}