Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Git_Repository__c.field-meta.xml
<CustomField>
    <fullName>Git_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
    <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
    <label>Git Repository</label>
    <referenceTo>Git_Repository__c</referenceTo>
    <relationshipName>Deployment_Flows</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Static_Code_Analysis_Settings__c.field-meta.xml
<CustomField>
    <fullName>Static_Code_Analysis_Settings__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Static Code Analysis settings used whenever the analysis is run in Environments or User Stories linked to the Deployment Flow.</description>
    <inlineHelpText>Static Code Analysis settings used whenever the analysis is run in Environments or User Stories linked to the Deployment Flow.</inlineHelpText>
    <label>Static Code Analysis Settings</label>
    <referenceTo>Static_Code_Analysis_Settings__c</referenceTo>
    <relationshipName>Deployment_Flows</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/Deployment_Flow_Step__c.object-meta.xml
<CustomObject>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <inlineHelpText>Git branch linked to the source environment.</inlineHelpText>
    <label>Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Pipeline Connections</relationshipLabel>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Destination_Branch__c.field-meta.xml
<CustomField>
    <fullName>Destination_Branch__c</fullName>
    <description>Value updated automatically by Copado. This is defined in the Deployment Flow Step of the Destination Environment.</description>
    <inlineHelpText>Value updated automatically by Copado. This is defined in the Deployment Flow Step of the Destination Environment.</inlineHelpText>
    <label>Destination Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Destination_Environment__c.field-meta.xml
<CustomField>
    <fullName>Destination_Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Last_Merge_Base__c.field-meta.xml
<CustomField>
    <fullName>Last_Merge_Base__c</fullName>
    <description>Last date and time when the source and target branch were in Sync (no commits ahead or behind).</description>
    <inlineHelpText>Last date and time when the source and target branch were in Sync (no commits ahead or behind).</inlineHelpText>
    <label>Last Merge Base</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Last_Merge_CBM_Sync__c.field-meta.xml
<CustomField>
    <fullName>Last_Merge_CBM_Sync__c</fullName>
    <description>Last date and time when the CBM Sync button was clicked to merge and deploy changes to the destination environment.</description>
    <inlineHelpText>Last date and time when the CBM Sync button was clicked to merge and deploy changes to the destination environment.</inlineHelpText>
    <label>Last Merge CBM Sync</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Last_Pull_CBM_Sync__c.field-meta.xml
<CustomField>
    <fullName>Last_Pull_CBM_Sync__c</fullName>
    <description>Last date and time when the CBM Sync button was clicked to merge and deploy changes to the source environment.</description>
    <inlineHelpText>Last date and time when the CBM Sync button was clicked to merge and deploy changes to the source environment.</inlineHelpText>
    <label>Last Pull CBM Sync</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Source_Environment__c.field-meta.xml
<CustomField>
    <fullName>Source_Environment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&quot;Salesforce&quot;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Git_Repository__c/Git_Repository__c.object-meta.xml
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Static_Code_Analysis_Settings__c/Static_Code_Analysis_Settings__c.object-meta.xml
<CustomObject>
    <label>Static Code Analysis Settings</label>
    <nameField>
        <label>Static Code Analysis Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Static Code Analysis Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/classes/DeploymentFlowStepsSelector.cls
public inherited sharing class DeploymentFlowStepsSelector extends fflib_SObjectSelector {
    public Schema.SObjectType getSObjectType() {
        return Deployment_Flow_Step__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Deployment_Flow_Step__c.Id,
            Deployment_Flow_Step__c.Branch__c,
            Deployment_Flow_Step__c.Source_Environment__c,
            Deployment_Flow_Step__c.Destination_Environment__c,
            Deployment_Flow_Step__c.Deployment_Flow__c,
            Deployment_Flow_Step__c.Last_Merge_Base__c,
            Deployment_Flow_Step__c.Last_Merge_CBM_Sync__c,
            Deployment_Flow_Step__c.Last_Pull_CBM_Sync__c,
            Deployment_Flow_Step__c.Destination_Branch__c
        };
    }

    public List<Deployment_Flow_Step__c> byParentIds(Id pipelineId, Id sourceEnvironmentId, Id targetEnvironmentId) {
        return (List<Deployment_Flow_Step__c>) Database.query(
            newQueryFactory()
                .setCondition(
                    Deployment_Flow_Step__c.Deployment_Flow__c +
                    ' = :pipelineId AND ' +
                    Deployment_Flow_Step__c.Source_Environment__c +
                    ' = :sourceEnvironmentId AND ' +
                    Deployment_Flow_Step__c.Destination_Environment__c +
                    ' = :targetEnvironmentId'
                )
                .toSOQL()
        );
    }

    public List<Deployment_Flow_Step__c> byPipelineAndSourceEnvironment(Id pipelineId, Id sourceEnvironmentId) {
        return (List<Deployment_Flow_Step__c>) Database.query(
            newQueryFactory()
                .setCondition(
                    Deployment_Flow_Step__c.Deployment_Flow__c +
                    ' = :pipelineId AND ' +
                    Deployment_Flow_Step__c.Source_Environment__c +
                    ' = :sourceEnvironmentId'
                )
                .toSOQL()
        );
    }

    public Map<Id, List<Deployment_Flow_Step__c>> byEnvironment(List<Environment__c> environments) {
        Map<Id, List<Deployment_Flow_Step__c>> result = new Map<Id, List<Deployment_Flow_Step__c>>();

        List<Deployment_Flow_Step__c> connections = (List<Deployment_Flow_Step__c>) Database.query(
            selectFields()
                .setCondition(
                    Deployment_Flow_Step__c.Source_Environment__c +
                    ' IN :environments OR ' +
                    Deployment_Flow_Step__c.Destination_Environment__c +
                    ' IN :environments'
                )
                .toSOQL()
        );

        for (Deployment_Flow_Step__c connection : connections) {
            if (!result.containsKey(connection.Source_Environment__c)) {
                result.put(connection.Source_Environment__c, new List<Deployment_Flow_Step__c>());
            }

            if (!result.containsKey(connection.Destination_Environment__c)) {
                result.put(connection.Destination_Environment__c, new List<Deployment_Flow_Step__c>());
            }

            result.get(connection.Source_Environment__c).add(connection);
            result.get(connection.Destination_Environment__c).add(connection);
        }

        return result;
    }

    public List<Deployment_Flow_Step__c> byEnvironment(Id environmentId) {
        return Database.query(
            selectFields()
                .setEnforceFLS(true)
                .setCondition(
                    Deployment_Flow_Step__c.Source_Environment__c +
                    ' = :environmentId OR ' +
                    Deployment_Flow_Step__c.Destination_Environment__c +
                    ' = :environmentId'
                )
                .toSOQL()
        );
    }

    public Map<Id, List<Deployment_Flow_Step__c>> byPipeline(List<Deployment_Flow__c> pipelines) {
        Map<Id, List<Deployment_Flow_Step__c>> result = new Map<Id, List<Deployment_Flow_Step__c>>();
        Set<Id> pipelineIds = new Set<Id>();
        for (Deployment_Flow__c pipeline : pipelines) {
            pipelineIds.add(pipeline.Id);
        }
        result = new DeploymentFlowStepsSelector().byPipeline(pipelineIds);

        return result;
    }

    public Map<Id, List<Deployment_Flow_Step__c>> byPipeline(Set<Id> pipelineIds) {
        Map<Id, List<Deployment_Flow_Step__c>> result = new Map<Id, List<Deployment_Flow_Step__c>>();

        List<Deployment_Flow_Step__c> connections = (List<Deployment_Flow_Step__c>) Database.query(
            selectFields().setCondition(Deployment_Flow_Step__c.Deployment_Flow__c + ' IN :pipelineIds').toSOQL()
        );

        for (Deployment_Flow_Step__c connection : connections) {
            if (!result.containsKey(connection.Deployment_Flow__c)) {
                result.put(connection.Deployment_Flow__c, new List<Deployment_Flow_Step__c>());
            }
            result.get(connection.Deployment_Flow__c).add(connection);
        }

        return result;
    }

    // PRIVATE

    private fflib_QueryFactory selectFields() {
        return newQueryFactory()
            .selectField('Source_Environment__r.Name')
            .selectField('Destination_Environment__r.Name')
            .selectField('Deployment_Flow__r.Platform__c')
            .selectField('Source_Environment__r.Platform__c')
            .selectField('Destination_Environment__r.Platform__c')
            .selectField('Deployment_Flow__r.Static_Code_Analysis_Settings__c')
            .selectField('Deployment_Flow__r.Static_Code_Analysis_Settings__r.RecordTypeId')
            .selectField('Deployment_Flow__r.Git_Repository__c');
    }
}