Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, all Branch Management features will be enabled in the Deployment Flow.</description>
    <inlineHelpText>If checked, all Branch Management features will be enabled in the Deployment Flow.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Git_Repository__c.field-meta.xml
<CustomField>
    <fullName>Git_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
    <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
    <label>Git Repository</label>
    <referenceTo>Git_Repository__c</referenceTo>
    <relationshipName>Deployment_Flows</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Main_Branch__c.field-meta.xml
<CustomField>
    <fullName>Main_Branch__c</fullName>
    <description>Main branch of the selected Git Repository (e.g. master).</description>
    <inlineHelpText>Main branch of the selected Git Repository (e.g. master).</inlineHelpText>
    <label>Main Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/Deployment_Flow_Step__c.object-meta.xml
<CustomObject>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <inlineHelpText>Git branch linked to the source environment.</inlineHelpText>
    <label>Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Pipeline Connections</relationshipLabel>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Destination_Branch__c.field-meta.xml
<CustomField>
    <fullName>Destination_Branch__c</fullName>
    <description>Value updated automatically by Copado. This is defined in the Deployment Flow Step of the Destination Environment.</description>
    <inlineHelpText>Value updated automatically by Copado. This is defined in the Deployment Flow Step of the Destination Environment.</inlineHelpText>
    <label>Destination Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Destination_Environment__c.field-meta.xml
<CustomField>
    <fullName>Destination_Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Source_Environment__c.field-meta.xml
<CustomField>
    <fullName>Source_Environment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Latest_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Latest_Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Environments</relationshipLabel>
    <relationshipName>Environments</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Org ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&quot;Salesforce&quot;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Git_Repository__c/Git_Repository__c.object-meta.xml
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/System_Property__c.object-meta.xml
<CustomObject>
    <label>System Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>System Properties</relationshipLabel>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>This value is automatically populated when selecting a Pipeline, Environment or User. If none is selected, the record Id this property is linked to must be entered manually.</description>
    <inlineHelpText>This value is automatically populated when selecting a Pipeline, Environment or User. If none is selected, the record Id this property is linked to must be entered manually.</inlineHelpText>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>System Properties</relationshipLabel>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/ClonePipeline.cls
public with sharing class ClonePipeline {
    private static final Set<String> SYSTEM_FIELDS = new Set<String>{
        'isdeleted',
        'createddate',
        'lastmodifieddate',
        'createdbyid',
        'lastmodifiedbyid',
        'systemmodstamp',
        'lastvieweddate',
        'lastreferenceddate',
        'ownerid'
    };

    // PUBLIC

    @AuraEnabled(cacheable=false)
    public static String getData(Id recordId) {
        try {
            return new RecordData(recordId).asJsonString();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static String saveCopy(String data) {
        try {
            return new CloneData((RecordData) JSON.deserialize(data, RecordData.class)).save();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // PRIVATE

    private abstract class Pipeline {
        protected String platform {
            get {
                return pipeline.Platform__c;
            }
        }
        protected Deployment_Flow__c pipeline;
        protected List<Deployment_Flow_Step__c> connections;
        protected List<Environment__c> environments;
        protected List<System_Property__c> properties;

        // PROTECTED

        protected void pipeline(Id id) {
            pipeline = Database.query(byId());
        }

        private void connections() {
            connections = Database.query(byPipeline());
        }

        protected void environments() {
            Set<Id> environmentIds = environmentIds();
            environments = Database.query(byIds());
        }

        protected abstract String byId();
        protected abstract String byPipeline();
        protected abstract String byIds();

        // PRIVATE

        private Set<Id> environmentIds() {
            Set<Id> result = new Set<Id>();

            for (Deployment_Flow_Step__c connection : connections) {
                result.add(connection.Source_Environment__c);
                result.add(connection.Destination_Environment__c);
            }

            return result;
        }
    }

    private class RecordData extends Pipeline {
        // CTOR

        public RecordData(Id id) {
            pipeline(id);
            connections();
            environments();
        }

        // PUBLIC

        public String asJsonString() {
            return JSON.serialize(this);
        }

        // PROTECTED

        protected override String byId() {
            return 'SELECT Name, Git_Repository__c, Main_Branch__c, Platform__c FROM Deployment_Flow__c WHERE Id = :id WITH SECURITY_ENFORCED';
        }

        protected override String byPipeline() {
            return 'SELECT Branch__c, Source_Environment__c, Destination_Environment__c FROM Deployment_Flow_Step__c WHERE Deployment_Flow__c = \'' +
                String.escapeSingleQuotes(pipeline.Id) +
                '\' WITH SECURITY_ENFORCED';
        }

        protected override String byIds() {
            return 'SELECT Name FROM Environment__c WHERE Id IN :environmentIds WITH SECURITY_ENFORCED';
        }
    }

    private class CloneData extends Pipeline {
        private RecordData record;

        // CTOR

        public CloneData(RecordData record) {
            record(record);
            pipeline(record.pipeline.Id);
            connections();
            environments();
            properties();
        }

        // PUBLIC

        public Id save() {
            pipeline(clonePipeline().Id);
            Map<Id, Environment__c> environmentClones = platform == 'Salesforce' ? new Map<Id, Environment__c>() : cloneEnvironments();
            cloneProperties(environmentClones);
            cloneConnections(environmentClones);

            return pipeline.Id;
        }

        // PROTECTED

        private void properties() {
            properties = Database.query(byParentIds());
        }

        protected override String byId() {
            return 'SELECT ' + pipelineFields() + ' FROM Deployment_Flow__c WHERE Id = :id WITH SECURITY_ENFORCED';
        }

        protected override String byPipeline() {
            return 'SELECT ' +
                connectionFields() +
                ' FROM Deployment_Flow_Step__c WHERE Deployment_Flow__c = \'' +
                String.escapeSingleQuotes(pipeline.Id) +
                '\' WITH SECURITY_ENFORCED';
        }

        protected override String byIds() {
            return 'SELECT ' + environmentFields() + ' FROM Environment__c WHERE Id IN :environmentIds WITH SECURITY_ENFORCED';
        }

        // PRIVATE

        private void record(RecordData record) {
            this.record = record;
        }

        private String byParentIds() {
            String query =
                'SELECT ' +
                propertyFields() +
                ' FROM System_Property__c WHERE Pipeline__c = \'' +
                String.escapeSingleQuotes(pipeline.Id) +
                '\'';

            if (platform != 'Salesforce') {
                query += ' OR Environment__c IN :environments';
            }
            query += ' WITH SECURITY_ENFORCED';

            return query;
        }

        private String pipelineFields() {
            return String.join(stripSystemFields(Deployment_Flow__c.sObjectType.getDescribe().fields.getMap().keySet()), ',');
        }

        private String connectionFields() {
            return String.join(stripSystemFields(Deployment_Flow_Step__c.sObjectType.getDescribe().fields.getMap().keySet()), ',');
        }

        private String environmentFields() {
            return String.join(stripSystemFields(Environment__c.sObjectType.getDescribe().fields.getMap().keySet()), ',');
        }

        private String propertyFields() {
            return String.join(stripSystemFields(System_Property__c.sObjectType.getDescribe().fields.getMap().keySet()), ',');
        }

        private List<String> stripSystemFields(Set<String> fields) {
            List<String> result = new List<String>();

            for (String field : fields) {
                if (!ClonePipeline.SYSTEM_FIELDS.contains(field)) {
                    result.add(field);
                }
            }

            return result;
        }

        private Deployment_Flow__c clonePipeline() {
            Deployment_Flow__c result = pipeline.clone();

            result.Name = record.pipeline.Name;
            result.Git_Repository__c = record.pipeline.Git_Repository__c;
            result.Main_Branch__c = record.pipeline.Main_Branch__c;
            result.Active__c = false;
            insert result;

            return result;
        }

        private Map<Id, Environment__c> cloneEnvironments() {
            List<Environment__c> records = clonedRecords();

            // StripInaccessible removes the clone source id from the cloned record, so Secure_DML is used instead.
            Utilities.Secure_DML(records, Utilities.DML_Action.INS, SObjectType.Environment__c);

            Map<Id, Environment__c> result = new Map<Id, Environment__c>();
            for (Environment__c clone : records) {
                result.put(clone.getCloneSourceId(), clone);
            }

            return result;
        }

        private List<Environment__c> clonedRecords() {
            List<Environment__c> result = new List<Environment__c>();
            Map<Id, Environment__c> environmentInputs = environmentInputs();

            for (Environment__c environment : environments) {
                Environment__c clone = environment.clone();
                clone.Name = environmentInputs.get(environment.Id)?.Name;
                clone.Org_ID__c = null;
                clone.Latest_Deployment__c = null;
                result.add(clone);
            }

            return result;
        }

        private Map<Id, Environment__c> environmentInputs() {
            Map<Id, Environment__c> result = new Map<Id, Environment__c>();

            if (record.environments != null) {
                for (Environment__c environment : record.environments) {
                    result.put(environment.Id, environment);
                }
            }

            return result;
        }

        private void cloneProperties(Map<Id, Environment__c> environmentClones) {
            List<System_Property__c> result = new List<System_Property__c>();

            for (System_Property__c property : properties) {
                System_Property__c clone = property.clone();
                clone.ParentId__c = null;
                clone.Value__c = null;
                if (String.isNotBlank(clone.Pipeline__c)) {
                    clone.Pipeline__c = pipeline.Id;
                } else if (String.isNotBlank(clone.Environment__c)) {
                    clone.Environment__c = environmentClones.get(property.Environment__c)?.Id;
                }
                result.add(clone);
            }

            insert Security.stripInaccessible(AccessType.CREATABLE, result).getRecords();
        }

        private Map<Id, Deployment_Flow_Step__c> connectionInputs() {
            Map<Id, Deployment_Flow_Step__c> result = new Map<Id, Deployment_Flow_Step__c>();

            if (record.connections != null) {
                result = new Map<Id, Deployment_Flow_Step__c>(record.connections);
            }

            return result;
        }

        private void cloneConnections(Map<Id, Environment__c> environmentClones) {
            List<Deployment_Flow_Step__c> result = new List<Deployment_Flow_Step__c>();

            Map<Id, Deployment_Flow_Step__c> inputs = connectionInputs();
            Map<String, String> branchesByOldName = branchesByOldName(inputs);

            for (Deployment_Flow_Step__c connection : connections) {
                String branch = inputs.get(connection.Id)?.Branch__c;
                String destinationBranch = branchesByOldName.get(connection.Destination_Branch__c);

                Deployment_Flow_Step__c clone = connection.clone();
                clone.Deployment_Flow__c = pipeline.Id;
                clone.Branch__c = branch;
                clone.Destination_Branch__c = String.isBlank(destinationBranch) ? pipeline.Main_Branch__c : destinationBranch;
                clone.Source_Environment__c = environmentClones.get(connection.Source_Environment__c)?.Id;
                clone.Destination_Environment__c = environmentClones.get(connection.Destination_Environment__c)?.Id;
                result.add(clone);
            }

            insert Security.stripInaccessible(AccessType.CREATABLE, result).getRecords();
        }

        private Map<String, String> branchesByOldName(Map<Id, Deployment_Flow_Step__c> inputs) {
            Map<String, String> result = new Map<String, String>();

            for (Deployment_Flow_Step__c connection : connections) {
                result.put(connection.Branch__c, inputs.get(connection.Id)?.Branch__c);
            }

            return result;
        }
    }
}