Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Git_Repository__c.field-meta.xml
<CustomField>
    <fullName>Git_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
    <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
    <label>Git Repository</label>
    <referenceTo>Git_Repository__c</referenceTo>
    <relationshipName>Deployment_Flows</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Git_Repository__c/Git_Repository__c.object-meta.xml
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MultiCloudAutomation__mdt/fields/PackageImportAPIName__c.field-meta.xml
<CustomField>
    <fullName>PackageImportAPIName__c</fullName>
    <label>PackageImportAPIName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MultiCloudAutomation__mdt/fields/PlatformName__c.field-meta.xml
<CustomField>
    <fullName>PlatformName__c</fullName>
    <label>PlatformName</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/PackageImportActionTest.cls
@IsTest
public class PackageImportActionTest {
    @TestSetup
    private static void makeData() {
        new DataHelper().userSetup();
    }

    @IsTest
    private static void multipleRequests() {
        System.runAs(getRunAsUser()) {
            // Setup
            PackageImportAction.Request request = new PackageImportAction.Request();

            try {
                // Exercise
                PackageImportAction.startImport(new List<PackageImportAction.Request>{ request, request });
            }
            catch (Exception ex) {
                // Verify
                System.assertEquals('Only 1 request is available.', ex.getMessage(), 'Multiple requests should be sent.');
            }
        }
    }

    @IsTest
    private static void repositoryNotFound() {
        System.runAs(getRunAsUser()) {
            // Setup
            PackageImportAction.Request request = new PackageImportAction.Request();

            try {
                // Exercise
                PackageImportAction.startImport(new List<PackageImportAction.Request>{ request });
            }
            catch (Exception ex) {
                // Verify
                System.assertEquals('Repository not found.', ex.getMessage(), 'Repository should be blank/invalid.');
            }
        }
    }

    @IsTest
    private static void pipelineNotFound() {
        System.runAs(getRunAsUser()) {
            // Setup
            DataHelper helper = new DataHelper().createRepository();

            PackageImportAction.Request request = new PackageImportAction.Request();
            request.repositoryId = helper.repository.Id;
            request.pipelineId = helper.repository.Id;

            try {
                // Exercise
                PackageImportAction.startImport(new List<PackageImportAction.Request>{ request });
            } catch (Exception ex) {
                // Verify
                System.assertEquals('Pipeline not found.', ex.getMessage(), 'Pipeline should be invalid.');
            }
        }
    }

    @IsTest
    private static void platformNotFound() {
        System.runAs(getRunAsUser()) {
            // Setup
            DataHelper helper = new DataHelper().createRepository();

            PackageImportAction.Request request = new PackageImportAction.Request();
            request.repositoryId = helper.repository.Id;

            try {
                // Exercise
                PackageImportAction.startImport(new List<PackageImportAction.Request>{ request });
            }
            catch (Exception ex) {
                // Verify
                System.assertEquals('Please provide valid pipeline or platform details.', ex.getMessage(), 'Pipeline and platform should be blank.');
            }
        }
    }

    @IsTest
    private static void templateNotFound() {
        System.runAs(getRunAsUser()) {
            // Setup
            DataHelper helper = new DataHelper().createRepository();

            PackageImportAction.Request request = new PackageImportAction.Request();
            request.repositoryId = helper.repository.Id;
            request.platformName = 'Salesforce';

            try {
                // Exercise
                PackageImportAction.startImport(new List<PackageImportAction.Request>{ request });
            }
            catch (Exception ex) {
                // Verify
                System.assertEquals('Template not found.', ex.getMessage(), 'Template should be absent.');
            }
        }
    }

    @IsTest
    private static void startImport() {
        System.runAs(getRunAsUser()) {
            // Setup
            DataHelper helper = new DataHelper()
                                    .createRepository()
                                    .createPipeline()
                                    .createJobTemplate()
                                    .mockDefaultTemplates();

            PackageImportAction.Request request = new PackageImportAction.Request();
            request.repositoryId = helper.repository.Id;
            request.pipelineId = helper.pipeline.Id;

            // Exercise
            List<PackageImportAction.Response> response = PackageImportAction.startImport(new List<PackageImportAction.Request>{ request });

            // Verify
            System.assertEquals(1, response.size(), 'Response should not be empty');
            System.assertNotEquals(null, response.get(0).job, 'Job execution should be started.');
        }
    }

    // Helper

    private class DataHelper {
        private Git_Repository__c repository;
        private Deployment_Flow__c pipeline;
        private JobTemplate__c template;

        private DataHelper createRepository() {
            repository = TestDataFactory.createGitRepository();
            insert repository;

            return this;
        }

        private DataHelper createPipeline() {
            pipeline = TestDataFactory.createDeploymentFlow('Test Pipeline', true, repository.Id, true);
            pipeline.Platform__c = 'Salesforce';
            insert pipeline;

            return this;
        }

        private DataHelper createJobTemplate() {
            template = new JobTemplate__c(Name = 'PackageImportTemplate', Version__c = 1);
            insert template;

            return this;
        }

        private DataHelper mockDefaultTemplates() {
            MultiCloudAutomationsSelector.mock = new Map<String, MultiCloudAutomation__mdt>{
                'Salesforce' => new MultiCloudAutomation__mdt(PlatformName__c = 'Salesforce', PackageImportAPIName__c = 'PackageImportTemplate_1')
            };

            return this;
        }

        private void userSetup() {
            TestUtilities.enableLicenses(2, 2, 2, 2, 2);
            TestDataFactory.createUsers();

            User u = getRunAsUser();
            List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();

            for (PermissionSet ps : [SELECT Id FROM PermissionSet WHERE Name IN ('Copado_User', 'Copado_Job_Engine')]) {
                assignments.add(new PermissionSetAssignment(AssigneeId = u.Id, PermissionSetId = ps.Id));
            }
            insert assignments;

            System.runAs(u) {
                TestUtilities.assignLicense(u.Username, true, true, true, true, true);
            }
        }
    }

    private static User getRunAsUser() {
        return [SELECT Id, Username
                FROM User
                WHERE Profile.Name = 'Standard User' AND Username LIKE '%pstdUser002@amamama.com%'
                LIMIT 1];
    }
}