Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/Deployment_Flow_Step__c.object-meta.xml
<CustomObject>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Pipeline Connections</relationshipLabel>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Destination_Environment__c.field-meta.xml
<CustomField>
    <fullName>Destination_Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Source_Environment__c.field-meta.xml
<CustomField>
    <fullName>Source_Environment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Pipeline.</inlineHelpText>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/Promoted_User_Story__c.object-meta.xml
<CustomObject>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promoted User Stories</relationshipLabel>
    <relationshipName>Promoted_User_Stories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promoted_User_Story__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Promotions</relationshipLabel>
    <relationshipName>Promoted_User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Back_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Back_Promotion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the promotion is from a higher environment to a lower environment in the deployment flow.</description>
    <inlineHelpText>Select this checkbox if you are promoting from a higher to a lower environment in the pipeline.</inlineHelpText>
    <label>Is Back-Promotion</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Destination_Environment__c.field-meta.xml
<CustomField>
    <fullName>Destination_Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Promotions (Destination Environment)</relationshipLabel>
    <relationshipName>Promotions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a project linked to an active pipeline.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will provide the ability to deploy User Stories within a Release.</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Promotion__c/fields/Source_Environment__c.field-meta.xml
<CustomField>
    <fullName>Source_Environment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project where the User Story belongs.</description>
    <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product version or release where this User Story will be released.</description>
    <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/PromotedUserStoriesDatatableController.cls
public with sharing class PromotedUserStoriesDatatableController {

    // PUBLIC

    @AuraEnabled
    public static List<Promoted_User_Story__c> fetchData(String promotionId, String selectFieldSet) {
        try {
            return new PromotedUserStoriesSelector().byPromotionIdWithFields(new Set<Id>{ promotionId }, getProcessedFields(Promoted_User_Story__c.SObjectType, selectFieldSet));
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }

    @AuraEnabled
    public static List<User_Story__c> availableUserStories(String promotionId, String selectFieldSet) {
        List<User_Story__c> userStories = new List<User_Story__c>();
        Promotion__c promotion = promotionDetailsById(promotionId);
        Set<Id> alreadyAddedUserStoryIds = alreadyAddedUserStoryIds(new Set<Id>{ promotion.Id });
        Set<Id> projectIds = new Set<Id>{ promotion.Project__c };
        Set<Id> releaseIds = new Set<Id>{ promotion.Release__c };
        Set<Id> environmentIds = new Set<Id>{ promotion.Source_Environment__c };

        if (!promotion.Back_Promotion__c) {
            for(User_Story__c userStory : new UserStoriesSelector().readyToPromoteWithFields(getProcessedFields(User_Story__c.SObjectType, selectFieldSet), environmentIds, projectIds, releaseIds)) {
                if(!alreadyAddedUserStoryIds.contains(userStory.Id)) {
                    userStories.add(userStory);    
                }
            }
        } else {
            Id pipelineId = null;
            if(promotion.Project__c != null) {
                pipelineId = promotion.Project__r.Deployment_Flow__c;
            } else if(promotion.Release__c != null) {
                pipelineId = promotion.Release__r.Project__r.Deployment_Flow__c;
            }
            List<Deployment_Flow_Step__c> pipelineConnections = new DeploymentFlowStepsSelector().byPipelineAndSourceEnvironment(pipelineId, promotion.Destination_Environment__c);

            Set<Id> userStoryIds = new Set<Id>();
            if (!pipelineConnections.isEmpty()) {
                for (User_Story__c userStory : GlobalUtilities.getUserStoriesFromFieldsetBehind(getProcessedFields(User_Story__c.SObjectType, selectFieldSet), pipelineConnections.get(0))) {
                    userStoryIds.add(userStory.Id);
                }

                for(User_Story__c userStory : new UserStoriesSelector().readyToBackPromoteWithFields(getProcessedFields(User_Story__c.SObjectType, selectFieldSet), userStoryIds)) {
                    if(!alreadyAddedUserStoryIds.contains(userStory.Id) && (promotion.Project__c != null && promotion.Project__c == userStory.Project__c || promotion.Release__c != null && promotion.Release__c == userStory.Release__c)) {
                        userStories.add(userStory);    
                    }
                }
            }
        }

        return userStories;
    }

    @AuraEnabled
    public static void addSelectedUserStoriesToPromotion(String promotionId, List<Id> userStoryIds) {
        try { 
            List<Promotion__c> promotions = new PromotionsSelector().onlyPromotionsDetailByIds(new Set<Id>{ promotionId });
            Promotion__c promotion = promotions.isEmpty() ? new Promotion__c() : promotions[0];
            List<Promoted_User_Story__c> promotedUserStories = new List<Promoted_User_Story__c>();
            List<User_Story__c> userStories = new UserStoriesSelector().byIds(new Set<Id>(userStoryIds));

            for(User_Story__c userStory : userStories) {
                String promotedUserStoryName = promotion.Back_Promotion__c ? 'Back Promoted User Story: ' + userStory.Name : 'Promoted User Story: ' + userStory.Name;
                promotedUserStories.add(new Promoted_User_Story__c(Name = promotedUserStoryName, Promotion__c = promotion.Id, User_Story__c = userStory.Id));
            }

            SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, promotedUserStories);
            insert decision.getRecords();
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }

    @AuraEnabled
    public static void removeSelectedPromotedUserStories(List<Id> promotedUserStoryIds) {
        try {
            if (!promotedUserStoryIds.isEmpty()) {
                List<Promoted_User_Story__c> promotedUserStories = [SELECT Id FROM Promoted_User_Story__c WHERE Id IN :promotedUserStoryIds WITH SECURITY_ENFORCED];
                Utilities.Secure_DML(promotedUserStories, Utilities.DML_Action.DEL, Schema.SObjectType.Promoted_User_Story__c);
            }
        } catch (Exception e) {
            throw new ApplicationException().auraHandled(e);
        }
    }


    // PRIVATE 

    private static Promotion__c promotionDetailsById(Id promotionId) {
        List<Promotion__c> promotions = new PromotionsSelector().onlyPromotionsDetailByIds(new Set<Id>{ promotionId });
        return promotions.isEmpty() ? new Promotion__c() : promotions[0];
    }

    private static Set<Id> alreadyAddedUserStoryIds(Set<Id> promotionIds) {
        Set<Id> result = new Set<Id>();
        for(Promoted_User_Story__c promotedUserStories : new PromotedUserStoriesSelector().byPromotionId(promotionIds)) {
            result.add(promotedUserStories.User_Story__c);
        }
        return result;
    }

    private static Set<String> getProcessedFields(SObjectType objectType, String fieldSet) {
        Set<String> result = new Set<String>();
        for (FieldSetMember field : getFieldSetFields(objectType, fieldSet)) {
            String fieldToAdd = field.getFieldPath();
            if (field.getType() == DisplayType.REFERENCE ) {
                if (field.getFieldPath().endsWith('__c')) {
                    fieldToAdd = field.getFieldPath().replace('__c', '__r.Name');
                } else if (field.getFieldPath().endsWith('Id')) {
                    // Trick to no to replace other possible appearances of 'Id' in the field name
                    fieldToAdd = field.getFieldPath() + '__';
                    fieldToAdd = fieldToAdd.replace('Id__', '.Name');
                }
            }
            result.add(fieldToAdd);
        }
        return result;
    }

    private static List<FieldSetMember> getFieldSetFields(SObjectType objectType, String fieldSet) {
        return fflib_SObjectDescribe.getDescribe(objectType).getFieldSets().get(fieldSet).getFields();
    }
}