Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, all Branch Management features will be enabled in the Deployment Flow.</description>
    <inlineHelpText>If checked, all Branch Management features will be enabled in the Deployment Flow.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Calculate_Based_on__c.field-meta.xml
<CustomField>
    <fullName>Calculate_Based_on__c</fullName>
    <inlineHelpText>If Branch is selected, Branch Management page will work as before, if User Story selected, calculation and result will be based on User Stories.</inlineHelpText>
    <label>Calculate Based on</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>User Story</fullName>
                <default>true</default>
                <label>User Story</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/Deployment_Flow_Step__c.object-meta.xml
<CustomObject>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <inlineHelpText>Git branch linked to the source environment.</inlineHelpText>
    <label>Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Pipeline Connections</relationshipLabel>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Destination_Environment__c.field-meta.xml
<CustomField>
    <fullName>Destination_Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps1</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow_Step__c/fields/Source_Environment__c.field-meta.xml
<CustomField>
    <fullName>Source_Environment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipName>Deployment_Flow_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Pipeline.</inlineHelpText>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
    <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Org_Credential__c.field-meta.xml
<CustomField>
    <fullName>Org_Credential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
    <inlineHelpText>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
    <label>Credential</label>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>User Stories (Credential)</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project where the User Story belongs.</description>
    <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/Test_WorkSetService.cls
@IsTest
private class Test_WorkSetService {

    @TestSetup
    private static void setUpData() {
        List<User> users = TestDataFactory.createUsers();

        TestUtilities.enableLicenses(2, 2, 2, 2, 2);
        FeatureManagement.setPackageIntegerValue('CBM_Branches', 1);
        FeatureManagement.setPackageIntegerValue('CCM_Licenses_Enabled', 2);
        FeatureManagement.setPackageIntegerValue('EE_Licenses_Enabled', 2);

        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Copado_User'];
        insert new PermissionSetAssignment(AssigneeId = users[0].Id, PermissionSetId = ps.Id);
    }


    @IsTest
    private static void workSetWithInvalidFilterCriteria() {
        User u = [SELECT Id, Username FROM User WHERE Email = 'test1@test1.com'];
        TestUtilities.assignLicense(String.valueOf(u.Username), true, true, true, true, true);

        System.runAs(u) {
            WorkSetService.Request request = new WorkSetService.Request();
            request.criteria = 'Id';
            request.value = UserInfo.getOrganizationId();

            CliProxy.CLIWrapper reqBody = new CliProxy.CLIWrapper();
            reqBody.mainService = 'work';
            reqBody.subService = 'set';
            reqBody.body = JSON.serialize(request);

            RestContext.request = Test_CliProxy.commonRequest(JSON.serialize(reqBody));

            Test.startTest();
            String response = CliProxy.doPost();
            Test.stopTest();

            WorkSetService.Response resp = (WorkSetService.Response) JSON.deserialize(response, WorkSetService.Response.class);
            String expectedMessage = String.format(Label.NoUserStoryFound, new List<String> { 'Id', UserInfo.getOrganizationId()});

            System.assertEquals(expectedMessage, resp.message);
            System.assertEquals(CliSfDataWrapper.StatusResult.ERROR.name(), resp.status);
        }
    }


    @IsTest
    private static void workSetSearchUS() {
        User u = [SELECT Id,Username FROM User WHERE Email = 'test1@test1.com'];
        TestUtilities.assignLicense(String.valueOf(u.Username), true, true, true, true, true);

        System.runAs(u) {
            List<Environment__c> environments = new List<Environment__c> {
                new Environment__c(Name = 'Environment 1'),
                new Environment__c(Name = 'Environment 2')
            };

            insert environments;

            Deployment_Flow__c pipeline = new Deployment_Flow__c();
            pipeline.Name = 'MyPipeline';
            pipeline.Active__c = true;
            pipeline.Calculate_Based_on__c = 'User Story';
            insert pipeline;

            Deployment_Flow_Step__c connection = new Deployment_Flow_Step__c();
            connection.Deployment_Flow__c = pipeline.Id;
            connection.Branch__c = 'env1';
            connection.Source_Environment__c = environments[0].Id;
            connection.Destination_Environment__c = environments[1].Id;
            insert connection;

            Project__c prj = new Project__c();
            prj.Name = 'My Project';
            prj.Deployment_Flow__c = pipeline.Id;
            insert prj;

            User_Story__c us = new User_Story__c();
            us.Environment__c = environments[0].Id;
            us.Project__c = prj.Id;
            insert us;
            us = [SELECT Id, Name, Environment__c, Project__c FROM User_Story__c WHERE Id = :us.Id];

            mockRequest('Id', us.Id);

            Test.startTest();
            String response = CliProxy.doPost();
            Test.stopTest();

            WorkSetService.Response resp = (WorkSetService.Response) JSON.deserialize(response, WorkSetService.Response.class);

            System.assertEquals(CliSfDataWrapper.StatusResult.OK.name(), resp.status);

            System.assertEquals(null, resp.message);
            System.assertEquals('env1', resp.environmentBranch);

            System.assertEquals(us.Name, resp.userStory.Name);
            System.assertEquals(us.Environment__c, resp.userStory.Environment__c);
            System.assertEquals(us.Project__c, resp.userStory.Project__c);
        }
    }


    @IsTest
    private static void workSetWithInvalidCredential() {
        User u = [SELECT Id,Username FROM User WHERE Email = 'test1@test1.com'];
        TestUtilities.assignLicense(String.valueOf(u.Username), true, true, true, true, true);

        System.runAs(u) {
            User_Story__c us = new User_Story__c();
            insert us;
            us = [SELECT Id, Name, Environment__c, Project__c FROM User_Story__c WHERE Id = :us.Id];

            mockRequest('Id', us.Id, 'Invalid Credential');

            Test.startTest();
            String response = CliProxy.doPost();
            Test.stopTest();

            WorkSetService.Response resp = (WorkSetService.Response) JSON.deserialize(response, WorkSetService.Response.class);

            System.assertEquals(Label.InvalidOrgCredential, resp.message);
            System.assertEquals(CliSfDataWrapper.StatusResult.ERROR.name(), resp.status);
        }
    }


    @IsTest
    private static void workSetWithCredential() {
        User u = [SELECT Id,Username FROM User WHERE Email = 'test1@test1.com'];
        TestUtilities.assignLicense(String.valueOf(u.Username), true, true, true, true, true);

        System.runAs(u) {
            List<Environment__c> environments = new List<Environment__c> {
                new Environment__c(Name = 'Environment 1'),
                new Environment__c(Name = 'Environment 2')
            };

            insert environments;

            Org__c credential = new Org__c();
            credential.Name = 'Credential 1';
            credential.Environment__c = environments[0].Id;
            insert credential;

            Deployment_Flow__c pipeline = new Deployment_Flow__c();
            pipeline.Name = 'MyPipeline';
            pipeline.Active__c = true;
            pipeline.Calculate_Based_on__c = 'User Story';
            insert pipeline;

            Deployment_Flow_Step__c connection = new Deployment_Flow_Step__c();
            connection.Deployment_Flow__c = pipeline.Id;
            connection.Branch__c = 'env1';
            connection.Source_Environment__c = environments[0].Id;
            connection.Destination_Environment__c = environments[1].Id;
            insert connection;

            Project__c prj = new Project__c();
            prj.Name = 'My Project';
            prj.Deployment_Flow__c = pipeline.Id;
            insert prj;

            User_Story__c us = new User_Story__c();
            us.Project__c = prj.Id;
            insert us;
            us = [SELECT Id, Name, Environment__c, Project__c FROM User_Story__c WHERE Id = :us.Id];

            mockRequest('Id', us.Id, credential.Name);

            Test.startTest();
            String response = CliProxy.doPost();
            Test.stopTest();

            WorkSetService.Response resp = (WorkSetService.Response) JSON.deserialize(response, WorkSetService.Response.class);

            System.assertEquals(CliSfDataWrapper.StatusResult.OK.name(), resp.status);

            System.assertEquals(null, resp.message);
            System.assertEquals('env1', resp.environmentBranch);

            System.assertEquals(us.Name, resp.userStory.Name);
            System.assertEquals(credential.Id, resp.userStory.Org_Credential__c);
        }
    }


    @IsTest
    private static void workSetUsWithoutEnvironment() {
        User u = [SELECT Id,Username FROM User WHERE Email = 'test1@test1.com'];
        TestUtilities.assignLicense(String.valueOf(u.Username), true, true, true, true, true);

        System.runAs(u) {
            User_Story__c userStory = new User_Story__c();
            insert userStory;
            mockRequest('Id', userStory.Id);

            Test.startTest();
            String response = CliProxy.doPost();
            Test.stopTest();

            CliSfDataWrapper resp = (CliSfDataWrapper) JSON.deserialize(response, CliSfDataWrapper.class);

            System.assertEquals(CliSfDataWrapper.StatusResult.ERROR.name(), resp.status);
            System.assertEquals(Label.Org_Credential_Not_Included_In_Deployment_Flow, resp.message);
        }
    }


    // PRIVATE
    private static void mockRequest(String name, String value) {
        String credentialName = null;
        mockRequest(name, value, credentialName);
    }

    private static void mockRequest(String name, String value, String credentialName) {
        WorkSetService.Request wrks = new WorkSetService.Request();
        wrks.value = value;
        wrks.criteria = name;
        wrks.credentialName = credentialName;

        CliProxy.CLIWrapper reqBody = new CliProxy.CLIWrapper();
        reqBody.mainService = 'work';
        reqBody.subService = 'set';
        reqBody.body = JSON.serialize(wrks);

        RestContext.request = Test_CliProxy.commonRequest(JSON.serialize(reqBody));
    }
}