Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, all Branch Management features will be enabled in the Deployment Flow.</description>
    <inlineHelpText>If checked, all Branch Management features will be enabled in the Deployment Flow.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Block_Commits__c.field-meta.xml
<CustomField>
    <fullName>Block_Commits__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, committing changes on user stories linked to this Pipeline will not be allowed</description>
    <inlineHelpText>If checked, committing changes on user stories linked to this Pipeline will not be allowed</inlineHelpText>
    <label>Block Commits</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/CommitJobTemplate__c.field-meta.xml
<CustomField>
    <fullName>CommitJobTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select the Job Template that implements the commit action for this Pipeline</description>
    <inlineHelpText>Select the Job Template that implements the commit action for this Pipeline</inlineHelpText>
    <label>Commit Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Pipelines (Commit Job Template)</relationshipLabel>
    <relationshipName>Pipelines2</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/CommitJobTemplateOverride__c.field-meta.xml
<CustomField>
    <fullName>CommitJobTemplateOverride__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select a Job Template to override the default Commit Job Template defined in the Pipeline</description>
    <inlineHelpText>Select a Job Template to override the default Commit Job Template defined in the Pipeline</inlineHelpText>
    <label>Commit Job Template Override</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Environments (Commit Job Template Override)</relationshipLabel>
    <relationshipName>Environments2</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Git_Commit__c/Git_Commit__c.object-meta.xml
<CustomObject>
    <label>Git Commit</label>
    <nameField>
        <displayFormat>Commit-{0000}</displayFormat>
        <label>Git Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Git Commits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Git_Commit__c/fields/Commit_Date__c.field-meta.xml
<CustomField>
    <fullName>Commit_Date__c</fullName>
    <label>Commit Date</label>
    <type>Date</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Git_Org_Commit__c/Git_Org_Commit__c.object-meta.xml
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Git_Org_Commit__c/fields/Commit_Date__c.field-meta.xml
<CustomField>
    <fullName>Commit_Date__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Commit Date</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/DataJson__c.field-meta.xml
<CustomField>
    <fullName>DataJson__c</fullName>
    <label>DataJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Validated_Date__c.field-meta.xml
<CustomField>
    <fullName>Validated_Date__c</fullName>
    <description>Latest OAuth authentication validation date.</description>
    <inlineHelpText>Latest OAuth authentication validation date.</inlineHelpText>
    <label>Validated Date</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Pipeline.</inlineHelpText>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
    <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Latest_Commit_Date__c.field-meta.xml
<CustomField>
    <fullName>Latest_Commit_Date__c</fullName>
    <label>Latest Commit Date</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Org_Credential__c.field-meta.xml
<CustomField>
    <fullName>Org_Credential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
    <inlineHelpText>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
    <label>Credential</label>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>User Stories (Credential)</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project where the User Story belongs.</description>
    <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Commit__c/User_Story_Commit__c.object-meta.xml
<CustomObject>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Commit__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Commits</relationshipLabel>
    <relationshipName>User_Story_Commits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/User_Story_Metadata__c.object-meta.xml
<CustomObject>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Action to be performed with the current metadata when committing</description>
    <inlineHelpText>Action to be performed with the current metadata when committing</inlineHelpText>
    <label>Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Represents a grouping of metadata, i.e. vlocity, cpq</description>
    <inlineHelpText>Represents a grouping of metadata, i.e. vlocity, cpq</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/ModuleDirectory__c.field-meta.xml
<CustomField>
    <fullName>ModuleDirectory__c</fullName>
    <description>Folder where the metadata is allocated</description>
    <inlineHelpText>Folder where the metadata is allocated</inlineHelpText>
    <label>Directory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story_Metadata__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Metadata</relationshipLabel>
    <relationshipName>User_Story_Metadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/CommitAction.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class CommitAction implements JobExecutionCallback {
    @InvocableMethod(label='Commit changes' description='Commit your changes' category='Copado Multi-Cloud')
    global static List<Response> commitChanges(List<Request> requests) {
        if (requests.size() > 1) {
            throw new ApplicationException(Label.OnlyOneRequestAvailable);
        }

        // TODO: Query for job execution with parent US and status in progress. If exists, do not continue and throw exception

        // No need of bulkification right now, so keep it simple
        Request request = requests[0];

        if (request.changes.isEmpty()) {
            throw new ApplicationException(Label.ThereShouldBeAtLeastOneChangeToCommit);
        }

        User_Story__c userStory = new UserStoriesSelector().byIdsForMulticloud(new Set<Id>{ request.userStoryId })[0];

        // So far, this checks were taking place on page load
        validateCommitRequirements(userStory);

        if (request.recreateFeatureBranch) {
            deletePreviousUserStoryMetadata(userStory);
        }

        saveChangesAsUserStoryMetadata(request, userStory);

        CreateExecutionRequestData data = new CreateExecutionRequestData(userStory, request).createCommitRecords();

        List<Response> result = new List<Response>();
        if (request.executeCommit) {
            result.add(new Response(executeCommitJobTemplate(request, data, userStory)));
        }
        return result;
    }

    // Job Callback, called only after the job finishes
    global void execute(JobExecution__c job, String status) {
        // TODO: result handling

        job = [SELECT DataJson__c FROM JobExecution__c WHERE Id = :job.Id];
        CreateExecutionRequestData data = (CreateExecutionRequestData) JSON.deserialize(job.DataJson__c, CreateExecutionRequestData.class);

        User_Story__c userStory = new UserStoriesSelector(false, false).byId(new Set<Id>{ data.userStoryId })[0];
        userStory.Latest_Commit_Date__c = System.now();

        // Note: False positive, checked permissions before in this method
        update userStory;

        // TODO: maybe delete file used by job execution? not for now, but likely later
    }

    // PRIVATE

    private static void validateCommitRequirements(User_Story__c userStory) {
        List<String> commitUnavailabilityReasons = getCommitUnavailabilityReasons(userStory);

        if (!commitUnavailabilityReasons.isEmpty()) {
            throw new ApplicationException(
                String.format(Label.CanNotPerformThisAction, new List<Object>{ String.join(commitUnavailabilityReasons, ', ') })
            );
        }
    }

    private static List<String> getCommitUnavailabilityReasons(User_Story__c userStory) {
        List<String> result = new List<String>();

        result.addAll(hasRequiredLicenses());
        result.addAll(hasSobjectPermissions());
        result.addAll(userStoryIsValid(userStory));
        result.addAll(pipelineIsValid(userStory));

        return result;
    }

    private static List<String> hasRequiredLicenses() {
        List<String> result = new List<String>();

        if (LicenseHelper.isLicensesExceeded()) {
            result.add(Label.LICENSES_EXCEEDED);
        }

        if (!LicenseHelper.actionIsLicenseEnabled('commitFiles')) {
            result.add(Label.CCM_License_Restriction);
        }

        if (!FeatureHelper.isChangeChangeManagementEnabled()) {
            result.add(Label.FEATURE_NOT_SUPPORTED);
        }

        return result;
    }

    private static List<String> hasSobjectPermissions() {
        List<String> result = new List<String>();

        if (!Schema.SObjectType.User_Story__c.isUpdateable()) {
            result.add(Label.Insufficient_Access_Rights + ' ' + Label.Related_Object + ' ' + Schema.SObjectType.User_Story__c.Label);
        }

        if (!Schema.SObjectType.Deployment_Flow__c.isAccessible()) {
            result.add(Label.MISSING_PERMISSIONS_CBM_FLOW);
        }

        if (
            !Schema.SObjectType.User_Story_Metadata__c.isCreateable() ||
            !Schema.SObjectType.User_Story_Metadata__c.isUpdateable() ||
            !Schema.SObjectType.User_Story_Metadata__c.isDeletable()
        ) {
            result.add(Label.Insufficient_Access_Rights + ' ' + Label.Related_Object + ' ' + Schema.SObjectType.User_Story_Metadata__c.Label);
        }

        if (!Schema.SObjectType.Git_Commit__c.isCreateable()) {
            result.add(Label.Insufficient_Access_Rights + ' ' + Label.Related_Object + ' ' + Schema.SObjectType.Git_Commit__c.Label);
        }

        if (!Schema.SObjectType.Git_Org_Commit__c.isCreateable()) {
            result.add(Label.Insufficient_Access_Rights + ' ' + Label.Related_Object + ' ' + Schema.SObjectType.Git_Org_Commit__c.Label);
        }

        if (!Schema.SObjectType.User_Story_Commit__c.isCreateable()) {
            result.add(Label.Insufficient_Access_Rights + ' ' + Label.Related_Object + ' ' + Schema.SObjectType.User_Story_Commit__c.Label);
        }

        return result;
    }

    private static List<String> userStoryIsValid(User_Story__c userStory) {
        List<String> result = new List<String>();

        if (String.isBlank(userStory.Project__c)) {
            result.add(Label.UserStoryWithoutProject);
        }

        if (String.isBlank(userStory.Environment__c)) {
            result.add(Label.USER_STORY_COMMIT_NO_ENVIRONMENT);
        }

        if (userStory.Org_Credential__r.Validated_Date__c == null) {
            result.add(Label.Org_Is_Not_Valid);
        }

        result.addAll(hasEditAccesOnCredential(userStory));

        return result;
    }

    private static List<String> hasEditAccesOnCredential(User_Story__c userStory) {
        List<String> result = new List<String>();

        List<UserRecordAccess> credentialAccess = [
            SELECT RecordId, HasEditAccess
            FROM UserRecordAccess
            WHERE UserId = :UserInfo.getUserId() AND RecordId = :userStory.Org_Credential__c
        ];

        if (!credentialAccess.isEmpty() && !credentialAccess[0].HasEditAccess) {
            result.add(Label.Read_Write_Access_Missing);
        }

        return result;
    }

    private static List<String> pipelineIsValid(User_Story__c userStory) {
        List<String> result = new List<String>();
        GlobalUtilities.deploymentFlowDetails flowDetails = GlobalUtilities.getUserStoryDeploymentFlowDetails(userStory.Id, '');

        if (flowDetails.flow == null || !flowDetails.flow.Active__c) {
            result.add(Label.PROMOTION_FLOW_INACTIVE);
        }

        if (flowDetails.flow != null && flowDetails.flow.Block_Commits__c) {
            result.add(Label.DEPLOYMENT_FLOW_COMMITS_BLOCKED);
        }

        return result;
    }

    private static void deletePreviousUserStoryMetadata(User_Story__c userStory) {
        delete new UserStoriesMetadataSelector().byUserStoryId(new Set<Id>{ userStory.Id });
    }

    private static void saveChangesAsUserStoryMetadata(Request request, User_Story__c userStory) {
        List<User_Story_Metadata__c> changes = new List<User_Story_Metadata__c>();
        for (Change change : request.changes) {
            changes.add(change.toUserStoryMetadata(userStory));
        }

        // Note: False positive, checked permissions before
        upsert changes Unique_ID__c; // NOPMD
    }

    private static JobExecution__c executeCommitJobTemplate(Request request, CreateExecutionRequestData data, User_Story__c userStory) {
        Id contentVersionId = upsertFile(userStory.Id, 'Copado Commit changes.json', JSON.serialize(request.changes, true));
        data.fileWithSelectedChanges(contentVersionId);

        CreateExecution.Request jobRequest = createJobRequest(data, userStory);

        return executeJob(jobRequest);
    }

    // Note: this is the File that the Job will read if/when executed, avoiding the need of any Flow to gather the information
    private static Id upsertFile(Id parentId, String name, String content) {
        deleteExistingFile(parentId);

        return createVersionWithLink(name, content, parentId);
    }

    private static void deleteExistingFile(Id parentId) {
        Set<Id> contentDocumentIds = new Set<Id>();

        for (ContentDocumentLink cdl : new ContentDocumentLinksSelector().byLinkedEntityId(new Set<Id>{ parentId })) {
            contentDocumentIds.add(cdl.ContentDocumentId);
        }

        // Note: False positive since it is file
        delete new ContentDocumentsSelector().byId(contentDocumentIds);
    }

    private static Id createVersionWithLink(String name, String content, Id parentId) {
        ContentVersion cv = new ContentVersion(Title = name, PathOnClient = name, VersionData = Blob.valueOf(content), ContentLocation = 'S');
        // Note: False positive since it is file
        insert cv; // NOPMD

        Id contentDocumentId = new ContentVersionsSelector().byId(new Set<Id>{ cv.Id })[0].ContentDocumentId;

        // Note: False positive since it is file
        insert new ContentDocumentLink(LinkedEntityId = parentId, ContentDocumentId = contentDocumentId, shareType = 'V'); // NOPMD

        return cv.Id;
    }

    private static CreateExecution.Request createJobRequest(CreateExecutionRequestData data, User_Story__c userStory) {
        CreateExecution.Request result = new CreateExecution.Request();
        result.runAfterInstantiation = true;
        result.parentId = data.userStoryCommitId();
        result.pipelineId = userStory.Project__r.Deployment_Flow__c;
        result.templateName = getTemplateName(userStory);
        result.callback = CommitAction.class.getName();
        result.dataJson = JSON.serializePretty(data, true);
        result.sourceId = userStory.Environment__c;

        return result;
    }

    private static String getTemplateName(User_Story__c userStory) {
        String result;

        if (String.isNotBlank(userStory.Environment__r?.CommitJobTemplateOverride__r?.ApiName__c)) {
            result = userStory.Environment__r.CommitJobTemplateOverride__r.ApiName__c;
        } else if (String.isNotBlank(userStory.Project__r?.Deployment_Flow__r?.CommitJobTemplate__r?.ApiName__c)) {
            result = userStory.Project__r.Deployment_Flow__r.CommitJobTemplate__r.ApiName__c;
        } else {
            throw new ApplicationException(Label.TemplateIsMissing);
        }

        return result;
    }

    private static JobExecution__c executeJob(CreateExecution.Request jobRequest) {
        return CreateExecution.execute(new List<CreateExecution.Request>{ jobRequest })[0];
    }

    // INNER

    global with sharing class Request {
        @InvocableVariable(label='User Story Id' description='Commit your changes' required=true)
        global Id userStoryId;

        @InvocableVariable(label='Changes' description='List of changes to commit')
        global List<Change> changes = new List<Change>();

        @InvocableVariable(
            label='Recreate feature branch'
            description='If specified, previous branch and User Story Metadata records previously commited will be deleted. Defaults to false'
        )
        global Boolean recreateFeatureBranch = false;

        @InvocableVariable(
            label='Execute commit'
            description='If set to false, actual commit behaviour will be skipped and only operations in Copado will happen. Likely specified to false when commiting from CLI. Defaults to true'
        )
        global Boolean executeCommit = true;

        @InvocableVariable(
            label='Base branch'
            description='Base branch for the commit. If not provided, a default value is calculated based on User Story, Release, or Pipeline'
        )
        global String baseBranch; // optional, default value calculated

        @InvocableVariable(
            label='Message'
            description='Commit message. If not provided, a default value is calculated based on User Story Name and Title'
        )
        global String message; // optional, default value calculated

        @InvocableVariable(label='JSON Information' description='Additional commit information in JSON format')
        global String jsonInformation; // optional

        @InvocableVariable(label='Commit Id' description='Id of an existing git commit with the changes. Likely specified when commiting from CLI')
        global String commitId; // optional, CLI specific
    }

    // Note: names are short to reduce memory/heap/transmission sizes
    global with sharing class Change {
        global String a; // "action" add, delete, ret-only, full pps, ...
        global String c; // "category": copadodx, vlocity, cpq, ...
        global String m; // "module directory" e.g. force-app/main/default
        global String n; // "name"
        global String t; // "type"
        global String j; // "json additional information"

        // PRIVATE OUTTER

        private User_Story_Metadata__c toUserStoryMetadata(User_Story__c userStory) {
            String metadataApiName = t + '.' + n;
            String uniqueId = uniqueId(userStory.Id);

            return new User_Story_Metadata__c(
                Action__c = a,
                Category__c = c,
                ModuleDirectory__c = m,
                Type__c = t,
                JsonInformation__c = j,
                User_Story__c = userStory.Id,
                Metadata_API_Name__c = n, // Create Name__c later if needed
                Name = (userStory.Name + ' ' + a + ' ' + metadataApiName).left(80),
                Last_Commit_Date__c = System.now(), // needed?
                Unique_ID__c = uniqueId
            );
        }

        // PRIVATE INNER

        private String uniqueId(String userStoryId) {
            String result = userStoryId + ';' + m + ';' + t + ';' + n;
            return getEncodedUniqueIdWhenNeeded(result);
        }

        // Note: Encoding is skipped when not needed due to CPU performance and readability purposes
        private String getEncodedUniqueIdWhenNeeded(String uniqueId) {
            if (uniqueId.length() > 255) {
                uniqueId = EncodingUtil.convertToHex(Crypto.generateDigest('MD5', Blob.valueOf(uniqueId)));
            }
            return uniqueId;
        }
    }

    global with sharing class Response {
        @InvocableVariable(label='Commit changes' description='Commit your changes' required=true)
        global JobExecution__c jobExecution;

        // @InvocableVariable
        // global User_Story_Commit__c userStorycommit;

        // CTOR OUTTER

        private Response(JobExecution__c jobExecution) {
            this.jobExecution = jobExecution;
        }
    }

    private with sharing class CreateExecutionRequestData {
        // Shared variables with Request
        private Id userStoryId;
        private boolean recreateFeatureBranch = false;
        private String baseBranch;
        private String message;
        private String jsonInformation;
        private String commitId;

        // Only used by the Job execution
        private String featureBranchName;
        private Id sourceCredentialId;
        private Id orgCommitId;
        private Id userStoryCommitId;
        private Id fileWithSelectedChanges;

        // CTOR OUTTER

        private CreateExecutionRequestData(User_Story__c userStory, Request request) {
            userStoryId = userStory.Id;
            featureBranchName = 'feature/' + userStory.Name;
            sourceCredentialId = userStory.Org_Credential__c;
            setMessage(request.message, userStory);
            setBaseBranch(request.baseBranch, userStory);
        }

        // PRIVATE OUTTER

        private CreateExecutionRequestData createCommitRecords() {
            Git_Org_Commit__c orgCommit = new Git_Org_Commit__c(
                Commit_Date__c = datetime.now(),
                Commit_Message__c = message.left(255),
                Org__c = sourceCredentialId,
                Status__c = 'Pending'
            );
            // Note: False positive, checked permissions before
            insert orgCommit; // NOPMD
            orgCommitId = orgCommit.Id;

            User_Story_Commit__c userStoryCommit = new User_Story_Commit__c(
                Snapshot_Commit__c = orgCommit.Id,
                User_Story__c = userStoryId,
                Name = message.left(80)
            );
            // Note: False positive, checked permissions before
            insert userStoryCommit; // NOPMD
            userStoryCommitId = userStoryCommit.Id;

            return this;
        }

        private void fileWithSelectedChanges(Id contentVersionId) {
            fileWithSelectedChanges = contentVersionId;
        }

        private Id userStoryCommitId() {
            return userStoryCommitId;
        }

        // PRIVATE INNER

        private void setMessage(String message, User_Story__c userStory) {
            if (String.isNotBlank(message)) {
                this.message = message;
            } else {
                this.message = String.format('[{0}] {1}', new List<Object>{ userStory.Name, userStory.User_Story_Title__c });
            }
        }

        private void setBaseBranch(String branchName, User_Story__c userStory) {
            if (String.isNotBlank(branchName)) {
                baseBranch = branchName;
            } else if (String.isNotBlank(userStory.Base_Branch__c)) {
                baseBranch = userStory.Base_Branch__c;
            } else if (String.isNotBlank(userStory.Release__r.Base_Branch__c)) {
                baseBranch = userStory.Release__r.Base_Branch__c;
            } else if (String.isNotBlank(userStory.Project__r.Deployment_Flow__r.Main_Branch__c)) {
                baseBranch = userStory.Project__r.Deployment_Flow__r.Main_Branch__c;
            } else {
                baseBranch = '';
            }
        }
    }
}