Dummy_Package_for_scratch_org/main/default/objects/Copado_Protected_Settiing__mdt/Copado_Protected_Settiing__mdt.object-meta.xml
<CustomObject>
    <label>Copado Protected Settiing</label>
    <pluralLabel>Copado Protected Settings</pluralLabel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Copado_Protected_Settiing__mdt/fields/Text_Field__c.field-meta.xml
<CustomField>
    <fullName>Text_Field__c</fullName>
    <label>Text Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/Deployment_Job__c.object-meta.xml
<CustomObject>
    <label>Deployment Job</label>
    <nameField>
        <displayFormat>DJ-{00000}</displayFormat>
        <label>Deployment Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/fields/Destination_Id__c.field-meta.xml
<CustomField>
    <fullName>Destination_Id__c</fullName>
    <description>Read only field used internally for system property replacement.</description>
    <formula>CASESAFEID(Destination_Org__r.To_Org__r.Environment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Read only field used internally for system property replacement.</inlineHelpText>
    <label>Destination Id</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <description>Read only field used internally for system property replacement.</description>
    <formula>CASESAFEID(Step__r.Deployment__r.From_Org__r.Environment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Read only field used internally for system property replacement.</inlineHelpText>
    <label>Source Id</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Job__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <referenceTo>Step__c</referenceTo>
    <relationshipLabel>Deployment Jobs</relationshipLabel>
    <relationshipName>Deployment_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&quot;Salesforce&quot;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Destination_Id__c.field-meta.xml
<CustomField>
    <fullName>Destination_Id__c</fullName>
    <formula>CASESAFEID(JobExecution__r.Destination__c)</formula>
    <label>Destination Id</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Parent_Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Owner_Id__c</fullName>
    <formula>IF(NOT(ISBLANK( JobExecution__r.Deployment__c )), JobExecution__r.Deployment__r.Promotion__r.OwnerId,
    IF(NOT(ISBLANK( JobExecution__r.Promotion__c )), JobExecution__r.Promotion__r.OwnerId, OwnerId))</formula>
    <label>Parent Owner Id</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <formula>CASESAFEID(JobExecution__r.Source__c)</formula>
    <label>Source Id</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Default_Credential__c.field-meta.xml
<CustomField>
    <fullName>Default_Credential__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this will be the preferred credential for Promotion deployments</inlineHelpText>
    <label>Default Credential</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Developer_Hub_Org__c.field-meta.xml
<CustomField>
    <fullName>Developer_Hub_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Developer Hub Credential</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Org__c.is_Developer_Hub_Org__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <formula>TEXT(Environment__r.Platform__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Platform</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Step__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/CredentialExpression.cls
@SuppressWarnings('PMD.CyclomaticComplexity')
public inherited sharing class CredentialExpression extends DynamicExpression {
    private static final Boolean AUTOMATED_PROCESS = UserInfo.getUserType() == 'AutomatedProcess';

    private static final String CONTEXT_REGEX1 = '(?i)\\{\\$?Context.Credential.(Endpoint|SessionId)\\}';
    private static final String CONTEXT_REGEX2 = '(?i)\\{\\$?(Source|Destination).Credential.(Endpoint|SessionId)\\}';

    private static final Pattern CONTEXT_PATTERN1 = Pattern.compile(CONTEXT_REGEX1);
    private static final Pattern CONTEXT_PATTERN2 = Pattern.compile(CONTEXT_REGEX2);

    private SObject record;
    private String objectName;
    private Map<Id, Org__c> credentialByEnvironment = new Map<Id, Org__c>();

    // CONSTRUCTOR

    public CredentialExpression(String contextId) {
        this.contextId = contextId;
    }

    // PUBLIC

    public override Boolean matches(Parameter parameter) {
        return (CONTEXT_PATTERN1.matcher(parameter.value).matches() || CONTEXT_PATTERN2.matcher(parameter.value).matches());
    }

    public override void prepare() {
        objectName = objectName(recordId());

        if (String.isNotBlank(objectName) && objectName.equalsIgnoreCase('Deployment_Job__c')) {
            record = [SELECT Source_Id__c, Destination_Id__c FROM Deployment_Job__c WHERE Id = :contextId WITH SECURITY_ENFORCED];
        } else if (String.isNotBlank(objectName) && objectName.equalsIgnoreCase('JobStep__c')) {
            record = [SELECT Source_Id__c, Destination_Id__c FROM JobStep__c WHERE Id = :contextId WITH SECURITY_ENFORCED];
        }

        credentialByEnvironment = credentialByEnvironment();

        assertRecordIdExpression();
    }

    public override void parse(Parameter parameter) {
        Matcher contextMatcher1 = CONTEXT_PATTERN1.matcher(parameter.value);
        Matcher contextMatcher2 = CONTEXT_PATTERN2.matcher(parameter.value);
        String value = null;

        if (contextMatcher1.matches()) {
            WebhookCallout.Credential credential = getCredential(contextId);
            String propertyName = contextMatcher1.group(1);

            value = propertyName.equalsIgnoreCase('Endpoint') ? credential.endPoint : credential.sessionId;
        } else if (contextMatcher2.matches()) {
            String orgType = contextMatcher2.group(1);
            String propertyName = contextMatcher2.group(2);

            Id environmentId = orgType == 'Source' ? getSourceId() : getDestinationId();

            WebhookCallout.Credential credential = getCredential(environmentId);

            value = propertyName.equalsIgnoreCase('Endpoint') ? credential.endPoint : credential.sessionId;
        }

        parameter.value = value;
        parameter.sensitive = true;
    }

    // PRIVATE

    private Id recordId() {
        try {
            return Id.valueOf(contextId);
        } catch (Exception ex) {
            throw new CopadoFunctionException(
                String.format(
                    Label.invalidContextId,
                    new List<String>{ Label.DEPLOYMENT_JOB + ' / ' + Label.JobStep + ' / ' + Label.USDependency_Environment }
                )
            );
        }
    }

    private Id getSourceId() {
        return (Id) record.get('Source_Id__c');
    }

    private Id getDestinationId() {
        return (Id) record.get('Destination_Id__c');
    }

    private Map<Id, Org__c> credentialByEnvironment() {
        Map<Id, Org__c> result = new Map<Id, Org__c>();

        Set<Id> environmentIds = environmentIds();

        for (Environment__c environment : [
            SELECT Id, (SELECT Id, Default_Credential__c, OwnerId, Environment__r.Platform__c FROM Org_Credentials__r)
            FROM Environment__c
            WHERE Id IN :environmentIds
            WITH SECURITY_ENFORCED
        ]) {
            result.put(environment.Id, userCredential(environment.Org_Credentials__r));
        }

        return result;
    }

    private Org__c userCredential(List<Org__c> orgs) {
        Org__c result = null;

        for (Org__c org : orgs) {
            if (org.OwnerId == UserInfo.getUserId() || org.Default_Credential__c == true) {
                result = org;
                break;
            }
        }

        return result;
    }

    private void assertRecordIdExpression() {
        for (Parameter parameter : parameters) {
            Matcher contextMatcher1 = CONTEXT_PATTERN1.matcher(parameter.value);

            if (contextMatcher1.matches() && objectName(contextId) != 'Environment__c') {
                throw new CopadoFunctionException(String.format(Label.invalidContextId, new List<String>{ Label.Org_Credential }));
            }
        }
    }

    private Set<Id> environmentIds() {
        Set<Id> result = new Set<Id>();

        if (objectName(contextId) == 'Environment__c') {
            result.add(contextId);
        }

        if (record != null) {
            result.add(getSourceId());
            result.add(getDestinationId());
        }

        return result;
    }

    private WebhookCallout.Credential getCredential(Id environmentId) {
        Org__c org = credentialByEnvironment.get(environmentId);

        if (org == null) {
            throw new CopadoFunctionException(Label.credentialNotAvailable + environmentId);
        }

        String clientKey = [SELECT Text_Field__c FROM Copado_Protected_Settiing__mdt WHERE DeveloperName = 'FunctionCredentialClientKey' LIMIT 1]
        .Text_Field__c;

        HttpCallout callout = new WebhookCallout(path(org.Id))
            .type(WebhookCallout.Credential.class)
            .header('Content-Type', 'application/json')
            .header('X-Client-Key', clientKey)
            .request();

        // TODO: ADD API KEY ERROR AND OTHER DETAILS
        if (callout.response().getStatusCode() != 200) {
            throw new CopadoFunctionException(Label.InvalidRequest);
        }

        WebhookCallout.Credential result = (WebhookCallout.Credential) callout.parseResponse();

        if (result.isSuccess != true) {
            throw new CopadoFunctionException(result.error);
        }

        return result;
    }

    private String path(Id orgId) {
        return Settings.server_url + '/json/v1/webhook/copadoSession/' + orgId + '?api_key=' + apiKey();
    }

    // Note: this runs as an Automated process user so not CRUD check needed
    @SuppressWarnings('PMD.ApexCRUDViolation')
    private String apiKey() {
        User user = user();

        return DeployAPI.decryptAPIKey([SELECT API_Key__c FROM Personal_Settings__c WHERE SetupOwnerId = :user.Id LIMIT 1]?.API_Key__c);
    }

    // Note: this runs as an Automated process user so not CRUD check needed
    @SuppressWarnings('PMD.ApexCRUDViolation')
    private User user() {
        User user;

        if (AUTOMATED_PROCESS) {
            user = [SELECT Email, Name FROM User WHERE Id = :ownerId()];
        } else {
            user = [SELECT Email, Name FROM User WHERE Id = :UserInfo.getUserId()];
        }

        return user;
    }

    @SuppressWarnings('PMD.ApexSOQLInjection')
    private Id ownerId() {
        Id result;
        String objectType = objectName(contextId);

        if (objectType == 'Deployment_Job__c') {
            result = [SELECT Step__r.Deployment__r.OwnerId FROM Deployment_Job__c WHERE Id = :contextId WITH SECURITY_ENFORCED]
            ?.Step__r.Deployment__r.OwnerId;
        } else if(objectType == 'JobStep__c') {
            result = [SELECT Parent_Owner_Id__c FROM JobStep__c WHERE Id = :contextId WITH SECURITY_ENFORCED]?.Parent_Owner_Id__c;
		} else {
            String query = 'SELECT OwnerId FROM ' + objectType + ' WHERE Id = :contextId WITH SECURITY_ENFORCED';

            List<SObject> records = Database.query(query);
            result = (records.isEmpty()) ? null : (Id) records[0].get('OwnerId');
        }

        if (String.isBlank(result)) {
            throw new ApplicationException(Label.Context_Owner_Not_Found);
        }

        return result;
    }
}