Dummy_Package_for_scratch_org/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <description>If a project is broken down into multiple sprints this object should be used.</description>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Sprint__c/fields/ActualVelocity__c.field-meta.xml
<CustomField>
    <fullName>ActualVelocity__c</fullName>
    <label>Actual Velocity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Sprint__c/fields/InitialPlannedVelocity__c.field-meta.xml
<CustomField>
    <fullName>InitialPlannedVelocity__c</fullName>
    <label>Initial Planned Velocity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Sprint__c/fields/PlannedVelocity__c.field-meta.xml
<CustomField>
    <fullName>PlannedVelocity__c</fullName>
    <label>Planned Velocity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Sprint__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project where the User Story belongs.</description>
    <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sprint where the User Story is planned.</description>
    <inlineHelpText>Sprint where the User Story is planned.</inlineHelpText>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the implementation of the User Story.</description>
    <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Story_Points_Other__c.field-meta.xml
<CustomField>
    <fullName>Story_Points_Other__c</fullName>
    <label>Planned Points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/SprintTriggerHandlerTest.cls
@isTest
private class SprintTriggerHandlerTest {
    private static final String STANDARD_USER_QUERY = 'SELECT Username FROM User WHERE Username = \'test_user@myorg.com\' LIMIT 1';

    @testSetup
    static void setupData() {
        TestUtilities.enableLicenses(2, 2, 2, 2, 2, 30);
        ITestDefaults userCreation = new CopadoSetupTestDefaults.UserDefaults().createRunAsUsers();
        userCreation.executeDML();
    }

    static testMethod void testSprintUpdate() {
        User currentUser = Database.query(STANDARD_USER_QUERY);
        TestUtilities.assignLicense(currentUser.Username, true, true, true, true, true);
        System.runAs(currentUser) {
            Project__c testProject = CMTestMethodUtilities.createProject('my project');
            insert testProject;

            Sprint__c testSprint = CMTestMethodUtilities.createSprint('my sprint');
            testSprint.Project__c = testProject.Id;
            testSprint.Status__c = 'Draft';
            insert testSprint;

            List<User_Story__c> userStories = new List<User_Story__c>();
            for (Integer i = 0; i < 20; i++) {
                User_Story__c testUserStory = CMTestMethodUtilities.createUserStory('test');
                testUserStory.Sprint__c = testSprint.Id;
                testUserStory.Project__c = null;
                testUserStory.Status__c = 'Draft';
                testUserStory.Story_Points_Other__c = 3;
                userStories.add(testUserStory);
            }
            insert userStories;

            Sprint__c sprintRecord = [
                SELECT Id, Status__c, PlannedVelocity__c, ActualVelocity__c, InitialPlannedVelocity__c
                FROM Sprint__c
                WHERE Id = :testSprint.Id
                LIMIT 1
            ];

            system.assertEquals(sprintRecord.PlannedVelocity__c, 60);
            system.assertEquals(sprintRecord.ActualVelocity__c, null);
            system.assertEquals(sprintRecord.InitialPlannedVelocity__c, null);

            Test.startTest();
            testSprint.Status__c = 'In progress';
            update testSprint;
            Test.stopTest();

            Sprint__c sprint = [
                SELECT Id, Status__c, PlannedVelocity__c, ActualVelocity__c, InitialPlannedVelocity__c
                FROM Sprint__c
                WHERE Id = :testSprint.Id
                LIMIT 1
            ];

            system.assertEquals(sprint.PlannedVelocity__c, 60);
            system.assertEquals(sprint.ActualVelocity__c, null);
            system.assertEquals(sprint.InitialPlannedVelocity__c, 60);
        }
    }

    static testMethod void testSprintUpdateBulk() {
        User currentUser = Database.query(STANDARD_USER_QUERY);
        TestUtilities.assignLicense(currentUser.Username, true, true, true, true, true);
        System.runAs(currentUser) {
            Project__c testProject = CMTestMethodUtilities.createProject('my project');
            insert testProject;

            List<Sprint__c> sprints = new List<Sprint__c>();
            for (Integer i = 0; i < 155; i++) {
                Sprint__c testSprint = CMTestMethodUtilities.createSprint('my sprint');
                testSprint.Project__c = testProject.Id;
                testSprint.Status__c = 'Draft';
                sprints.add(testSprint);
            }
            insert sprints;

            List<User_Story__c> userStories = new List<User_Story__c>();
            for (Sprint__c eachSprint : sprints) {
                for (Integer i = 0; i < 20; i++) {
                    User_Story__c testUserStory = CMTestMethodUtilities.createUserStory('test');
                    testUserStory.Sprint__c = eachSprint.Id;
                    testUserStory.Project__c = null;
                    testUserStory.Status__c = 'Draft';
                    testUserStory.Story_Points_Other__c = 3;
                    userStories.add(testUserStory);
                }
            }
            insert userStories;

            Sprint__c sprintRecord = [SELECT Id, Status__c, PlannedVelocity__c, ActualVelocity__c, InitialPlannedVelocity__c FROM Sprint__c LIMIT 1];

            system.assertEquals(sprintRecord.PlannedVelocity__c, 60);
            system.assertEquals(sprintRecord.ActualVelocity__c, null);
            system.assertEquals(sprintRecord.InitialPlannedVelocity__c, null);

            Test.startTest();
            List<Sprint__c> sprintsToUpdate = new List<Sprint__c>();
            for (Sprint__c eachSprint : sprints) {
                eachSprint.Status__c = 'In progress';
                sprintsToUpdate.add(eachSprint);
            }
            update sprintsToUpdate;
            Test.stopTest();

            for (Sprint__c sprint : [SELECT Id, PlannedVelocity__c, ActualVelocity__c, InitialPlannedVelocity__c FROM Sprint__c]) {
                system.assertEquals(sprint.PlannedVelocity__c, 60);
                system.assertEquals(sprint.ActualVelocity__c, null);
                system.assertEquals(sprint.InitialPlannedVelocity__c, 60);
            }
        }
    }
}