Dummy_Package_for_scratch_org/main/default/objects/Artifact__c/Artifact__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Artifact__c/fields/Artifact_Version__c.field-meta.xml
<CustomField>
    <fullName>Artifact_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Package Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Artifact_Version__c.Artifact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Artifact_Version__c</referenceTo>
    <relationshipLabel>Artifacts</relationshipLabel>
    <relationshipName>Artifacts</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Artifact__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Artifact__c/fields/Target_Dev_Hub_Org__c.field-meta.xml
<CustomField>
    <fullName>Target_Dev_Hub_Org__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Copado org credential for the dev hub which will be used to create and store the package and its versions</inlineHelpText>
    <label>Target Dev Hub Org</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only dev hub org credentials can be selected. Given value not found or it is not a dev hub org.</errorMessage>
        <filterItems>
            <field>Org__c.is_Developer_Hub_Org__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Artifacts (Target Dev Hub Org)</relationshipLabel>
    <relationshipName>packageArtifacts</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/Artifact_Version__c.object-meta.xml
<CustomObject>
    <label>Package Version</label>
    <nameField>
        <label>Package Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/fields/Artifact__c.field-meta.xml
<CustomField>
    <fullName>Artifact__c</fullName>
    <label>Package</label>
    <referenceTo>Artifact__c</referenceTo>
    <relationshipLabel>Package Versions</relationshipLabel>
    <relationshipName>Artifact_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/fields/Version_Description__c.field-meta.xml
<CustomField>
    <fullName>Version_Description__c</fullName>
    <inlineHelpText>The description of the package version</inlineHelpText>
    <label>Version Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/fields/Version_Name__c.field-meta.xml
<CustomField>
    <fullName>Version_Name__c</fullName>
    <inlineHelpText>the name of the package version which entered by user while version creation.</inlineHelpText>
    <label>Version Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/fields/Version_number__c.field-meta.xml
<CustomField>
    <fullName>Version_number__c</fullName>
    <inlineHelpText>The version number of the package version. Must be in major.minor.patch.build format.</inlineHelpText>
    <label>Version number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&quot;Salesforce&quot;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MultiCloudAutomation__mdt/fields/PackageVersionCreateApiName__c.field-meta.xml
<CustomField>
    <fullName>PackageVersionCreateApiName__c</fullName>
    <label>PackageVersionCreateApiName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <formula>TEXT(Environment__r.Platform__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Platform</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/PackageVersionCreateAction.cls
public with sharing class PackageVersionCreateAction {

    private Request request;

    // CONSTRUCTOR

    public PackageVersionCreateAction(Request request) {
        this.request = request;
    }


    // public

    @InvocableMethod(label='Package Version Create Action' category='Copado Action')
    public static List<Response> create(List<Request> requests) {
        assertRequest(requests);
        Request request = requests[0];

        JobExecution__c job = new PackageVersionCreateAction(request).execute();

        return new List<Response>{ new Response(job) };
    }


    public JobExecution__c execute() {
        Artifact__c artifact = getArtifact();
        Artifact_Version__c version = createPackageVersion(artifact);

        return new CreateExecution(executionRequest(artifact, version)).execute();
    }


    // PRIVATE


    @SuppressWarnings('PMD.ApexCRUDViolation')
    private Artifact_Version__c createPackageVersion(Artifact__c artifact) {
        Artifact_Version__c result = new Artifact_Version__c();
        result.Artifact__c = artifact.Id;
        result.Version_Name__c = request.versionName;
        result.Version_number__c = request.versionNumber;
        result.Version_Description__c = request.description;
        result = (Artifact_Version__c) Security.stripInaccessible(AccessType.CREATABLE, new List<SObject> { result }).getRecords()[0];
        insert result;

        return result;
    }


    private static void assertRequest(List<Request> requests) {
        if (requests.size() != 1) {
            throw new ApplicationException(Label.MultiplePackageVersionCreationRequestNotAllowed);
        }
    }


    private Artifact__c getArtifact() {
        List<Artifact__c> result = [SELECT Pipeline__r.Platform__c, Target_Dev_Hub_Org__r.Environment__c FROM Artifact__c WHERE Id = :request.packageId WITH SECURITY_ENFORCED];

        if(result.isEmpty()) {
            throw new ApplicationException(Label.InvalidPackageId);
        }

        return result[0];
    }


    private CreateExecution.Request executionRequest(Artifact__c artifact, Artifact_Version__c version) {
        CreateExecution.Request result = new CreateExecution.Request();

        result.dataJson = request.json;
        result.parentId = version.Id;
        result.runAfterInstantiation = true;
        result.templateName = getJobTemplateName(artifact);
        result.destinationId = artifact.Target_Dev_Hub_Org__r?.Environment__c;

        return result;
    }


    private String getJobTemplateName(Artifact__c artifact) {
        String platform = artifact.Pipeline__r?.Platform__c;
        MultiCloudAutomation__mdt actionTemplate = new MultiCloudAutomationsSelector().byPlatform(platform);

        return actionTemplate?.PackageVersionCreateApiName__c;
    }


    // INNER

    public class Request {
        @InvocableVariable(required=true label='Package Id')
        public String packageId;

        @InvocableVariable(required=true label='Version Name')
        public String versionName;

        @InvocableVariable(required=true label='Version Number')
        public String versionNumber;

        @InvocableVariable(required=false label='Description')
        public String description;

        @InvocableVariable(label='Version data JSON format')
        public String json;

        public Request(String packageId, String json) {
            this.packageId = packageId;
            this.json = json;
        }
    }

    public class Response {
        @InvocableVariable
        public JobExecution__c job;

        public Response(JobExecution__c job) {
            this.job = job;
        }
    }
}