Dummy_Package_for_scratch_org/main/default/objects/Artifact__c/Artifact__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Artifact__c/fields/Package_Type__c.field-meta.xml
<CustomField>
    <fullName>Package_Type__c</fullName>
    <inlineHelpText>For detailed information : https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_plan_pkg_types.htm</inlineHelpText>
    <label>Package Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unlocked</fullName>
                <default>true</default>
                <label>Unlocked</label>
            </value>
            <value>
                <fullName>Second-Generation Package</fullName>
            </value>
            <value>
                <fullName>First-Generation Package</fullName>
            </value>
            <value>
                <fullName>Unmanaged</fullName>
                <isActive>false</isActive>
                <label>Unmanaged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Artifact__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/Deployment_Flow__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Flow__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/DataJson__c.field-meta.xml
<CustomField>
    <fullName>DataJson__c</fullName>
    <label>DataJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MultiCloudAutomation__mdt/fields/PackageVersionCreateApiName__c.field-meta.xml
<CustomField>
    <fullName>PackageVersionCreateApiName__c</fullName>
    <label>PackageVersionCreateApiName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MultiCloudAutomation__mdt/fields/PlatformName__c.field-meta.xml
<CustomField>
    <fullName>PlatformName__c</fullName>
    <label>PlatformName</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/PackageVersionCreateServiceTest.cls
@IsTest
private class PackageVersionCreateServiceTest {

    @IsTest
    private static void executeWithMultipleRequest() {
        // Setup
        Exception expectedException = null;

        List<PackageVersionCreateAction.Request> requests = new List<PackageVersionCreateAction.Request> {
            new PackageVersionCreateAction.Request(UserInfo.getUserId(), null),
            new PackageVersionCreateAction.Request(UserInfo.getUserId(), null)
        };


        // Exercise
        try {
            System.runAs(getStandardUser()) {
                PackageVersionCreateAction.create(requests);
            }
        }
        catch (Exception ex) {
            expectedException = ex;
        }


        // Verify

        System.assertNotEquals(null, expectedException, 'Should throw Exception');
        System.assertEquals(Label.MultiplePackageVersionCreationRequestNotAllowed, expectedException.getMessage(), 'Should have Invalid Package Id message');
    }


    @IsTest
    private static void executeWithInValidPackageId() {
        // Setup
        Exception expectedException = null;

        PackageVersionCreateAction.Request request = new PackageVersionCreateAction.Request(UserInfo.getUserId(), null);
        CliProxy.CLIWrapper cliRequest = new CliProxy.CLIWrapper();
        cliRequest.body = JSON.serialize(request);


        // Exercise
        try {
            System.runAs(getStandardUser()) {
                new PackageVersionCreateService().run(cliRequest);
            }
        }
        catch (Exception ex) {
            expectedException = ex;
        }


        // Verify

        System.assertNotEquals(null, expectedException, 'Should throw Exception');
        System.assertEquals(Label.InvalidPackageId, expectedException.getMessage(), 'Should have Invalid Package Id message');
    }


    @IsTest
    private static void executeWithoutJobTemplate() {

        // Setup
        Artifact__c artifact;
        Exception expectedException = null;

        MultiCloudAutomationsSelector.mock = new Map<String, MultiCloudAutomation__mdt> {
            'Other' => new MultiCloudAutomation__mdt( PlatformName__c = 'Other')
        };

        System.runAs(getStandardUser()) {
            Deployment_Flow__c pipeline = new Deployment_Flow__c(Name='Other', Platform__c='Other');
            insert pipeline;

            artifact = new Artifact__c();
            artifact.pipeline__c = pipeline.Id;
            artifact.Package_Type__c = 'First-Generation Package';
            insert artifact;
        }

        PackageVersionCreateAction.Request request = new PackageVersionCreateAction.Request(artifact.Id, null);
        CliProxy.CLIWrapper cliRequest = new CliProxy.CLIWrapper();
        cliRequest.body = JSON.serialize(request);


        // Exercise
        try {
            System.runAs(getStandardUser()) {
                new PackageVersionCreateService().run(cliRequest);
            }
        }
        catch (Exception ex) {
            expectedException = ex;
        }


        // Verify

        System.assertNotEquals(null, expectedException, 'Should throw Exception');
        System.assertEquals(Label.InvalidTemplateId, expectedException.getMessage(), 'Should have Template not found message');
    }


    @IsTest
    private static void executeWithValidJobTemplate() {

        // Setup
        Artifact__c artifact;

        System.runAs(getStandardUser()) {
            Deployment_Flow__c pipeline = new Deployment_Flow__c(Name='Other', Platform__c='Other');
            insert pipeline;

            artifact = new Artifact__c();
            artifact.pipeline__c = pipeline.Id;
            artifact.Package_Type__c = 'First-Generation Package';
            insert artifact;

            JobTemplate__c template = new JobTemplate__c(Name = 'TestVersionCreate', Version__c = 1);
            insert template;
        }

        MultiCloudAutomationsSelector.mock = new Map<String, MultiCloudAutomation__mdt> {
            'Other' => new MultiCloudAutomation__mdt( PlatformName__c = 'Other', PackageVersionCreateApiName__c = 'TestVersionCreate_1')
        };


        List<PackageVersionCreateAction.Request> requests = new List<PackageVersionCreateAction.Request> {
            new PackageVersionCreateAction.Request(artifact.Id, '{"key": "value"}')
        };


        // Exercise
        System.runAs(getStandardUser()) {
            PackageVersionCreateAction.create(requests);
        }


        // Verify
        List<JobExecution__c> jobs = [SELECT DataJson__c FROM JobExecution__c];

        System.assertEquals(1, jobs.size());
        System.assertEquals('{"key": "value"}', jobs[0].DataJson__c);
    }


    // HELPER

    private static User getStandardUser() {
        return [SELECT Username FROM User WHERE Username = 'test_user@myorg.com' LIMIT 1];
    }


    @TestSetup
    private static void createData() {
        TestUtilities.enableLicenses(2, 2, 2, 2, 2, 30);
        User standardUser = new CopadoSetupTestDefaults.UserDefaults()
            						.createRunAsUsers()
            						.executeDML()
            						.getRunAsUsers()
            						.get('Standard')[0];

        System.runAs(standardUser) {
            TestUtilities.assignLicense(String.valueOf(standardUser.Username), true, false, false, false, false);
        }

        List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();
        for (PermissionSet ps : [
            SELECT Id
            FROM PermissionSet
            WHERE Name IN ('Copado_Functions', 'Copado_Job_Engine')
        ]) {
            assignments.add(new PermissionSetAssignment(AssigneeId = standardUser.Id, PermissionSetId = ps.Id));
        }
        insert assignments;
    }
}