Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Script</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/SupportedObject__mdt/SupportedObject__mdt.object-meta.xml
<CustomObject>
    <label>Supported Object</label>
    <pluralLabel>Supported Objects</pluralLabel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/classes/CreateStandardRecordCtrlTest.cls
@IsTest
private class CreateStandardRecordCtrlTest {
	
    @IsTest
    private static void getSupportedObjectsByName() {
        // Setup
        SupportedObjectsSelector.mockRecords = new List<SupportedObject__mdt> { new SupportedObject__mdt() };

        // Exercise
        List<CreateStandardRecordCtrl.SupportedObject> result = CreateStandardRecordCtrl.getSupportedObjects();
			
        // Verify
        System.assertEquals(1, result.size());
    }
    
    @IsTest
    private static void allSupportedObject() {

        // Exercise
        List<SupportedObject__mdt> result = new SupportedObjectsSelector().allObjects();
			
        // Verify
        System.assertEquals(1, result.size());
    }
    
    @IsTest
    private static void getSupportedObjectsWithoutMock() {

        // Exercise
        Map<String, String> result = new SupportedObjectsSelector().all();
			
        // Verify
        System.assertEquals(1, result.size());
    }
    
    @IsTest
    private static void getRecordBundle() {
        // Setup
        Exception expectedException = null;
        
        Function__c f = new Function__c();
        f.API_Name__c = 'SampleFunction';
        f.Script__c = 'echo "Old"';
        insert f;
        
        // Exercise
        try {
            CreateStandardRecordCtrl.getRecordBundle(new List<Id> { f.Id });
        } catch(Exception ex) {
            expectedException = ex;
        }
        
        // Verify
        System.assertEquals(null, expectedException);
    }
}