Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Handler format: ClassName
The class must implement the MCCallBack interface.</description>
    <inlineHelpText>Handler format: ClassName
The class must implement the MCCallBack interface.</inlineHelpText>
    <label>ApexClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Callback_Type__c.field-meta.xml
<CustomField>
    <fullName>Callback_Type__c</fullName>
    <description>Trigger a Flow or Apex class each time a function execution completes. This trigger happens when the function result status changes to Success or Failed.</description>
    <inlineHelpText>Trigger a Flow or Apex class each time a function execution completes. This trigger happens when the function result status changes to Success or Failed.</inlineHelpText>
    <label>Callback Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ApexClass</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/FlowHandler__c.field-meta.xml
<CustomField>
    <fullName>FlowHandler__c</fullName>
    <description>Handler format: FlowAPIName</description>
    <inlineHelpText>Handler format: FlowAPIName</inlineHelpText>
    <label>FlowHandler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Script</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Worker_Size__c.field-meta.xml
<CustomField>
    <fullName>Worker_Size__c</fullName>
    <label>Worker Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <default>true</default>
                <label>S</label>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/IsFinished__c.field-meta.xml
<CustomField>
    <fullName>IsFinished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Finished</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Success</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/MC_Result__e/fields/ResultId__c.field-meta.xml
<CustomField>
    <fullName>ResultId__c</fullName>
    <label>Result Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copado Function that triggered this result.</inlineHelpText>
    <label>Function</label>
    <referenceTo>Function__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function_Worker_Size__c.field-meta.xml
<CustomField>
    <fullName>Function_Worker_Size__c</fullName>
    <label>Function Worker Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Date time when the job started.</description>
    <inlineHelpText>Date time when the job started.</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Current status of the result. Confirms if the result is pending or completed.</description>
    <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/MCResultsTest.cls
@isTest
private class MCResultsTest {
    private static final User RUNNING_USER;

    static {
        RUNNING_USER = createRunningUser();
    }

    @TestSetup
    private static void setup() {
        assignUserPermissions(RUNNING_USER.Id);
        System.runAs(RUNNING_USER) {
            insertTestData();
        }
    }

    @isTest
    private static void runApexClassCallback() {
        // Setup
        Result__c result = [SELECT Id FROM Result__c WHERE Function__r.API_Name__c = 'muleDeploy'];

        // Exercise
        System.runAs(RUNNING_USER) {
            Test.startTest();
            EventBus.publish(
                new MC_Result__e(
                    ResultId__c = result.Id,
                    isFinished__c = false,
                    isSuccess__c = false,
                    Progress_Status__c = 'Job enqueued on the backend'
                )
            );
            Test.stopTest();
        }

        // Verify
        result = [SELECT Progress_Status__c, Status__c FROM Result__c WHERE Id = :result.Id];
        System.assertEquals('In Progress', result.Status__c, 'Status should be updated to in progress.');
        System.assertEquals('Processing request...', result.Progress_Status__c, 'Progress Status should be updated in the callback class');
    }

    @isTest
    private static void runFlowCallback() {
        // Setup
        Result__c result = [SELECT Id FROM Result__c WHERE Function__r.API_Name__c = 'herokuDeploy'];

        //Exercise
        System.runAs(RUNNING_USER) {
            Test.startTest();
            EventBus.publish(new MC_Result__e(ResultId__c = result.Id, isFinished__c = true, isSuccess__c = true, Progress_Status__c = ''));
            Test.stopTest();
        }

        // Verify
        result = [SELECT Progress_Status__c, Status__c FROM Result__c WHERE Id = :result.Id];
        System.assertEquals('Success', result.Status__c, 'Status should be updated to success.');
        System.assertEquals('callback-executed', result.Progress_Status__c, 'Progress Status should be updated in the callback flow');
    }

    @isTest
    private static void runInvalidApexCallback() {
        // Setup
        Result__c result = [SELECT Id FROM Result__c WHERE Function__r.API_Name__c = 'muleDeploy'];

        // Exercise
        System.runAs(RUNNING_USER) {
            Test.startTest();
            HandleBackendResponse.mockCallback = namespacePrefix() + 'VerifyCallbacks';
            EventBus.publish(
                new MC_Result__e(ResultId__c = result.Id, isFinished__c = true, isSuccess__c = true, Progress_Status__c = 'Job execution in progress')
            );
            Test.stopTest();
        }

        // Verify
        result = [SELECT Progress_Status__c, Status__c, Error_Message__c FROM Result__c WHERE Id = :result.Id];
        System.assertEquals('Failed', result.Status__c, 'Status should be updated to failed.');
        System.assertEquals('Error', result.Progress_Status__c, 'Progress Status should be updated to Error');

        String errorMessage = String.format(
            Label.Function_Callback_Failed,
            new List<String>{
                String.format(Label.Callback_not_Found, new List<String>{ 'ApexClass', namespacePrefix() + 'VerifyCallbacks' }) +
                ' ' +
                Label.Callback_not_Found_Information
            }
        );
        System.assertEquals(errorMessage, result.Error_Message__c, 'The error message should point to an invalid callback class.');
    }

    @isTest
    private static void runInvalidFlowCallback() {
        // Setup
        Result__c result = [SELECT Id FROM Result__c WHERE Function__r.API_Name__c = 'herokuDeploy'];

        // Exercise
        System.runAs(RUNNING_USER) {
            Test.startTest();
            HandleBackendResponse.mockCallback = 'InvalidFlow';
            EventBus.publish(
                new MC_Result__e(ResultId__c = result.Id, isFinished__c = true, isSuccess__c = true, Progress_Status__c = 'Job execution in progress')
            );
            Test.stopTest();
        }

        // Verify
        result = [SELECT Progress_Status__c, Status__c, Error_Message__c FROM Result__c WHERE Id = :result.Id];
        System.assertEquals('Failed', result.Status__c, 'Status should be updated to failed.');
        System.assertEquals('Error', result.Progress_Status__c, 'Progress Status should be updated to Error');

        String errorMessage = String.format(
            Label.Function_Callback_Failed,
            new List<String>{ String.format(Label.Flow_Callback_Failed, new List<String>{ 'Invalid type: InvalidFlow' }) }
        );
        System.assertEquals(errorMessage, result.Error_Message__c, 'The error message should point to an unknown callback class.');
    }

    // HELPER

    private static User createRunningUser() {
        List<User> users = TestDataFactory.createUsers();
        return users[0];
    }

    private static void assignUserPermissions(Id userId) {
        List<PermissionSet> permissionSets = [SELECT Id FROM PermissionSet WHERE Name IN ('Copado_User', 'Copado_Functions', 'Copado_Job_Engine')];
        List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();
        for (PermissionSet permissionSet : permissionSets) {
            assignments.add(new PermissionSetAssignment(AssigneeId = userId, PermissionSetId = permissionSet.Id));
        }
        insert assignments;
    }

    private static void insertTestData() {
        List<Function__c> functions = new List<Function__c>();
        Function__c muleDeploy = new Function__c(
            Name = 'muleDeploy',
            API_Name__c = 'muleDeploy',
            Script__c = 'echo "Hello World"',
            Callback_Type__c = 'ApexClass',
            ApexClass__c = namespacePrefix() + 'MCCallbackHandlerTestClass',
            Worker_Size__c = 'XL'
        );
        functions.add(muleDeploy);
        Function__c herokuDeploy = new Function__c(
            Name = 'herokuDeploy',
            API_Name__c = 'herokuDeploy',
            Script__c = 'echo "Hello World"',
            Callback_Type__c = 'Flow',
            FlowHandler__c = namespacePrefix() + 'MCCallbackHandlerTestFlow',
            Worker_Size__c = 'S'
        );
        functions.add(herokuDeploy);
        insert functions;

        List<Result__c> results = new List<Result__c>();
        results.add(
            new Result__c(
                Job_Type__c = 'Integration',
                Start_Time__c = Datetime.now(),
                Status__c = 'In Progress',
                Function__c = muleDeploy.Id,
                Progress_Status__c = 'backend called',
                Function_Worker_Size__c = 'XL'
            )
        );
        results.add(
            new Result__c(
                Job_Type__c = 'Integration',
                Start_Time__c = Datetime.now(),
                Status__c = 'In Progress',
                Function__c = herokuDeploy.Id,
                Progress_Status__c = 'backend called',
                Function_Worker_Size__c = 'S'
            )
        );
        insert results;
    }

    private static String namespacePrefix() {
        return Settings.ns.replace('__', '.');
    }
}