Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Image_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Name__c</fullName>
    <description>The docker image name provided by Copado. You will find available image paths in the Copado documentation. An image name is made up of slash-separated name components, prefixed by a registry hostname.</description>
    <inlineHelpText>The docker image name provided by Copado. You will find available image paths in the Copado documentation. An image name is made up of slash-separated name components, prefixed by a registry hostname.</inlineHelpText>
    <label>Image Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Script</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Worker_Size__c.field-meta.xml
<CustomField>
    <fullName>Worker_Size__c</fullName>
    <label>Worker Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <default>true</default>
                <label>S</label>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/FunctionPayload.cls
/**
 * @description Builds the payload for the Copado Function callout.
 * @exception throws JSONException. Make sure to handle it from the calling context.
 */
public with sharing class FunctionPayload {
    private String function;
    private String script;
    private String resultId;
    private String image;
    private List<Parameter> options;
    private List<Parameter> parameters;

    // CTOR

    public FunctionPayload(Function__c function) {
        this.function = function.API_Name__c;
        this.script = function.Script__c;
        this.image = function.Image_Name__c;
        options(function);
    }

    // PUBLIC

    public FunctionPayload options(List<Parameter> options) {
        if (options != null) {
            if (this.options == null) {
                this.options = new List<Parameter>();
            }
            this.options.addAll(options);
        }
        return this;
    }

    public FunctionPayload parameters(List<Parameter> parameters) {
        this.parameters = parameters;
        return this;
    }

    public FunctionPayload resultId(String resultId) {
        this.resultId = resultId;
        return this;
    }

    public String getResultId() {
        return this.resultId;
    }

    /**
     * @exception throws Exception. Make sure to handle it from the calling context.
     */
    public FunctionPayload validate(String functionParams) {
        Map<String, String> parameterMap = new Map<String, String>();
        for (Parameter parameter : parameters) {
            parameterMap.put(parameter.name, parameter.value);
        }
        List<Parameter> baseParams = (List<Parameter>) JSON.deserialize(functionParams, List<Parameter>.class);
        for (Parameter parameter : baseParams) {
            Boolean required = Boolean.valueOf(parameter.required);
            if (required) {
                String name = String.valueOf(parameter.name);
                String value = parameterMap.get(name);
                if (String.isBlank(value)) {
                    throw new FunctionPayloadException(
                        Label.Required_Parameters_Missing +
                        ': ' +
                        name +
                        '. ' +
                        Label.Value_not_Found +
                        ': ' +
                        parameter.defaultValue
                    );
                }
            }
        }

        return this;
    }

    public String toJson() {
        return JSON.serialize(this);
    }

    // PRIVATE

    private void options(Function__c record) {
        if (String.isNotBlank(record.Options__c)) {
            this.options = (List<Parameter>) JSON.deserialize(record.Options__c, List<Parameter>.class);
        }
        if (String.isNotBlank(record.Worker_Size__c)) {
            if (this.options == null) {
                this.options = new List<Parameter>();
            }
            this.options.add(new Parameter('workerSize', record.Worker_Size__c));
        }
    }

    private class FunctionPayloadException extends Exception {
    }
}