Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copado Function that triggered this result.</inlineHelpText>
    <label>Function</label>
    <referenceTo>Function__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/MCCallbackHandlerTestClass.cls
// note: prepend Copado namespace when implementing the interface from an installed package: copado.MCCallback
public with sharing class MCCallbackHandlerTestClass implements MCCallBack {
    public void execute(Function__c function, Result__c result, String status) {
        result.Progress_Status__c = progress(status);

        update Security.stripInaccessible(AccessType.UPDATABLE, new List<Result__c>{ result }).getRecords();
    }

    private String progress(String status) {
        String result = '';

        switch on status {
            when 'In Progress' {
                result = 'Processing request...';
            }
            when 'Success' {
                result = 'Function execution completed. See details attached.';
            }
            when 'Failed' {
                result = 'Function execution failed. See details attached.';
            }
            when else {
                result = 'Function execution not started or cancelled.';
            }
        }

        return result;
    }
}