Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Copado Function that triggered this result.</inlineHelpText>
    <label>Function</label>
    <referenceTo>Function__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/StepCallback.cls
public with sharing class StepCallback implements MCCallBack {

    // PUBLIC

    public void execute(Function__c function, Result__c result, String status) {
        execute(result.JobStep__r.JobExecution__c, status);
    }


    public void execute(Id jobId, String status) {
        if(status == 'Success') {
            if(Test.isRunningTest()) {
                new RunJob(jobId).executeNextStep();
            } else {
                System.enqueueJob(new RunJob(jobId));
            }   
        }
        else if(status == 'Failed' || status == 'Error') {
            new RunJob(jobId).finish('Error');
        }
    }
}