Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Script</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/CreateStandardRecordsTest.cls
@IsTest
private class CreateStandardRecordsTest {
    @IsTest
    private static void executeNewRecords() {

        // Setup
        System.Savepoint savePoint = Database.setSavepoint();
        Function__c f = new Function__c();
        f.API_Name__c = 'SampleFunction';
        f.Script__c = 'echo "Hello"';
        insert f;
        String json = CreateStandardRecords.serialize(new Set<Id> { f.Id });
        
        StaticResourcesSelector.mock = new List<StaticResource> {
            new StaticResource(Name = 'CopadoStandardRecords', Body = Blob.valueOf(json))
        };

        SupportedObjectsSelector.mock = new Map<String, String> { 
            'copado__Function__c' => 'copado__API_Name__c'
         };

        Database.rollback(savePoint);

        
        // Exercise
        CreateStandardRecords.execute('CopadoStandardRecords');


        // Verify
        List<Function__c> results = [SELECT Id, API_Name__c, Script__c FROM Function__c];
        System.assertEquals(1, results.size());
        System.assertEquals(f.API_Name__c, results[0].API_Name__c);
        System.assertEquals(f.Script__c, results[0].Script__c);
    }
    
    
    @IsTest
    private static void executeExistingRecords() {

        // Setup
        Function__c f = new Function__c();
        f.API_Name__c = 'SampleFunction';
        f.Script__c = 'echo "Old"';
        insert f;
        String json = CreateStandardRecords.serialize(new Set<Id> { f.Id });
        f.Script__c = 'echo "Updated"';
        update f;
        
        StaticResourcesSelector.mock = new List<StaticResource> {
            new StaticResource(Name = 'CopadoStandardRecords', Body = Blob.valueOf(json))
        };

        SupportedObjectsSelector.mock = new Map<String, String> { 
            'copado__Function__c' => 'copado__API_Name__c'
         };
             
        
        // Exercise
        CreateStandardRecords.execute('CopadoStandardRecords');


        // Verify
        List<Function__c> results = [SELECT Id, API_Name__c, Script__c FROM Function__c];
        System.assertEquals(1, results.size());
        System.assertEquals(f.API_Name__c, results[0].API_Name__c);
        System.assertEquals('echo "Old"', results[0].Script__c);
    }
}