Dummy_Package_for_scratch_org/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Function__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Custom&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Settings__c/fields/Enable_Standard_Function_Edit__c.field-meta.xml
<CustomField>
    <fullName>Enable_Standard_Function_Edit__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Turn on this checkbox if you want to modify standard functions</inlineHelpText>
    <label>Enable Standard Function Edit</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/VerifyThatFunctions.cls
public with sharing class VerifyThatFunctions {
  private static final String STANDARD = 'Standard';
  private List<Function__c> records;
  private Map<Id, Function__c> old;

  // CONSTRUCTOR

  public VerifyThatFunctions(List<Function__c> records) {
    this.records = records;
  }

  public VerifyThatFunctions(
    List<Function__c> records,
    Map<Id, Function__c> old
  ) {
    this(records);
    this.old = old;
  }

  // PUBLIC

  public void areNotStandard() {
    Settings__c setting = Settings__c.getOrgDefaults();

    if(setting.Enable_Standard_Function_Edit__c != true) {
      for (Function__c function : records) {
        if (Trigger.isInsert || Trigger.isDelete) {
          if (function.Type__c == STANDARD) {
            function.addError(Label.Standard_Functions_not_Creatable);
          }
        } else if (Trigger.isUpdate) {
          Function__c oldFunction = old.get(function.Id);
          if (
            (oldFunction.Type__c == STANDARD &&
            oldFunction.Type__c != function.Type__c) ||
            function.Type__c == STANDARD
          ) {
            function.addError(Label.Standard_Functions_not_Editable);
          }
        }
      }
    }
  }
}