Dummy_Package_for_scratch_org/main/default/objects/Git_Backup__c/Git_Backup__c.object-meta.xml
<CustomObject>
    <description>A Git Snapshot record in Copado defines a connection between a Salesforce Org with a Git Repository/branch.</description>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Git_Backup__c/fields/Git_Repository__c.field-meta.xml
<CustomField>
    <fullName>Git_Repository__c</fullName>
    <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
    <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
    <label>Git Repository</label>
    <referenceTo>Git_Repository__c</referenceTo>
    <relationshipLabel>Git Snapshots</relationshipLabel>
    <relationshipName>Git_Backups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Git_Backup__c/fields/Git_Snapshot_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Git_Snapshot_Permissions__c</fullName>
    <label>Git Snapshot Permissions</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Allow Snapshots &amp; Commits</fullName>
                <default>true</default>
                <label>Allow Snapshots &amp; Commits</label>
            </value>
            <value>
                <fullName>Allow Snapshots Only</fullName>
            </value>
            <value>
                <fullName>Allow Commits Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Git_Backup__c/fields/Org__c.field-meta.xml
<CustomField>
    <fullName>Org__c</fullName>
    <description>A validated Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
    <inlineHelpText>A validated Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
    <label>Credential</label>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>Git Snapshots</relationshipLabel>
    <relationshipName>Git_Backups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Git_Repository__c/Git_Repository__c.object-meta.xml
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/classes/GitSnapshotSelector.cls
public with sharing class GitSnapshotSelector extends fflib_SObjectSelector {
    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{ Git_Backup__c.Id };
    }

    public SObjectType getSObjectType() {
        return Git_Backup__c.sObjectType;
    }

    public List<Git_Backup__c> byCredentialRepoSnapshotOnly(Id orgId, Id repositoryId) {
        return Database.query(
            newQueryFactory()
                .setEnforceFLS(true)
                .setCondition('Org__c = :orgId AND Git_Repository__c = :repositoryId AND Git_Snapshot_Permissions__c != \'Allow Snapshots Only\'')
                .toSOQL()
        );
    }
}