Dummy_Package_for_scratch_org/main/default/objects/TestType__mdt/fields/ExecuteVia__c.field-meta.xml
<CustomField>
    <fullName>ExecuteVia__c</fullName>
    <label>ExecuteVia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/TestType__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/TestTypesSelector.cls
public with sharing class TestTypesSelector extends fflib_SObjectSelector {
    @TestVisible
    private static List<TestType__mdt> mock = new List<TestType__mdt>();

    // PUBLIC

    public Schema.SObjectType getSObjectType() {
        return TestType__mdt.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            TestType__mdt.Id,
            TestType__mdt.ExecuteVia__c,
            TestType__mdt.Namespace__c,
            TestType__mdt.Category__c,
            TestType__mdt.Tool__c
        };
    }

    public List<TestType__mdt> getAll() {
        return Test.isRunningTest() ? mock : (List<TestType__mdt>) Database.query(newQueryFactory().setEnforceFLS(true).toSOQL());
    }

    public List<TestType__mdt> byTool(String tool) {
        return Test.isRunningTest()
            ? mock
            : (List<TestType__mdt>) Database.query(newQueryFactory().setEnforceFLS(true).setCondition('Tool__c = :tool').toSOQL());
    }

    public static void mock(List<TestType__mdt> providers) {
        mock = providers;
    }
}