Dummy_Package_for_scratch_org/main/default/objects/Bundled_Story__c/Bundled_Story__c.object-meta.xml
<CustomObject>
    <label>Bundled Story</label>
    <nameField>
        <displayFormat>BS-{0000000}</displayFormat>
        <label>Bundled Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundled Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Bundled_Story__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Bundled Stories</relationshipLabel>
    <relationshipName>Bundled_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
    <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Org_Credential__c.field-meta.xml
<CustomField>
    <fullName>Org_Credential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
    <inlineHelpText>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
    <label>Credential</label>
    <referenceTo>Org__c</referenceTo>
    <relationshipLabel>User Stories (Credential)</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project where the User Story belongs.</description>
    <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product version or release where this User Story will be released.</description>
    <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/User_Story_Title__c.field-meta.xml
<CustomField>
    <fullName>User_Story_Title__c</fullName>
    <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
    <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
    <label>User Story Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/LockBundleCtrl.cls
public with sharing class LockBundleCtrl {
    private static final Set<SObjectField> PREFILL_FIELDS = new Set<SObjectField>{
        User_Story__c.Release__c,
        User_Story__c.Project__c,
        User_Story__c.Environment__c,
        User_Story__c.Org_Credential__c
    };

    //PUBLIC

    @AuraEnabled(cacheable=true)
    public static List<String> getFieldsFromFieldSet(String objectName, String fieldSet) {
        List<String> result = new List<String>();

        for (FieldSetMember field : fflib_SObjectDescribe.getDescribe(objectName).getDescribe().fieldSets.getMap().get(fieldSet).getFields()) {
            result.add(field.getFieldPath());
        }

        return result;
    }

    @AuraEnabled
    public static BundlingProcess.BundlingResult lockBundle(User_Story__c story, Id bundleId) {
        BundlingProcess.BundlingResult result = new BundlingProcess.BundlingResult();

        try {
            result = new BundlingProcess(bundleId, story).execute();
        } catch (Exception ex) {
            new ApplicationException(ex.getMessage()).throwAuraHandled();
        }

        return result;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getLockedChildStories(Id version) {
        Set<String> result = new Set<String>();

        try {
            Set<Id> childStories = getBundledChildStories(version);
            for (Bundled_Story__c junction : new BundledStorySelector().byStoryIdsAndVersionStatus(childStories, new Set<String>{ 'Locked' })) {
                result.add(junction.User_Story__r.Name);
            }
        } catch (Exception ex) {
            new ApplicationException(ex.getMessage()).throwAuraHandled();
        }

        return new List<String>(result);
    }

    @AuraEnabled(cacheable=true)
    public static User_Story__c createPrefilledStory(Id version) {
        User_Story__c result = new User_Story__c();

        try {
            List<User_Story__c> stories = new UserStoriesSelector().byBundlePackageVersions(new Set<Id>{ version });

            Map<SObjectField, Set<Object>> valuesByField = Utilities.groupValuesByField(stories, PREFILL_FIELDS, false);

            result = createRecord(valuesByField);

            result.User_Story_Title__c = new ArtifactVersionsSelector().byIds(new Set<Id>{ version }).get(0).Name;

            if (result.Org_Credential__c == null) {
                result.Org_Credential__c = getDefaultOrgCred(result.Environment__c);
            }
        } catch (Exception ex) {
            new ApplicationException(ex.getMessage()).throwAuraHandled();
        }

        return result;
    }

    // PRIVATE

    private static Set<Id> getBundledChildStories(Id version) {
        return (Set<Id>) Utilities.getFieldValues(
            new BundledStorySelector().byPackageVersion(new Set<Id>{ version }),
            Bundled_Story__c.User_Story__c,
            Set<Id>.class,
            false
        );
    }

    private static User_Story__c createRecord(Map<SObjectField, Set<Object>> valuesByField) {
        User_Story__c result = new User_Story__c();

        for (SObjectField field : valuesByField.keySet()) {
            if (valuesByField.get(field).size() == 1) {
                result.put(field, new List<Object>(valuesByField.get(field))[0]);
            }
        }

        return result;
    }

    private static Id getDefaultOrgCred(Id environment) {
        Id result = null;

        List<Org__c> defaultOrg = new OrgsSelector().byEnvironmentAndIsDefault(new Set<Id>{ environment }, true);
        if (!defaultOrg.isEmpty()) {
            result = defaultOrg[0].Id;
        }

        return result;
    }
}