Dummy_Package_for_scratch_org/main/default/objects/Git_Repository__c/Git_Repository__c.object-meta.xml
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/System_Property__c.object-meta.xml
<CustomObject>
    <label>System Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>This value is automatically populated when selecting a Pipeline, Environment or User. If none is selected, the record Id this property is linked to must be entered manually.</description>
    <inlineHelpText>This value is automatically populated when selecting a Pipeline, Environment or User. If none is selected, the record Id this property is linked to must be entered manually.</inlineHelpText>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/System_Property__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/SetPropertyParentsTest.cls
@IsTest
private class SetPropertyParentsTest {
    @TestSetup
    private static void makeData() {
        TestUtilities.setTestSettingsEE();
    }

    @IsTest
    private static void createUserProperty() {
        // Exercise

        Test.startTest();
        System_Property__c property = new System_Property__c(API_Name__c = 'USER-PROPERTY', User__c = UserInfo.getUserId());
        insert property;
        Test.stopTest();

        // Verify

        property = [SELECT User__c, ParentId__c FROM System_Property__c WHERE Id = :property.Id];
        System.assertEquals(UserInfo.getUserId(), property.User__c, 'The parent user does not match the current user.');
        System.assertEquals(property.User__c, property.ParentId__c, 'The value in User__c was not copied into the property\'s ParentId field.');
    }

    @IsTest
    private static void createGitProperty() {
        // Setup

        Git_Repository__c repository = new Git_Repository__c();
        insert repository;

        // Exercise

        Test.startTest();
        System_Property__c property = new System_Property__c(API_Name__c = 'USER-PROPERTY', ParentId__c = repository.Id);
        insert property;
        Test.stopTest();

        // Verify

        property = [SELECT ParentId__c FROM System_Property__c WHERE Id = :property.Id];
        System.assertEquals(
            repository.Id,
            property.ParentId__c,
            'The value in ParentId does not match the Git Repository Id for which it was created.'
        );
    }

    @IsTest
    private static void updatePropertyParent() {
        // Setup

        Git_Repository__c repository = new Git_Repository__c();
        insert repository;
        System_Property__c property = new System_Property__c(API_Name__c = 'USER-PROPERTY', ParentId__c = repository.Id);
        insert property;

        // Exercise

        Test.startTest();
        property.User__c = UserInfo.getUserId();
        update property;
        Test.stopTest();

        // Verify

        property = [SELECT User__c, ParentId__c FROM System_Property__c WHERE Id = :property.Id];
        System.assertEquals(UserInfo.getUserId(), property.User__c, 'The parent user does not match the current user.');
        System.assertEquals(property.User__c, property.ParentId__c, 'The ParentId field was not overriden by the new parent that was set (User__c).');
    }
}