Dummy_Package_for_scratch_org/main/default/objects/Git_Commit__c/Git_Commit__c.object-meta.xml
<CustomObject>
    <label>Git Commit</label>
    <nameField>
        <displayFormat>Commit-{0000}</displayFormat>
        <label>Git Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Git Commits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/DataJson__c.field-meta.xml
<CustomField>
    <fullName>DataJson__c</fullName>
    <label>DataJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobExecution__c/fields/VolumeOptions__c.field-meta.xml
<CustomField>
    <fullName>VolumeOptions__c</fullName>
    <label>VolumeOptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/ExecutionSequence__c.field-meta.xml
<CustomField>
    <fullName>ExecutionSequence__c</fullName>
    <description>Used to define the order of execution in the context of User Story Deployment</description>
    <label>Execution Sequence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>before</fullName>
            </value>
            <value>
                <fullName>after</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/JobTemplate__c.field-meta.xml
<CustomField>
    <fullName>JobTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
    if(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobStep__c/fields/UserStory__c.field-meta.xml
<CustomField>
    <fullName>UserStory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Deployment Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Custom&apos;</defaultValue>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/JobTemplate__c/fields/VolumeOptions__c.field-meta.xml
<CustomField>
    <fullName>VolumeOptions__c</fullName>
    <inlineHelpText>A JSON containing transaction and volume options</inlineHelpText>
    <label>VolumeOptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the implementation of the User Story.</description>
    <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/CreateExecutionTest.cls
@IsTest
private class CreateExecutionTest {

    @TestSetup
    private static void setupData() {
        List<User> users = TestDataFactory.createUsers();
        List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();

        for(PermissionSet ps : [SELECT Id FROM PermissionSet WHERE Name = 'Copado_User' OR Name = 'Copado_Job_Engine']) {
            assignments.add(new PermissionSetAssignment(AssigneeId = users[0].Id, PermissionSetId = ps.Id));
        }
        insert assignments;
    }


    @IsTest
    private static void executeWithInvalidTemplateName() {

        // Setup
        Exception expectedException = null;

        Git_Commit__c gitCommit = new Git_Commit__c();
        insert gitCommit;

        CreateExecution.request request = new CreateExecution.request();
        request.parentId = gitCommit.Id;
        request.templateName = 'Invalid Template';

        List<CreateExecution.request> requests = new List<CreateExecution.request> { request };

        // Exercise
        try {
            CreateExecution.execute(requests);
        }
        catch(Exception ex) {
            expectedException = ex;
        }

        // Verify
        System.assertNotEquals(null, expectedException);
        System.assertEquals(Label.InvalidTemplateId, expectedException.getMessage());
    }


    @IsTest
    private static void executeWithRunAfterInstantiationDisabled() {

        // Setup
        User copadoUser = [SELECT Id, Name, LastName, Email, Username FROM User WHERE Email = 'test1@test1.com' LIMIT 1];

        JobTemplate__c template = new JobTemplate__c();
        template.Name = 'Sample';
        template.Version__c = 1;
        template.VolumeOptions__c = '[{ "name": "volumeEnabled", "value": "true" }]';
        insert template;

        JobStep__c step1 = new JobStep__c(Name = 'step1', JobTemplate__c = template.Id, Type__c = 'Manual');
        JobStep__c step2 = new JobStep__c(Name = 'step2', JobTemplate__c = template.Id, Type__c = 'Manual');
        insert new List<SObject>{ step1, step2 };

        Git_Commit__c gitCommit = new Git_Commit__c();
        insert gitCommit;

        CreateExecution.request request = new CreateExecution.request();
        request.templateName = 'Sample_1';
        request.dataJson = '{"key1": "value1"}';
        request.parentId = gitCommit.Id;

        List<CreateExecution.request> requests = new List<CreateExecution.request> { request };


        // Exercise
        List<JobExecution__c> executions;
        System.runAs(copadoUser) {
            executions = CreateExecution.execute(requests);
        }

        // Verify
        System.assertEquals(1, executions.size());
        JobExecution__c execution = executions[0];
        List<Parameter> parameters = (List<Parameter>)JSON.deserialize(execution.VolumeOptions__c, List<Parameter>.class);

        System.assertEquals(2, parameters.size());

        System.assertEquals('true', parameters[0].value);
        System.assertEquals('volumeEnabled', parameters[0].name);

        System.assertEquals(execution.Id, parameters[1].value);
        System.assertEquals('transactionId', parameters[1].name);

        System.assertEquals('Not Started', execution.Status__c);
        System.assertEquals('{"key1": "value1"}', execution.DataJson__c);
        System.assertEquals(2, [SELECT count() FROM JobStep__c WHERE JobExecution__c = :execution.Id]);
    }


    @IsTest
    private static void executeWithPreAndPostSteps() {

        // Setup
        User copadoUser = [SELECT Id, Name, LastName, Email, Username FROM User WHERE Email = 'test1@test1.com' LIMIT 1];
        User_Story__c userStory = new User_Story__c();
        insert userStory;

        JobStep__c step1 = new JobStep__c(Name = 'step1', UserStory__c = userStory.Id, Type__c = 'Manual', Order__c = 5, ExecutionSequence__c = 'before');
        JobStep__c step2 = new JobStep__c(Name = 'step2', UserStory__c = userStory.Id, Type__c = 'Manual', Order__c = 30, ExecutionSequence__c = 'before');

        JobStep__c step5 = new JobStep__c(Name = 'step5', UserStory__c = userStory.Id, Type__c = 'Manual', Order__c = 1, ExecutionSequence__c = 'after');
        JobStep__c step6 = new JobStep__c(Name = 'step6', UserStory__c = userStory.Id, Type__c = 'Manual', Order__c = 2, ExecutionSequence__c = 'after');

        JobTemplate__c template = new JobTemplate__c();
        template.Name = 'Sample';
        template.Version__c = 1;
        insert template;

        JobStep__c step3 = new JobStep__c(Name = 'step3', JobTemplate__c = template.Id, Type__c = 'Manual', Order__c = 10);
        JobStep__c step4 = new JobStep__c(Name = 'step4', JobTemplate__c = template.Id, Type__c = 'Manual', Order__c = 20);
        insert new List<SObject>{ step1, step2, step3, step4, step5, step6 };

        Git_Commit__c gitCommit = new Git_Commit__c();
        insert gitCommit;

        CreateExecution.request request = new CreateExecution.request();
        request.parentId = gitCommit.Id;
        request.templateName = 'Sample_1';
        request.preSteps = new List<JobStep__c> { step1, step2 };
        request.postSteps = new List<JobStep__c> { step5, step6 };

        List<CreateExecution.request> requests = new List<CreateExecution.request> { request };


        // Exercise
        List<JobExecution__c> executions;
        System.runAs(copadoUser) {
            executions = CreateExecution.execute(requests);
        }

        // Verify
        System.assertEquals(1, executions.size());
        JobExecution__c execution = executions[0];
        List<JobStep__c> steps = [SELECT Name, Order__c FROM JobStep__c WHERE JobExecution__c = :execution.Id ORDER BY Order__c ASC];

        System.assertEquals(6, steps.size());

        System.assertEquals(1, steps[0].Order__c);
        System.assertEquals('step1', steps[0].Name);

        System.assertEquals(2, steps[1].Order__c);
        System.assertEquals('step2', steps[1].Name);

        System.assertEquals(3, steps[2].Order__c);
        System.assertEquals('step3', steps[2].Name);

        System.assertEquals(4, steps[3].Order__c);
        System.assertEquals('step4', steps[3].Name);

        System.assertEquals(5, steps[4].Order__c);
        System.assertEquals('step5', steps[4].Name);

        System.assertEquals(6, steps[5].Order__c);
        System.assertEquals('step6', steps[5].Name);
    }


    @IsTest
    private static void executeWithRunAfterInstantiationEnabled() {

        // Setup
        User copadoUser = [SELECT Id, Name, LastName, Email, Username FROM User WHERE Email = 'test1@test1.com' LIMIT 1];
        JobTemplate__c template = new JobTemplate__c(Name = 'Sample', Version__c = 1);
        insert template;

        Git_Commit__c gitCommit = new Git_Commit__c();
        insert gitCommit;

        CreateExecution.request request = new CreateExecution.request();
        request.templateName = 'Sample_1';
        request.parentId = gitCommit.Id;
        request.runAfterInstantiation = true;

        List<CreateExecution.request> requests = new List<CreateExecution.request> { request };

        // Exercise
        Test.startTest();
        List<JobExecution__c> executions;
        System.runAs(copadoUser) {
            executions = CreateExecution.execute(requests);
        }
        Test.stopTest();


        // Verify
        System.assertEquals(1, executions.size());
        System.assertEquals(0, [SELECT count() FROM JobStep__c]);
        System.assertEquals('Successful', [Select Status__c FROM JobExecution__c WHERE Id = :executions[0].Id].Status__c);
    }
}