Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/Artifact_Version__c.object-meta.xml
<CustomObject>
    <label>Package Version</label>
    <nameField>
        <label>Package Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipName>Artifact_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Bundle Versions</relationshipLabel>
    <relationshipName>Bundle_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/Deployment_Task__c.object-meta.xml
<CustomObject>
    <label>Deployment Task</label>
    <nameField>
        <label>Deployment Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Deployment_Task__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Deployment Tasks</relationshipLabel>
    <relationshipName>Deployment_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Git_Org_Commit__c/Git_Org_Commit__c.object-meta.xml
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Git_Org_Commit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the commit. This value is updating automatically by Copado.</description>
    <inlineHelpText>The status of the commit. This value is updating automatically by Copado.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>No changes</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Commit undone</fullName>
            </value>
            <value>
                <fullName>Commit not in branch</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Org__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
    <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Credentials</relationshipLabel>
    <relationshipName>Org_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/fields/Deployment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Flow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Pipeline.</inlineHelpText>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
    <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Is_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Is_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Bundle</label>
    <type>Checkbox</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project where the User Story belongs.</description>
    <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product version or release where this User Story will be released.</description>
    <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the implementation of the User Story.</description>
    <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/recordTypes/Utility.recordType-meta.xml
<RecordType>
    <fullName>Utility</fullName>
    <active>true</active>
    <label>Utility</label>
</RecordType>

Dummy_Package_for_scratch_org/main/default/classes/BundlingProcess.cls
public with sharing class BundlingProcess {
    private static final Map<String, String> OPERATIONS_BY_ATTACHMENT = new Map<String, String>{
        'Metadata' => 'Commit Files',
        'Full Profiles & Permission Sets' => 'Full Profiles & Permission Sets',
        'Destructive Changes' => 'Destructive Changes'
    };
    private static final Map<String, String> ATTACHMENTS_BY_OPERATIONS = new Map<String, String>{
        'Commit Files' => 'MetaData',
        'Full Profiles & Permission Sets' => 'MetaData',
        'Destructive Changes' => 'Git Deletion'
    };

    private Map<Id, User_Story__c> childrenStoriesById = new Map<Id, User_Story__c>();
    private Set<Id> environments = new Set<Id>();
    private Set<Id> projects = new Set<Id>();
    private Set<Id> releases = new Set<Id>();
    private List<AggregateResult> pipelines;
    private User_Story__c parentStory;
    private Id pipeline;
    private Id bundle;

    // CONSTRUCTOR

    public BundlingProcess(Id bundleId, User_Story__c userStory) {
        for (User_Story__c story : new UserStoriesSelector().byBundlePackageVersions(new Set<Id>{ bundleId })) {
            childrenStoriesById.put(story.Id, story);
            environments.add(story.Environment__c);
            projects.add(story.Project__c);
            releases.add(story.Release__c);
        }

        environments.add(userStory.Environment__c);
        pipelines = queryPipeline(userStory.Project__c, projects, releases);
        pipeline = (Id) pipelines[0].get(Settings.ns + 'Deployment_Flow__c');
        parentStory = userStory;
        bundle = bundleId;
    }

    // PUBLIC

    public BundlingResult execute() {
        environmentConsistency();
        pipelineConsistency();
        insertParentStory();
        updateBundle();
        updateChildStories();
        cloneDeploymentTasks();
        return commitMetadata();
    }

    // PRIVATE

    private void insertParentStory() {
        parentStory.Is_Bundle__c = true;
        parentStory.RecordTypeId = Schema.SObjectType.User_Story__c.getRecordTypeInfosByDeveloperName().get('Utility').getRecordTypeId();
        parentStory = (User_Story__c) Utilities.Secure_DML(parentStory, Utilities.DML_Action.INS, Schema.SObjectType.User_Story__c);
    }

    private List<AggregateResult> queryPipeline(Id project, Set<Id> projects, Set<Id> releases) {
        Set<Id> allIds = (Set<Id>) Utilities.getFieldValues(new ReleasesSelector().byIds(releases), Release__c.Project__c, Set<Id>.class, false);
        allIds.addAll(projects);
        allIds.add(project);

        return [SELECT Deployment_Flow__c FROM Project__c WHERE Id = :allIds WITH SECURITY_ENFORCED GROUP BY Deployment_Flow__c];
    }

    private void updateBundle() {
        Artifact_Version__c bundle = new Artifact_Version__c(Id = bundle);
        bundle.User_Story__c = parentStory.Id;
        bundle.Status__c = 'Locked';

        Utilities.Secure_DML(bundle, Utilities.DML_Action.UPD, Schema.SObjectType.Artifact_Version__c);
    }

    private void updateChildStories() {
        for (User_Story__c story : childrenStoriesById.values()) {
            story.Stop_Indexing_Metadata__c = true;
            story.Exclude_From_CBM__c = true;
        }

        Utilities.Secure_DML(childrenStoriesById.values(), Utilities.DML_Action.UPD, Schema.SObjectType.User_Story__c);
    }

    private void cloneDeploymentTasks() {
        Set<Id> tasks = new Map<Id, Deployment_Task__c>(new DeploymentTasksSelector().byStories(childrenStoriesById.keyset())).keySet();
        if (!tasks.isEmpty()) {
            String serialized = SObjectDataLoader.serialize(
                tasks,
                new SObjectDataLoader.SerializeConfig().followChild(Attachment.ParentId).omit(Deployment_Task__c.User_Story__c)
            );
            SObjectDataLoader.deserialize(serialized, new SetParentStoryCallback(parentStory));
        }
    }

    private BundlingResult commitMetadata() {
        List<Id> commitIds = new List<Id>();
        List<Git_Org_Commit__c> commits = new List<Git_Org_Commit__c>();
        Map<String, Attachment> attachmentByMessage = new Map<String, Attachment>();
        String snapshotId = queryGitSnapshot(parentStory.Org_Credential__c, pipeline);
        parentStory = new UserStoriesSelector().byIds(new Set<Id>{ parentStory.Id }).get(0);

        for (Attachment attachment : new AttachmentsSelector().byParentIdAndName(new Set<Id>{ bundle }, OPERATIONS_BY_ATTACHMENT.keySet())) {
            String key = parentStory.Name + ': ' + parentStory.User_Story_Title__c + ' Bundle ' + attachment.Name;
            commits.add(createCommit(key, parentStory.Org_Credential__c, snapshotId, OPERATIONS_BY_ATTACHMENT.get(attachment.Name)));
            attachmentByMessage.put(key, attachment.clone());
        }
        Utilities.Secure_DML(commits, Utilities.DML_Action.INS, schema.SObjectType.Git_Org_Commit__c);

        for (Git_Org_Commit__c cmm : commits) {
            commitIds.add(cmm.Id);
            String key = cmm.Commit_Message__c;
            attachmentByMessage.get(key).ParentId = cmm.Id;
            attachmentByMessage.get(key).Name = ATTACHMENTS_BY_OPERATIONS.get(cmm.Git_Operation__c);
        }
        Utilities.Secure_DML(attachmentByMessage.values(), Utilities.DML_Action.INS, schema.SObjectType.Attachment);

        BundlingResult result = new BundlingResult();
        result.storyId = parentStory.Id;
        result.commitIds = commitIds;
        result.snapshotId = snapshotId;
        return result;
    }

    private Id queryGitSnapshot(String orgId, Id pipelineId) {
        Deployment_Flow__c pipeline = new PipelineSelector().byId(new Set<Id>{ pipelineId })[0];
        return new GitSnapshotSelector().byCredentialRepoSnapshotOnly(orgId, pipeline.Git_Repository__c)[0].Id;
    }

    private void environmentConsistency() {
        if (!(environments.size() == 1)) {
            new ApplicationException('Environments in the selection does not match').throwAuraHandled();
        }
    }

    private void pipelineConsistency() {
        if (!(pipelines.size() == 1)) {
            new ApplicationException('Pipelines in the selection does not match').throwAuraHandled();
        }
    }

    private Git_Org_Commit__c createCommit(String commitMessage, String orgId, String snapshotId, String operationName) {
        return new Git_Org_Commit__c(
            Commit_Message__c = commitMessage,
            Org__c = orgId,
            Git_Backup__c = snapshotId,
            Status__c = 'Pending',
            Git_Operation__c = operationName
        );
    }

    private class SetParentStoryCallback implements SObjectDataLoader.IDeserializeCallback {
        private Id scenarioId;

        public SetParentStoryCallback(SObject clone) {
            scenarioId = clone.Id;
        }

        public void unresolvedReferences(SObjectType type, List<SObjectDataLoader.UnresolvedReferences> unresolved) {
            if (type == Deployment_Task__c.SObjectType) {
                for (SObjectDataLoader.UnresolvedReferences refs : unresolved) {
                    if (refs.References.contains(Deployment_Task__c.User_Story__c)) {
                        refs.Record.put(Deployment_Task__c.User_Story__c, scenarioId);
                    }
                }
            }
        }
    }

    //INNER

    public class BundlingResult {
        @AuraEnabled
        public Id storyId;

        @AuraEnabled
        public List<Id> commitIds;

        @AuraEnabled
        public Id snapshotId;
    }
}