Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/Artifact_Version__c.object-meta.xml
<CustomObject>
    <label>Package Version</label>
    <nameField>
        <label>Package Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/Artifact_Version__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Bundle Versions</relationshipLabel>
    <relationshipName>Bundle_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dummy_Package_for_scratch_org/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the implementation of the User Story.</description>
    <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Dummy_Package_for_scratch_org/main/default/classes/ArtifactVersionsSelector.cls
public with sharing class ArtifactVersionsSelector extends fflib_SObjectSelector {
    // CONSTRUCTOR

    public ArtifactVersionsSelector() {
        this(true, true);
    }

    public ArtifactVersionsSelector(Boolean enforceCRUD, Boolean enforceFLS) {
        super(false, enforceCRUD, enforceFLS);
    }

    // PUBLIC

    public Schema.SObjectType getSObjectType() {
        return Artifact_Version__c.sObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{ Artifact_Version__c.Name,
            Artifact_Version__c.User_Story__c,
            Artifact_Version__c.Status__c };
    }

    public List<Artifact_Version__c> byIds(Set<Id> ids) {
        return selectSObjectsById(ids);
    }

    public List<Artifact_Version__c> byStoryIdWithBundledStories(Set<Id> stories) {
        fflib_QueryFactory query = newQueryFactory().setCondition(Artifact_Version__c.User_Story__c + ' IN :stories');

        new BundledStorySelector().addQueryFactorySubselect(query);

        return Database.query(query.toSOQL());
    }
}